### ISSUE TITLE
Crashing on `With` on a `WithEvent`'d variable?

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#104]
**Describe the bug**
While testing out ADO on tB, I discovered it was crashing if I used `With` block on a variable that had `WithEvents`.

**To Reproduce**
1. Create a standard EXE project
2. Use code:
```
Public Module MainModule
    Public ExitMain As Boolean
    
    Public Sub Main()
        Dim t As Test = New Test
        t.DoIt
        
        Debug.Print "Ok"
    End Sub
End Module

Public Class Test
    Private WithEvents AdoRecordset As ADODB.Recordset
    
    Public Sub DoIt()
        Set AdoRecordset = New ADODB.Recordset
        With AdoRecordset
            Debug.Print .State
        End With
    End Sub
End Class
```
3. Place breakpoint in main and step through the code with F5.
4. Get to `With AdoRecordset`. Try to step one more time and the execution will abruptly halt. Debug console eventually prints `Canceled` and exits immediately.

**Expected behavior**
It should have entered the `With` block and read the `State` and thus return `0`. Note that this behaves correctly if we avoid use of the `With` block. I am not sure if this is something to do with `ADODB.Recordset` itself but I can verify that the crash only happens if the `ADODB.Recordset` has `WithEvents`. If thee is no `WithEvents` on the variable, the `With` block can be entered without a problem.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler 0.9.2220

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.9.2300, thanks for reporting
