### ISSUE TITLE
twinBASIC not able to find the coclass for certain property (imported libraries?)

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#107]
**Describe the bug**
When using certain objects, VSC will report that there is no default interface for the coclass. It might be specific to ADO library or may be artifact of Access library importing ADO, I'm not sure which.

**To Reproduce**
1. Use the following code:
```

Public Module Example
    Public Sub DoIt()
        Dim Acc As Access.Application
        
        Dim db As DAO.Database
        Set db = Acc.CurrentDb
        
        Dim con As ADODB.Connection
        Set con = Acc.CurrentProject.Connection
    End Sub
End Module
```
2. VSC will highlight the `Acc.Currentproject`, indicating there's no default interface for `Connection`.
![image](https://user-images.githubusercontent.com/2367644/116833175-41e94380-ab7d-11eb-8ee7-d24e3fdc631b.png)
3. A possible factor is the fact that the `Access` type library imports ADO 2.8 while the twinBASIC project is referencing the ADO 6.1 library.
![image](https://user-images.githubusercontent.com/2367644/116833344-35191f80-ab7e-11eb-920c-0e9725cb777c.png)
Normally, that shouldn't be a problem since 6.1 is supposed to be backward compatible with 2.8.

Note: The project will still build without errors, though it's quite confusing to see an error reported. I have not tested running with it, however. 

Note 2: Another possible workaround is to late-bind by casting the intermediate objects to `Object` then retrieving the `AccessConnection`. 

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.9.2220

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.9.2355.  Thanks for reporting.
