### ISSUE TITLE
Replace$() "invalid use of datatype hint"

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#108]
**Describe the bug**
The Replace$ function throws an "invalid use of datatype hint" error. The Replace() function works OK.

**To Reproduce**
```
MsgBox Replace("100,0", ",", ".") ' Works
MsgBox Replace$("100,0", ",", ".") ' Works not
```

**Expected behavior**
That Replace$() works like Replace()

**Screenshots**
![image](https://user-images.githubusercontent.com/33756666/116847153-426bf380-abea-11eb-84f1-e2257b432fef.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.9.2220]

**Additional context**
n/a

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.9.2300, thanks for reporting
