### ISSUE TITLE
WithDispatchForwarding should be an attribute

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#110]
**Is your feature request related to a problem? Please describe.**
Based on the changelog for 0.9.2300, it seems we added a keyword `WithDispatchForwarding` to allow use of `IRibbonExtensibility` as the interface for dispatched callbacks. That's awesome!

**Describe the solution you'd like**
However, I would point out that this is probably best implemented as an attribute rather than a keyword for the same reasons touched upon in #22; an attribute class can be updated or even replaced much easily than a keyword in a language. 

This requires implementing #25, though. However, I wanted this to be considered to ensure tB evolves in a consistent way.

**Comment by WaynePhillipsEA** [comment]
I struggled with this one simply because it is an important feature to get in ASAP as people are starting to experiment writing COM Add-ins, but attributes are not yet supported....

I probably will retire this syntax soon after #25 is implemented, and given the preview status I feel this is acceptable at the moment.  However, it does add more urgency to implement #25 sooner rather than later.

**Comment by wqweto** [comment]
Btw, you can link project's [changelog](https://marketplace.visualstudio.com/items/twinbasic.twinbasic/changelog) from repo's README to be discoverable without requiring installation.

**Comment by bclothier** [comment]
Definitely can appreciate the sense of urgency since COM Add-Ins is a great niche for tB to fill. (do not recommend using .NET for COM Add-Ins... 😆 ) As long people are able to get the messaging that's subject to change, I think that should be fine. :)

**Comment by WaynePhillipsEA** [comment]
Just for context, I've now put out a sample Access/Excel COM addin that demonstrates this modifier:
https://t.co/IK2YtJrdKl?amp=1

![E0jgKiMXsAABI60](https://user-images.githubusercontent.com/25738109/117051543-92dc7180-ad0e-11eb-8633-33c675cbd02c.png)

**Comment by Kr00l** [comment]
Out of curiosity, is below syntax
```
Private Function GetCustomUI(ByVal RibbonID As String) As String _
		Implements IRibbonExtensibility.GetCustomUI
```
an alias (same as) following?
`Private Function IRibbonExtensibility_GetCustomUI(ByVal RibbonID As String) As String`

**Comment by WaynePhillipsEA** [comment]
@Kr00l yes that's right.  tB supports both forms, though the intent is much clearer in the new form.

**Comment by wqweto** [comment]
> . . . though the intent is much clearer in the new form.

And the new form allows `GetCustomUI` being \*public\* on the default interface while keeping the original method name which is very convenient bonus IMO.

**Comment by WaynePhillipsEA** [comment]
Old syntax now removed in v0.10.575, use [WithDispatchForwarding] attribute instead.
