### ISSUE TITLE
Crashing with a class containing a `WithEvents` variable

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#112]
**Describe the bug**
It appears that if a twinBASIC class contains a `WithEvents` variable, calling a method on the class even though it's unrelated will crash. It's possible to new it up but calling a method, even a empty stub seems crash simply because there's a variable with `WithEvents`. If it's remove, there is no problem using the class.

**To Reproduce**
1. Create an ActiveX DLL project
2. Provide the following code:
```
Public Class Foo
    Private WithEvents AdoConnection As ADODB.Connection
    
    Public Sub New()
    End Sub
        
    Public Sub Initialize( _
        Fizz As String, _
        Buzz As String _ 
    )
    End Sub
End Class
```
3. Build the project
4. Open up a VBA host (Access was used in this test), add a reference to the built project.
5. Add the following code to VBA host (using Access form as an example):
```
Private Foo As MyLibrary.Foo

Private Sub Form_Load()
    Set Foo = New MyLibrary.Foo
    Foo.Initialize "", ""
End Sub
```
6. Open Access form normally. It will crash.

Note that if you remove the `WithEvents` from the twinBasic's `AdoConnection`, it will not crash.

Note also that the original version had other objects being passed through the methods but the steps above shows that simply passing objects isn't the cause since we crash even on an empty stub.

**Expected behavior**
It should not crash. 

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.9.2300]

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.9.2311, thanks for reporting
