### ISSUE TITLE
Renaming project name and description

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#113]
**Is your feature request related to a problem? Please describe.**
Currently, tB provides properties via the `Settings` file to set the project name and the project description.

However, you have to scroll down to get to the project description. Consequently, this leads to confusion when you rename an ActiveX DLL project, build, then try to reference it from a VBA host only to see the old description used in the references list, giving the impression that the renaming didn't work.

**Describe the solution you'd like**
I think it's best to have the project name and description adjacent to each other in the settings so that it's easy to see the them together.

**Comment by WaynePhillipsEA** [comment]
Done in v0.9.2311, thanks
