### ISSUE TITLE
#Else block formatting broken when it has an empty line

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#118]
**Describe the bug**
I already like the formatting of tB for conditional compilation constants. (gray and italic)
However, there is a formatting issue when in the #Else block has an empty line.
There is no issue when the #If block has an empty line. See screenshots, says more than words.

**To Reproduce**
```
#If VBA7 Then
Private Type MyType
Ptr As LongPtr
End Type
Private Declare PtrSafe Sub CopyMemory Lib "kernel32" Alias "RtlMoveMemory" (ByRef Destination As Any, ByRef Source As Any, ByVal Length As Long)
Private ShadowObjectPointer As LongPtr
#Else
Private Type MyType
Ptr As Long
End Type

Private Declare Sub CopyMemory Lib "kernel32" Alias "RtlMoveMemory" (ByRef Destination As Any, ByRef Source As Any, ByVal Length As Long)
Private ShadowObjectPointer As Long
#End If
```

**Screenshots**
Without empty line, everything looks great.
![image](https://user-images.githubusercontent.com/33756666/116995351-4119f400-acda-11eb-8cb5-b3011f7c7d3d.png)

After empty line is inserted, it looks like this:
![image](https://user-images.githubusercontent.com/33756666/116995410-53942d80-acda-11eb-9d8a-a74038c60453.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.9.2311]

**Additional context**
The functionality is not broken. The project will run, so it is only a cosmetic bug.

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.9.2355.  Thanks for reporting.
