### ISSUE TITLE
Support RubberDuck annotation @PredeclaredId

### ISSUE THREAD

**Issue by WaynePhillipsEA** [WaynePhillipsEA/twinbasic#12]
Describe the solution you'd like
twinBASIC should understand the RubberDuck @PredeclaredId annotation

Additional context
Currently, twinBASIC requires you to set 'Attribute VB_PredeclaredId = True' on a class in order for the compiler to auto-generate a global variable of the same name as the class, with the As-New class type. This useful annotation has the same effect, but is more readable.

**Comment by retailcoder** [comment]
I think this one can be closed now =)

**Comment by WaynePhillipsEA** [comment]
@retailcoder this annotation is not yet supported😉

**Comment by FullValueRider** [comment]
The Attribute does not appear to be supported.  I have lots of classes with PredeclaredId and call against the predeclared instance are still being flagged as 'unrecognised symbol.

Is the usage below correct|?

```
Public Class Convertor
Option Explicit
Attribute VB_PredeclaredId = True
```

**Comment by WaynePhillipsEA** [comment]
Sorry, predeclared identifiers not yet supported.  Coming very soon though!  (You can simulate with a global variable for now)

**Comment by WaynePhillipsEA** [comment]
Sorry, predeclared identifiers not yet supported.  Coming very soon though!  (You can simulate with a global variable for now)

**Comment by WaynePhillipsEA** [comment]
Supported from v0.9.2648
