### ISSUE TITLE
Settings is broken after 2450 update

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#123]
**Describe the bug**
Clicking on the settings tab in the file explorer does bring up the setting page, but only as a single string of text.  This applies to new and old projects.  I  redownloaded project to test and found the same for those.

**To Reproduce**
1. Open a  twinBasic Workspace
2. Open the file explorer
3. Click on the Setting item

You get

{"project.references":[{"id":"{00020430-0000-0000-C000-000000000046}","name":"OLE Automation","versionMajor":2,"versionMinor":0,"lcid":0,"path32":"C:\\Windows\\SysWOW64\\stdole2.tlb","path64":"C:\\Windows\\System32\\stdole2.tlb"},{"id":"{420B2830-E718-11CF-893D-00A0C9054228}","name":"Microsoft Scripting Runtime","versionMajor":1,"versionMinor":0,"lcid":0,"path32":"C:\\Windows\\SysWOW64\\scrrun.dll","path64":"C:\\Windows\\System32\\scrrun.dll"},{"id":"{BED7F4EA-1A96-11D2-8F08-00A0C9A6186D}","name":"mscorlib.dll","versionMajor":2,"versionMinor":4,"lcid":0,"path32":"C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\mscorlib.tlb","path64":"C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\mscorlib.tlb"},{"id":"{2582CE0E-FFF3-45D4-B486-2628A7480A3F}","name":"GKvp: A flexible Dictionary for VBA","versionMajor":1,"versionMinor":0,"lcid":0,"path32":"","path64":"C:\\Users\\slayc\\source\\repos\\CShp\\GKvpLib.git\\GKvpLib\\bin\\Debug\\GKvpLib.tlb"}],"project.name":"AdventOfCode2020Project","project.description":"AdventOfCode2020 project","project.id":"{B768C096-6072-450A-84A8-01D07F690907}","configuration.inherits":"Defaults","project.buildType":"Standard EXE","project.buildPath":"${SourcePath}\\Build\\${ProjectName}_${Architecture}.${FileExtension}","runtime.useUnicodeStandardLibrary":true,"project.optionExplicit":true}

in the settings screen

For a freshly downloaded copy of the HelloWorld project you get

{"project.references":[{"id":"{00020430-0000-0000-C000-000000000046}","name":"OLE Automation","versionMajor":2,"versionMinor":0,"lcid":0,"path32":"C:\\Windows\\SysWOW64\\stdole2.tlb","path64":"C:\\Windows\\System32\\stdole2.tlb"}],"project.name":"HelloWorldProject","project.description":"HelloWorld project","project.id":"{B768C096-6072-450A-84A8-01D07F690907}","configuration.inherits":"Defaults","project.buildType":"Standard EXE","project.buildPath":"${SourcePath}\\Build\\${ProjectName}_${Architecture}.${FileExtension}","runtime.useUnicodeStandardLibrary":true,"project.optionExplicit":true}

**Comment by WaynePhillipsEA** [comment]
Hmmm... looks not to be related to the twinBASIC update, but something due to the vscode 1.56 update pushed out today (https://code.visualstudio.com/updates/v1_56)

**Comment by FullValueRider** [comment]
Ah.  Most likely a plot by MS :-}

**Comment by WaynePhillipsEA** [comment]
So, this took a lot longer than it should've done to work out what was wrong.   Anyway, it's fixed in v0.9.2451 now

It seems that VS Code changed the glob pattern matching used for the contributes.customEditors.selector.filenamePattern in package.json.   Now it will match in lowercase only (even when the actual file/folder name is really in uppercase), so I've modified the globs used to allow for either case, because I'm guessing at some point they'll notice and fix it and we don't want this happening again (related PR https://github.com/microsoft/vscode-json-languageservice/pull/93 )

**Comment by FullValueRider** [comment]
Whooosh.  That was quick.  Cheers. ;-}
