### ISSUE TITLE
typo settings > Project COM Threading

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#124]
**Screenshots**
![image](https://user-images.githubusercontent.com/33756666/117421526-e58c7800-af1e-11eb-995c-13d0a23f8301.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.9.2451]

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.9.2648, thanks for reporting.
