### ISSUE TITLE
Project has no errors but does not compiule

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#127]
**Describe the bug**
Following the availability of the PredeclaredId attribute I was able to import the supporting library for myAdvent Of Code 2020 attempts.  The (manual) import represents over 2000 lines of VBA code but only two lines required fixing (use of Like operator).  The project indicates that there are no errors in the code but it will not compile (Not connected error)

I've attached the project with only the Day1 solution together with my custom GKvp library which is referenced by the code.
[AdventOfCode2020.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6445787/AdventOfCode2020.zip)

**Comment by WaynePhillipsEA** [comment]
I've found the bug.... it's in the type library generation stage.   When a parameter type or return type is the internal VBA.Collection type, the type library generation is failing.   I'll get this fixed tomorrow morning.   Thanks for reporting.

**Comment by WaynePhillipsEA** [comment]
Additionally, you've got two members marked as DefaultMember in the Kvp class (Deb and GetByKey).  

Once you've removed one, this now builds in v0.9.2699.   I haven't tested whether it actually works correctly, as I don't have the Day01RawData data file referenced by your code.
