### ISSUE TITLE
Project files should be human readable

### ISSUE THREAD

**Issue by mansellan** [WaynePhillipsEA/twinbasic#130]
**Is your feature request related to a problem?**
Modern source control systems expect to deal with non-binary files. Their diff tools are set up to optimise for this convention.

**Describe the solution you'd like**
Either JSON, XML, or (even) INI project files.

**Additional context**
Currently, twinBASIC uses:
1. workspace files (json)
2. twinproj files (binary, with source code embedded (as UTF-8?))

.Net (with the .Core reset) has moved to minimal, convention-based project files, expressed in XML form. This decision made it much easier to diff commits and critique any changes made (as there was much less boilerplate).

VB6, for all its faults with indeterministic serialisation, tended to keep with renderable file formats, except for binary resource files. Everything except .**x files could be diffed for source control.

Using a binary project file seems like a step backwards.

**Comment by WaynePhillipsEA** [comment]
You have to consider the twinproj file as a virtual file system.  It's like a zip file.

There are good reasons that the twinproj file format is not text based, in the same way that there are good reasons ZIP files, VDI files etc are not text based.  

The decision mostly comes down to efficiency, and serialization simplicity.  There is also meta-data that does not lend itself well to text-based storage, such as indices.  Soon, you'll also be able to include binary files such as graphics inside the twinproj file once the one-file limit has been removed.

When thinking of SCC, you wouldn't diff a ZIP file, and so you wouldn't diff a twinproj file.  You'd diff the extracted content, and once we support SCC from inside VS code, that's exactly how it'll work with tB projects.

If the twinproj file wasn't a self-contained virtual file system, then a text-based human readable file format would likely have been chosen.
