### ISSUE TITLE
Unable to save project

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#133]
**Describe the bug**
Following a short editing session twinBasic fails to save the project.  Quitting and reloading the project leads to a dialog box saying "It seems the twin basic compiler is crashing. Please report this bug"

Prior to this starting to happen I had converted some c# to vb.net (within Visual Studio 2019) and then cut and pasted the vb.net into the twin basic editor.  The lock ups started after about 5 minuets of editing.

The twinbasic project (AutoKey) is attached.  I was using the Hello World project as a scratchpad to convert some code before pasting it into a much larger twin basic project.
[Autokey.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6450926/Autokey.zip)

**Comment by WaynePhillipsEA** [comment]
Ah yes, there are still some edge cases where bad code can crash the compiler.  Thankfully getting fewer day by day...

Fixed in v0.9.2720.  Thanks for reporting!
