### ISSUE TITLE
Error reading file

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#137]
I seem to be getting this error but I'm not sure why I'm seeing it. It seems to happen whenever I open the project first time. If I then reload the twinBASIC via the right-click menu on the win32 settings, it opens fine. 

![image](https://user-images.githubusercontent.com/2367644/117896583-7e582600-b286-11eb-82db-8061c9edcc11.png)

**Comment by WaynePhillipsEA** [comment]
Interesting one.  Not seen that.  I can work around it anyway, but would like to have repro'd.  Might not be able to get it fixed until next week.

**Comment by WaynePhillipsEA** [comment]
Is this still reproducing for anyone?  I made some tweaks recently that should've resolved this.

**Comment by WaynePhillipsEA** [comment]
Closing as I believe this to be fixed.
