### ISSUE TITLE
Support Friend access modifier on class members

### ISSUE THREAD

**Issue by WaynePhillipsEA** [WaynePhillipsEA/twinbasic#14]
**Describe the bug**
twinBASIC doesn't currently recognize the Friend access modifier on class members

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.9.1602

**Additional context**
[https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/friend-keyword](url)

**Comment by wqweto** [comment]
Can TB parse and treat `Friend` scope as `Public` until properly implemeted?

**Comment by WaynePhillipsEA** [comment]
@wqweto Yes, that's a good idea.  I'll sort that today.

**Comment by WaynePhillipsEA** [comment]
@wqweto that temporary fix is now live in 0.10.1923

**Comment by WaynePhillipsEA** [comment]
The Friend modifier is now properly supported, as of v0.13.32
