### ISSUE TITLE
No warning if calling undefined method or property

### ISSUE THREAD

**Issue by dmrvb** [WaynePhillipsEA/twinbasic#142]
Calling a non existent method or property in an object gives NO warning at edit time or at compile time, but gives "Unknown Name" error at runtime.

This is BAD, I need to catch errors like this before my customers!! 

**To Reproduce**
Insert this code and note the D.yyy=10

Module Dave
    Public Sub Main()
        dim D as new DaveObj
        
        on error goto e
        D.yyy=10
        
    exit sub
    
    e:
    call msgbox(Format$(Err.Number) & " " & err.Description )    
          
    End Sub
  End Module

class DaveObj

public xxx as long

end class

**Expected behavior**
I want to see this problem reported whilst editing, or at least while compiling

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version  0.9.2720

**Comment by WaynePhillipsEA** [comment]
We are aware of this one, but there was no issue opened for it, so thanks for reporting.   Classes are currently seen (wrongly) as runtime extensible, that's why you don't see an error at compiler time.

**Comment by wqweto** [comment]
> Classes are currently seen (wrongly) as runtime extensible

Btw, `ADODB.Connection` is deliberately missing `nonextensible` attribute so that one can call stored procedures with `cn.MyStoreProc Param1, Param2, ...` syntax in VB code.

It might be good candidate for testing `nonextensible` attribute implementation.

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.509, thanks for reporting
