### ISSUE TITLE
No automatic adjustment of upper/lower case on variable names

### ISSUE THREAD

**Issue by dmrvb** [WaynePhillipsEA/twinbasic#144]
**Describe the bug**
In VB6 when typing a variable name the case (upper/lower) is automatically adjusted to match that in the variable declaration.
It would be good if TwinBasic could do this.

**To Reproduce**
Dim AAA as long

aaa=10

**Expected behavior**

I would expect aaa to auto adjust to AAA

This helps to keep code neat and tidy.
I have reported it as a bug because in some situations it will prevent intellisense from working, for example no pop up member list when dealing with UDT's

**Desktop 
Windows 10
twinBASIC compiler version  0.9.2720

**Comment by WaynePhillipsEA** [comment]
Yes this is planned, please see #17.  Closing as a duplicate.  Thanks.
