### ISSUE TITLE
Mid statement not working

### ISSUE THREAD

**Issue by cristianbuse** [WaynePhillipsEA/twinbasic#147]
**Describe the bug**
Mid/Mid$/MidB statement not working.

**To Reproduce**
```VBA
Public Sub Main()
    Dim s As String
    
    s = 1200067
    Mid$(s, 3, 3) = 345
    MsgBox s 'Should show 1234567 instead it shows 1200067
End Sub
```

**Expected behavior**
[Mid statement](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/mid-statement) (not the function - used on the left side of the assignment) should replace characters into a string.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise V1909
 - twinBASIC compiler v0.9.2720

**Additional context**
None

**Comment by WaynePhillipsEA** [comment]
Thanks.  This is noted as a limitation of the preview, on the preview documentation webpage ( https://twinbasic.com/preview.html ).

However, I will leave this issue open for tracking it, as I don't think we've got it covered by another issue.

**Comment by WaynePhillipsEA** [comment]
The Mid statement is now supported, as of v0.10.717.  Thanks.
