### ISSUE TITLE
Compiler error - workspace corrupted

### ISSUE THREAD

**Issue by cristianbuse** [WaynePhillipsEA/twinbasic#151]
**Describe the bug**
Compiler issue when using a ```With``` block on an object that has an items collection.

**To Reproduce**
```VBA
Module Test
    Public Sub Main()
        Dim coll1 As New Collection
        Dim coll2 As New Collection
        
        coll1.Add Empty
        With coll1
            coll2.Add .Item(1) 'Compiler error and workspace corruption on this line
        End With
    End Sub
End Module
```

**Expected behavior**
Code is valid and works in VBA. Same code should compile and work in TB.

**Screenshots**
![test](https://i.stack.imgur.com/lY4Ru.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise V1909
 - twinBASIC compiler v0.9.2720

**Additional context**
Once the error occurs the workspace gets corrupted. I had to use backups in order to narrow down this issue because I could not use the workspace even if I reverted back all changes. The workspace folder cannot be read anymore and the compiler does not restart until I replace the whole project with a backup (while VS Code is closed, of course).

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.313, thanks for reporting.   Project itself was not corrupt, but the compiler was unable to get past the first stage of opening it, making it seem like the project file was corrupt.
