### ISSUE TITLE
Fixed-length strings not shown in Locals window

### ISSUE THREAD

**Issue by cristianbuse** [WaynePhillipsEA/twinbasic#152]
**Describe the bug**
The Locals window does not display the value for fixed-length strings.

**To Reproduce**
```VBA
Module ModHelloWorld
    Public Sub Main()
        Dim fixedLengthString As String * 8
        Dim dynamicLengthString As String

        fixedLengthString = "1234567890"
        dynamicLengthString = "1234567890"
    End Sub
End Module
```

**Expected behavior**
The value of a fixed-length string should appear in the Locals window.

**Screenshots**
![test](https://i.stack.imgur.com/Qpni9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise V1909
 - twinBASIC compiler v0.9.2720

**Additional context**
None

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.313, thanks for reporting
