### ISSUE TITLE
Chained calls on Collections fail

### ISSUE THREAD

**Issue by cristianbuse** [WaynePhillipsEA/twinbasic#153]
**Describe the bug**
Chained calls on Collections are failing at runtime

**To Reproduce**
```VBA
Module Test
    Public Sub Main()
        Dim coll As New Collection
        Dim coll2 As New Collection
        
        coll.Add 111, "key1"
        coll2.Add coll, "key2"
        
        MsgBox coll2("key2")("key1")
        MsgBox coll2.Item("key2").Item("key1")
    End Sub
End Module
```

**Expected behavior**
The above code should print the value 111 as in VBA.

**Screenshots**
![test](https://i.stack.imgur.com/if567.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise V1909
 - twinBASIC compiler v0.9.2720

**Additional context**
The problem doesn't appear to be related to the default member of the class because using ```coll2.Item("key2").Item("key1")``` also fails.

Another example:  
```VBA
Module Test
    Public Sub Main()
        MsgBox Array(1, 2, Array(3,4))(2)(1)             'This works
        MsgBox Collection(1, 2, Collection(3,4))(3)(2)   'This fails
    End Sub

    Public Function Collection(ParamArray values() As Variant) As Collection
        Dim v As Variant
        Dim coll As Collection
        
        Set coll = New Collection
        For Each v In values
            coll.Add v
        Next v
        
        Set Collection = coll
    End Function
End Module
```

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.833, thanks for reporting.
