### ISSUE TITLE
Execution aborted when expanding a zero-length array in the Locals window

### ISSUE THREAD

**Issue by cristianbuse** [WaynePhillipsEA/twinbasic#156]
**Describe the bug**
Code execution is aborted during debugging if expanding a zero-length array in the Locals window.

**To Reproduce**
Run code:
```VBA
Module Test
    Public Sub Main()
        Dim zeroLengthArray() As Variant
        
        zeroLengthArray = Array()
        Stop
    End Sub
End Module
```
and when execution breaks on the ```Stop``` line go to the Locals window and click the arrow next to the variable.

**Expected behaviour**
In VBA the expansion shows the text "No Variables" and doesn't abort execution.

**Screenshots**
![test](https://i.stack.imgur.com/bS3lE.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise V1909
 - twinBASIC compiler v0.9.2720

**Additional context**
None

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.509, thanks for reporting
