### ISSUE TITLE
Function Called Name leads to unexpected line errors when assigning to the Name member

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#159]
**Describe the bug**
The following function raises three errors
```
Public Function Name() as String
     Name = "Name"
End Function
```
**To Reproduce**
Steps to reproduce the behaviour:
1. Open a New Hello World project
2. Add the function listed above
3. The 'Name="Name" line generates three errors

•Unexpected end of expression
•Unexpected end of line
•unrecognized symbol '{unexpected end of line}'",
	
Replacing "Name =" with "return" eliminates the above errors.  Renaming 'Name' to 'AName' eliminates the above errors.

**Comment by WaynePhillipsEA** [comment]
Thanks.  Closing as a duplicate of #115.
