### ISSUE TITLE
Allow setting command-line arguments for debug sessions

### ISSUE THREAD

**Issue by mwolfe02** [WaynePhillipsEA/twinbasic#160]
<s>**Is your feature request related to a problem? Please describe.**
Is there an official way to pass command-line arguments to a console application in twinBASIC?

**Describe the solution you'd like**
At minimum, a way to access the raw text that follows the call to the console application .exe.

**Describe alternatives you've considered**
Setting environment variables in the console and then using Environ() to read them in.</s>

We need to be able to set command line arguments in the build configuration so that it is effective in the debug session, and retrievable via the Command$ function during debugging.

**Comment by mwolfe02** [comment]
More about my workaround here: [Pseudo-Command Line Args in twinBASIC](https://nolongerset.com/pseudo-command-line-args-in-twinbasic/)

**Comment by EduardoVB** [comment]
I just tested and the standard VB6 way to pass command line arguments works:

**Comment by WaynePhillipsEA** [comment]
As @EduardoVB said, that should work.   Though we really need a way to pass command line args in debug sessions, via the build configuration properties.

**Comment by mwolfe02** [comment]
Mea culpa.  My Google-fu [failed me](https://nolongerset.com/twinbasic-update-may-23-2021/#around-the-web).  I could not find the standard VB6 way to pass command-line arguments.

On the bright side, the workaround I used _does_ support setting values for command-line arguments to be used while debugging.

**Comment by mwolfe02** [comment]
@WaynePhillipsEA Should I close this issue and open a new one specifically about setting command line args in debug sessions or just change the title of this issue?

**Comment by mwolfe02** [comment]
Sorry...clicked the wrong button (didn't mean to close the case just yet).

**Comment by WaynePhillipsEA** [comment]
@mwolfe02 No problem Mike, I've just edited the issue.

**Comment by WaynePhillipsEA** [comment]
Now available in v0.10.509:

<img width="563" alt="tb_cmdLineOption" src="https://user-images.githubusercontent.com/25738109/119962058-91fdcf00-bf9e-11eb-8720-669f1ae339aa.png">
