### ISSUE TITLE
Implementing a derived interface ought to require implementation in all derived interfaces

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#165]
**Describe the bug**
If a class implements an interface that is derived from another interface that is not `IUnknown` or `IDispatch`, twinBASIC does not require the class to implemented the derived interface members. That should be required to avoid errors. In this example, we use `Excel.Adjustments`, which derives from `_IMsoDispObj `:
![image](https://user-images.githubusercontent.com/2367644/119916727-af915100-bf2a-11eb-9724-5ab272072aed.png)

Note that tB lists only the members directly on the `Excel.Adjustments` interface:
```
[
  odl,
  uuid(000C0310-0000-0000-C000-000000000046),
  helpcontext(0x00019258),
  dual,
  nonextensible,
  oleautomation
]
interface Adjustments : _IMsoDispObj {
    [id(0x00000001), propget, helpcontext(0x00019259)]
    HRESULT Parent([out, retval] IDispatch** Parent);
    [id(0x00000002), propget, helpcontext(0x0001925a)]
    HRESULT Count([out, retval] int* Count);
    [id(00000000), propget, helpcontext(0x0001925b)]
    HRESULT Item(
                    [in] int Index, 
                    [out, retval] single* Val);
    [id(00000000), propput, helpcontext(0x0001925b)]
    HRESULT Item(
                    [in] int Index, 
                    [in] single Val);
};
```

However, the `_IMsoDispObj ` interface requires 2 additional members that must be present on the derived interface implementations:
```
[
  odl,
  uuid(000C0300-0000-0000-C000-000000000046),
  hidden,
  dual,
  nonextensible,
  oleautomation
]
interface _IMsoDispObj : IDispatch {
    [id(0x60020000), propget, helpcontext(0x000003e9)]
    HRESULT Application([out, retval] IDispatch** ppidisp);
    [id(0x60020001), propget, helpcontext(0x000003ea)]
    HRESULT Creator([out, retval] long* plCreator);
};
```

**To Reproduce**
1. Create a new class in a twinBASIC project that has reference to Excel object library.
2. Add `Implements Excel.Adjustments`.
3. Observe that twinBASIC only requires implementation of the members on `Excel.Adjustments` but does not require implementations of the members on the `_IMsoDispObj` interface.

**Expected behavior**
Implementing the `Excel.Adjustments` should require that the implementator implements the base interface's members, walking the chain up to `IUnknown`/`IDispatch`.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - twinBASIC compiler version 0.10.313

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.540, thanks for reporting.
