### ISSUE TITLE
Inconsistent quoting for Runtime Command Line Arguments

### ISSUE THREAD

**Issue by mwolfe02** [WaynePhillipsEA/twinbasic#169]
**Describe the bug**
Double-quotes in the Debugger: Runtime Command Line Arguments setting get escaped with backslashes when stepping through the code interactively.  The backslashes do not appear when running the .exe.

**To Reproduce**
1. Set **Runtime Command Line Arguments** to: `"Quoted string"`
2. Add the following code: `Public Sub Main(): MsgBox Command$: End Sub`
3. Run `Main` from the Debug Console
4. The message box displays: `\"Quoted string\""`

**Expected behavior**
The message box should display: `"Quoted string"`

**Screenshots**
Build config setting:
![image](https://user-images.githubusercontent.com/305213/120085231-51887900-c0a4-11eb-8c32-142cb5623628.png)

### GOOD
When run from exe:
![image](https://user-images.githubusercontent.com/305213/120085272-afb55c00-c0a4-11eb-9832-3196619535df.png)

### BAD
When run from Debug Console via call to `Main`:
![image](https://user-images.githubusercontent.com/305213/120085250-77158280-c0a4-11eb-92a2-7633df846608.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit version 2004 (OS Build 19041.985)
 - twinBASIC compiler version: 0.10.655

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.660.  Thanks for reporting!
