### ISSUE TITLE
Auto correct symbol case whilst typing

### ISSUE THREAD

**Issue by WaynePhillipsEA** [WaynePhillipsEA/twinbasic#17]
**Describe the solution you'd like**
twinBASIC should auto-correct the case of resolved symbols whilst typing.   e.g. 'Dim abc : ABC = 5' should become 'Dim abc : abc = 5'

**Additional context**
We should not use the global symbol table to auto-correct the case of symbols, which is what VB6 / VBA does.  Instead, only correct the case when a symbol resolves to a definition, and assume the definition as the authoritative version.

**Comment by retailcoder** [comment]
Casing to the in-scope definition seems sensible. I submit that keywords and reserved identifiers should also auto-case.

**Comment by mansellan** [comment]
Can I upvote this? It seems trivial, but it's a bit of a culture-shock to come from a VBx environment to find this missing.

**Comment by WaynePhillipsEA** [comment]
I agree, and I think it's about time that this was looked at.

**Comment by mwolfe02** [comment]
Yes, please.  I've gotten used to the VBA case-changing idiosyncrasies more than I realized.  For example, I only worry about properly setting the case when I'm defining variables, routine names, or referencing enums.  For everything else, I just type in all lower-case and let the VBIDE fix things.  Even given its various foibles, it is a big time-saver and does help create more consistent looking code.

To have all the benefits of the auto-case changing without the downsides of the globally-scoped implementation?  Sign me up!

By the way, if anyone is interested, I think my article on this topic breaks down the VBA behavior pretty well: [VBA's Case Changing "Feature"](https://nolongerset.com/vbas-case-changing-feature/).

**Comment by WaynePhillipsEA** [comment]
v0.10.1923 just released that includes the first rough cut of the auto-correct case feature.  You need to enable it in your project settings.  WARNING: Make a backup of your twinproj file first!!

<img width="786" alt="tbAutoCorrectCase" src="https://user-images.githubusercontent.com/25738109/122421776-89d4f600-cf84-11eb-9989-520c06fd3ef7.png">

**Comment by WaynePhillipsEA** [comment]
![tb_autoCaseCorrect](https://user-images.githubusercontent.com/25738109/122424301-83477e00-cf86-11eb-9624-1f7cce7c8116.gif)

The case is considered authoritative at the definition of the symbol.   

The main problem at the moment with this experimental version is that when the case is corrected, this creates an undo-point in the editor, and when trying to undo the edit, the compiler immediately notices the mismatched case again and auto-corrects it again 😁

**Comment by Kr00l** [comment]
I don't know if this falls into this issue, but in VBx the below code
```
Dim Buffer As String
Buffer = Space$(   255)
```
will be "auto corrected" into
```
Dim Buffer As String
Buffer = Space$(255)
```

So basically, will tB be able at some point to erase all "unnecessary" spaces ?
Or is there another issue for that, which I overlooked ?

Thanks

**Comment by WaynePhillipsEA** [comment]
@Kr00l it probably does make sense for me to look at this at the same time

**Comment by Kr00l** [comment]
@WaynePhillipsEA Great! Just for completeness. (You are aware for sure)

There are also "corrections" where a space should be "enforced".
Example:
This..
`Buffer = Left$(Buffer,RetVal)`
Should become to..
`Buffer = Left$(Buffer, RetVal)`

**Comment by WaynePhillipsEA** [comment]
Do we want separate settings for the auto-correction of case and the prettifying of spaces, or put them both under the same option 'Auto Prettify Code' or something like that.  Or do we even need settings at all and just enforce them like the VBE does?

**Comment by Kr00l** [comment]
My vote goes for no setting. (Once it is stable)
This will effectively avoid "unpretty" code snippets in the wild.
But also 1 setting (default Yes once stable) would be OK. So if there is an issue it could be turned off.
However, I see no reason why somebody would turn it off "always".

**Comment by Kr00l** [comment]
Perhaps the compiler "safe mode" setting can disable the "prettify". So it's bundled.

**Comment by WaynePhillipsEA** [comment]
'Auto Prettify Source Code' is now the name of this experimental feature in v0.10.2122.    

Lots of improvements to the prettifier today.   Spacing between arguments in calls is now corrected as you type.  I've only added the spacing correction to call arguments for now, I'll do the same for between operators in the coming days.   

**_If any of you get chance, please do give the prettifier a go and let me know the bugs you find._**     
Though please do BACKUP your twinproj file beforehand.

**Comment by WaynePhillipsEA** [comment]
For the next planned update, I'll excluded the line being edited from being auto-corrected until the cursor is moved away from the edited line.  That way, the behaviour will more closely match what happens in the VBE.

**Comment by mansellan** [comment]
> 
> 
> I don't know if this falls into this issue, but in VBx the below code
> 
> ```
> Dim Buffer As String
> Buffer = Space$(   255)
> ```
> 
> will be "auto corrected" into
> 
> ```
> Dim Buffer As String
> Buffer = Space$(255)
> ```
> 
> So basically, will tB be able at some point to erase all "unnecessary" spaces ?
> Or is there another issue for that, which I overlooked ?
> 
> Thanks

I'm sure you know, but VBx does case-correction by necessity. After you leave a source line, it's compiled to p-code, and that's back-rendered to "source". So symbols have to match either built-in symbols, or those that you define. Extra whitespace doesn't get a look-in.

twinBASIC doesn't do this, It stores the source, and compiles it when you ask it to. Hence not correcting anything, unless Wayne builds a prettifier.

**Comment by mansellan** [comment]
@WaynePhillipsEA, I would vote to eventually make prettification (of both casing and whitespace) the default, once it's stable. I find it's _occasionally_ useful to add whitespace to align cases, but honestly very rarely. I think accessibility trumps flexibility here.

**Comment by WaynePhillipsEA** [comment]
Lots of fixes just gone in to the prettifier, in v0.10.2166

**Comment by WaynePhillipsEA** [comment]
In v0.10.2235, the currently editing line is now NOT auto-corrected until the cursor moves away from the line, much like the VBE behaviour.  Spacing between operators is now auto-corrected too.   There are still many more places that need the spacing to be auto-corrected, but it's starting to feel a lot more like the VBE once the prettifier is ON.

**Comment by Greedquest** [comment]
Should indenting and line-spacing come into this? Or other formatting concerns like where to place line breaks `_`. These are subjective as they are not enforced by the VBE, however having it built into the editor from the beginning would help with consistency.

I guess the scope of what you're willing to prettify is whatever the VBE enforces with its round-trip prettifying, and other formatting tools like smart indenter or something even more substantial like [python's black formatter](https://pypi.org/project/black/) should be IDE plugins or automatic command line tools that can run on and modify a twinproj file?

**Comment by Kr00l** [comment]
I would leave indentation and line spacing off from this, to match VBx and to allow user style. Everybody indents differently. This keeps the coding style flexible. Of course it could be managed by another extra setting, which is then off by default.
My 2 cent. :-)

**Comment by Greedquest** [comment]
@Kr00l I agree, there is no single perfect style given the flexibility of the syntax and everyone's different indentation approaches are legitimate. The idea with such a set of features is to remove the time wasted deciding what the best formatting is, and instead enforce consistency within sensible (minimally configurable) defaults since consistency is IMO what we're really after for readability & clarity. Defining these sensible defaults at an "official" language level so everyone's snippets naturally look similar is the motivation for integrating them with the other prettifying pre-processing steps

**Comment by WaynePhillipsEA** [comment]
`Should indenting and line-spacing come into this?
`
I'm inclined to agree with @Kr00l and say no, as I doubt there would be consensus among everybody.  Though if you've got specific ideas in this regard, I'll certainly be listening.   Once tB provides VS Code with proper code-folding data through the LSP, I believe VS Code should put the default indent point for new lines at the correct position inside blocks, which will certainly help somewhat.  

VS Code offers 'Format Document' and 'Format Selection' options, but tB doesn't yet provide for them through the LSP.  I'll have to look closer at Smart Indenter / Rubberduck to see what work will need to be done to support that feature.

**Comment by Kr00l** [comment]
Just something I noticed and would like to point out. (If not already known)
If the current line got changed (= dirty flag) and the user does not change the cursor and just saves, then the pretty does not get raised and the file is saved un-pretty.
So I guess in the save routine something can/shall be added?

**Comment by Kr00l** [comment]
Also what I noticed is that the prettifier should remove any spaces at the end of a line
![image](https://user-images.githubusercontent.com/33756666/122808596-60420480-d2cd-11eb-8489-eb0e23ee63d4.png)

**Comment by WaynePhillipsEA** [comment]
Thanks @Kr00l  I rewrote the prettifier today.  Almost complete, just need to fix a couple of failing tests in the morning, then we should be good to go.

**Comment by bclothier** [comment]
IMO, the less user configuration, the better. I hate the idea of having X different ways to format code, including the # of indentations, tabs v. spaces, whatever. It may seem minor but it can really grate on one's nerves if one is accustomed to doing it this way and must deal with a codebase that does it Y way. 

For that reason, I'd much rather that there is only one way to format code, so that we don't have to get into the silly debate of "One True Style™®" or be tempted to reformat someone else's code. 

For that reason, "less is more" is what I vote for allowing user configuring the formatting. 

A possible alternative is to allow the code editor to always re-format the code according to the user's preference but I'm hesitant about that because that could end up generating a set of bugs. An opinionated way to format code avoids this unnecessary complexity. We have more important things to do than deciding on the one true style like making wrong code look wrong.

**Comment by mwolfe02** [comment]
@bclothier I have mixed feelings on this.  I like the idea of language-enforced formatting consistency, especially if we all agree to use my personal style 😉.  Seriously, though, I expect there are a lot of codebases out there with a consistent format based on Smart Indenter/Rubberduck/MZ-Tools settings.

I'd prefer to see twinBASIC enforce its preferred style via _default settings_, while still allowing users to override those settings.

Perhaps it makes sense to have project-level settings.  New projects would inherit from a user's default settings.  

This way, large community projects (like Rubberduck, in terms of scale) could enforce a consistent coding-style.  This would also allow organizations to enforce their own internal coding styles, some of which may already be long-established.

**Comment by bclothier** [comment]
FWIW, some time ago, I had worked on a C# GitHub project and made lot of changes to it for better COM interop. Once I got that tested & worked, I figured I'd open a pull request to share. While setting it up, I noticed the diff was way too high. Perplexed, I looked and I found out that they had a coding style that differed only in whitespace (tabs vs. space) so that it wasn't too obvious that it was different from the default C# coding styles but because I was using the default, I now had a bastardized project with 2 different coding style and a bad diff because of that. As a consequence, I had to drop the idea of sharing the changes because I couldn't and didn't want to waste time on figuring out how to fix the differences in the coding styles to conform to theirs. 

Had there been only one coding style, that wouldn't have happened. Hence my inclination toward "less is more" philosophy especially over something like formatting which _should_ have no impact on the code's behavior but _does_ impact the sharing of the code. I do think that for tB to succeed, it needs to encouraging sharing, and having only one style helps a lot in that respect. The idea of having a project-level setting may help but that implies that it's a part of the repository and that we won't have any unintentional bugs due to migrating from one coding style to another.

**Comment by WaynePhillipsEA** [comment]
We could have the prettifier auto-correct dates from the usual US format, to a more universal one, e.g.

#1/8/2020#  gets auto-corrected to   #8-Jan-2020#

Thoughts?    I'm thinking of adding this to the prettifier, and making it the default behaviour.

**Comment by bclothier** [comment]
I agree wholeheartedly with the idea but not the format. To avoid i18n issues with month and weekday names, best to format them as `YYYY-MM-DD HH:NN:SS` (the ODBC canonical format) or `YYYYMMDDTHHNNSSZ` (ISO-8603). Every programmer should be using the non localized and unambiguous format.

Oh, yes, I believe in One True Date Format. ;-)

**Comment by WaynePhillipsEA** [comment]
@bclothier  from a programmers perspective I absolutely agree.  However, from a BASIC point of view, which follows English language constructs, I'm not so sure.  For example I've never heard anyone in the real world describe a date to me starting with the year.

I still think that DD-MMM-YYYY (HH:NN:SS) format is unambiguous and much more BASIC-like.  It is also only a minor variation on the existing VB6/VBA format.

**Comment by Kr00l** [comment]
VBx is english-based. A literal decimal is always with a dot char, regardless of the decimal seperator system setting. So the date literal must be english-based too. And I agree with @WaynePhillipsEA that a "more" readable english-based date literal is better than nothing.

**Comment by wqweto** [comment]
I've had troubles submitting patches to C# projects because of different "prettifier" settings.

Not sure if in latest VS they allowed repo's formatting option to be embedded in the project file (or in a separate editor config file) which would have prevented so much PITA in first place.

**Comment by WaynePhillipsEA** [comment]
@wqweto I decided not to add any options for the prettifier in tB.  VB6/VBA managed pretty well without them, despite them being a little restrictive on occasion.

**Comment by WaynePhillipsEA** [comment]
As of v0.10.2477, the prettifier is now out of the experimental stage, and active by default.  You can disable it through the project setting.  Closing this issue for now as the discussions around the potential formatting feature should be a separate issue.

**Comment by Kr00l** [comment]
The entire experience feels now elevated and really like a VBE editor. Not to underestimate.. :-)
