### ISSUE TITLE
UDT/Enum with no members should not compile

### ISSUE THREAD

**Issue by cristianbuse** [WaynePhillipsEA/twinbasic#170]
**Describe the bug**
User Defined Types and Enumerations without members should not be allowed.

**To Reproduce**
```VBA
Module Test
    Public Type TESTUDT
    End Type
    Public Enum TESTENUM
    End Enum

    Public Sub Main()
        Dim x As TESTUDT
        Dim y As TESTENUM
        Debug.Print VarPtr(x)
        Debug.Print VarPtr(y)
    End Sub
End Module
```

**Expected behavior**
The above code should not compile. UDTs and Enums should have at least one member.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 20H2
 - twinBASIC compiler v0.10.660

**Additional context**
Unimportant, but the memory addresses for the ```x``` and ```y``` variables are exactly the same. They would be different if the UDT had members.

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.717.  Thanks for reporting.
