### ISSUE TITLE
With block not working on ByRef UDT

### ISSUE THREAD

**Issue by cristianbuse** [WaynePhillipsEA/twinbasic#171]
**Describe the bug**
With blocks on User Defined Types don't work when passed to a different method ```ByRef```

**To Reproduce**
```VBA
Module Test
    Public Type TESTUDT
        m1 As Long
    End Type

    Public Sub Main()
        Dim x As TESTUDT

        x.m1 = 5
        UseUDT x
        With x
            Debug.Print .m1
        End With
    End Sub
    
    Public Sub UseUDT(ByRef u As TestUDT)
        With u
            Debug.Print .m1
        End With
    End Sub
End Module
```

**Expected behavior**
The above code should compile

**Screenshots**
![test](https://i.stack.imgur.com/zG3fH.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 20H2
 - twinBASIC compiler v0.10.660

**Additional context**
With block works just fine within the scope of the method where the UDT is declared.

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.717.  Thanks for reporting.
