### ISSUE TITLE
Multiple implementations of one interface member should be disallowed

### ISSUE THREAD

**Issue by mansellan** [WaynePhillipsEA/twinbasic#172]
**Describe the bug**
Multiple implementations of a single interface member in the same class should be a compile error

**To Reproduce**
``` vb
Public Module Module1

    Sub Main()
        Dim TheFoo As IFoo = New Foo
        TheFoo.GetFoo
    End Sub

End Module

Public Interface IFoo
    Public Function GetFoo() As Boolean
End Interface

Public Class Foo 
     Implements IFoo
    
    Public Function Method1() As Boolean Implements IFoo.GetFoo
        MsgBox "First Method1"
    End Function
    
    Public Function Method1() As Boolean Implements IFoo.GetFoo
        Msgbox "Second Method1"
    End Function
    
End Class
```
Shows "First Method1"

**Expected behavior**
Compile error, with red squigglies on the multiple implementations

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.10.660

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.810, thanks for reporting
