### ISSUE TITLE
Issue with UDT containing a member defined as Enum

### ISSUE THREAD

**Issue by cristianbuse** [WaynePhillipsEA/twinbasic#174]
**Describe the bug**
Code execution freezes while debugging if expanding a User Defined Type containing an Enumeration.

**To Reproduce**
Run code:
```VBA
Module Test
    Public Enum TESTENUM
        v = 1
    End Enum
    Public Type TESTUDT
        m As Long
        u As TESTENUM
    End Type

    Public Sub Main()
        Dim x As TESTUDT

        Debug.Print x.u
        Stop
    End Sub
End Module
```
and when execution breaks on the ```Stop``` line go to the Locals window and click the arrow next to the ```x``` variable.

**Expected behaviour**
Should not freeze execution.

**Screenshots**
![test](https://i.stack.imgur.com/7I7UX.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise V1909
 - twinBASIC compiler v0.10.717

**Additional context**
None

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.810, thanks for reporting
