### ISSUE TITLE
[QUESTION] plans about android ?

### ISSUE THREAD

**Issue by graysuit** [WaynePhillipsEA/twinbasic#178]
`Compiles to Win32 and Win64 architectures. Mac, Linux and Android compilation planned.`
As the wiki on main page states that support for android is planned.
Now my concerns are whether android development would be pure native as well ?

I rarely see native development for android part. Most ones use java byte code, and say its name as native development. lol
And if yes, what framework will you use ? Is it ndk ?
And how much android versions would be supported ?
And what would be final release size of hello world apk ?
And what would be compilation speed of twinbasic for compiling an apk ?

I'm very excited and interested about twinbasic development. 
Regards & Thanks.

**Comment by WaynePhillipsEA** [comment]
The vague plan here is indeed to offer native compilation (not java byte code etc).  However, Android support will undoubtedly come last, with Mac/Linux support coming first (and initially on x86 architectures).

Following the current twinBASIC path, you can of course expect super small file sizes for APKs, and compilation in the blink of an eye.  😉

**Comment by graysuit** [comment]
Really impressive !
Freelancers and I would surely wait for easy mobile development.

And whats estimated time ?
And do you work single ? without getting any coding help from community ?

**Comment by WaynePhillipsEA** [comment]
Thanks!  My partner Louise works for me doing mostly admin work and keeping my other business running.

The community here are an amazing help in testing and finding all the weird edge cases of the classic VB language.  They are also very knowledgeable folks and provide fantastic feedback that helps improve tB now and in the future.

**Comment by graysuit** [comment]
Most folks here are derived from vbforum. 
That forum mostly contain old and stone users of vb6. 
So they are very thirsty for vb6 maintenance. They fear ms will end vb6 runtime as well on later releases. So they are finding alternatives.

As twinbasic is development is completed to be usable for normal use, I and other developers will start spreading the word "twinbasic".
My wishes are with twinbasic. I hope it would become an monster of software development with keeping the old strategy. 
Cheers !

**Comment by WaynePhillipsEA** [comment]
Thanks for your support!
