### ISSUE TITLE
Offer proper block-based code folding

### ISSUE THREAD

**Issue by WaynePhillipsEA** [WaynePhillipsEA/twinbasic#18]
**Describe the solution you'd like**
Block based code folding needs to be implemented.  Currently, twinBASIC doesn't provide code folding information via LSP, so VS Code only offers tab-based code folding, which is inferior.

**Comment by mansellan** [comment]
Can it also please support the [#Region directive](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/directives/region-directive)? Although sometimes abused, it's still occasionally useful.

**Comment by WaynePhillipsEA** [comment]
Now available in v0.10.3212.  Got to it at last :)   Also includes support for `#Region` statement, as requested by @mansellan
