### ISSUE TITLE
Breakpoints not working on ElseIf/Else lines

### ISSUE THREAD

**Issue by cristianbuse** [WaynePhillipsEA/twinbasic#181]
**Describe the bug**
Breakpoints are not working on ```ElseIf``` or ```Else``` lines.

**To Reproduce**
```VBA
Module Test
    Sub Main()
        If Bool("IF") Then
            Debug.Print "IF"
        ElseIf Bool("First ElseIf") Then
            Debug.Print "First ElseIf"
        ElseIf Bool("Second ElseIf") Then
            Debug.Print "Second ElseIf"
        Else
            Debug.Print "Else"
        End If
    End Sub
    
    Private Function Bool(ByVal note As String) As Boolean
        Debug.Print note & " was reached"
    End Function
End Module
```

**Screenshots**
![test](https://i.stack.imgur.com/CVEzk.png)

**Expected behavior**
The above code prints correctly. However, no breakpoints work if set on the ```ElseIf``` or ```Else``` lines while in VBA are working.

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise V1909
 - twinBASIC compiler v0.10.871

**Additional context**
Stepping through lines in debug mode also skips the ```ElseIf``` and ```Else``` lines.

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.1066, thanks for reporting.
