### ISSUE TITLE
Not Not Operator

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#184]
**Describe the bug**
The "Not Not" operator is not recognized. It states "[not] operator not allowed here"

**To Reproduce**
```
Public Function UTF8_To_UTF16(ByRef Source() As Byte) As String
If (0 / 1) + (Not Not Source()) = 0 Then Exit Function ' Legacy way for VBx
If IsArrayInitialized(Source()) = False Then Exit Function ' > Preferred way for tB <
' ...
End Function
```

**Expected behavior**
Even though there is a solution (IsArrayInitialized) there might be other edge cases where Not Not might be needed, which I am not aware right now. However, to be fully 100% compatible it should be supported somehow.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.10.933]

**Additional context**
n/a

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.1066, thanks for reporting.
