### ISSUE TITLE
Multifile project showing three editing issues

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#194]
**Describe the bug**
There are three issues
1.  Even minor edits cause the compiler to crash such that twinbasic is effectively unusable.
2. After splitting the previous single file into module and class related files the keyword colour coding seems out sync  in places (see Kvp.twin).
3.  The lines in which errors occur, as indicted by the red lines in the overview window ,are off screen when shown as included by the preview window scroll bar (See error at line 2081 in Kvp.twin)

The project is attached.

[twinBASIC_VBALib.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6607891/twinBASIC_VBALib.zip)

**Comment by WaynePhillipsEA** [comment]
@FullValueRider thanks for the bug report.  I've located the #1 error and fixed internally.   I'm looking into #2.

For #3, could you show me a screenshot?  I'm struggling to understand that one.  Thanks.

**Comment by FullValueRider** [comment]
The block you drag to scroll up and down the current editing window encompasses the red error indicator but the error line is not in the editor window.  Its difficult to show on a screen grab because the grey block doesn't appear unless the mouse cursor is over the vertical scroll bar or in the current edit window.

![image](https://user-images.githubusercontent.com/81257042/121016103-a5c1e600-c793-11eb-8839-409c0dc74433.png)

**Comment by WaynePhillipsEA** [comment]
<img width="337" alt="fullValueRider1" src="https://user-images.githubusercontent.com/25738109/121024682-5cc25f80-c79c-11eb-8d0e-9ed80290a224.png">

Looks OK here.  twinBASIC provides the error information to VS Code, but doesn't have any involvement in the rendering of the window, so provided the correct part of the code is underlined in the main window, then it is a VS Code rendering bug.

**Comment by WaynePhillipsEA** [comment]
1 & 2 fixed in v0.10.1164.  Thanks for reporting.
