### ISSUE TITLE
Editor crashing at first use

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#198]
**Describe the bug**
Following the update to v0.10.1164 and a short editing session I am once again stuck with a crashing compiler. Its not possible to do further editing as the compiler crashes when VScode starts up twinBasic.  Project attached
[twinBASIC_VBALib.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6611776/twinBASIC_VBALib.zip)

**Comment by WaynePhillipsEA** [comment]
Apologies.  This wasn't actually specific to v0.10.1164.   The particular typo in your code would have tripped up all recent versions.  Fixed in v0.10.1168.  Thanks for reporting.
