### ISSUE TITLE
"Extract to File" refactoring

### ISSUE THREAD

**Issue by retailcoder** [WaynePhillipsEA/twinbasic#2]
**Is your feature request related to a problem? Please describe.**

When twinBASIC starts supporting multiple files per project/workspace, it would be nice to have a tool that can extract all the types (or a selection thereof) in a code file, into as many separate code files named after their respective defining type.

**Describe the solution you'd like**

I suppose the dream would be a diagnostic that squiggle-underlines a class that isn't named as per its containing .twin file, and offers a quick-fix to extract that class into a `{classname}.twin` file under the project's `\Sources` folder, ideally with options to apply that fix to all occurrences of this diagnostic, making it possible to explode a potentially huge single-file / multiple-component .twin project into as many single-component files, with a single click.

**Comment by WaynePhillipsEA** [comment]
This refactor is now implemented in v0.10.3256, although the UX around this area will improve once warnings are implemented (#208), where it will be shown as a quickfix.   For now, you need to put the caret on the first line of the definition to get the light bulb:

<img width="377" alt="tb_refactor_moveFile" src="https://user-images.githubusercontent.com/25738109/124091098-62366100-da4d-11eb-8183-f4bfddb6552f.png">

Attributes will also be moved.
