### ISSUE TITLE
InIDE() problem one liner syntax

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#205]
**Describe the bug**
In VB6 the below code is commonly used to know if the code is currently running in the IDE or not.
tB seems to have a problem here in the one liner version.

**To Reproduce**
Not working (one liner)
```
Private Function InIDE(Optional ByRef B As Boolean = True) As Boolean
If B = True Then Debug.Assert Not InIDE(InIDE) Else B = True
End Function
```

Working! (long version)
```
Private Function InIDE(Optional ByRef B As Boolean = True) As Boolean
If B = True Then
    Debug.Assert Not InIDE(InIDE)
Else
    B = True
End if
End Function
```

**Expected behavior**
To have the one liner version also working.

**Screenshots**
![image](https://user-images.githubusercontent.com/33756666/121353375-17359c00-c92e-11eb-9bab-d1db2be6de6a.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.10.1315]

**Additional context**
n/a

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.1386, thanks for reporting.
