### ISSUE TITLE
Update "getting started" text on the Details page of the VS Code extension

### ISSUE THREAD

**Issue by mwolfe02** [WaynePhillipsEA/twinbasic#219]
Here is the current text (note the reference to downloading the .zip file):

![image](https://user-images.githubusercontent.com/305213/121818504-a35d0180-cc55-11eb-8be9-f0e451701fda.png)

With the implementation of the 'Create new twinBASIC project' feature in v0.10.1386, this text should be updated to advise new users to make use of this feature.

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.1616, thanks!
