### ISSUE TITLE
Offer build type of 'Standard DLL', without COM registration

### ISSUE THREAD

**Issue by WaynePhillipsEA** [WaynePhillipsEA/twinbasic#22]
**Describe the solution you'd like**
We should allow creation of standard (non-ActiveX) DLLs from twinBASIC.  For this to work, we'd need to allow module procedures to be exposed via DLL entry points in the compiled PE file.   VBA for instance, could then just reference the generated DLLs via Declare statements, without the need to register the DLL in the registry at all.   Other languages can also easily reference the generated DLLs, using standard LoadLibrary()/GetProcAddress() Windows calls.

**Additional context**
We'd need to consider a new keyword to add to procedures that we want to expose.  e.g.
   Exposed Function GetMyClass() As MyClass
      Set GetMyClass = New MyClass
   End Function

In this example, the caller can then either use the returned object late-bound as an Object type, or they could reference a separate type-library that we can generated alongside the DLL file that has the MyClass defined in it.  The type library would not need to be registered on end-user systems, as you are not relying on COM for instantiating the class.

Being able to create registration-free DLLs could be a really good feature.

**Comment by mansellan** [comment]
Would this allow for callers to access overloaded methods?

**Comment by retailcoder** [comment]
And generics?

**Comment by WaynePhillipsEA** [comment]
No, for those scenarios we'd need something akin to a MAP file in C that defines the DLL entry points to be exposed.  e.g.

    Expose GetMyClass(Of Long) As "GetMyClassLong" 
    Expose GetMyClass(Of Double) As "GetMyClassDouble"

**Comment by bclothier** [comment]
Just a thought. 

Instead of having to choose between a standard vs. ActiveX EXE/DLL project types, allow the author to specify what should be exported and how it will be exported. 

Because all types defined in BASIC are COM by default, it makes sense to mark a module or class as non-COM-visible. If it's not visible, then twinBASIC simply don't have to generate the type library information for that type. 

That would then allow us to implement the common functions such as `DllRegisterService` simply by exposing it without requiring any special wrapper or whatever.

**Comment by mansellan** [comment]
Also, perhaps the syntax should follow the existing import syntax:
```[Public | Private] Declare Sub name Lib "libname" [Alias "aliasname"] [([arglist])]```
```[Public | Private] Declare Function name Lib "libname" [Alias "aliasname"] [([arglist])] [As type]```

so, maybe:
```[Public] Export Sub name [Alias "aliasname"]```
```[Public] Export Function name [Alias "aliasname"]```

**Comment by WaynePhillipsEA** [comment]
I don't see the need for the Public specifier, since exporting makes it publicly accessible.  Perhaps we should enforce module qualifiers?....

Export Sub MyModule.MyProc [Alias "aliasname"]
Export Function MyModule.MyProc [Alias "aliasname"]

**Comment by retailcoder** [comment]
IMO the simpler the better; I would expect public types to be COM-visible by default (unless it doesn't have a default/parameterless ctor, exposes public method overloads, or is a generic type), and making a type `Private` would make that type not COM-visible.

In other words, why shouldn't access modifiers alone drive what types get exported?

It appears the current implicit access modifiers are `Private Module` and `Public Class`; would supporting explicit modifiers not adequately address this concern? Put the private stuff in a private module, and the exposed stuff in a public one?

**Comment by bclothier** [comment]
I agree with keeping it simple as possible.

A question, though. Is there a reason to have a `Public` class that's not COM-visible? For example, exposing it for use  by other tB DLL/EXE? 

My inclination is to say no. If it's public, then it's gonna to be COM-visible but maybe there's a case I'm missing.

**Comment by mansellan** [comment]
@WaynePhillipsEA  I proposed Public as optional for that reason - superfluous but not a compiler fail either. But not really fussed.

**Comment by WaynePhillipsEA** [comment]
@retailcoder Thinking only about compatibility with VB6, 'public' modules (i.e. ones that don't have Option Private Module set) don't get output to the type library.  I'm not sure if you were suggesting that making a module Public would automatically mean that its members get added as DLL exports(?), but we can't do that due to backwards compatibility since VB6 doesn't do that.

So if we want to keep the DLL exports really simple, we could just add a keyword to the Module syntax...   Export Module?

`Export Module MyDllEntryPoints
   Function GetMyClass() As MyClass
      Set GetMyClass = New MyClass
   End Function
End Module`

You wouldn't be able to offer generics or overloads in 'Export' modules though, but I'm not sure that it matters all that much.

**Comment by WaynePhillipsEA** [comment]
To better clarify the intent, perhaps DllExport as the modifier name:

DllExport Module MyDllEntryPoints
   Function GetMyClass() As MyClass
      Return New MyClass
   End Function
End Module

**Comment by WaynePhillipsEA** [comment]
Considering proper attributes support as discussed in #25, it would now be worth considering NOT adding a DllExport modifier to the syntax, and instead use an attribute for this.  So my new proposed syntax would be:

```
[DllExport]
Module MyDllEntryPoints
   Function GetMyClass() As MyClass
      Return New MyClass
   End Function
End Module
```

And as mentioned in #29, if the project produces a type library, then the type library should include a module containing the exported DLL entries from the DllExport module.

**Comment by bclothier** [comment]
I think the attribute is the way to go. You gain the ability to provide updates to the `DllExport` attribute or to delegate to a new attribute to handle the edge cases without having to change the language itself.

**Comment by mansellan** [comment]
I just realised there wasn't yet a discussion on namespaces, so I added #111. It's a thorny subject to be sure. For this particular issue though, I don't think it's necessary to solve - a simple means to alter the name of the imported library space should be all that's needed here?

**Comment by XusinboyBekchanov** [comment]
Do this:
```
Sub MySub Alias "MySub"() Export
End Sub
```

**Comment by DaveInCaz** [comment]
VB6 sort of had support for fucntion exports, but it required external help. I was only vaguely familiar with this from vbAdvance: https://classicvb.net/tools/vbAdvance/ ... but there might have been other approaches as well.

The vbAdvance add-in to the VB6 IDE could do...

> **Function Exports -** Build standard DLLs that export functions using Visual Basic. Function exports are required for certain application types such as Control Panel Applets. Having access to this feature allows you to build these applications using VB. You can also implement the DllInstall feature of RegSvr32.exe in your DLLs to provide command-line switch customized registration of your DLLs. Many application plug-ins, such as WinAmp and InstallShield plug-ins, require function exports, which means you can now use Visual Basic to create them instead of having to resort to another language, or rely on non-VB proxy DLLs and the troubles that go with them.

It did this by letting you pick functions (or subs?) in a GUI:
![image](https://user-images.githubusercontent.com/18285074/127876770-59fb14e1-0c0b-4be1-b0aa-ff1de7aa9c44.png)

I recall reading somewhere that the underlying capability for this actually existed in the VB6 compiler but for whatever reason wasn't exposed in the language or IDE.  So there may be some VB6 projects for which TB should _ideally_ be able to produce "identical" or at least close equivalent exports to whatever the VB6 compiler would have done.

(I don't think the GUI-only approach would really be ideal for TB however. )

**Comment by WaynePhillipsEA** [comment]
@DaveInCaz that's cool.  I didn't know about that, but makes sense since the linker (which produces the DLL export table) was probably shared with MSVC at that time.

It looks like vbAdvance didn't do any name mangling, so it should be easily ported to twinBASIC with the attributes mentioned in https://github.com/WaynePhillipsEA/twinbasic/issues/22#issuecomment-831212032

**Comment by madeinaus** [comment]
VB6 'Native Code' generation used the same compiler/linker as c++. Only the first pass language parsing was different. Renaming the VC++ execuatable/dll allows you dummy the second pass compiler and pass the command-line arguments for DLL building instead of EXE building.

**Comment by WaynePhillipsEA** [comment]
`Standard DLL` is now a supported build type (via Settings -> Project: Build Type).  This option produces a lightweight non-ActiveX DLL.

`[ DllExport ]` attribute is also now supported above module procedures.  If you want to change the exported symbol name, you can provide a string name: `[ DllExport ("MyFunction") ]`

**Comment by bclothier** [comment]
Thinking that's a good candidate for a compiler warning. IDK if it's necessarily a good idea to rely on object startup via LoadLibrary because we can't be sure that it's safe to load an object at that point, right?

**Comment by bclothier** [comment]
I was thinking about the windows service -- I don't know enough but if one wanted to build a windows service that had the support for GUI, that'd be one way to do it but in that case, I would imagine that the object startup must be done on a new thread, independent from the thread that runs the DllMain functions. I don't know if that is a legitimate scenario as I don't know enough about the windows service architecture.

**Comment by WaynePhillipsEA** [comment]
I suppose one valid use case would be a resource-only DLL.

**Comment by WaynePhillipsEA** [comment]
> I was thinking about the windows service -- I don't know enough but if one wanted to build a windows service that had the support for GUI, that'd be one way to do it but in that case, I would imagine that the object startup must be done on a new thread, independent from the thread that runs the DllMain functions. I don't know if that is a legitimate scenario as I don't know enough about the windows service architecture.

Windows services tend to have their GUI as a completely separate, normal (non-service) process, that connects to the service process.

**Comment by Greedquest** [comment]
@WaynePhillipsEA Could you explain a little more about what the VB6 precedent for this is; certainly there were no attributes like [DllExport] for saying what parts of the library were COM visible. How did it work in VB6? I have a VBA background. My understanding comes from how one excel file can reference another. There you consider things like `Option Private Module` for standard modules and `Public Not Creatable` for class modules, these dictate what stuff defined in project A can be accessed in some shape or form from project B. Is it the same sort of rules for VB6, except we have project A as a dll rather than a .xlam? 

All I would say is that I agree with @retailcoder that from a language design p.o.v. `Public`, `Exposed` and `DllExport`ed are all slightly confusing overlapping terms.

I guess what you're saying is about VB6's `Option Private Module` mapping onto `Public/Private Module` in twinBASIC. Is that a set-in-stone decision? I think we could consider using the new Public/Private Module/Class for a slightly different purpose, and have `[Instancing PublicNotCreatable]` `[Instancing Private]` `[Option Private Module]` etc. as attributes inside the body of the module. Then perhaps a `Private` Module could be something entirely different to `[Option Private Module]`. 

IMO the Public/Private access modifiers on modules and classes should be used for some tB-only NEW functionality (I'm thinking about namespaces), and the old VB* functionality to do with exposing projects could be achieved with `[attributes]`.

**Comment by bclothier** [comment]
@Greedquest, those are different things. 

With a standard DLL, the only way you can interact with it (at least initially) is via a `Declare` statement. You cannot reference that DLL like you would another COM library and use objects. You could in theory define a `Declare` statement that returns an object but there will be other complications. However, the intention here is to have a flat DLL that exposes some functions that you can use from VBA easily without any registration; just drop in the DLL in a folder and point your `Declare` to it (or use `LoadLibrary`) and you're all set to use the code from that DLL. 

This is great for writing algorithms or things like that where you don't want overhead of objects, registration & references.

**Comment by Greedquest** [comment]
@bclothier Thanks, yeah I understand the difference between a _registered_ dll (that lets you instantiate objects via New or CreateObject and exposes standard modules and methods) versus the feature proposed in this issue, which is for a flat dll that only exposes functions and methods, not class "templates" (as you say, those functions _could_ still return an object _instance_, as in the example in Wayne's first post. They just cannot define a class or anything that can be "Newed up").

No the thing I'm really asking relates to something Wayne said earlier: https://github.com/WaynePhillipsEA/twinbasic/issues/22#issuecomment-820538463

> I'm not sure if you were suggesting that making a module Public would automatically mean that its members get added as DLL exports(?), **but we can't do that due to backwards compatibility since VB6 doesn't do that.**

I'm questioning the implicit assumption that `Public/Private Module` in tB means the same thing as `Option Private` in VB*. I think the Public access modifier in tB should have it's own meaning for some concept not even possible to represent in VB*. I need to flesh the idea out a bit more.

**Comment by bclothier** [comment]
Except, the whole thing about exporting functions is not technically a part of the compilation of the tB source file but rather a post-compiler activity. I have this mental image of those being a "compiler service" and all attributes tend to work like that. The export of a function and the visibility of a function are two unrelated things because the `Public`/`Private` modifier relates to the tB source code whereas `DllExport` relates to whether the function is added to an export table. IMO, to make it a keyword would be to mix 2 different concepts and confuse the language. Ditto for vice versa.

**Comment by WaynePhillipsEA** [comment]
> > Sure, there are certain things you shouldn't do during the DllMain events.
> 
> For instance loading other DLLs is strictly forbidden in DllMain but not in VB's `Sub Main`.
> 
> Is this different in TB and now we should heed DllMain's limitations in TB's `Sub Main`?
 
It's on my long list to change tB's ActiveX DLLs to fire Sub Main from DllGetClassObject instead of DllMain.  I've bumped it up the list to do it tomorrow as I had largely forgotten about it.   Whilst I'm in there, I'll also change the behaviour for Standard DLLs to match (so that every entry point first checks if Sub Main call is needed).

**Comment by WaynePhillipsEA** [comment]
Do we want a new project type of `Standard DLL` on the new-project dialog?  Perhaps with a description of `(non-ActiveX)` underneath it?
