### ISSUE TITLE
Enumerations Crash

### ISSUE THREAD

**Issue by Dragonock** [WaynePhillipsEA/twinbasic#220]
**Describe the bug**
When creating Enumerations for some reason line number 14 causes TwinBasic to crash entirely and the project freezes up and the only way to close is via Task Manager. This freeze doesn't occur in Vb6, so I'm assuming this is a bug as I can't use line 14 which is from my legacy Vb6 code.

**To Reproduce**
1. Create New Project
2. Type in Line Number 14
3. TwinBasic will crash entirely

**Expected behavior**
To run smoothly and not crash

**Screenshots**
TwinBasic Crash
https://i.imgur.com/RPuZGWQ.png

Vb6 Normal
https://i.imgur.com/ft6xxOP.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version [e.g. 0.9.1111]

**Comment by WaynePhillipsEA** [comment]
This should now be fixed in v0.10.1604.  Thanks for reporting.
