### ISSUE TITLE
API Declaration with identifier type character not working

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#221]
**Describe the bug**
API Declaration without an explicit return type, e.g. `As Long` throws an syntax error "no handler for this symbol".
The return type is declared with an literal identifier type character. (& = As Long)

**To Reproduce**

```
Module MainModule

Private Declare Function MessageBeep& Lib "user32.dll" (ByVal wType As Long)

Private Const MB_OK As Long = &H0

    Public Sub Main()
        
        Call MessageBeep(MB_OK)
        
    End Sub

End Module
```

**Expected behavior**
The API Declaration should as with the "normal" API Declaration.
`Private Declare Function MessageBeep Lib "user32.dll" (ByVal wType As Long) As Long`

**Screenshots**
![image](https://user-images.githubusercontent.com/33756666/121882352-b7b20480-cd10-11eb-8b67-6e0c02d5df63.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [0.10.1455]

**Additional context**
The unusual API Declaration (with the identifier type character) works in VBx and should also work in tB for compatibility reasons.

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.1615, thanks for reporting.
