### ISSUE TITLE
comma and semicolon inactive after Debug.print in a loop

### ISSUE THREAD

**Issue by camomille22003** [WaynePhillipsEA/twinbasic#223]
**Describe the bug**

**To Reproduce**
Dim i As Byte
For i = 0 To 5
   Debug.Print i ' result A
Next i
For i = 0 To 5
  Debug.Print i;  ' result B
Next i
Debug.Print
For i = 0 To 5
  Debug.Print i,  ' result C
Next i

**Expected behavior**

In Tb result A or B or C = result A

for equivalence with VB6 :

; = ;Spc(0);
, = ;Spc(11);
**Screenshots**

![DebugPrint](https://user-images.githubusercontent.com/33807881/122203558-73546f00-ce9e-11eb-8ad4-11d005b00a35.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.10.1628]

**Additional context**

**Comment by WaynePhillipsEA** [comment]
This should now be working as of v0.13.27.  Thanks for reporting.

**Comment by WaynePhillipsEA** [comment]
@KarlSevenSeven that's a known issue where the tB prettifier 'corrects'/formats the code to its expectations (which is slightly different to VBx in a few instances).  The corrections that tB makes form part of VS Codes undo stack, and so the first undo request puts back the code before the auto-correction, and then the tB prettifier kicks in again to auto-correct it...  so at the moment you have to be quick :)

**Comment by KarlSevenSeven** [comment]
It's not that important.
Only wanted to mention it.

**Comment by WaynePhillipsEA** [comment]
Well, it does need fixing... just priorities.

**Comment by camomille22003** [comment]
the right of the console is invisible because no Hscroolbar
![HScrool_console](https://user-images.githubusercontent.com/33807881/145777274-43e0d4ac-efb5-4878-8c65-66ede4dac0c6.jpg)
