### ISSUE TITLE
Apologies.  I've broken the editor/compiler again

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#231]
updated to 1923.  Following the update my project loads into vscode but the compiler does not connect.

[twinBASIC_VBALib.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6676535/twinBASIC_VBALib.zip)

**Comment by WaynePhillipsEA** [comment]
No, it is my apologies that are due 😜

Fixed in v0.10.2122, thanks!
