### ISSUE TITLE
Prettify space - argument in bracket

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#239]
**Describe the bug**
The prettifier (here MsgBox) erases the space for an argument which is in a bracket.

**To Reproduce**
```
    Public Sub Main()

        MsgBox(1 > 2)

    End Sub
```

**Expected behavior**
```
    Public Sub Main()

        MsgBox (1 > 2)

    End Sub
```

**Screenshots**
tB
![image](https://user-images.githubusercontent.com/33756666/123428909-9b428180-d5c6-11eb-8e19-f197a7232870.png)

VB6
![image](https://user-images.githubusercontent.com/33756666/123428879-8fef5600-d5c6-11eb-9de0-4b8957d652b6.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.10.2773]

**Additional context**
n/a

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.3423, thanks for reporting.
