### ISSUE TITLE
VS-Code: Create a new workspace not possible

### ISSUE THREAD

**Issue by uwbwsvd** [WaynePhillipsEA/twinbasic#241]
**Describe the bug**
The command "Create new project" don't finish its work
**To Reproduce**

1. F1
2. Select "twinBasic: Create new project" etc.
4. In the Twinbasic section of the explorer appears "Not Connected [Compiler, LSP, DAP, FS]"
5. nothing else happend.

Screenshot:
![grafik](https://user-images.githubusercontent.com/41230018/123476008-723ce380-d5fc-11eb-9509-4b6e3657398a.png)

![grafik](https://user-images.githubusercontent.com/41230018/123475725-16725a80-d5fc-11eb-8514-5b2fb9237db6.png)

 - twinBASIC compiler version v0.10.2773

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting this.  Is your machine heavily locked down?  The twinBASIC VS code extension relies on a separate EXE for the compiler services, and if that compiler EXE is unable to launch (for example in a corporate environment that prevents unauthorised EXEs to be run), then you'll see messages like this.  Heavy-handed antivirus software could also potentially have the same effect.

**Comment by uwbwsvd** [comment]
Sorry I do not really know, what "heavily locked down" means. I did some tryings a few days ago and had fun. And now nothing works. I deleted a older extension in the .vscode folder by hand perhaps is this the reason. I deleted the extension and reinstalled it.
I can start the 
![grafik](https://user-images.githubusercontent.com/41230018/123478053-348d8a00-d5ff-11eb-89bf-8b3d74aded0c.png)
allone.

**Comment by WaynePhillipsEA** [comment]
Ah, now I rewrote the parsing of the command line arguments in the last few releases and I'm betting that the space in your Windows username that I can see in your screenshot is throwing it off.  I'll check it out tomorrow and if that's all it is, it will be an easy fix.

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.2780.  Thanks for reporting.
