### ISSUE TITLE
Unable to load resource with ResourceHacker

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#247]
**Describe the bug**
When creating a new Standard EXE project (via F1) and just remove the ICON folder in the resources section the compiled executable cannot be opened by the tool ResourceHacker.

**To Reproduce**
Vanilla Standard EXE project and just remove ICON folder
![image](https://user-images.githubusercontent.com/33756666/123924770-91d06500-d98a-11eb-8309-c6ca83fe3a48.png)

**Screenshots**
Trying to open tB "NewProject_win32.exe"
![image](https://user-images.githubusercontent.com/33756666/123924925-b4fb1480-d98a-11eb-8dcf-ec693462881e.png)

**Expected behavior**
a similar VB6 with a manifest resource just opens fine with ResourceHacker. So something must be wrong.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.10.2914]

**Additional context**
An un-modified new project in tB gets open fine with ResourceHacker. (ICON folder not removed)
![image](https://user-images.githubusercontent.com/33756666/123925540-4cf8fe00-d98b-11eb-87a6-1d93fbc9ca94.png)
However, something must be wrong, because when attempting to delete the ICON
![image](https://user-images.githubusercontent.com/33756666/123925608-5edaa100-d98b-11eb-8e40-972dc2940802.png)
the following error occurs
![image](https://user-images.githubusercontent.com/33756666/123925666-6dc15380-d98b-11eb-8241-ed26a0f8ea2d.png)

**Comment by Kr00l** [comment]
Addirional info:
A vanilla hello world project runs fine in win10.
However, ob a win XP vm it runs only when there is no resource at all.
So that's indicating that something is off for the resources which win10 forgives.

**Comment by WaynePhillipsEA** [comment]
Thanks @Kr00l, I'll look into this later today.

**Comment by WaynePhillipsEA** [comment]
@Kr00l I suspect it's the empty string table that is being generated being the problem.  Could you add a string localization and test on Win XP again?

**Comment by Kr00l** [comment]
> @Kr00l I suspect it's the empty string table that is being generated being the problem. Could you add a string localization and test on Win XP again?

I played around with it and it runs on WinXP when no MANIFEST is inside the resource file. So the string table does not matter here.
I tried even to import a resource file (with ResourceHacker) from a VB6 project into the tB exe and it fails on Win XP.
So, my feeling is that it has something todo with the visual styles and the Win XP OS. However, a VB6 exe does not fail with a MANIFEST on Win XP...

**Comment by WaynePhillipsEA** [comment]
Thanks. I'll fire up my WinXP box tomorrow and find out what's going on.

**Comment by Kr00l** [comment]
Confirm that ResourceHacker issue is solved.

**Comment by Kr00l** [comment]
I found this article which describes perfectly the scenario with an app that refuses to start with an manifest on WinXP. [Dev-cpp XP manifest file](https://www.daniweb.com/programming/software-development/threads/180286/dev-cpp-xp-manifest-file/amp)
They described the solution to call InitCommonControlsEx() at startup.
So that is no bug on tB.
And I know remember that this is a bug also in VB6. Also VB6 apps which starts directly with a Form (no Sub Main) have this issue.
The solution for VB6 was to call InitCommonControlsEx() on Sub Main.
So I think you can close the issue without further action.

**Comment by WaynePhillipsEA** [comment]
Ahh yes, I do vaguely recall that now.  I guess if there's a visual-styles manifest in the project, then we could safely just call IniCommonControlsEx in the EXE internal startup, where we already call CoInitialize etc.

**Comment by Kr00l** [comment]
> Ahh yes, I do vaguely recall that now. I guess if there's a visual-styles manifest in the project, then we could safely just call IniCommonControlsEx in the EXE internal startup, where we already call CoInitialize etc.

That would be convenient. I think it is safe to call it always even when there is no manifest.

**Comment by bclothier** [comment]
Just to verify, will there be any effect if we call the `InitCommonControlsEx` again via our user code?

**Comment by Kr00l** [comment]
> Just to verify, will there be any effect if we call the `InitCommonControlsEx` again via our user code?

No harm. It can be called 100 times. It just needs to be called once.
So tB could call it internally at startup with just ICC_STANDARD_CLASSES, that's sufficient.

**Comment by WaynePhillipsEA** [comment]
@Kr00l v0.10.3234 is being published for you to test when you get chance.  tB calls it with dwICC set to 0, and this call succeeds on Win10.  I would imagine that this should be sufficient to fix the issue, but if not I'll change it to ICC_STANDARD_CLASSES.

**Comment by Kr00l** [comment]
It works that InitCommonControlsEx is called with dwICC set to 0 !
![image](https://user-images.githubusercontent.com/33756666/124010213-d7b71880-d9de-11eb-9bae-0d08821a4196.png)
(icon resource was removed for testing, that's why it shows the default windows app icon)

Thanks

**Comment by WaynePhillipsEA** [comment]
Awesome, thanks for confirming, and for your assistance.

**Comment by wqweto** [comment]
Doesn't `InitCommonControlsEx` call needlessly load `comctl32` e.g. for console applications?

I remember these was an extra `Call LoadLibrary("shell32.dll")` needed on XP without SP3 for the application to not AV on tear-down.

**Comment by Kr00l** [comment]
> I remember these was an extra `Call LoadLibrary("shell32.dll")` needed on XP without SP3 for the application to not AV on tear-down.


Yes, in my VBCCR I do this `LoadLibrary("shell32.dll")`
However, you need to FreeLibrary afterwards on each call. (E.g. UserControl_Terminate)
But that was only necessary for UserControls and VisualStyles. (Not for Forms, intrinsic controls etc..)
So, I think such thing is not needed at exe startup for tB. Maybe when GUI works we can check if tB can handle it somewhere internally, if needed at all..

**Comment by WaynePhillipsEA** [comment]
> Doesn't `InitCommonControlsEx` call needlessly load `comctl32` e.g. for console applications?

Yes.  I'll adjust the codegen so that it only gets called when the project setting of 'Is Console Application' is not set.

**Comment by WaynePhillipsEA** [comment]
> > Doesn't `InitCommonControlsEx` call needlessly load `comctl32` e.g. for console applications?
> 
> Yes. I'll adjust the codegen so that it only gets called when the project setting of 'Is Console Application' is not set.

This change is now live in v0.10.3256
