### ISSUE TITLE
brackets for block end auto-complete

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#248]
**Describe the bug**
The block end auto-complete does not work for procedures when not entering `()` brackets.

**To Reproduce**
Enter `private sub test` and then pressing enter will result in
![image](https://user-images.githubusercontent.com/33756666/123956406-f56a8a80-d9aa-11eb-9d53-cfd85688df67.png)

**Expected behavior**
It should auto-complete the `()` brackets. Like in VBx.
![image](https://user-images.githubusercontent.com/33756666/123956504-0adfb480-d9ab-11eb-840c-33e2d36e1822.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.10.3212]

**Additional context**
n/a

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.3227, thanks for reporting.
