### ISSUE TITLE
Lost Debugger

### ISSUE THREAD

**Issue by cristianbuse** [WaynePhillipsEA/twinbasic#254]
I have no idea what I've done but the debugger is not working anymore:  
![debugger](https://i.stack.imgur.com/X2BdU.png)

Is there something I can do to make it work again? I've already uninstalled TB and installed back.
I can build and run an .exe with no problem as the linker seems to be working fine.

**Comment by Greedquest** [comment]
I have the same problem. F5 and ctrl+F5 both give that message, however hitting the running man icon will execute the code for me.

**Comment by camomille22003** [comment]
running man icon +1

**Comment by cristianbuse** [comment]
@Greedquest  That's a good point thanks. If I click the running man I get:
>RunCodeUnderCursor failed: main thread is busy.

and pressing F5 doesn't do anything. I get the VS message only if I use the menu Run/Start Debugging, which is weird because that is supposed to be what F5 does.

**Comment by WaynePhillipsEA** [comment]
If I remember correctly, the Run/Start Debugging menu has never yet worked, but F5 used to.  I can't immediately see why F5 has stopped working, but I've got a fix ready in a few minutes.

**Comment by WaynePhillipsEA** [comment]
(Should be)  Fixed in v0.10.3334.   Very strange this one.  The fix was to override the F5 key binding and issue a vscode.commands.executeCommand('workbench.action.debug.continue'),.   But that's what the F5 key should be doing anyway...

Please close the issue once you've confirmed it's now working for you.  Thanks!

**Comment by cristianbuse** [comment]
Working fine now. Thank you!
