### ISSUE TITLE
Intellisense Issue

### ISSUE THREAD

**Issue by uwbwsvd** [WaynePhillipsEA/twinbasic#269]
Strg & Space
![grafik](https://user-images.githubusercontent.com/41230018/124657314-a472fe80-dea2-11eb-994a-5d4a51df45db.png)
![grafik](https://user-images.githubusercontent.com/41230018/124657643-10edfd80-dea3-11eb-9db2-9a8ab2091ce9.png)

Intellisense works
![grafik](https://user-images.githubusercontent.com/41230018/124657836-4b579a80-dea3-11eb-9eec-9025efd8dd7b.png)

TwinBASIC: v0.10.3423

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.4333, thanks for reporting.
