### ISSUE TITLE
Enable IntelliSense in the Debug Console

### ISSUE THREAD

**Issue by mwolfe02** [WaynePhillipsEA/twinbasic#272]
**Is your feature request related to a problem? Please describe.**
IntelliSense does not currently work in the Debug Console.  Both autocomplete and parameter hints seem to be missing.

![image](https://user-images.githubusercontent.com/305213/125199405-11d0b780-e234-11eb-9696-54f0c35976c2.png)

**Describe the solution you'd like**
If VS Code supports it, it would be nice to see the same IntelliSense in the Debug Console as what appears when entering code in a normal code window.

**Additional context**
IntelliSense works in the VBA Immediate Window.  

I know there are technical differences between the Immediate Window and the Debug Console, so this may just be a limitation of the VS Code environment.

**Comment by WaynePhillipsEA** [comment]
Indeed, VS code supports this.  tB doesn't yet provide for it through the DAP, but it shouldn't be too difficult to implement.

**Comment by WaynePhillipsEA** [comment]
As of v0.10.5422, intellisense in the debug console is now available...

![tb_intellisenseDebugConsole](https://user-images.githubusercontent.com/25738109/132086234-b00e7aa8-5e7d-4eb5-9ca2-b98fd1b35377.gif)

It's was a bit tricky to implement, as the DAP only allows for intellisense and not signature-help, plus the DAP CompletionItem is much less flexible than the LSP equivalent.  

Anyhow, we've included both normal intellisense results AND signature help (when appropriate).  The intellisense is context aware of the code being debugged, prioritizing local scoped results (e.g. local variables) then component-scoped results (e.g. global variables / class fields), and then everything else.   

Whilst this is not a perfect solution, it is greatly superior to what we had before... and I feel this satisfies this request, and is the best implementation we can do given the current (limited) DAP support for this feature.
