### ISSUE TITLE
Editor crash leaves project in uneditable state

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#276]
**Describe the bug**
Editing code in an attempt at writing some unit tests for the Lyst class in my VBALib.  The language server crashed and has left the project in a non editable state.

Unit tests are in Lyst.zip

The Library (which has compiled successfully)  which is reference by the code in Lyst.zip is in VBALib.zip

[VBALib.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6824937/VBALib.zip)
[Lyst.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6824938/Lyst.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version v0.10.3423, 4th July 2021

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.3429, thanks for reporting!
