### ISSUE TITLE
PredeclaredId classes in library cannot be used to call methods

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#278]
**Describe the bug**
I have a twinbasic project (VBALib) that has several classes with PredeclaredId set to true using the '@PredecaredId annotation.  In the calling code, the PredeclaredIds are flagged as 'unrecognised'.

If I try adding the project name then intellisense for the project name does not list any of the declared classes (just declared constant and enums)

The two sets of code are attached.
[VBALib.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6835907/VBALib.zip)
[Lyst.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6835908/Lyst.zip)

 - OS: Widows 10
 - twinBASIC compiler version v0.10.3429, 15th July 2021

**Comment by WaynePhillipsEA** [comment]
Apologies, I had forgotten that we haven't yet hooked up predeclared objects from external type libraries.  It was mentioned in #57 but went off the radar as I closed that issue.

I'll try to get to it this week for you.

**Comment by FullValueRider** [comment]
No worries.  At least I wasn't being Mr Stupid again.

**Comment by EduardoVB** [comment]
I'm also waiting for this feature. Just FYI.

**Comment by WaynePhillipsEA** [comment]
This is next up guys, apologies for the delay.

**Comment by WaynePhillipsEA** [comment]
Predeclared classes from external type libraries are now supported as of v0.10.3744.  Thanks for your patience.
