### ISSUE TITLE
Missing DLL gives untrappable error on startup

### ISSUE THREAD

**Issue by dmrvb** [WaynePhillipsEA/twinbasic#284]
**Describe the bug**
If a DLL is missing my twinBasic app gives an untrappable error as soon as it runs, and stops.
This happens before any calls are made to the DLL

**To Reproduce**
create a project with a call to a non existent DLL and select build.

**Expected behavior**
in VB6 a (trappable) error only occurs when a call is made to the DLL

Why I need this to work:
my users can install optional third party DLLs (drivers for additional hardware) if they own suitable hardware.
I make an initial error trapped DLL call to find if the DLL is installed and if so offer additional functionality.
If the DLL is missing then execution continues without the additional functionality.

Additional info
in VSCode I get a rather unhelpful message:
 process 10832 exited with code -1073741515 (dll error: STATUS_DLL_NOT_FOUND)

but when I run the compiled EXE I get a proper msgbox that gives the name of the missing DLL

**Desktop (please complete the following information):**
Windows 10
 twinBASIC compiler version [e.g. 0.10 3429
 - 
 - 
 additional context

in VSCode I get a rather unhelpful message:
 process 10832 exited with code -1073741515 (dll error: STATUS_DLL_NOT_FOUND)

but when I run the compiled EXE I get a proper msgbox that gives the name of the missing DLL

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting.  I am aware of this one and it's on the list to be fixed soon.  At the moment the tB linker early binds DLL entries and let's the OS loader handle the problem as it loads the EXE, but for backwards compatibility tB should be binding them on demand like VB6 does.

**Comment by Kr00l** [comment]
AFAIK VB6 binds an API call on first demand.
So the first call has a small performance penalty. All further calls reuse the bind.

**Comment by WaynePhillipsEA** [comment]
@Kr00l yes that's correct

**Comment by WaynePhillipsEA** [comment]
This should now be fixed in v0.13.40.  Thanks!
