### ISSUE TITLE
Does twinbasic.com have to be whitelisted (for corporate internet filtering)?

### ISSUE THREAD

**Issue by DaveInCaz** [WaynePhillipsEA/twinbasic#285]
From my corporate network when I tried to visit https://twinbasic.com/ from the readme here, I get this error / warning:

![image](https://user-images.githubusercontent.com/18285074/126480163-918ec937-37f4-44fd-b35a-28d4b4b47c89.png)

Clicking [Continue] _does_ work.

I think this is reflective of the fact that the domain is probably newish and the zscaler filtering service doesn't know about it. Potentially this would put some people off from visiting the site. I do not know specifically, but I bet there's a way you can register the domain with them to avoid this. But I'm not familiar enough with zscaler to really advise further.

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting.  I'm not familiar with zscaler.  A quick Google search suggests they might offer some form of "priority categorization service", but the details seem pretty vague, along the lines of "call one of our sales managers to discuss..."

**Comment by DaveInCaz** [comment]
I think this might be the right place; https://sitereview.zscaler.com/request-review

**Comment by WaynePhillipsEA** [comment]
Unfortunately I get "Access Limited
Site review service is available for Zscaler customers only. Ensure you go through Zscaler cloud to access this site."

**Comment by DaveInCaz** [comment]
Strange... no idea how they expect people to get their websites in their system from the outside.  

Assuming you wouldn't mind I submitted a request from that page that they categorize it as "information technology - other" (which was the only category that fit - others were like "politics", "movies", etc.) Assuming they perform some sort of review I think that should mean future visitors using the same zscaler service won't get the warning message.

**Comment by WaynePhillipsEA** [comment]
Of course, that's absolutely fine.  Thanks!
