### ISSUE TITLE
endif autcorrect in IDE

### ISSUE THREAD

**Issue by machthree** [WaynePhillipsEA/twinbasic#289]
In the VBA IDE typing 'endif' (without the quotes) will be auto-corrected to 'End If'. The TwinBasic IDE 'endif' is left unchanged (with red squiggles underneath). Admittedly this is a minor issue but I am so used to typing 'endif' in the VBA IDE I really miss this auto-correct.

**Comment by WaynePhillipsEA** [comment]
This is now auto-corrected as of v0.10.3471.  Thanks!
