### ISSUE TITLE
Autocorrect of Function name without brackets

### ISSUE THREAD

**Issue by machthree** [WaynePhillipsEA/twinbasic#295]
**Description**
In the VBA IDE entering "function _funcname_ as boolean" (i.e. without brackets after the function name) will be auto-corrected to "function _funcname()_ as Boolean". In TwinBasic the function type declaration is damaged by the auto-correct process.

**To reproduce**
Enter "function x as boolean":
After auto-correction (e.g. by pressing Enter) the line will be changed to "Function xasboolean()"

**Software version**
Using TwinBasic 0.10.3472

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting.  This was mentioned in discussion https://github.com/WaynePhillipsEA/twinbasic/discussions/261#discussioncomment-969755 but I will leave this issue open as it will get more attention here.

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.3482, thanks for reporting.
