### ISSUE TITLE
Prettifier: Trailing whitespace on current line

### ISSUE THREAD

**Issue by mansellan** [WaynePhillipsEA/twinbasic#301]
The prettifier runs after a short dwell time (1s?), which is very useful. However,  it can get in the way a little when it removes a trailing space on a line still being worked on.

**Describe the solution you'd like**
Add an exception such that the prettifier only removes _trailing_ whitespace when Enter is pressed.

**Describe alternatives you've considered**
Typing faster 😄

**Comment by DaveInCaz** [comment]
For C# in Visual Studio I used an extension https://marketplace.visualstudio.com/items?itemName=MadsKristensen.TrailingWhitespaceVisualizer which works a little differently. It does 2 main things:

1. Visualizes trailing whitespace as a color
2. Removes trailing whitespace when the file is saved

Personally I find this works perfectly... maybe this is another approach to consider that while still being automated avoids the pitfalls mentioned here.

**Comment by WaynePhillipsEA** [comment]
The prettifier shouldn't be doing anything to the line currently being edited.  It should only be prettifying once you've moved away from the line.  A quick test here suggests this seems to be working as expected.  Could you clarify / provide an example where the active line is being prettified?

**Comment by WaynePhillipsEA** [comment]
@mansellan have you by chance got the auto-save VS code feature on?

**Comment by mansellan** [comment]
Ah, yes. Apologies!
