### ISSUE TITLE
Allow opening of vb6 vbp project files

### ISSUE THREAD

**Issue by mika76** [WaynePhillipsEA/twinbasic#303]
**Is your feature request related to a problem? Please describe.**
I did not see this in the issues anywhere so it if it's there please let me know and I can subscribe to it.

**Describe the solution you'd like**
Basically to open vb6 projects as is.

**Comment by WaynePhillipsEA** [comment]
Thanks for opening the issue.  Obviously this is something that is planned, but we didn't have an actual issue open for it, so thanks.

Once we've got some support for forms in place, we'll be adding this capability.

**Comment by mika76** [comment]
Can't wait 😊

**Comment by dmrvb** [comment]
Maybe this should wait till TB also supports vb.FRM's. It could also be part of a VB6 upgrade tool that resolves any minor incompatibilities and warns about things like GOSUB.

**Comment by jpbro** [comment]
I think the sooner we have this available to us, the better. I'm about 80% committed to the idea of subscribing to tB, but it would all but guarantee I will if I can open some of my ActiveX DLL projects via the VBP and start playing whack-a-mole with issues to gain some confidence. Maybe I'm just being lazy, but some of my projects have tens of references, and it would eliminate a lot of friction to be able to open a VBP in tB and get to work right away as opposed to having to manually get everything setup manually.

**Comment by WaynePhillipsEA** [comment]
@jpbro good points, noted.  I think you're probably right about this, and if we do go with this soon, we'll just have to be really clear about what was NOT imported/migrated in terms of (as yet) unsupported features like FRM files etc.

**Comment by WaynePhillipsEA** [comment]
This is now supported as of v0.13.36.  There is a new import option in the tB activity panel:

<img width="284" alt="tbImportFromVBP" src="https://user-images.githubusercontent.com/25738109/146158794-d06b3f95-7914-469f-965a-2f2ce006092d.png">

After import, you'll be presented with a simple log of the process:

<img width="651" alt="tbImportFromVBPLog" src="https://user-images.githubusercontent.com/25738109/146158878-54e2d539-010e-45c4-8ed3-1584a647f8e3.png">

Only supported documents are imported (i.e. modules and classes, not forms etc).  Once VB6 forms are supported, they will of course also be imported.

If you find any bugs relating to this feature, please raise a new issue.  Thanks!

**Comment by mika76** [comment]
@WaynePhillipsEA This is fantastic, can't wait to try it... Is there an issue for getting a basic forms working? If not could you maybe create one so we can follow it?

**Comment by WaynePhillipsEA** [comment]
> @WaynePhillipsEA This is fantastic, can't wait to try it... Is there an issue for getting a basic forms working? If not could you maybe create one so we can follow it?

Thanks... just created one #567

**Comment by DinyaZ** [comment]
Very big thanks!  :)

**Comment by DinyaZ** [comment]
Works fine, very good first try! :) I have noticed only a few errors. For example:
.
unrecognized member 'PrevInstance' on type '_App' [non-extensible object

unrecognized datatype symbol 'DirListBox'
unrecognized datatype symbol 'FileListBox'
(in the source code:
Dim FileSorozat As FileListBox 
Dim DirSorozat  As DirListBox)

undeclared variables give warnings.
(Dim fso
 Set fso = CreateObject("scripting.FileSystemObject")

**Comment by OldestCoderInTown** [comment]
When will vb6 forms be supported for impoting like this?

**Comment by fafalone** [comment]
Importing forms has been available for some time now; recent updates have completed that support by correctly importing references, OCX controls, and UserControls.

**Comment by dmrvb** [comment]
There's still a fair bit of work to be done on some controls, and a bit of missing functionality, but it is possible to import, compile and run a project as long as its GUI is relatively simple.
