### ISSUE TITLE
Debug Console should be able to evaluate multiple expressions

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#31]
**Describe the bug**
This may be a part of preview limitation, but it isn't listed explicitly. The Debug Console does not allow multiple expressions.

**To Reproduce**
1. Create a module:
```
Module Foo
  Public Sub Bar
    Dim x As String = "hi, there"
    Dim y As Long = 123
   
    Stop
  End Sub
End Module
```
2. Put the cursor in the procedure and press 5 to run code under the cursor.
3. VSC will break at `Stop`
4. On Debug console, enter: `?x, y`
5. VSC reports: `(compile error: Sorry, file operations are not yet implemented.)`

This can be worked around by doing:
```
?x : ?y
```

**Expected behavior**
Running `?x, y` should return:
```
"hi, there"     123
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version v0.9.1602

**Additional context**
In previous version, expressions like `?Foo("hi there", 123)` did not work but this seems to be fixed in the 1602 version.

**Comment by WaynePhillipsEA** [comment]
This is due to the Print statements not yet supporting the full print statement syntax.  Only a single string is supported at present.

**Comment by WaynePhillipsEA** [comment]
Full Debug.Print syntax is now supported in v0.10.1604.  Thanks
