### ISSUE TITLE
Error when creating and naming New Project

### ISSUE THREAD

**Issue by dmrvb** [WaynePhillipsEA/twinbasic#313]
**Describe the bug**
Project name does not update when giving new project name, and error/crash when saving.

**To Reproduce**

Make a new project (standard EXE)
(create a new folder and specify a new .twinproj file)

breadcrumb shows:  Project:NewProject>NewProject>Sources>MainModule.twin
(why does it show NewProject twice????) 

In Settings give a new name to the project (NP1)
I would like the name in the breadcrumb and explorer to change to this new name but it does not

Select SaveAll
This brings up a msgbox "settings have changed need to save documents and reload compiler"
(compiler reload sounds a bit excessive for a simple rename)
select yes and get an error "Extension "twinBASIC" failed to update workspace folders"
VScode is part crashed, explorer does not work.

Close and restart VScode, all is well and name is now updated
breadcrumb: Project:NP1>NP1>Sources>MainModule.twin

but still have NP1 shown twice

**Expected behavior**
I would like name to update without a save and re-open (and no errors)

**Desktop (please complete the following information):**
 - Win10
 - twinBASIC . 0.10:3664

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting.  That sounds a bit cumbersome -- I'm sure it can be improved. 😊

**Comment by WaynePhillipsEA** [comment]
>(why does it show NewProject twice????)

This is a VS code bug.  The file path part of the breadcrumbs are constructed by VS Code, and we have no control over.  FWIW, I personally turn off the file path inside breadcrumbs feature in the VS code settings.

If I get chance, I'll report the bug over on the VS Code repository.

**Comment by WaynePhillipsEA** [comment]
The error that was occurring during the restart of the compiler is now fixed in v0.10.3697.  Thanks for reporting.

The compiler caches a lot of static project information/settings during its initial load of the project that are difficult to unwind, therefore a compiler restart is currently required for this name change.  I appreciate the compiler restart is an inconvenience, but fortunately this isn't something that needs to be done regularly so I feel we can put up with this for now.

**Comment by WaynePhillipsEA** [comment]
I've opened an issue for the breadcrumb bar problem on the VS Code repository: https://github.com/microsoft/vscode/issues/129881

**Comment by dmrvb** [comment]
Can I comment on a closed issue????
Yes this is now much much better, thanks.
After SaveAll the compiler/files reload fine but start with the Explorer collapsed rather than in its previous state.
This is disconcerting, but is very trivial on the grand scheme of things.

**Comment by WaynePhillipsEA** [comment]
Yep you can 👍 

I noticed the collapsed node in the explorer, but couldn't see a quick solution for it.  We'll probably have to live with that quirk for now.
