### ISSUE TITLE
Invalid Use of Datatype Hint

### ISSUE THREAD

**Issue by dmrvb** [WaynePhillipsEA/twinbasic#314]
**Describe the bug**
Calling a sub with a datatype hint gives a compile error (problem) "Invalid use of datatype hint".

**To Reproduce**

Private Const R2_COPYPEN& = 13

Call aasub(R2_COPYPEN&)

this gives compile time error "Invalid Use of Datatype Hint"
(more detail available if required.)

**Expected behavior**
This is pretty poor programming from me and deserves an error, but it compiles ok in VB6 so if we really want 100% VB6 compatibility then it should be downgraded to a warning.

Maybe a future "VB6 upgrade utility" should fix things like this?????

**Desktop (please complete the following information):**
 - OS: Win 10
 - twinBASIC . 0.10.3685

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.3697, thanks for reporting.
