### ISSUE TITLE
appobject / VB_GlobalNameSpace support

### ISSUE THREAD

**Issue by WaynePhillipsEA** [WaynePhillipsEA/twinbasic#316]
**Describe the bug**
twinBASIC currently doesn't offer appobject support

**Additional context**
With predeclared objects in type-libraries now implemented (#278), we need to support appobjects.  This feature allows class members to be called implicitly on a predeclared class, without qualifying the call with the class name.  Many of the Office applications use this feature in their typelibraries.  For example, in Access you can do this:

```
MsgBox Access.Name  ' Access is the type library identifier.  this routes through to the predeclared Application class, via Application.Name
MsgBox Name   ' Same as above, showing you don't need the type library identifier.

```
VB6 supported this feature via the Attribute VB_GlobalNameSpace in class headers.  twinBASIC needs to also support this legacy attribute, as well as providing a new twinBASIC style attribute of [AppObject].   Classes marked with such an attribute should then generate typelibraries with the appobject flag for consumption in other projects.

**Comment by WaynePhillipsEA** [comment]
This is now supported as of v0.10.3790, so for example the two examples in the OP work as expected if a COM reference to the Access type library is set.

<img width="182" alt="tb_AppObjectExample" src="https://user-images.githubusercontent.com/25738109/127770533-3183003b-e138-49f5-b132-3193c007383e.png">

Additionally, we now have a `[AppObject]` attribute, as picture above, to allow unqualified access to predeclared object members, matching the legacy VB6 VB_GlobalNameSpace attribute (which is also supported).

**Comment by eantar** [comment]
Wayne this looks awesome. Could  you give an example of what would needed to be done in Access to implement it. I'm assuming this would be a DLL, and that you would have to add a reference to it. But what would you need to add in the VB editor? How would the code look? Thanks.
