### ISSUE TITLE
Add a cls File to the project Error

### ISSUE THREAD

**Issue by uwbwsvd** [WaynePhillipsEA/twinbasic#317]
**Describe the bug**
![grafik](https://user-images.githubusercontent.com/41230018/127764311-7708840c-42dd-441b-8e0c-ec7c7c6aab44.png)
Press Enter
![grafik](https://user-images.githubusercontent.com/41230018/127764342-113932b7-19c3-4040-a314-676a7c10b028.png)
But the file is there.

Remark: I renamed the projekt as I created it. The name ist not shown.
![grafik](https://user-images.githubusercontent.com/41230018/127764648-be662ea7-2d2a-492d-bc95-f5fec3935a8d.png)

 - twinBASIC compiler version [e.g. 0.10.3744]

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting!  Yes, that's strange.  This doesn't happen when creating files from the twinBASIC panel, only when creating the file manually.  Also doesn't happen for BAS or TWIN files... only CLS files.  I'll look at this tomorrow for you.

**Comment by WaynePhillipsEA** [comment]
FIxed in v0.10.3881, thanks for reporting!
