### ISSUE TITLE
Incompatibility with BSPrinter

### ISSUE THREAD

**Issue by EduardoVB** [WaynePhillipsEA/twinbasic#325]
**Describe the bug**

The variable declared WithEvents raises an error "no handler for this symbol".

![imagen](https://user-images.githubusercontent.com/42319299/127893306-df192c89-9509-4e6d-a869-3f687468a2b9.png)

**To Reproduce**
Having referenced BSPrinter and VB6 libraries as described in the previous issue #324, this is the code being tested now (and that isn't working):

```
Module MainModule
    Private WithEvents mPrinterExEvents As PrinterExEvents
    
    Private Sub mPrinterExEvents_PrepareReport(Cancel As Boolean)
        PrintPreview.PrintEx "Hello World"
    End Sub
    
    Public Sub Main()
        Set mPrinterExEvents = PrintPreview.Events
        PrintPreview.ShowPreview
    End Sub

    Public Property Get Printer() As Printer
        Set Printer = PrinterReplacement
    End Property
    
    Public Property Set Printer(nPrinter As Printer)
        Set PrinterReplacement = nPrinter
    End Property

End Module

```

**Expected behavior**
I'm trying to see if the print preview features work.

**Desktop (please complete the following information):**
 - Windows 10 21H1
 - twinBASIC compiler version 3881

**Additional context**
There seem to be at least two issues, one is the problem with the WithEvents declaration as explained above, but if I declare the mPrinterExEvents variable without WithEvents, then the line `Set mPrinterExEvents = PrintPreview.Events` also raises an error:

![imagen](https://user-images.githubusercontent.com/42319299/127894947-eb3ebd7d-bf58-49b9-9964-5f4e33ee08b4.png)

**tB project files**
[BSPrinter twinBASIC test 2.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6918412/BSPrinter.twinBASIC.test.2.zip)

A similar code is in Sample 28 (1) of BSPrinter samples for VB6.

**Comment by WaynePhillipsEA** [comment]
You can't define WithEvents inside a Module.  Change it to a Class and you should hopefully find that it works.👍

**Comment by WaynePhillipsEA** [comment]
Also, if I just remove the 'WithEvents' from mPrinterExEvents, the Main routine runs without error here, so not sure what's going on there.

**Comment by EduardoVB** [comment]
Yes, the DoPrint procedure is executing now. 
Sometimes I get the error at the `Set mPrinterExEvents = PrintPreview.Events` line and other times I don't, but the line `PrintPreview.ShowPreview` never does anything anyway.
It should show a VB6 form with the print preview.

These are the project files: 
[BSPrinter twinBASIC test 3.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6918897/BSPrinter.twinBASIC.test.3.zip)

**Comment by WaynePhillipsEA** [comment]
Hmmm... the PrepareReport event is firing, but yes the ShowPreview call then crashes.  I'll look into this further tomorrow.

**Comment by WaynePhillipsEA** [comment]
I've confirmed that this is no problem with WithEvents support, as the problem can be reproduced without using events:

```
    Public Sub OnPrint()
        PrintPreview.PrintEx "Hello World"
    End Sub
    
    Public Sub DoPrint()
        PrintPreview.SetPrintingProcedure Me, "OnPrint"
        PrintPreview.ShowPreview
    End Sub
```

For now I'm going to mark this as an incompatibility with BSPrinter.  Without seeing the innards of the ShowPreview method, this would take a lot of debugging effort to look into further.

**Comment by EduardoVB** [comment]
I guess there is no way to be able to run BSPrinter in the VB6 IDE in source code while being consumed by twinBASIC... or there is?

If it is not possible, I'll have to debug it the hard way, by logging from the compiled OCX.

> Without seeing the innards of the ShowPreview method, this would take a lot of debugging effort

And seeing too...

I'll see to publish the source code.

**Comment by WaynePhillipsEA** [comment]
> I guess there is no way to be able to run BSPrinter in the VB6 IDE in source code while being consumed by twinBASIC... or there is?

It might be possible.   You'd have to build an EXE from the tB project, and set that EXE in the BSPrinter Project Properties dialog in the VB6 IDE > Debugging tab

**Comment by EduardoVB** [comment]
> It might be possible. You'd have to build an EXE from the tB project, and set that EXE in the BSPrinter Project Properties dialog in the VB6 IDE > Debugging tab

Yes, it "worked" but the tB exe raised another error:
![imagen](https://user-images.githubusercontent.com/42319299/127971199-cc1ca36b-0cd8-4996-97a7-a4ce820a1d82.png)

and the ShowPreview method didn't even enter.

I'll prepare to release the source code.

**Comment by WaynePhillipsEA** [comment]
I'm wondering whether https://github.com/WaynePhillipsEA/twinbasic/issues/326 could be applicable here, however your preview form looks to be modal, so shouldn't be affected.

**Comment by EduardoVB** [comment]
> I'm wondering whether #326 could be applicable here, however your preview form looks to be modal, so shouldn't be affected.

It can be non-modal or modal, in this case it must be non-modal since there are not other VB6 forms.

**Comment by EduardoVB** [comment]
I was able to fix the issue, it was what [Krool said](https://github.com/WaynePhillipsEA/twinbasic/issues/326#issuecomment-891837052): it must check whether non-modal is allowed with App.NonModalAllowed.

New updated version of BSPrinter is available [at the site](http://www.balkesoft.com/bsprinter/download.html).

**Comment by EduardoVB** [comment]
FYI with the latest/current version of [BSPrinter](http://www.balkesoft.com/bsprinter/download.html) it is not necessary any more to reference the VB6 library. It now contains the Printer object type information inside the BSPrinter OCX.
Also, it supplies the Printers collection, so we could say that it provides full printing support for twinBASIC with 100% backward compatibility.

Only reference needed:

![imagen](https://user-images.githubusercontent.com/42319299/128389487-c34607e8-68d4-46b0-9b69-bf44d9094640.png)

Example code:

```
Module MainModule

    Public Sub Main()
        PrintPreview.PrintEx "Hello World"
        Printer.EndDoc
    End Sub
End Module
```

When issues #324 are sorted out, tB with BSPrinter will be able to run any legacy VB6 printing code.

Code using the Printers collection already works:

```
Module MainModule

    Public Sub Main()
        Dim prn As Printer

        For Each prn In Printers
            If prn.DeviceName = "Microsoft Print to PDF" Then
                Set Printer = prn
                Exit For
            End If
        Next

        PrintPreview.PrintEx "Hello World"
        Printer.EndDoc
    End Sub
End Module

```

When it becomes possible in the future, BSPrinter could be compiled with tB to avoid the dependency on VB6 runtime entirely.

I guess, even now, that BSPrinter could provide the Printer object to any other Basic, like VBA (Access, Excel) and other Basic dialects, but so far I didn't test that (I can't do it right now).

**Comment by WaynePhillipsEA** [comment]
That's brilliant, @EduardoVB.  Thanks for sharing!
