### ISSUE TITLE
Constructor syntax

### ISSUE THREAD

**Issue by mansellan** [WaynePhillipsEA/twinbasic#327]
**Describe the problem**
~~The current syntax for constructors is ambiguous, and could cause issues with imported VBx code.~~
Currently constructors in twinBASIC use a special-cased `Sub` called `New`.

**Describe the solution you'd like**
Disambiguate constructors from standard `Sub` procedures.

**Describe alternatives you've considered**
The status quo.

**Additional context**
As constructors do not exist in VBx, their syntax is up for grabs. The possibility exists to define a bespoke syntax to clarify that these are not "normal" `Sub` procedures. ~~syntax that does not have potential to clash with imported VBx code.~~

Currently, twinBASIC allows instance constructors by special-casing a `Sub` called `New`:

```vb
Public Sub New(someParam As Integer)
  ' code
End Sub
```

~~This presents two problems:~~

~~1. Imported VBx code could already have a `Sub` called `New`, with different usage semantics (as VBx does not have constructors).~~
~~2. The constructor could be called as a standard `Sub` after the object is constructed.~~

Would it be better to devise an entirely new syntax ~~to avoid these issues~~? I can think of two candidates:

1. Use the class name (simliarly to C#)
```vb
Public MyClass(someParam As Integer)
  ' code
End MyClass
```

2. Explicit `Constructor` keyword
```vb
Public Constructor(someParam As Integer)
  ' code
End Constructor
```

My personal preference is for 2 (it seems to fit better with the BASIC ethos of being plain-speaking), but I'd like to know what others think.

VB.Net has the same issues for potential clashes with imported VBx code - in my opinion they dropped the ball when they repurposed `Sub`.

EDIT: Strikethrough original comments based on comments below.

**Comment by WaynePhillipsEA** [comment]
As far as I can see, you can't create a procedure named New in a VB6/VBA class, since New is a reserved word.  My guess is that the .NET guys chose it **_because_** it wouldn't clash.

' The constructor could be called as a standard Sub after the object is constructed.

That could, and should, be prevented.  I'll look at it.

**Comment by WaynePhillipsEA** [comment]
As far as I can see, you can't create a procedure named New in a VB6/VBA class.  My guess is that the .NET guys chose it **_because_** it wouldn't clash.

> The constructor could be called as a standard Sub after the object is constructed.

That can, and should, be prevented.  I'll look at it.

**Comment by WaynePhillipsEA** [comment]
In v0.10.3900, Sub New procedures cannot be called directly, only via the New syntax

**Comment by mansellan** [comment]
Thanks @WaynePhillipsEA, yeah that makes sense. I'd forgotten that `New` is a reserved keyword.

I'd still suggest that it might be preferable to have an explicit syntax for constructors, if only for clarity. But I'll update the OP to strike through the bits that don't apply.

**Comment by WaynePhillipsEA** [comment]
This is a difficult one, due to the "prior art" argument for using the VB.NET syntax that many will already be familiar with.  So my gut feeling is to leave it as it is.   That said, I've marked this as a discussion , so I'd be interested to hear from others.

If I had to choose out of the two proposed options, I'd also favour option 2.  Potentially we could offer a quick-fix to change Public Sub New into Public Constructor (or whatever), so the change could be made easily.

**Comment by Kr00l** [comment]
Ok here my two cents.
I would keep it as it is "Sub New" for 2 reasons.
1.
The "Sub" makes it intent clear that no return value exists, which is logic as a "= New" operator should return the new constructed class from the blueprint.
2.
"New" method name is short, simple and easy to directly connect/relate to the "= New" operator.

**Comment by mansellan** [comment]
OK, on reflection I'm persuaded. The prior art thing is compelling, and I can't really disagree with the reasons @Kr00l gave either. I guess it's just my C# bias showing through.

I'll close the issue, if anyone feels strongly enough in future they can reopen.

**Comment by WaynePhillipsEA** [comment]
It's good to have these discussions, so thanks for opening it.
