### ISSUE TITLE
OT perhaps: Settings VSCode

### ISSUE THREAD

**Issue by uwbwsvd** [WaynePhillipsEA/twinbasic#334]
I am little bit worried, what this means. Anyone has a suggestion?
![grafik](https://user-images.githubusercontent.com/41230018/128593123-8dc75eab-9efa-458d-b43e-ae5ff562e67a.png)

**Comment by WaynePhillipsEA** [comment]
Duplicate of #89.  It's not a problem on your machine, just a problem of tB.  I'll hopefully look at it very soon.

**Comment by uwbwsvd** [comment]
That reassures me. Also because I wasn't sure whether I should post this.

**Comment by WaynePhillipsEA** [comment]
If in doubt, then please post.  I won't bite😜

**Comment by WaynePhillipsEA** [comment]
Should be fixed in v0.10.3988, see comment https://github.com/WaynePhillipsEA/twinbasic/issues/89#issuecomment-894637324
