### ISSUE TITLE
Hover terminates the debugger

### ISSUE THREAD

**Issue by uwbwsvd** [WaynePhillipsEA/twinbasic#341]
![grafik](https://user-images.githubusercontent.com/41230018/128907725-ee4c6a9d-cd12-410b-898a-0a7868dbbdba.png)
If i hover to xChild, the run ist canceled
![grafik](https://user-images.githubusercontent.com/41230018/128908124-a48d8eb0-cc43-4405-b67f-0beb56f483a2.png)

[xmltest2.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6963426/xmltest2.zip)
tB: v0.10.4030

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.4081, thanks for reporting.

There was also a problem in our handling of For-Each that the XML library did not like, which is also now fixed.
