### ISSUE TITLE
Brackets: any special to know in tB?

### ISSUE THREAD

**Issue by uwbwsvd** [WaynePhillipsEA/twinbasic#345]
I copied following code from tB to VBA
xmlDoc.setProperty ("SelectionNamespaces", "xmlns:ns2='http://name_of_the_url/'")
in VBA I had to delete the brackets.
Is this 
https://docs.microsoft.com/en-us/office/vba/language/concepts/getting-started/using-parentheses-in-code
correct für tB too?

**Comment by WaynePhillipsEA** [comment]
Please see https://github.com/WaynePhillipsEA/twinbasic/issues/262

If short; twinBASIC is more relaxed about the parsing here, and so your code with brackets is acceptable.
