### ISSUE TITLE
Characters entered using Alt+Code do not survive when exported module is dragged to twinbasic

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#353]
**Describe the bug**
I have a series of constants to define quotation marks which in the VBA  Ide appear as

```
Private Const DOUBLE_QUOTE                      As String = """"
Private Const SINGLE_QUOTE                      As String = "'"
Private Const SMART_SINGLE_QUOTE_OPEN           As String = "‘" ' Alt+0145
Private Const SMART_SINGLE_QUOTE_CLOSE          As String = "’" ' Alt+0146
Private Const SMART_DOUBLE_QUOTE_OPEN           As String = "“" ' Alt+0147
Private Const SMART_DOUBLE_QUOTE_CLOSE          As String = "”" ' Alt+0148
```

If I copy and paste from the VBA IDE into VSCode twinbasic I get the above.  However if I export the module then drag that module into VSCode Twin basic I get

```
Private Const DOUBLE_QUOTE                      As String = """"
Private Const SINGLE_QUOTE                      As String = "'"
Private Const SMART_SINGLE_QUOTE_OPEN           As String = "�"
Private Const SMART_SINGLE_QUOTE_CLOSE          As String = "�"
Private Const SMART_DOUBLE_QUOTE_OPEN           As String = "�"
Private Const SMART_DOUBLE_QUOTE_CLOSE          As String = "�"
```

The file containing the above definitions is attached
[Fmt.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6982810/Fmt.zip)

**Comment by WaynePhillipsEA** [comment]
Thanks for opening the issue.  This was mentioned in the BAS/CLS support discussion here https://github.com/WaynePhillipsEA/twinbasic/discussions/257#discussion-3443129

Currently, BAS and CLS files are being wrongly treated as UTF8 encoded, whereas they should be treated as ANSI, using the codepage of the system.

We haven't got an actual issue open for this though, so let's keep this one open for tracking it.

**Comment by WaynePhillipsEA** [comment]
This is now fixed in v0.10.4503.

When editing BAS/CLS files in VS Code, files are massaged to UTF8 encoding, but when persisted to (or loaded from) storage they are ANSI-encoded using the system codepage, which provides backwards compatibility with VB6/VBA.

**Comment by FullValueRider** [comment]
For info, after the installation of v0.10.4503 I found that the first block of constants presented above had changed to
```
Private Const DOUBLE_QUOTE                      As String = """"
Private Const SINGLE_QUOTE                      As String = "'"
Private Const SMART_SINGLE_QUOTE_OPEN           As String = "â€˜" ' Alt+0145
Private Const SMART_SINGLE_QUOTE_CLOSE          As String = "â€™" ' Alt+0146
Private Const SMART_DOUBLE_QUOTE_OPEN           As String = "â€œ" ' Alt+0147
Private Const SMART_DOUBLE_QUOTE_CLOSE          As String = "â€" ' Alt+0148
```
the changes were corrected easily using the alt + codes.

**Comment by WaynePhillipsEA** [comment]
Apologies, that's because they were previously saved (wrongly) as UTF8 and are now being interpreted as ANSI, which is a slight breaking change from the earlier versions.  If you were to import/drag the file again from a real CLS/BAS file, it should work without modification.
