### ISSUE TITLE
For each loop of ParamArray failing unexpectedly

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#355]
**Describe the bug**
I am iterating a ParamArray using a for each loop.  twinbasic is generating an error on the first iteration of the loop.  

```
Testing started
TestStringifier testing completed
TestFmt.T07_ConvertVariableFieldsStringRepresentations_01_FourArgs  raised an error: #-2147024809 - The parameter is incorrect.
```
The affected code works fine in VBA. 

The error does not occur if I convert the paramarray to a variant

The error is ocurring in the

```
Stringifier.ToString
```
method called via 
```
TestFmt.T07_ConvertVariableFieldsStringRepresentations_01_FourArgs 
Fmt.pvConvertVariableFieldsToStringRepresentations
```

**To Reproduce**
Run the main procedure in Testing.twin. I have placed a stop command before the the call to Fmt.pvConvertVariableFieldsToStringRepresentations in TestFmt.T07_ConvertVariableFieldsStringRepresentations_01_FourArgs 

[VBALib.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6983806/VBALib.zip)

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.4276, thanks for reporting!
