### ISSUE TITLE
Inline ByVal attribute issue

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#358]
**Describe the bug**
Attached is a tB project which has a very stripped down version of my CommonDialog.cls. It contains only the ShowColor dialog. The problem is here when a .lpfnHook is provided for the API. It goes back to CommonDialog.cls through a ISubclass helper class. In that ISubclass_Message function it goes further to another helper function CallbackProcDialog. If I instead use DefSubclassProc API there is no issue.

![image](https://user-images.githubusercontent.com/33756666/129561811-56bdfaed-469f-4c66-b81e-1f20fb54ff8b.png)

**To Reproduce**
twinBASIC project files
[Standard EXE.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6992197/Standard.EXE.zip)

**Expected behavior**
Having no error. The same code 1:1 runs in VB6.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.10.4441]

**Additional context**
Clicking the debugger Stop button will then run the project. Of course the callback is not working then.

**Comment by WaynePhillipsEA** [comment]
It's a codegen error involving the ByVal keyword.  Change this:
`SendMessage hDlg, CommonDialogSetRGBMsg, 0, ByVal .RGBResult
`
To:
`SendMessage hDlg, CommonDialogSetRGBMsg, 0, ByVal CLng(.RGBResult)
`
And it should work for now, then I'll get this fixed very soon.

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.4503.  Thanks for reporting!
