### ISSUE TITLE
Default Member of collection passed as variant not recognised

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#359]
**Describe the bug**
The following code  works fine when ipIterableKeys is a variant containing an array, but fails when it is a variant containing a collection.  The code works as expected in VBA.

```
Public Sub pvAddOrInsertIterableIterable(ByVal ipIterableKeys As Variant, ByVal ipIterableItems As Variant, ByVal ipStartIndex As Long)

    If s.FirstUse Then pvInitialiseAutoKey ipIterableKeys(0)
    
    If ipStartIndex = -1 Then
    
        s.Keys.AddRange ipIterableKeys
        s.Values.AddRange ipIterableItems
        
    Else
    
        s.Keys.InsertRange ipStartIndex, ipIterableKeys
        s.Values.InsertRange ipStartIndex, ipIterableItems
        
    End If
    
End Sub
```
**To Reproduce**
1. Exec method Main in TestingTwin.

In Module TestKvp the method
Public Sub Test04_pvAddOrInsertIterableIterableAsAddArrayArray - variants containing arrays passes
Public Sub Test05_pvAddOrInsertIterableIterableAsAddCollectionCollection  Variants containing collections fails

**Expected behavior**
The statement 'ipIterableKeys(0)' should invoke the default Item method for collections

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - twinBASIC compiler version [v0.10.4441

[VBALib.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6993930/VBALib.zip)

**Comment by WaynePhillipsEA** [comment]
Collections have 1-base index, so I believe it should be ipIterableKeys(1).

I'll let you confirm and close the issue if that solves it for you.

**Comment by FullValueRider** [comment]
Yup, you are correct, which for me, is hilarious, as one of the objectives of the VBALib Kvp class is to remove that issue from consideration.  Just goes to show that somedays its just better to stay in bed.
