### ISSUE TITLE
Q: .twinproj to plain text files

### ISSUE THREAD

**Issue by KarlSevenSeven** [WaynePhillipsEA/twinbasic#361]
**Is your feature request related to a problem? Please describe.**
How is it possibe to get the plain text from .twinproj file?
Without opening it in VS?

**Describe the solution you'd like**
A tool/method/whatever to 'explode' a complete tB project.

**Describe alternatives you've considered**
Or there could be a mechanism inside VS to be able to compare another state of the project.

**Additional context**
In order to be able to WinMerge different versions of a project.

**Comment by WaynePhillipsEA** [comment]
There is a command line option for this, please see #232.  Thanks
