### ISSUE TITLE
Set ByRef Variant to Nothing crashes compiler

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#370]
**Describe the bug**
Setting a ByRef Variant to Nothing crashes the compiler. There is no compilation error.

**To Reproduce**
```
Public Sub Main()
    Dim V As Variant
    Set V = New StdFont
    
    SetVarNothing V
    
    MsgBox (V Is Nothing)
    
End Sub

Private Sub SetVarNothing(ByRef V As Variant)
    Set V = Nothing ' [New StdFont] would work
End Sub
```

**Expected behavior**
To work like in VBx.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.10.4628]

**Additional context**
Setting to New something would work. So there is a problem specific to `Nothing`

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.4755, thanks for reporting
