### ISSUE TITLE
Twinbasic editor cannot continue after edits

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#373]
**Describe the bug**
I was editing  'TryToLystOfLysts' in Class 'Arrays' when the editor locked up and has stopped responding to input.

Project is attached

[VBALib.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7025488/VBALib.zip)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - twinBASIC compiler version [v0.10.4755n]

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.4756, thanks for reporting.
