### ISSUE TITLE
Possible Regression of erroring on duplicate enumeration members.

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#374]
**Describe the bug**
I was wondering if there has been a regression of flagging up duplicate enumeration members.  

![DuplicateMembers](https://user-images.githubusercontent.com/81257042/130327556-f000a3f0-777e-48e0-bbea-8fa70b333005.jpg)

**Desktop (please complete the following information):**
 - OS: [ Windows 10]
 - twinBASIC compiler version [v0.10.4756]

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.4904, thanks!

(wasn't a regression, just a missed validation opportunity)
