### ISSUE TITLE
ByVal in Brackets gives internal error

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#379]
**Describe the bug**
The following code gives an internal error

**To Reproduce**
```
Private Declare Function memcpy Lib "kernel32.dll" Alias "RtlMoveMemory" (Destination As Any, Source As Any, ByVal Length As Long) As Long

Public Sub Main()
    Dim m_pMemoryPtr As Long
    memcpy ByVal (m_pMemoryPtr + 4&), ByVal 0& , 4
    
End Sub
```

**Screenshots**
![image](https://user-images.githubusercontent.com/33756666/130398148-85b12cd8-bd2f-4919-86e6-9305ae9a87f2.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.10.4756]

**Additional context**
Putting the brackets in CLng() solves it for the moment.

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.4904, thanks!
