### ISSUE TITLE
Ambiguous conflict same Enum and Property/Method (Me object)

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#384]
**Describe the bug**
The code below causes an ambiguous type conflict as `Me.MyThing` could be either refer to the enum or the property.
However, it shall be clear that `Me.` can only refer to the property/method.

**To Reproduce**
```
Class Class1
    Public Enum MyThing
        MyThing1 = 1
        MyThing2 = 2
    End Enum
    Private PropMyThing As MyThing
    
    Public Property Let MyThing(Value As MyThing): PropMyThing = Value: End Property
    Public Property Get MyThing() As MyThing: MyThing = PropMyThing: End Property
    
    Sub Class_Initialize()
        Me.MyThing = MyThing1
    End Sub
    
End Class
```

**Screenshots**
![image](https://user-images.githubusercontent.com/33756666/130641337-78135332-05b8-4367-96ea-03ed61f23f5c.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.10.4966]

**Additional context**
the MyThing could also refer to a sub/function. So, it's not only issue with property.

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.4980, thanks.   I've also made some adjustments to the formatting in the 'ambiguous' error results, as clearly the markdown formatting was incorrect there.
