### ISSUE TITLE
End Sub/Function on Property Get

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#394]
**Describe the bug**
Similar topic like #386 
However, it does not affect the Exit but rather the End syntax.
Sorry for not reporting earlier. I found a piece of real code that uses End Function for a Property Get..

**To Reproduce**
Both Property-Get are valid in VBx...
```
Public Property Get MyProp1() As Long
    MyProp1 = 42
End Function

Public Property Get MyProp2() As Long
    MyProp2 = 42
End Sub
```

**Expected behavior**
to support those with a warning. I leave it up to you to group this into TB0004 or to create a new TB0005 for it.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.10.5080]

**Additional context**
n/a

**Comment by WaynePhillipsEA** [comment]
Now supported in v0.10.5101, thanks!
