### ISSUE TITLE
How about including the MS Access Nz function into the VBA library of tB ?

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#397]
(Wayne is very busy and to keep track of such an valueable addition IMO is worth a new issue)

How about including the MS Access Nz function into the VBA library of tB ?

Below function should be 100% compatible. (returning Empty if Value is null)
```
Public Function Nz(ByRef Value As Variant, Optional ByRef ValueIfNull As Variant = Empty) As Variant
    If IsNull(Value) Then Nz = ValueIfNull Else Nz = Value
End Function
```

_Originally posted by @Kr00l in https://github.com/WaynePhillipsEA/twinbasic/issues/66#issuecomment-907200519_

**Comment by WaynePhillipsEA** [comment]
Now available in v0.10.5101.  Thanks!
