### ISSUE TITLE
VBA.Constants do not accept type-declaration character suffix

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#398]
**Describe the bug**
All of the VBA.Constants do not accept the type-declaration character suffix in tB.
In VBx it is allowed.

**To Reproduce**
```
MsgBox vbNullString& ' Only String suffix allowed
MsgBox vbObjectError& ' Only Long suffix allowed
```

**Expected behavior**
to allow in tB that constants can be suffixed with it's data type.

**Screenshots**
![image](https://user-images.githubusercontent.com/33756666/131262237-62d8d1f5-e2d6-4e54-b44f-af3910b79e1e.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.10.5135]

**Additional context**
Self defined constants seems to be allowed already. So no problem there, example:
```
Private Const MY_CONST As Double = 1#
MsgBox MY_CONST#
```

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.5165, thanks!
