### ISSUE TITLE
Breakpoints can be added to Declarations but are then ignored

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#405]
**Describe the bug**
If I place a breakpoint on a declaration line, VSCode happily flags up that line with the red breakpoint marker.  However, when I run the code the breakpoint is ignored.

![Breakpoints](https://user-images.githubusercontent.com/81257042/132122073-9baadb71-7a80-46cc-940f-a6e24fe6e51a.jpg)

**Expected behaviour**
VBA does not allow a breakpoint on a declaration statement.  twinBasic has the added benefit of allowing declaration and assignment in the same statement.  For this reason I would like that twinBasic respects the breakpoint on a declaration only statement and stops at that line or at least the next runnable line after the breakpoint.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - twinBASIC compiler version [v0.10.5452]

**Comment by WaynePhillipsEA** [comment]
Thanks @FullValueRider.  It looks like breakpoints on Dim statements with initializers on the same line are working correctly?  If so, I think the rest of this issue is covered by #24, and hopefully I'll get to look at this later in the month.

**Comment by WaynePhillipsEA** [comment]
I'll close this for now.  If you feel that #24 doesn't fully cover this issue, please reopen.  Thanks
