### ISSUE TITLE
VBA.Information.RGBA() function

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#408]
**Is your feature request related to a problem? Please describe.**
The VBA.Information module has the RGB function. However, it would be nice to add (like in FreeBasic) an RGBA function.

**Describe the solution you'd like**
`RGBA ( ByVal Red As Integer, ByVal Green As Integer, ByVal Blue As Integer, ByVal Alpha As Integer ) As Long`

**Describe alternatives you've considered**
low-priority

**Additional context**
In FreeBasic are also "extracting" functions. Like RGB_R() to extract the red color of an RGB value, or RGBA_A() to extract the alpha value of an RGBA value, and so on.
Maybe it makes sense to include those ones as well to make this more complete..

**Comment by WaynePhillipsEA** [comment]
Now available in v0.10.5494.  Thanks for reporting.

**Comment by Kr00l** [comment]
Thanks for fast implementation. :)
And sorry to nag for this as below.

1. I found out that the RGBA() function accepts negative value for Alpha. For the Red, Green and Blue it throws an exception when negative (also for RGB() function). So I assume for Alpha it should throw out an exception too when negative.
2. The extracting routines (RGB_R(), RGBA_A()) are returning Byte. In FreeBasic they return Integer as well, like the inputing values for RGB/RGBA. Maybe this looks more VB-Ish as Integer is often more used than Byte.

**Comment by WaynePhillipsEA** [comment]
You're welcome @Kr00l.  I'll fix the Alpha guard check and change the return values to Integer in the next update as suggested.

**Comment by WaynePhillipsEA** [comment]
Done in v0.10.5646, thanks.

**Comment by Kr00l** [comment]
Sorry for being fussy.. :>
The parameter on RGBA_A() function should be named `RGBA As Long` instead of `RGB As Long`.
![image](https://user-images.githubusercontent.com/33756666/133094777-1cd51b1c-52a2-45e8-befc-f9a00364dc86.png)
