### ISSUE TITLE
"Global Const" not supported

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#409]
**Describe the bug**
The old/deprecated VBx "Global Const" is not recognized in tB.

**To Reproduce**
```
Global Const MyConst As String = "hello world"

Public Sub Main()
    
    MsgBox MyConst
    
End Sub
```

**Expected behavior**
I think the scope of `Global` is equivalent to `Public`. So Global could be just allowed as an alias for Public.

**Screenshots**
![image](https://user-images.githubusercontent.com/33756666/132176648-ad647d5a-c0ba-4d54-b5da-2224d528a23d.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.10.5474]

**Additional context**
n/a

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.5494.  Thanks for reporting.

**Comment by Kr00l** [comment]
Thanks for fixing this.

However, I noticed that in VBx the `Global` keyword can only be used in standard modules for constants and variables.

tB allows now the usage of Global in class modules. Do we want to keep it or disallow in tB as in VBx ?

**Comment by Kr00l** [comment]
Addition:

tB already only allows `Dim` for modules and not in classes.
![image](https://user-images.githubusercontent.com/33756666/132195780-13248039-c89e-4f32-bd62-d18d52c47131.png)

So, following this logic it would be good to dissallow Global in class modules as well.

**Comment by WaynePhillipsEA** [comment]
Good catch.   We should indeed disallow it, as 'Global' suggests full scope not instance specific.

**Comment by WaynePhillipsEA** [comment]
Done in v0.10.5646, thanks

**Comment by Kr00l** [comment]
Works good. Thanks.

However, I noticed some small detail. Maybe it's just OK to allow it..
A Global Type and Enum is not possible in VBx.
```
Global Type MyUDT
MyUDT1 As Long
End Type
Global Enum MyEnum
MyEnum1 = 1&
End Enum
```

When defining above in a .bas module (other than .bas anyhow not allowed) in VBx it will be prettified to:
```
Type MyUDT
MyUDT1 As Long
End Type
Enum MyEnum
MyEnum1 = 1&
End Enum
```

So, just allow Global keyword (as it is right now) or dissallow ? Or third option to also prettify ? .. :)
