### ISSUE TITLE
unexpected end of procedure

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#410]
**Describe the bug**
The code below causes an "unexpected end of procedure" bug.
Needs to be in a bas source.
![image](https://user-images.githubusercontent.com/33756666/132205961-0fb32b0a-6530-4c7f-99b1-d8f6af16c28b.png)

**To Reproduce**
```

Private Declare Sub Sleep Lib "Kernel32" (ByVal dwMilliseconds As Long)

' Public Sub test()
' End Sub

```

**Expected behavior**
to have no error

**Screenshots**
![image](https://user-images.githubusercontent.com/33756666/132205757-9eec077f-d508-4d9e-a426-d5f3977ddfdc.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.9.1111]

**Additional context**
Commenting out the Sub test resolves the bug.
![image](https://user-images.githubusercontent.com/33756666/132205875-e4f6e733-7acb-4f45-b1e5-62e36d9127c5.png)

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.5646, thanks!
