### ISSUE TITLE
Hidden interfaces show up in intellisense

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#413]
**Describe the bug**
When reporting the issue #412 , I also found this odd behavior with the intellisense. See the screenshot:
![image](https://user-images.githubusercontent.com/2367644/132267795-037becaf-d7c6-48ed-b421-2c323af1c44f.png)

**To Reproduce**
Create a COM project, name it "Sample" and use the following code:
```
Public Class Example
    Public Sub New()
    End Sub
    
    Public Sub New(Foo As String)
    End Sub
End Class

Public Module Test
    Public Sub DoIt()
        Dim x1 As Example
        Dim x2 As Example

        'Put cursor here
    End Sub
End Module
```

Add a new line `Set x1 = ` and pause to see the intellisense show the hidden interface `[_Example]` which doesn't seems appropriate. 

**Expected behavior**
I think it should at minimum, suggest nothing, or at least a `New Example`.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - twinBASIC compiler version v0.10.5646

**Comment by WaynePhillipsEA** [comment]
This is the new feature where a datatype hint is given via intellisense in assignments and arguments.  Selecting the option does nothing as it is just a hint.  Indeed it should be the class name, not the hidden interface name, so I'll fix that.

I think that 'New <class>' should be an additional option in the intellisense.  

Perhaps the datatype hint needs to be more explicit, e.g. '[datatype: Example]' ?

**Comment by WaynePhillipsEA** [comment]
@bclothier I've tweaked this in v0.10.5711 as mentioned above.  Please re-open if you feel this still isn't right. Thanks
