### ISSUE TITLE
Bad variable type accessing a paramarray directly but not if dereference by for each

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#414]
**Describe the bug**
Maybe another case of dodgy code from a hobbyist programmer but I've come across a case where a direct reference to an item in a ParamArray is giving a bad variable type error, but if I loop over the paramarray I don't get any errors.  The error occurs when executing Test27_ArrayToLystOfLystsByRow in module TestArrays.  There are numerous calls to the add method of the Lyst object before this method which don't generate this error.

In the example below, if I switch to using the commented out code, I don't get the error

![Bad variable type](https://user-images.githubusercontent.com/81257042/132315414-edb04b19-3a38-465a-b624-3223b5eff975.jpg)

**To Reproduce**
In the attached project execute method Tester in Testing.twin.  I've set breakpoints so that you can check progress and a text comment to warn when to step using f11 vs f5/f10

**Expected behavior**
ipArgs(0) should not produce a bad variable error

**Desktop (please complete the following information):**
 - OS: [ Windows 10]
 - twinBASIC compiler version [v0.10.5646]

[VBALib.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7120343/VBALib.zip)

**Comment by WaynePhillipsEA** [comment]
Fixed in 0.10.5711, thanks for reporting
