### ISSUE TITLE
Object does not accumulate references

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#415]
**Describe the bug**
I have a Lyst object which is a wrapper for the MS ArrayList. I'm adding new lyst objects to a lyst object (Lyst.deb is the factory method for getting a new Lyst).

```
Class TableArrayToRowLysts

    '@predeclaredId
    Option Explicit
    Option Private Module
    
    Public Function ExecAction(ByVal ipTableArray As Variant) As Lyst
        
        Guard NotTableArray, Arrays.IsNotTableArray(ipTableArray), "VBALib.TableArray.Exec", TypeName(Me)
        
        Dim myFirstDim1 As Long
        myFirstDim1 = LBound(ipTableArray, 1)
        
        Dim myLastDim1 As Long
        myLastDim1 = UBound(ipTableArray, 1)
        
        Dim myFirstDim2 As Long
        myFirstDim2 = LBound(ipTableArray, 2)
        
        Dim myLastDIm2 As Long
        myLastDIm2 = UBound(ipTableArray, 2)
        
        Dim myLystOfLyst As Lyst
        Set myLystOfLyst = Lyst.Deb
        Dim myDim1 As Long
        Dim myDim2 As Long
        For myDim1 = myFirstDim1 To myLastDim1
        
            Dim myInnerLyst As Lyst
            Set myInnerLyst = Lyst.Deb
            'myLystOfLyst.Add Lyst.Deb
            
            For myDim2 = myFirstDim2 To myLastDIm2
                
                myInnerLyst.Add ipTableArray(myDim1, myDim2)
                'myLystOfLyst.Item(myDim1 - myFirstDim1).Add ipTableArray(myDim1, myDim2)
                
            Next
        
            myLystOfLyst.Add myInnerLyst
            
        Next
       
        Set ExecAction = myLystOfLyst
        
    End Function
    
End Class
```

In the code above, at 'ExecActionthe debugger is reporting that there are 5 items in myLystOfLyst but no elements are visible.  This causes 'Test27_ArrayToLystOfLystsByRow' in Module 'TestArrays' to fail.  However, if I replace
```
myLystOfLyst.Add myInnerLyst
```
with
```
myLystOfLyst.Add myInnerLyst.Clone
```
The code works fine.  I'm not clear on what I'm doing wrong as reassigning myInnerLyst each time through the outer loop should not delete the reference held my myLystOfLyst (if my understanding is correct).  A screenshot of the error is below.  If Run and debug is selected before code is run the debugger will report there are no elements.  If I select Debug and run after reaching the breakpoint then the code will crash with no error message.

**To Reproduce**
In the attached project run the Tester method in module Testing.  A breakpoint has been inserted at the relevant line.

**Expected behaviour**
The reassignment of myInnerLysts should not delete the reference held to the previous instance of myInnerLyst held by myLystOfLysts. (Again, if my understanding is correct)

**Screenshots**
![NoMembers](https://user-images.githubusercontent.com/81257042/132353111-f74564cc-37d4-4454-a43c-e4c935bf549e.jpg)

**Desktop (please complete the following information):**
 - OS: [ Windows 10]
 - twinBASIC compiler version [v0.10.5646]

[VBALib.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7122000/VBALib.zip)

**Comment by WaynePhillipsEA** [comment]
Fixed in 0.10.5711, thanks for reporting
