### ISSUE TITLE
Undefined behavior for class defining both `Finalize()` and `Class_Terminate()`

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#417]
**Describe the bug**
(Note: I thought I created this issue yesterday but I couldn't find it, apologies if I'm being oblivious)

tB provides `Sub Finalize()` to handle the destruction. However, in VBx, class could have a `Terminate` event to handle the destruction. Furthermore, the `Finalize` is not a special keyword so it may be possible to import a class that contains both `Finalize` and `Class_Terminate` methods.

In this case, the `Class_Terminate` sub is no longer called and `Finalize` is called instead. That's not good for backward compatibility.

As an aside, in VB.NET, it is apparently required to `Overrides Overloads Finalize()`. I think the syntax is awful but it shows that VB.NET avoided the problem by requiring `Overrides` instead of `Private Sub`. I'm not sure what is the best thing to do and frankly `Overrides` makes very little sense since there's nothing explicitly implemented and we don't have a .NET conception of an `Object`. 

**To Reproduce**
1. Create a class with code like so:
```
Public Class Foo
  Public Sub Finalize()
    Debug.Print "Finalized"
  End Sub

  Private Sub Class_Terminate()
    Debug.Print "Terminated"
  End Sub
End Class
```
2. Create a module to new it up:
```
Public Module Bar
  Public Sub Baz()
    Dim F As Foo
    Set F = New Foo
  End Sub
End Module
```
3. Run the sub `Baz`, observe that the debug console only prints `Terminated`.
4. Comment out the procedure `Class_Terminate`
5. Run the sub `Baz` again, and observe that the debug console now prints `Finalized`.

**Expected behavior**
I think it ought to be a compile error to define both `Finalize` and `Class_Terminate`, but that may break compatibility. The next thing to do would be require some keyword that was not legal in VBx so that there'll be no prior code that could have this syntax. One way would be to simply have just `Finalize()` rather than `Private Sub Finalize()`. We also probably should consider issuing an warning whenever a class has both defined. 

**Desktop (please complete the following information):**
 - OS: Windows 7
 - twinBASIC compiler version v0.10.5711

**Comment by WaynePhillipsEA** [comment]
Thanks @bclothier, I didn't see an issue yesterday for it, so I don't think it got through.

Compiler error for when both are defined... yes, most definitely.

Just `Finalize` instead of `Private/Public Sub Finalize` seems a sensible solution to maintaining back compatibility.  However, it is slightly at odds with the `Public Sub New` syntax, which we discussed in #327

**Comment by bclothier** [comment]
Yeah, in this case, `Public Sub New()` was borrowed from VB.NET. However, the `Overrides Overloads Finalize()` is an abomination even in VB.NET and much more so in tB (what are we overriding? Why are we overriding and overloading both? Brain hurts). 

So ultimately, we'll have to make a choice of keeping things consistent or prefer prior art. 

As one possible alternative, you could go C#-ish with `Private Sub ~Finalize()` which would be illegal in VBx and thus avoid colliding with a regularly defined `Private Sub Finalize()`. That would be more in keeping with the `Private Sub New()`, except for the fact that we require a tilde character for the destructor. 

Because constructors and destructors are _special_ and from what I read in other languages, things can be very different (e.g. the constructors may get called in the opposite order compared to inherited methods), I really want to just call them `Private New()` and `Private Finalize()`, eschewing any prior art arguments in favor of consistent. However if this is too late, then I think the `Private Sub ~Finalize()` is a reasonable compromise.

**Comment by Kr00l** [comment]
What's the gain of Finalize over Class_Terminate ?
For Sub New the gain is clear.
Is it just to be complete and offer the Sub New counterpart ?

**Comment by bclothier** [comment]
Actually, thinking about it some more, there is yet another option. Because the `Class_Terminate` takes precedence, the compiler can instead emit a warning that the `Finalize()` isn't a destructor` or something akin to that.

**Comment by WaynePhillipsEA** [comment]
> What's the gain of Finalize over Class_Terminate ?
> For Sub New the gain is clear.
> Is it just to be complete and offer the Sub New counterpart ?

Yes, and to appease developers coming from .NET, where they might expect Sub Finalize to work.  So I guess another option would be to NOT support Finalize at all, and if Sub Finalize IS defined then issue a warning that you should in fact use Class_Terminate

**Comment by bclothier** [comment]
FWIW, the article I looked at earlier might have been incorrect about requiring `Overrides Overload` - from Microsoft's documentation, it seems that it requires it to be `Protected Sub Finalize()`. [Source](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/objects-and-classes/object-lifetime-how-objects-are-created-and-destroyed#using-constructors-and-destructors)

Since the `Protected` keyword is apparently required and is not used by VBx, that would allow us to support both worlds without weird compromises, I think. We'd need the `Protected` keyword anyway when we get to class inheritance.

**Comment by Kr00l** [comment]
`Sub New` is safe as New is a restricted keyword.
However, I can think that some people us a `Sub Finalize` for other means. This would clash as Finalized is not a restricted keyword.

**Comment by EduardoVB** [comment]
It seems to me that the Sub Finalize and the Sub Class_Terminate are the same. My idea is just to issue a compiler error when both are declared (the developer needs to choose one).

> to appease developers coming from .NET

But it would break the rule of one only way for doing something.

**Comment by Kr00l** [comment]
Again, what If somebody uses a `Sub Finalize` in VBx for internal cleanup/housekeeping and calls that from within Class_Terminate. That code would get a warning.. but it was totally fine in VBx.

**Comment by EduardoVB** [comment]
> Again, what If somebody uses a `Sub Finalize` in VBx for internal cleanup/housekeeping and calls that from within Class_Terminate. That code would get a warning.. but it was totally fine in VBx.

I think I have that in my code.

**Comment by WaynePhillipsEA** [comment]
To be fair, Sub Finalize support was added a long time ago, when parameterized constructors we're first added to the language, and well before the public preview.  To be clear, I'm in total agreement that this needs fixing, because backwards compatibility is the number one priority with this project.

It's just a case of agreeing the fix.  My vote at the moment would be to just remove support for Sub Finalize, for now at least.

**Comment by Kr00l** [comment]
I agree for removal, for now.

Because (**even worse**) what if there is a `Public Sub Finalize` and it get called from outside to finish a job or whatever. That can't be fixed w/o breaking some code on the apps using that class.

**Comment by bclothier** [comment]
FWIW, `Public Sub Finalize` seems to be incompatible in VB.NET. Testing using the [.NET fiddler](https://dotnetfiddle.net/), it throws up warnings & errors because it wants me to override the `Finalize`. `Protected Overrides Sub Finalize()` is just fine. Without `Overrides` it's not a finalizer.

If my testing is accurate, porting VBx with a `Public Sub Finalize()` would mean it wouldn't be a real finalizer. Ditto for `Private Sub Finalize()`. Therefore to achieve compatibility with both VBx and VB.NET, tB should require `Overrides Sub Finalize()` for it to be a finalizer -- otherwise, emit a warning for the `Finalize()` being not a finalizer. 

Test code for .NET Fiddler:
```
Imports System

Public Module Module1
	Public Sub Main()
		Console.WriteLine("Starting...")
		Dim foo = New Foo
		foo = Nothing
		GC.Collect()
		GC.Collect()
		Console.WriteLine("Finished.")
	End Sub
End Module

Public Class Foo
	Public Sub Finalize()
		Console.WriteLine("finalized")
	End Sub
End Class
```

**Comment by EduardoVB** [comment]
I'm not sure what this Finalize does in .Net, but in VB6 the only way to finalize a Class instance is to free all the references. Then the Class_Terminate is fired. But it is (usually) a **Private** Sub.

**Comment by bclothier** [comment]
Both are basically the same thing -- they get called at the destruction of the object, though there is big difference in when they get called due to difference in garage collection (ref-counting vs. generational). Possibly also with how they may chain since .NET allows inherited classes to build upon the base's destructor -- that wouldn't be possible in VBx where the `Class_Terminate` are always private to the class being destructed. 

Furthermore, I've found that the behavior around the `Class_Initialize` and `Class_Terminate` to not be very well-defined and thus follow a conservative set of rules when working inside those procedure (e.g. try to avoid interacting with other components or passing around the class because the class isn't fully constructed or about to be destructed). With .NET, the compiler does a pretty good job of warning you when you are doing something that cannot be legal inside either constructor/destructor. Would be nice to see that from tB's compiler, too.

**Comment by EduardoVB** [comment]
I tested with VB6 and it seems to do something logical. 
If you reference the class from the Class_Initialize it works but it is only initialized to the point the code was executed.
About the Class_Terminate, it also works and you get a result according to how the class internal state was already set in the code of the Class_Terminate event, but if you maintain a reference to the object, the class instance doesn't get destroyed, and when the reference is freed, it gets destroyed but the Class_Terminate event does not execute again.

[Test_Initialize_Terminate.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7133351/Test_Initialize_Terminate.zip)

**Comment by WaynePhillipsEA** [comment]
Sub Finalize support has now been dropped in v0.10.5755.   We can revisit this once inheritance is supported (#73).

**Comment by mburns08109** [comment]
@Ben
> ... in garage collection...
GARAGE collection!? have they now changed garBage collection to garrage collection?! (or was that just a typo?)   :-)

**Comment by mburns08109** [comment]
For the future:
Unless tB will incorporate a future out-of-heap-space garbage collection memory management model, there will never be a need to support any sort of Sub Finalize() as the .Net platform does. Programmers coming to tB form a .Net mindset will NEED to be pushed to complete awareness of the differences in the two memory management methodologies, and that Class_Initiailize() and Class_Terminate() are not merely a Good Idea(tm) from days gone by, but in fact, they remain THE LAW (well, of COM code)!

**Comment by bclothier** [comment]
> GARAGE collection!? have they now changed garBage collection to garage collection?! (or was that just a typo?)   :-)

Well, suburbanites put their garbage in garage until it’s time for the garbage truck to come around, right? ;-)

> For the future:
> Unless tB will incorporate a future out-of-heap-space garbage collection memory management model (shudders at the thought), there will never be a need to support any sort of Sub Finalize() as the .Net platform does.

Actually, tB’s now-dropped `Finalize` behaved the same way as `Class_Terminate` does, and is determinstric and in process. Therefore, it had nothing in common with .NET’s finalizer except the name. Thiugh it was originally named as to make it easy to port VB.NET code, it could be argued it shouldn’t be a finalizer but a destructor in the same sense as understood by C/C++.
