### ISSUE TITLE
Each document should have its own undo stack

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#419]
**Is your feature request related to a problem? Please describe.**
It appears that there is only a single undo stack. This doesn't mesh well with VSCode's tabbed interface where several documents can be edited concurrently.

**Describe the solution you'd like**
Each document should have its own undo stack so that ctrl + Z will step through only changes in that document, not the other documents. I've found that to be very valuable and easier to understand than a global undo stack.

**Describe alternatives you've considered**
A possible alternative is an undo window (I believe Adobe has (or used?) to have that where you could see a list of actions and thus selectively undo.

**Comment by WaynePhillipsEA** [comment]
I'm not seeing that behaviour - I've got separate undo stacks for each document.  Steps to reproduce?

**Comment by bclothier** [comment]
You're right. I do have multiple undo stacks. This was triggered when I goofed something relating to moving file or creating file, and then went to another document, worked on it, then ctrl+z only to get a dialog about undoing something.

I tried few things but I couldn't reproduce the exact steps. But in process, I discovered that the object explorer has its own undo stack independent of the documents, meaning that any renames, deletions, additions of the documents can be undone as long as the object explorer has the focus. I _think_ that may be why I got confused because it was changing things not relating to the current (but not focused) document.

**Comment by bclothier** [comment]
Ok, I think I got it now:

1. Create a new module, name it `x.twin`
2. Add code:
```
Public Module x
    Public Sub y()
        
    End Sub
End Module
```
3. Rename the file `x.twin` to `y.twin`
4. Focus the document in `y.twin`
5. Hit ctrl + z (with the intention to undo code)
6. Get dialog "Would you like to undo 'Rename x.twin to y.twin'?"

So the confusion on my part is that I was expecting to undo my code (from the step 2), not to undo the rename.

**Comment by WaynePhillipsEA** [comment]
Yes, the undo-rename is taking priority and blocking the undo-code in the code editor, which feels a bit.. weird.  That said, unfortunately you'd have to take that issue up with the VS Code team if you feel that needs attention, as tB doesn't get any say in that behaviour, so I'll close this.
