### ISSUE TITLE
data type hint symbol on arrays not allowed

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#422]
**Describe the bug**
Unlike in VBx it is not possible in tB to add a data type hint symbol on an array.

**To Reproduce**
```
Private MyStrArr(0 To 1) As String

' This project type is set to 'Standard EXE' in the Settings file, so you need a Main() subroutine to run when the EXE is started.
Public Sub Main()
    
    MyStrArr(0) = "Hello"
    MyStrArr(1) = "World"
    
    Debug.Print MyStrArr$(0) & " " & MyStrArr$(1)
    
End Sub
```

**Expected behavior**
to allow data type hint.

**Screenshots**
![image](https://user-images.githubusercontent.com/33756666/132480582-f71afa89-324f-4650-88df-8d0cb03ac3e0.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.10.5725]

**Additional context**
n/a

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.5735, thanks!
