### ISSUE TITLE
Using Enums from VBA (MS Access)

### ISSUE THREAD

**Issue by KDGundermann** [WaynePhillipsEA/twinbasic#424]
**Describe the bug**
Creating an ActiveX Library in TB with an Enum and referncing this in MS Access gives a compile error:
"Variable uses a automation Type not supported by VisualBasic"

**To Reproduce**
1 .Create ActiveX Project in TB
2. Create Class:

    [ AppObject ]
    Class ColorManager
	Public Enum e_Color
		e_Red
		e_Blue
		e_Green
	End Enum

	Public Function ColorName(ByVal Color As e_Color) As String
		Select Case Color
			Case e_Blue: 	ColorName = "Blue"
			Case e_Green: 	ColorName = "Green"
			Case e_Red:		ColorName = "Red"
		End Select
	End Function
    End Class

4. Create MS Access Database
5. Reference generated TB ActiveX dll
6. Create Module 
7. try to compile VBA code

**Expected behavior**
Enums should be usable by VBA

**Screenshots**
![image](https://user-images.githubusercontent.com/208315/132491451-5604e835-4fd6-492e-8304-60cd26ff84a7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - twinBASIC v0.10.5725
 - MS Access 32bit (Microsoft  365 Apps for Business) Version 2108

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.5735, thanks for reporting!
