### ISSUE TITLE
Run-Time error '438': Object doesn't support this property or method

### ISSUE THREAD

**Issue by tdimitriou** [WaynePhillipsEA/twinbasic#425]
**Describe the bug**
Twin Basic is not raising runtime error '438' (Object doesn't support this property or method) when calling a missing method of an object instance (when the object is declared 'As Object or Variant'). It is instead raising runtime error -2147352570 (&H80020006).

**To Reproduce**
Use the following code to reproduce the error:
```

Module MainModule

    Public Sub Main()
        On Error Resume Next
        
        ' MyClass declared as a generic object
10        Dim Obj As Object = New MyClass
        ' Calling a not existing member of MyClass
20        Dim Msg As String = Obj.GetMessage2

        If Err Then

            Debug.Print "Error: Number:" ; Err.Number ; "(&H" Hex(Err.Number) ; _
                        ") - Description: " ; Err.Description ; " at line " ; Erl
            Err.Clear

        End If

        ' MyClass declared as a variant
30        Dim Var As Variant = New MyClass
        ' Calling a not existing member of MyClass
40        Msg = Var.GetMessage2

        If Err Then

            Debug.Print "Error: Number:" ; Err.Number ; "(&H" Hex(Err.Number) ; _
                        ") - Description: " ; Err.Description ; " at line " ; Erl
            Err.Clear

        End If

    End Sub
	
End Module

Class MyClass
    
    Function GetMessage() As String

        Return "Hello, World!"

    End Function

End Class
```

**Expected behavior**
It would be much better to get the same run-time error number (438) for backward compatibility.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version: 0.10.5767

**Additional context**
The output of the debug console is as follows:
```
Executing 'NewProject.MainModule.Main'...
Error: Number:-2147352570 (&H80020006) - Description: Unknown name. at line  20
Error: Number:-2147352570 (&H80020006) - Description: Unknown name. at line  40
(time taken: 0.0000697s)

```

**Comment by WaynePhillipsEA** [comment]
Thanks for opening the issue.   Unfortunately, almost all error numbers and descriptions don't match VBx yet. 

I feel this is covered by issue #56, which is due to be tackled soon (this month), so I will close this a dupe.  Thanks.
