### ISSUE TITLE
false positive TB0003 for fixed array with a datatype suffix hint

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#426]
**Describe the bug**
A Dimmed fixed array with a datatype suffix hint gives false positive for TB0003 that it will default to variant.

**To Reproduce**
```
Public Sub Main()
    
    Dim MyLongFixedArray&(0 To 6)
    
End Sub
```

**Expected behavior**
No warning TB0003 as the datatype is specified As Long via datatype suffix hint.

**Screenshots**
![image](https://user-images.githubusercontent.com/33756666/132808798-7e858615-1447-40db-92dc-3185c78a379b.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.10.5767]

**Additional context**
n/a

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.5788, thanks!
