### ISSUE TITLE
Reinstallation of VSCode and Twinbasic: all code modules have are external source file warning

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#427]
**Describe the bug**
I've just done a deletion and reinstall of VSCode (to version 1.60.0 ia32) and have reinstalled twinBasic.  When I open a workspace all code modules are flagged with the warning 'you are editing an external source that is not part of this project'  The workspace is trusted.

If I use twinbasic to create a new project all is OK.  

**Screenshots**
![twinBasicExternalproject](https://user-images.githubusercontent.com/81257042/132839934-8b342b11-9517-4ccf-8175-de3b3fbfa25a.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - twinBASIC compiler version [v0.10.5767]

**Comment by FullValueRider** [comment]
Investigation seems to link this problem with the Export.bat batch file by  Mike Wolfe (mike@nolongerset.com). The batch file doesn't do anything wrong, but the use of Source as a destination folder confused me.   I normally just close vscode rather than closing the workspace then vscode.  With a new installation of VScode and twinbasic it seems the workspace opened showing the external files rather than the internal project.  I've resolved this by chaning the source path in the batch file to use ExternalSource.

This (where "ExternalSource" was just "Source""

![externalsource](https://user-images.githubusercontent.com/81257042/132854261-4156102c-1b63-4de1-81c0-152d026fc61c.jpg)
rather than
![project sources](https://user-images.githubusercontent.com/81257042/132854292-7bf6745f-6779-49c6-879c-8df1a7f6746c.jpg)

**Comment by WaynePhillipsEA** [comment]
Uninstalling VS Code will cause VS Code to lose all of its cached information about your project which is stored in the Windows AppData folder (such as whether you've trusted the project, and the state of explorer treeview etc).  

Anyway I'm glad you got this figured out.  Thanks.
