### ISSUE TITLE
Cannot For Each a variant array stored in a collection.  

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#434]
**Describe the bug**
I'm using a collection to capture the content of a variable primitive (as array),array, collection type, dictionary type.  When I try to iterate over the item captured in the collection I get an error.  If I replace the Collection with an ArrayList all works as expected.

**To Reproduce**
The code below demonstrates the issue. Changing the variable type from ArrayList to Collection produced an error on the For Each line

```
    Private Function GetParamArray(ParamArray ipArgs() As Variant) As Variant
        GetParamArray = ipArgs
    End Function

    Public Sub TestEnumerationOfVariantArrayInArrayList()
        
        Dim myIterable As ArrayList 'Change to Collection
        Set myIterable = New ArrayList
        myIterable.Add GetParamArray(1, 2, 3, 4, 5)
        Dim myItem As Variant
        For Each myItem In myIterable(0) ' Collection errors on this line

            Debug.Print myItem

        Next
        
    End Sub
```
![CollectionError](https://user-images.githubusercontent.com/81257042/133566665-f266b3ff-a642-415b-a344-6d82e601b55b.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - twinBASIC compiler version v0.10.5788]

**Comment by wqweto** [comment]
Collection must be 1-based or is this some custom Collection implementation?

**Comment by FullValueRider** [comment]
Ah. Yet another day where getting out of bed was a mistake.

**Comment by FullValueRider** [comment]
Sorry for wasting folks time.
