### ISSUE TITLE
Test not failing on errors

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#437]
**Describe the bug**
If a test case has a runtime error that was not handled, it should fail the test.

**To Reproduce**
Set up the code:
```
Public Class Derp
    Public Sub New()
        Err.Raise 5
    End Sub
End Class

[ TestFixture ]
Public Module Bonk
    [ TestCase ]
    Public Sub Duh()
        Dim doofus As Derp
        Set doofus = New Derp
    End Sub
End Module
```

Run the test case via the VSC. It will pass. 
Compare to running using F5, which will correctly show an error when creating the `Derp` class.

**Expected behavior**
It should fail since there were no error handler and error bubbled up unhandled.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - twinBASIC compiler version 0.10.5788

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.11.36, thanks for reporting
