### ISSUE TITLE
Adding `Not` to a expression crashes the compiler

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#449]
**Describe the bug**
Modifying a Boolean function to reverse the result (e.g. return `True` instead of `False`) by using the `Not` operator seems to crash given certain expression.

**To Reproduce**
1. Define the following function:
```
    Public Function CheckResult(Result As Integer) As Boolean
        Return ((Result And (Not 1)) = 0) 
    End Function
```
2. Verify it builds and can run correctly.
3. Modify the function by adding the `Not` as shown:
```
    Public Function CheckResult(Result As Integer) As Boolean
        Return not ((Result And (Not 1)) = 0) 
    End Function
```
4. Compiler crashes.

**Expected behavior**
The compiler shouldn't crash on what should be a simple negation of the Boolean expression.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - twinBASIC compiler version  v0.10.5788

**Additional context**
The function is intended to consider `0` or `1` as truthy and any other number as `falsy`. 

Also, the compiler will not crash if we use `= False` instead of the `Not`.

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.11.36, thanks for reporting
