### ISSUE TITLE
stdole type lib not complete

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#45]
**Describe the bug**
TwinBasic references automatically to OLE Automation v2.0
It includes for example the StdFont and StdPicture classes.
However, some classes are missing. For example IFontDisp and IPictureDisp. (or hidden classes IFont, IUnknown etc.)

**To Reproduce**
"Dim MyFont as stdole.IFontDisp" or
"Dim IUnk as stdole.IUnknown"
will not get recognized

**Expected behavior**
same interfaces as VB6 has.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.9.1622

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.9.1666.   Thanks for reporting.
