### ISSUE TITLE
Procedure scoped `Declare` statement 

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#452]
In the discussion in #406, @EduardoVB posted what I think is a great idea:
> Just to consider (probably not a good idea): how about adding procedure level API declaration capability?

_Originally posted by @EduardoVB in https://github.com/WaynePhillipsEA/twinbasic/issues/406#issuecomment-917408850_

Encapsulating the `Declare` statement in a procedure makes much more sense and is easier to read than the traditional approach of creating a `Private Declare` in the module’s declaration section, then defining a `Public` procedure to call the declared procedure with buffers set up, etc. Most of time, there is a 1:1 correlation between a given private `Declare` and a given public procedure that calls it. Locally scoping it would make for more readable code. For that reason I think it merits its own issue and discussion.

**Comment by mburns08109** [comment]
@Benclothier

Ditto - except that backwards compatibility...etc., etc.

**Comment by bclothier** [comment]
I think #65 will cover this if you want to write code guaranteed to be portable to VBx.

**Comment by WaynePhillipsEA** [comment]
Closing this in favour of #619 that has broader scope.
