### ISSUE TITLE
Accessibility doesn't belong on interfaces.

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#459]
**Describe the bug**
This code is legal and will build but it shouldn't.
```
Public Interface IDerp
  Private Function Duh()
End Interface
```

**Expected behavior**
This shouldn't be legal. The members should not have any access modifiers. Bonus points if auto-prettifier can automatically strip it out. Only the interface itself can have access modifiers. This should be legal:
```
Public Interface IDerp
  Function Duh()
End Interface
```

Note that in VB.NET, it is not legal.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - twinBASIC compiler version 0.10.5788

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.11.36, thanks for reporting
