### ISSUE TITLE
Duplicate line numbers not handled gracefully

### ISSUE THREAD

**Issue by madeinaus** [WaynePhillipsEA/twinbasic#470]
If I put in two lines with the same line number, I get hopelessly and irretrievably lost. I  don't get an error message, and I can't "run procedure under cursor", and I have to restart the compiler (which was not an obvious action for a beginner).

**To Reproduce**
Public Sub Main()
       On Local Error GoTo 12
       Dim b, c, s$
       19906097 MsgBox "Hello world!"
       19906107 MsgBox "fred"
       s$ = "aa"
       200 debug.print s$
       200 debug.print b,c
	Exit Sub
    12: MsgBox "on error" & Erl
    End Sub

**Expected behavior**
I don't know. I'm not familiar with VSCode.  I thought maybe I'd get an error message and be able to correct the bad line and continue, but I can't.

Win 7 64
VSCode 1.61.1
twinBASIC win32 0.11.41

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.11.45, thanks for reporting.    The duplicate line number was causing the parser to get stuck in an infinite loop, so it was then unable to give feedback via VS Code.

It may take a few minutes before the update is available to you via the VS Code Extensions panel.
