### ISSUE TITLE
Automatic line numbering in IDE

### ISSUE THREAD

**Issue by madeinaus** [WaynePhillipsEA/twinbasic#474]
The TB IDE has 'indent' and 'outdent' and 'comment' and 'uncomment' but not 'add line numbers' or 'renumber' or, as far as I can see, a way to get it to add line numbers at all.

Line numbering was never a part of the VB or VBA IDE, but enough people wanted structured error handling that third-parties used to offer it as an IDE extension.

(Editor file line numbers are not BASIC line numbers. File line numbers are useful for doing editing tasks: BASIC line numbers are useful for structured error reporting. I can see how to get the VScode IDE to report the file line number, and if I'm ever using a line-editor, I'm sure that would be useful, but it's a different feature.)

**Comment by WaynePhillipsEA** [comment]
In general I wouldn't want to encourage use of the legacy line numbers, so I can't see us implementing ourselves.

However, VS Code is very extensible, and it just so happens that there is already a line number generator addin in the marketplace:
https://marketplace.visualstudio.com/items?itemName=andersliu.insert-line-number

I have briefly tested the extension above, and it appears to work well alongside twinBASIC, so I will close this request.  Thanks.
