### ISSUE TITLE
Registry entry

### ISSUE THREAD

**Issue by uwbwsvd** [WaynePhillipsEA/twinbasic#482]
Is this registry entry generatet by TB?

![grafik](https://user-images.githubusercontent.com/41230018/138562392-38b3b877-b064-41e8-a91e-ae9748b166f9.png)

 - twinBASIC compiler version [v0.11.562]

**Comment by WaynePhillipsEA** [comment]
Sorry, I have no idea where that has come from.   I can see no reference to 'twinproj_auto' at all in the tB compiler, nor in the VS Code extension.

**Comment by WaynePhillipsEA** [comment]
As I can't see any evidence of this coming from our end, I'll close this for now.  If you get any further details, do please update here and I will re-open the issue if necessary.  Thanks.
