### ISSUE TITLE
Add error handling example to getting started

### ISSUE THREAD

**Issue by LeslieMurphy** [WaynePhillipsEA/twinbasic#484]
**Is your feature request related to a problem? Please describe.**
Running a test of hello world with some additional code, i get a "shutdown" message box with "unhandled error".

I tried to add a on error goto into the module but it won't compile

**Describe the solution you'd like**
Please include steps to show how to capture errors in the helloworld example.

Also document where / how debug.print gets logged within an EXE.

**Describe alternatives you've considered**

**Additional context**
I am trying to create a connection to ADO - but I think it is not working because I have 64 bit versions of Office.

```
Dim cn As Object, rs As Object, output As String
Dim sql As String
Dim fileName As String = "my path to an excel file"

Set cn = CreateObject("ADODB.Connection")
With cn
            .Provider = "Microsoft.ACE.OLEDB.12.0"
            .ConnectionString = "Data Source=" & fileName & ";" & _
            "Extended Properties=""Excel 12.0 Xml;HDR=YES;MAXSCANROWS=0;READONLY=TRUE"";" 'READONLY=TRUE IMEX=1
            .Open
End With

' fails before getting here 
MsgBox "Created connection!"

 sql = "SELECT DISTINCT Manager" + _
        " FROM [WFM$] " + _
        " ORDER BY Manager"

Set rs = cn.Execute(sql)
```

**Comment by WaynePhillipsEA** [comment]
> I tried to add a on error goto into the module but it won't compile

Please show us an example of what you've tried.   Error handling support in tB is the same as in VB6 / VBA.

>I am trying to create a connection to ADO - but I think it is not working because I have 64 bit versions of Office.

Yes, that's probably the case.  If you run the code in the debugger (press F5 when the caret is inside the procedure), it will stop execution at the erroring line.  Unfortunately, due to #56, you'll just get a generic 'Exception occurred' error, rather than getting the proper error description at the moment.

**Comment by LeslieMurphy** [comment]
In the debugger I now see I get error H80020009 when I attempt the connection (I am pretty sure this is because I have 64 bit office and can't attach a 64 bit DLL to the 32 bit Twinbasic app.  Would be nice-to-have if the EXE for a failing exception would log the exception to console.

 Exception occurred.
   Error Number: -2147352567 (&H80020009)

I got the error handling to work, thanks!

Note that the Debugger can't "Watch" the Err object and expand it to it's members.  I can watch Err.Number, Err.Description, etc. but Err itself does not expand to view the instance variables within it. 

```
Module ModHelloWorld
    Public Sub Main()

        On Error GoTo errHandler
        Debug.Print "starting"
      
        Dim cn As Object, rs As Object, output As String
        Dim sql As String
        Dim fileName As String = "C:\xxxx.xlsx"
        
        Set cn = CreateObject("ADODB.Connection")
        Debug.Print "Created connection object!"
        
        With cn
            .Provider = "Microsoft.ACE.OLEDB.12.0"
            .ConnectionString = "Data Source=" & fileName & ";" & _
            "Extended Properties=""Excel 12.0 Xml;HDR=YES;MAXSCANROWS=0;READONLY=TRUE"";" 'READONLY=TRUE IMEX=1
            .Open
        End With
        
        ' MsgBox "Created connection!"
        Debug.Print "Created connection!"

        sql = "SELECT DISTINCT Manager" + _
        " FROM [WFM$] " + _
        " ORDER BY Manager"
       
        Set rs = cn.Execute(sql)
        Do
            Debug.Print rs(0)
        rs.MoveNext
        Loop Until rs.EOF
        Exit Sub
        errHandler:
            Debug.Print "er" & Err.Number & " " & Err.Description
	
    End Sub
End Module


```

**Comment by WaynePhillipsEA** [comment]
I see that you've now got the ADO working in another thread.  With error handling being the same as VBx, I'll now close this.
