### ISSUE TITLE
Environ function does not work when running EXE

### ISSUE THREAD

**Issue by LeslieMurphy** [WaynePhillipsEA/twinbasic#485]
**Describe the bug**
Running an EXE crashes (with no error message) if Environ("temp")  is called.  The code works correctly within the debugger

**To Reproduce**
1. Run in debugger
2. Run as EXE

`MsgBox "temp is " & Environ("temp")
`

**Expected behavior**
Environ should work for EXEs

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version *** NOT SURE HOW TO DETERMINE THIS! ***

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.12.117.  Thanks for reporting!   

> twinBASIC compiler version *** NOT SURE HOW TO DETERMINE THIS! ***

The version number is displayed in the callstack window, and also in the Extensions activity bar.
