### ISSUE TITLE
Renaming an imported module (.bas) does not rename the Attribute correctly

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#488]
**Describe the bug**
I have a module in TwinBAsic named ResultItemEnums.bas with the attribute "Attribute VB_Name = "ResultItemEnums""

I renamed the module using 'rename symbol'.  All ocurrences of the  symbol in code were updated appropriately, but with the Attribute line, the new name was inserted at the start of the line rather than between the "". i.e. "ResultItemsEnumsAttribute VB_Name = "ResultItemEnums""

![ResultItemEnums](https://user-images.githubusercontent.com/81257042/139820379-3c9ac798-388a-4132-8cc6-892fdba77666.jpg)

**Expected behavior**
The name in the attribute assignment should be changed correctly

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - twinBASIC compiler version [0.11.1368]

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.13.4.  Thanks for reporting!
