### ISSUE TITLE
Control names

### ISSUE THREAD

**Issue by DinyaZ** [WaynePhillipsEA/twinbasic#489]
Hi! This is my first question as a "Professional edition" supporter. 
Isn't it possible to use the original VB6 control names? Now all the controls begin with "Waynes...". Ok, I know that this is your name, but it can be shorter, simpler, easier to read and even more compatible to use the original VB6 control names, "Frame", "Button", "Form", etc

**Comment by WaynePhillipsEA** [comment]
Hi, and thanks for trying out the GUI work. 

Naturally, these aren't the final control names :)   The current set of controls in Sample 6 are just provisional.  They should be considered examples of how to create CustomControls, and certainly not considered as finished controls.  The final controls will be simpler and more similar in design to normal VB6 controls.

Thanks again;  I will close this issue as this is by-design in the ALPHA release.
