### ISSUE TITLE
For .... Next problem

### ISSUE THREAD

**Issue by DinyaZ** [WaynePhillipsEA/twinbasic#490]
An interesting bug with a simple demo code:

Dim Ciklus as integer

 For Ciklus = 0 To 5
    MsgBox "-"+Str(Ciklus)
 Next Ciklus       

 MsgBox "SUM: "+Str(Ciklus)

I hoped that ciklus shows finally "5" as VB6 does, but the sum gives "6", so gets an unintended extra!

TW version 0.12.1

**Comment by jpbro** [comment]
VB6 Shows "SUM: 6".

**Comment by WaynePhillipsEA** [comment]
As @jpbro says, this looks perfectly correct (matching VB6), so I'll close this as a non-issue.
