### ISSUE TITLE
VSCODE Interface - Grrr

### ISSUE THREAD

**Issue by wopag** [WaynePhillipsEA/twinbasic#493]
Theres a reason us VB6 coders stayed with VB6,  nice easy IDE , uncomplicated always works. So im trying hard to get my head around VSCODE - grrrrr.

Pressing F1 - create a new project often results in    "(command 'twinbasic.createNewProject' not found') 
     I end up uninstalling and installing twinbasic again.  (well apart from this evening  - just cant get it to work again now)

Can F5 be configured to run main() - seems to always run code under cursor ? - might be jumping ahead here - I presume our "start up object" has not been implemented yet ?

Can F5 force the running program infront of VSCODE ?

Executing 'NewProject.MainModule.Main'...
RunCodeUnderCursor failed: main thread is busy.

Any way to clear this without having to restart?

**Comment by WaynePhillipsEA** [comment]
I hear ya.  We will most likely be moving to Theia eventually, then we will working off something more stable, and can start to simplify and customise the IDE to be more VB6-friendly, see #458.

Although we haven't got startup options yet, we do expose a VS code command of 'twinbasic.debuggerExecute' that you should be able to bind to any key through the VS code key mappings (passing the line of code you want to execute as a string argument).   I'll see if I can get that working tomorrow and let you know the exact instructions.

With regards to the main thread being busy... Does the stop button on the debug floating toolbar sort it?  If not, there's a restart button on the twinBASIC panel (it's the first button), that takes only a second or so to restart the compiler and debugger.

**Comment by wopag** [comment]
Main thread being busy was down to a messagebox that was behind VSCODE from a previous run - so my bad.  Just didnt see it

**Comment by WaynePhillipsEA** [comment]
So it is quite straight-forward to create your own keyboard shortcut for executing some tB code.  In VS Code, press F1, type 'Open Keyboard Shortcuts (JSON)'.  In the JSON file that opens, create an entry like this:

`// Place your key bindings in this file to override the defaults
[
    {
        "key": "f4",
        "command": "twinbasic.debuggerExecute",
        "args": "Main"
    }
]`

Save the file, and the keyboard shortcut should work.

**Comment by KarlSevenSeven** [comment]
I would appreciate a more VB-ish interface as well.
It doesn't have to be 100% the same; then we could just use VB...
**But the most used things could be more obvious.**
I don't know much about Theia, but if it is more customizable, then this should be the right track.

**Comment by WaynePhillipsEA** [comment]
I'm going to close this to keep the issues down.  We have the Theia discussion in #458 that will massively help in this area.
