### ISSUE TITLE
Disallow AddressOf on class members

### ISSUE THREAD

**Issue by WaynePhillipsEA** [WaynePhillipsEA/twinbasic#5]
**Describe the bug**
twinBASIC currently allows AddressOf to be used on class members

**To Reproduce**
1. Create a class with a member
2. Use AddressOf operator to get the class members runtime address

**Expected behavior**
A compile time error

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.9.1602

**Additional context**
AddressOf on class (non-static) members is not particularly useful due to the implicit Me argument.   VB6 and VBA explicitly disallow it.

**Source**
Email [ben-c]

**Comment by wqweto** [comment]
This is actually nice to have feature and I don't see harm leaving it as is.

I usually resorted to using some [ASM thunking](https://github.com/wqweto/ModernSubclassingThunk/blob/master/src/mdModernSubclassing.bas#L51-L63) to retrieve address of class methods in VB6 before.

**Comment by WaynePhillipsEA** [comment]
@wqweto yes that's my concern here, as it seems reasonable to assume we'll add delegates at some point, and this might conflict with it if we leave it in and people start using it.

**Comment by wqweto** [comment]
I suppose you are going to reuse `AddressOf` operator for delegates too but `AddressOf MyInstance.MyMethod` is different than `AddressOf MyClass.MyMethod` and currently VB6 allows only `AddressOf MyModule.MyFunction` so this last one is needed being implemented for compatibility reasons.

Leaving `AddressOf MyClass.MyMethod` implemented is not particularly dangerous to me but I have no clue about VB.Net delagates and might be missing something obvious here.

**Comment by bclothier** [comment]
@wqweto, the advantage of a delegate over an AddressOf is that this avoids working with raw pointer and allow for additional compile-time validation (e.g. verifying that the procedure being called has the correct number of arguments & data types). I am not sure if .NET does additional things to ensure that the delegate do not go out of scope as long it is referenced, but if it does, that would be another protection that `AddressOf` doesn't offer.

For a new development, I'd rather use something akin to delegates in twinBASIC for that reason alone; runtime errors are more expensive to fix than compile-time errors.

**Comment by mansellan** [comment]
@bclothier good point. In C# you can only use raw pointers inside ```unsafe``` blocks. VB.Net has no equivalent, so, not sure whether tB should or should not...

**Comment by WaynePhillipsEA** [comment]
This is now explicitly disallowed as of v0.9.2220, due to conflict with delegate proposals as mentioned in #79.
