### ISSUE TITLE
Support a ReadOnly modifier & actual immutable types

### ISSUE THREAD

**Issue by retailcoder** [WaynePhillipsEA/twinbasic#50]
**Is your feature request related to a problem? Please describe.**

Parameterized object construction opens the door for immutable objects; it is currently possible to design a class that is *effectively* immutable, but there is no compiler-level enforcing of this immutability.

**Describe the solution you'd like**

twinBASIC compiler should support a `ReadOnly` modifier for field declarations, and issue a compiler warning/error for any assignment of such a field outside of a constructor.

**Describe alternatives you've considered**

The alternative is to let immutability be an implementation detail that the compiler shouldn't be concerned about.

**Additional context**

If possible (and I'm not sure it even makes sense to do this), additionally allow a `ReadOnly` modifier to be specified for the fields of a `Private Type` structure, which would only allow such fields to be written to in a constructor of the containing class.

Supporting `ReadOnly` UDT fields in class modules would work nicely with my `This` pattern which eliminates the need for any kind of prefixing scheme for a class' private field names.

```vb
Private Type TState
    ReadOnly ImmutableValue As Long
    MutableValue As Long
End Type
Private This As TState

Public Sub New(ByVal Value As Long)
    This.ImmutableValue = Value
    This.MutableValue = Value
End Sub

Public Sub Test()
    This.ImmutableValue += 1 'should be a compile-time error
    This.MutableValue += 1 'no problem here
End Sub
```

That said I'd be happy if a `ReadOnly` modifier only worked on class instance fields... It would probably end up making me drop this backing UDT pattern altogether.

**Comment by WaynePhillipsEA** [comment]
The ReadOnly modifier on class fields would be pretty easy to implement.   It would also be easy from the COM interface point of view, since we'd just include a property-get without the corresponding property-let/set.

The ReadOnly modifier on UDTs would be a little harder.  It raises some issues about UDTs exported to the type library, as we'd still have to include the ReadOnly fields in the type information in order to keep the structure memory layout correct, but obviously COM has no way of enforcing our ReeadOnly attribute.  So perhaps we restrict the ReadOnly attribute to Private UDTs, just to keep things simple?

**Comment by retailcoder** [comment]
> So perhaps we restrict the ReadOnly attribute to Private UDTs, just to keep things simple?

Yes, exactly! I was thinking it would only make sense when the private UDT is defined in a class, because then in a standard module there's nothing to construct so any write to a UDT field would happen outside of a constructor.

Hadn't realized it could also work with *public* class fields, although I tend to see public fields in classic-VB more as *auto-properties* since they are exposed as `Property Get`/`Let`/`Set` - indeed it makes complete sense that a `ReadOnly` modifier would make the auto-property implementation only expose a getter then.

**Comment by WaynePhillipsEA** [comment]
> then it cannot be public!
In VBA, that is the case  ;-)

**Comment by retailcoder** [comment]
Ooooh 🤯

**Comment by EduardoVB** [comment]
Instead of `ReadOnly` I suggest the possibility of using the keyword `Const` that already means that.

**Comment by mansellan** [comment]
`Const` means that a value is literal, and can be embedded as such by the compiler.

`ReadOnly` means that values can be set at runtime, but re-assignment after construction is not allowed. So, no fields, no property let/set, and all fields must also be `ReadOnly` (i.e. set during construction only). The only way to apply values is as parameters into the constructor.

The difference only really comes into play when you have constructors available.

**Comment by EduardoVB** [comment]
In classes read only properties are already possible (only have Get but not Let/Set), but I guess that's not what you are proposing.

**Comment by mansellan** [comment]
> In classes read only properties are already possible (only have Get but not Let/Set), but I guess that's not what you are proposing.

Correct. but putting `ReadOnly` on the type means you can't accidentally include letters/setters.

Internally, it also means the compiler can reason as to the immutability of types. That enables some pretty great things.

**Comment by bclothier** [comment]
The name could be better. I think it's more accurate to think of it as "InitOnly". 

To illustrate, this is not legal:
```
Public Const DateCreated As Date = Now()
```

This code is closer but that's lot of typing and still does not prevent incorrect use:
```
Private mDateCreated As Date

Public Property Get DateCreated() As Date
  DateCreated = mDateCreated
End Property

Private Sub Class_Initialize()
  mDateCreated = Now()
End Sub

Public Sub MakeALiarOutOfMe()
  mDateCreated = CDate(0) 'Legal but semantically incorrect
End Sub
```

With `ReadOnly` construct, the code becomes much more simple & the intention is clearly expressed:
```
Public ReadOnly Property Get DateCreated() As Date = Now()

Public Sub MakeALiarOutOfMe()
  mDateCreated = CDate(0) 'Now a compile-time error
End Sub
```

As mansellan said, it is very helpful in specifying the intention behind the members especially when dealing with evaluations that can't be done at compile-time (like `Now()` in this example).

**Comment by EduardoVB** [comment]
> Correct. but putting `ReadOnly` on the type means you can't accidentally include letters/setters.

Never happened that to me.
So you mean a double check that it is read only.

> Internally, it also means the compiler can reason as to the immutability of types. That enables some pretty great things.

May be. I have no idea. I would have thought that the compiler could see that there is no Let/Set.

**Comment by mansellan** [comment]
> I have no idea. I would have thought that the compiler could see that there is no Let/Set.

It can. But it's easier to reason that "Letter is not allowed for a read-only type" than it is to reason "Let property is not valid because one or more generic types expect that MyFunkyType is not mutable".

It's also quicker for the compiler to reason about types marked `ReadOnly` than it is for them to resolve the entire tree.

**Comment by WaynePhillipsEA** [comment]
This is now supported, using the syntax of `Public ReadOnly FieldName`, or `Private ReadOnly FieldName`, as of v0.14.1.   Thanks!
