### ISSUE TITLE
Optional default value prevents ActiveX from compiling

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#512]
**Describe the bug**
The inclusion of a default value of a Method in a Class with a PredeclaredId is preventing compilation to an ActiveX library.

The code in native VBA is slowly being converted to take advantage of twinBasic improvements and to run as an ActiveX library rather than a library embedded in a WordTemplate document.

This is the code that causes an issue

![WithDefaultValue](https://user-images.githubusercontent.com/81257042/144026578-8967edb7-46ed-4ed8-aace-30745f923a52.jpg)

This is the code with no default value

![WithoutDefaultValue](https://user-images.githubusercontent.com/81257042/144026645-a6d13085-fec8-42ab-aa61-08dd9139a025.jpg)

I'm unsure as to whether or not this is a twinBasic issue or me doing something stupid elsewhere in the code.

The Project is attached. The error is in the Ranges class

[TwinLib64.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7624830/TwinLib64.zip)

**Desktop (please complete the following information):**
 - OS: windows 11
 - twinBASIC compiler version v0.13.9

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.13.10, thanks for reporting.
