### ISSUE TITLE
Debug console is slow and out of sync

### ISSUE THREAD

**Issue by KarlSevenSeven** [WaynePhillipsEA/twinbasic#513]
**Describe the bug**
The Debug console is slow and out of sync.
If 'too much' data comes in, it dies completely.

**To Reproduce**
```
  Dim n As Long
  For n = 0 To 2000000
    Debug.Print CStr(n)
   Next
```

**Expected behavior**
Should just work.

**Screenshots**
![image](https://user-images.githubusercontent.com/88059532/144056794-fac2f1b2-ae7c-47d5-85c9-7f665480d727.png)

**Desktop (please complete the following information):**
 - Windows 10
 - twinBASIC 0.13.9

**Comment by KarlSevenSeven** [comment]
> VBx IDE truncates on something like last 200 lines in Immediate Window which is too low IMO.

I agree, that's too low.
1000 or so would be fine.

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting.  I will look into what options we have on this, but I suspect we might only be able to clear the content completely, which is not quite what we want!  I'll get back to you on it once I've had chance to look at the VS Code API in this area.

**Comment by camomille22003** [comment]
to improve readability and speed see  #223

**Comment by KarlSevenSeven** [comment]
Still slow in beta 12.
It takes minutes to get to 5000.

Also I can't stop or CTRL-BREAK the run.

**Comment by WaynePhillipsEA** [comment]
> Still slow in beta 12. It takes minutes to get to 5000.
> 
> Also I can't stop or CTRL-BREAK the run.

Should be much improved in BETA 14

**Comment by KarlSevenSeven** [comment]
Beta 14:

Not 100% super.
After running the code 2x, the editor becomes very slow.
Tried it several times.

See video.

https://user-images.githubusercontent.com/88059532/162977705-11df3763-0323-494a-8c9f-f03f73780879.mp4

**Comment by WaynePhillipsEA** [comment]
I think now it's just a case of the renderer struggling to handle 80,000 HTML DOM nodes. We'll probably have to restrict it to 1000 or something sensible.
