### ISSUE TITLE
Failure to compile: Disconnected from compiler

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#514]
**Describe the bug**
The latest editing to my project 'TwinLib64' has resulted in lots of strange effects in VSCode and , when all errors are eliminated, a failure to compile, giving a brief 'disconnected from compiler message'

The strange effects seen are

1.  A small edit results in many many errors and white text, presumably due to a failure to parse.  Reloading the compiler clears this problem.  It is an issue because it is now occurring every few characters I type.

2. Odd methods are not recognised even though they exist in the code.

3. Attempts at compilation result in a Compiler disconnected message.

4. Before all the above started occurring I was able to compile but although the classes in the Library registered OK in the code, when debugging I was getting the message that the classes were not registered.

I am currently working through this library changing .cls and .bas files to .twin files (by renaming and editing) before starting to refactor using the twinbasic improvements.
 

 - OS: Windows 11
 - twinBASIC compiler version [v0.13.9]
 - 
[TwinLib64.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7627339/TwinLib64.zip)
![NotRegistered](https://user-images.githubusercontent.com/81257042/144091758-1477ff6d-dce4-4a6d-a0e2-cd76f82c7e49.jpg)

**Comment by FullValueRider** [comment]
OK.  All .bas and .cls are now .twin.  A project that was just about clean and compiling now has 3K+ errors <sigh>

**Comment by FullValueRider** [comment]
I found that recreating each module as a twin module (ctrl shift P etc) and then pasting the contents of the previous incarnation (from between the Class/Module <name> and end Class/Module) gave me a project with no errors.  Quite a tedious task to do.

However I'm still seeing the Compiler disconnected error and the Editor could not be opened etc error
[TwinLib64.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7629600/TwinLib64.zip)
.

**Comment by WaynePhillipsEA** [comment]
Hmm strange.  I'll look into this today for you.  Do you have a copy of the file in its worst state (the 3K+ errors)?   Thanks

**Comment by WaynePhillipsEA** [comment]
v0.13.10 out now that addresses the compiler crash on building this project.

**Comment by WaynePhillipsEA** [comment]
The many errors problem turned out to be a glitch in parsing the UTF8-BOM marker, sometimes affecting the parsing of Line 1 of a .twin file.   Fixed in v0.13.11.

I will close this now.  If you feel something is still not quite right, please let me know here and I will re-open.  Thanks.
