### ISSUE TITLE
Class Not Registered when using ActiveX library

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#516]
**Describe the bug**
Using my newly compiled TwinLib64 activex library (Thanks for the fix Wayne) I'm unfortunately now finding that I'm getting an unregistered class error when I try to use a class in the library

![ClassNotRegistered](https://user-images.githubusercontent.com/81257042/144216365-112d31a8-73fb-471d-89fb-4c79b624046e.jpg)

The deb is a factory method that returns an initialised Lyst.  I use the Lyst Class extensively within the TwinLib64 library and there are no problems running the tests for the Lyst class from within the TwinLib64 library (see Module Testing)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - twinBASIC compiler version 0.13.11

[TwinLib64.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7633001/TwinLib64.zip)

Again, apologies if this turns out to be my dodgy code.

**Comment by WaynePhillipsEA** [comment]
In the project referencing the library, is the correct build configuration active? (win64)

**Comment by FullValueRider** [comment]
Yes.  Win64 in both the  code above and also in TwinLib64

**Comment by WaynePhillipsEA** [comment]
OK I'll take a look.  Could you also attach the project that references the library?  Thanks

**Comment by FullValueRider** [comment]
A slight confession.  When I checked the project was win32 (I got confused as I have several open at the moment).  However with Win64 selected whilst I don't get the Class not registered error, there is no response and the thread stay busy even when I try to stop debugging.
[TestingTwin64Lib.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7633176/TestingTwin64Lib.zip)

**Comment by WaynePhillipsEA** [comment]
Yes, I can repro that.  Though it appears the library will load correctly from VBA (x64).

**Comment by WaynePhillipsEA** [comment]
I've located the issue; this will be fixed in the next half hour or so.

**Comment by WaynePhillipsEA** [comment]
That should now be fixed in v0.13.12.  Thanks!
