### ISSUE TITLE
Another editor crash

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#520]
**Describe the bug**
I was having my first play with generics in Module PointXY and I hit the unable to save problem again

![UnableToWrite](https://user-images.githubusercontent.com/81257042/144385771-3c2a5248-5b11-4fd5-ac35-6658a83d3cc9.jpg)

The project

[AoC2021twinBasic.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7640315/AoC2021twinBasic.zip)

and the compiled library

[TwinLib64v2_win64.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7640341/TwinLib64v2_win64.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - twinBASIC compiler version 0.13.13

**Comment by FullValueRider** [comment]
As an aside I was able to export the project, edit the affected file and reimport to get back to a working project.  Import and Export were done using Mike Wolfe's Import and Export macros

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.13.14.  Thanks for reporting.
