### ISSUE TITLE
Split is slow

### ISSUE THREAD

**Issue by KarlSevenSeven** [WaynePhillipsEA/twinbasic#521]
**Describe the bug**
Split is slow.
It's very slow in VB6 as well, but tB takes 3.5x the time.

**To Reproduce**
```
  Public Sub Main()
        
'bake large string
Dim i As Long
Dim LargeString As String

Tick_Start 3
For i = 0 To 10
LargeString = LargeString & "ABC" & CStr(i) & vbCrLf
Next
For i = 0 To 10
LargeString = LargeString & LargeString
Next
For i = 0 To 7' try with 6 or 7
LargeString = LargeString & LargeString
Next

Tick_Show 3, "-> build $"
Debug.Print "-> Len(LargeString)", Len(LargeString)

'split the large string
Tick_Start 2
Dim test() As String
Debug.Print "-> before split"
test = Split(LargeString, vbCrLf)
Tick_Show 2, "-> Split took"
Debug.Print "-> UBound(test)", UBound(test)
    
    End Sub

Public Declare Function GetTickCount Lib "kernel32" () As Long

Public Tick(0 To 9) As Long

Public Sub Tick_Show(ByVal Index As Integer, ByVal TheMessage As String)

    On Error Resume Next
        
    Dim ms As String
    Dim m  As String
    '--------------------------------------------------
        
    ms = CStr(GetTickCount - Tick(Index)) & " msec."
    m = m & TheMessage & ": " & ms & vbCrLf
    Debug.Print m
        
    End Sub
        
    Public Sub Tick_Start(ByVal Index As Integer)
        
    On Error Resume Next
        
    Tick(Index) = GetTickCount
        
    End Sub
```

VB6 numbers (in IDE):
-> build $: 31 msec.
-> Len(LargeString)          35127296 
-> before split
-> Split took: **93812** msec.
-> UBound(test)              5767168 

tB numbers:
-> build $: 32 msec.
-> Len(LargeString)          35127296 
-> before split
-> Split took: **325515** msec.
-> UBound(test)              5767168 

**Expected behavior**
At least same performance as in VB6

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC 0.13.14

**Additional context**
I came to this because I use a class called Lickety when large files have to be stored in an array.
VB6's Split is far to slow for this usage.
As this class doesn't work correct in tB, I was eager to see if tB's Split is better.
Up to now it is not.

**Comment by wqweto** [comment]
Btw, the class above is using [SplitB05](http://www.xbeat.net/vbspeed/c_Split.htm#SplitB05) from vbspeed which is an unremarable (but quite fast) VB6 implementation using `SysAllocStringLen` from a typelib and this can be a good model for TB's internal `Split` implementation IMO.

**Comment by WaynePhillipsEA** [comment]
This should be somewhat better in v0.13.15.   Let me know how you get on

**Comment by KarlSevenSeven** [comment]
"Somewhat better", you are funny...
You improved it by factor 100!
30x faster than VB6.

VB6 IDE/EXE: 93812 msec.
0.13.14: 325515 msec.
0.13.15: 3141 msec.

Out of curiosity:
Is this based on SplitB05?

Very good Wayne.
Solved.

**Comment by WaynePhillipsEA** [comment]
Great.  Amazingly I only changed one line of code to get this improvement (a buffer size change).  The algo is not based on SplitB05, but looking at SplitB05, it's already very similar.  SplitB05 might be a little quicker in some instances as it pre-allocates the maximum needed buffer up-front (at the cost of potentially allocating much more memory than needed).  I feel that my algo is more balanced and suited for the general use case.

Anyway, I'm glad you're happy with it.  I'll close this now. Thanks.

**Comment by WaynePhillipsEA** [comment]
In v0.13.16 there's a further boost in performance if you use Option Compare Binary too (or pass the equivalent Compare argument to Split)

**Comment by KarlSevenSeven** [comment]
Seen it a couple of minutes ago.
Impressive!
