### ISSUE TITLE
Lickety: performance not on par with VB6

### ISSUE THREAD

**Issue by KarlSevenSeven** [WaynePhillipsEA/twinbasic#522]
**Describe the bug**

See attached VB6 and tB project.
They shall do exactly the same.
The VB6 project's results are the correct ones.

It's about this class which massively improves file reading:
https://www.vbforums.com/showthread.php?781599-VB6-Lickety-an-alternative-to-Slurp-n-Split&highlight=Lickety

In the example tB is quite slow, can't imagine why.
I also tried with the new Split from the .15 version, but that's not an acceptable replacement for Lickety.

Unfortunately the file to read is big, and the different ubound result is not with an arbitrary file.
So this file is attached as well  (adjust path in the examples).

**To Reproduce**
Run the examples

**Expected behavior**
Same result as in VB6 and better performance

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version [e.g. 0.13.15]

[Bigfile.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7649138/Bigfile.zip)
[LoadBig_VB6.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7649146/LoadBig_VB6.zip)
[LoadBig_tB.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7649154/LoadBig_tB.zip)

---

Edit:
I now tried with .16, and the Split performance is even better now.
Practically the same as VB6 with Lickety.
The question is, why Lickety doesn't perform as well as in VB6.

**Comment by WaynePhillipsEA** [comment]
I will check Lickety out tomorrow.   Thanks for reporting.

**Comment by WaynePhillipsEA** [comment]
This is the line failing in tB for Lickety:
`Lines = Split(vbNullString) 'Valid String array with Ubound = -1.`

tB produces an array with UBound = 0 for that edge case.  Fixed in my internal build, ready for release later.

**Comment by WaynePhillipsEA** [comment]
The above Split() edge case is fixed in v0.13.18.   The performance will also be a tiny bit better with Lickety now (with Option Compare Binary on), but still not quite on par with VB6.  I've identified the two lines of code that are slower than VB6 to work on next week.

**Comment by WaynePhillipsEA** [comment]
As of v0.13.19, performance of Lickety should be roughly on par with VB6 now.   If you switch InStr to the new InStr$ implementation, it will squeeze a little more out of it.   Plus switching to 64-bit also helps a fraction more.

**Comment by KarlSevenSeven** [comment]
Looks good now!

`InStr$`
Fine, it's faster. 
In future, how do we know that such optimized functions exist?
Or what do we need the regular Instr for?

---

In general, the whole Lickety thing is superflous now - Split is fine.
Except Lickety uses less memory.
On the other hand, this example revealed some weak points.

**Comment by wqweto** [comment]
There is no `InStr$` in VBx because `InStr` calls are actrually handled instrnallt by the compiler runtime calling __vbaInStr export, not as an external function in a DLL. This allows skipping string to variant conversions that would need to happen at `VBA.InStr` callsite. Here is the disassembly

```
    Print InStr("ba", "a")
0040199E 6A 01                push        1  
004019A0 68 28 16 40 00       push        offset ___vba@06ED15D0 (401628h)  
004019A5 68 34 16 40 00       push        offset ___vba@06ED15E0 (401634h)  
004019AA 6A 00                push        0  
004019AC E8 B1 F7 FF FF       call        @__vbaInStr (401162h)  
004019B1 50                   push        eax  
004019B2 FF 75 08             push        dword ptr [Me]  
004019B5 68 3C 16 40 00       push        offset ___vba@06ED15EC (40163Ch)  
004019BA E8 A9 F7 FF FF       call        ___vbaPrintObj (401168h)  
004019BF 83 C4 0C             add         esp,0Ch  
    Print VBA.InStr("ba", "a")
004019C2 C7 45 C4 04 00 02 80 mov         dword ptr [ebp-3Ch],80020004h  
004019C9 C7 45 BC 0A 00 00 00 mov         dword ptr [unnamed_var1],0Ah  
004019D0 C7 45 94 34 16 40 00 mov         dword ptr [ebp-6Ch],offset ___vba@06ED15E0 (401634h)  
004019D7 C7 45 8C 08 00 00 00 mov         dword ptr [unnamed_var1],8  
004019DE 8D 55 8C             lea         edx,[unnamed_var1]  
004019E1 8D 4D CC             lea         ecx,[unnamed_var1]  
004019E4 E8 6D F7 FF FF       call        ___vbaVarDup (401156h)  
004019E9 C7 45 A4 28 16 40 00 mov         dword ptr [ebp-5Ch],offset ___vba@06ED15D0 (401628h)  
004019F0 C7 45 9C 08 00 00 00 mov         dword ptr [unnamed_var1],8  
004019F7 8D 55 9C             lea         edx,[unnamed_var1]  
004019FA 8D 4D DC             lea         ecx,[unnamed_var1]  
004019FD E8 54 F7 FF FF       call        ___vbaVarDup (401156h)  
00401A02 6A 00                push        0  
00401A04 8D 45 BC             lea         eax,[unnamed_var1]  
00401A07 50                   push        eax  
00401A08 8D 45 CC             lea         eax,[unnamed_var1]  
00401A0B 50                   push        eax  
00401A0C 8D 45 DC             lea         eax,[unnamed_var1]  
00401A0F 50                   push        eax  
00401A10 8D 45 AC             lea         eax,[unnamed_var1]  
00401A13 50                   push        eax  
00401A14 E8 43 F7 FF FF       call        @__vba@06ED1F9C (40115Ch)  
00401A19 8D 45 AC             lea         eax,[unnamed_var1]  
00401A1C 50                   push        eax  
00401A1D FF 75 08             push        dword ptr [Me]  
00401A20 68 44 16 40 00       push        offset ___vba@06ED15F8 (401644h)  
00401A25 E8 3E F7 FF FF       call        ___vbaPrintObj (401168h)  
00401A2A 83 C4 0C             add         esp,0Ch  
00401A2D 8D 45 AC             lea         eax,[unnamed_var1]  
00401A30 50                   push        eax  
00401A31 8D 45 BC             lea         eax,[unnamed_var1]  
00401A34 50                   push        eax  
00401A35 8D 45 CC             lea         eax,[unnamed_var1]  
00401A38 50                   push        eax  
00401A39 8D 45 DC             lea         eax,[unnamed_var1]  
00401A3C 50                   push        eax  
00401A3D 6A 04                push        4  
00401A3F E8 0C F7 FF FF       call        @__vbaFreeVarList (401150h)  
00401A44 83 C4 14             add         esp,14h  
```

There are lot of "functions" which are included in VBx typelibs but are handled internally like `CLng` and most other conversion functions, `StrComp`, etc.

You can distinguish these "surrogate" functions which are implemented by the runtime when you try to get their pfn with `Address Of` e.g. this works
```
Debug.Print VBA.CLng(AddressOf VBA.InStr)
```
while this fails
```
Debug.Print VBA.CLng(AddressOf InStr)
```
because `InStr` is not `VBA.InStr` although it's a nice imitation and on `Shift+F2` over `InStr` the IDE suggests and locates `VBA.InStr` documentation.

**Comment by WaynePhillipsEA** [comment]
Yes, exactly.  VBx already has the InStr$ optimization, but just doesn't expose it manually and instead binds to it automatically when appropriate.  I think it's better for tB to expose it more openly as it does now, but I also want tB to auto-bind to it like VBx does in a future update.

FWIW most of the other ones you mention, e.g. all the conversion functions, are all internally handled much like VBx.

I'll close this now, as I feel this issue is fixed.  Thanks for reporting this issue, and do please report any other performance differences you notice.
