### ISSUE TITLE
Avoid as many reserved keywords as possible

### ISSUE THREAD

**Issue by EduardoVB** [WaynePhillipsEA/twinbasic#53]
**Is your feature request related to a problem? Please describe.**
Avoid to add many reserved keywords whenever if possible and also if possible remove some existent restrictions.
Reserved keywords limit the naming of variables and more importantly of properties and methods.

**Describe the solution you'd like**
It would be great if it could take into account the context where the name is used, to allow names when there is not conflict.
I guess it can be hard (it is easier to ban a keyword entirely), but still I want to express the wish.

**Additional context**
For example, I made a replacement of the SSTab control, but I was not able to achieve full backward compatibility due to the fact that "Tab" is a reserved keyword in VB6. And "Tab" is the name of a property of the original SStab.
Since the original SSTab was not compiled in VB6, it seems that this restriction didn't apply to it.

**Comment by WaynePhillipsEA** [comment]
You should already find that tB is lot more forgiving in this regard, as the parser does always take the context into account.

**Comment by EduardoVB** [comment]
Sorry I didn't want to imply that tB had these restrictions, I made the suggestion based on VB6. I'm glad that tB can lower the restrictions.

**Comment by WaynePhillipsEA** [comment]
Just for further information.... VB does this because it first tokenizes the code.  It has a list of internal tokens ('reserved words') and as a first-pass parses the source code into a tokenized form.

twinBASIC skips that step completely, and goes straight to context-aware parsing.
