### ISSUE TITLE
Editor, false indentation after special characters

### ISSUE THREAD

**Issue by adakordev** [WaynePhillipsEA/twinbasic#530]
**Describe the bug**
After having a special character in the code, the indentation of the following code does not work properly anymore. It does not matter if the special character is in a comment, or part of the code, for example a part of a variable name.

![grafik](https://user-images.githubusercontent.com/31490758/144701239-e3db8eab-9f5c-4dd9-b6bf-8195dd5c5bb0.png)

**To Reproduce**
Use one of the following special characters and place them in the code. Tested examples:
German: äÄ öÖ üÜ ß
Polish: Ł
Turkish: Â Ç
this smiley 'works' as well: 😀

win10
0.13.17

**Additional context**
Wayne, if possible, please read my second last post from thread #507 with the ICON/ .ico issue. 
Is it an issue and should I open an issue here? Thanks.

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting, I will check both of these soon and get back to you.

**Comment by WaynePhillipsEA** [comment]
v0.13.22 fixes this issue.  I have addressed the icon issue in the other discussion.

Thanks for reporting!
