### ISSUE TITLE
Project is destroyed on trying to set configuration

### ISSUE THREAD

**Issue by KarlSevenSeven** [WaynePhillipsEA/twinbasic#533]
**Describe the bug**
After trying to set a build configuration the project is destroyed.

**To Reproduce**
Start VS.
'Create ActiveX DLL'.
Name it, e.g. "C".
Trust the workspace.
(No Build config is selected)
Click the green folder icon win32.
Under 'Configuration: Inherits from', select win32.
'Save all' in the file menu.
Right click the green folder icon win32 or the text and try to set this configuration active.
Can't work, the menu entry to do so is missing.
Close VS.
Double click the "C.code-workspace" file.
The whole thing is destroyed somehow, the 'C.twinproj' doesn't load.

**Expected behavior**
Leave the project healthy.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version [e.g. 0.13.18]

**Additional context**
I drag/dropped a larger ActiveX project together from VB6 source files.
After some corrections I decided build the DLL.
Couldn't find a menu or icon or whatever to do so.
Then I saw the win32/64 config was not set, so I did (or better tried to) set it.
End of the story see above.

Q1:
How to build the ActiveX DLL?

Q2:
Any chance to repair the destroyed project?
So that I wouldn't have to start from scratch?

BTW, I have the .18 version in here, but I know it is .19.

---

VS is quite cumbersome to work with.

**Comment by WaynePhillipsEA** [comment]
You shouldn't be able to set the 'Inherits' option to the same name as the configuration you're editing, as it creates a circular reference.  That's a bug that I will get fixed shortly.

For now, please edit the code-workspace file in a text editor, changing the following line:
`"configuration.inherits": "win32",`
to 
`"configuration.inherits": "Defaults",`

Save the file, and then it should open as usual again in VS Code. 

I'm aware of the configuration icons being wrong and the menu option not being available.  This is a regression introduced in the November VS Code release.  I haven't checked if it is fixed yet in the upcoming release, but if it is not I will have to find a workaround.   Closing and re-opening VS code usually fixes it and the icons etc then work as expected.   

Note that you can also change the Active Build using the drop-down in the twinBASIC panel:
![tbActiveBuild](https://user-images.githubusercontent.com/25738109/144872739-d42a81a0-4f3a-47d4-9a0e-8872c81b59fd.png)

**Comment by WaynePhillipsEA** [comment]
Update: just tested with the insiders version of VS Code, and the icon & menu problem discussed above look to be fixed, so that will no longer be a problem once the next VS Code update is released  later this week.
