### ISSUE TITLE
Compiler crashes when trying to run ANY code

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#534]
**Describe the bug**
I have managed to get my project into a state where it compiles perfectly fine, but trying to run any code within the project (such as the tests in the Testing Module) causes the compiler to crash (cancelled).  It does not matter which test I run, the compiler immediately crashes.

**To Reproduce**
1. With the attached project attempt to run Tester in the Testing Module

Code is currently setup so that it only tries to run the first test in TestStrings.StringTester

 - OS: [e.g. Windows 11
 - twinBASIC compiler version 0.13.19
[VBALib64.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7661204/VBALib64.zip)

**Comment by WaynePhillipsEA** [comment]
Hmm, I'm not seeing that behaviour with my internal build, so I will investigate further.  

Changing this line makes the tests pass for me:
`If VBA.IsEmpty(ipIterable) Then Exit Function`  to 
`If VBA.IsEmpty(ipIterable) Or VBA.IsMissing(ipIterable) Then Exit Function`

(I also had to fix up 2 string encoding errors which I think is where you've switched from ANSI .bas/cls to unicode .twin format)

**Comment by WaynePhillipsEA** [comment]
Also, I've just pushed v0.13.20.  I'd appreciate if you could check if it still crashes for you with the latest build.   For me, when I open your unaltered file and run the Testing.Tester procedure, the debugger stops at the assertion in T09_ConvertDoubleQUotes, but does not crash.

**Comment by FullValueRider** [comment]
I'm a complete moron and do not deserve to be allowed anywhere near a PC.  Please accept my apologies for wasting your time - I attached the wrong zip.  Please try the attached zip
[TwinLib64.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7661714/TwinLib64.zip)

**Comment by WaynePhillipsEA** [comment]
No worries!  This crash is fixed in v0.13.21, and you will now receive a proper error diagnostic telling you of the problem that caused the crash.  In this case it was using Return with an expression that doesn't return a value (a subroutine).  Thanks for reporting!
