### ISSUE TITLE
Q: How to find compilation error

### ISSUE THREAD

**Issue by KarlSevenSeven** [WaynePhillipsEA/twinbasic#535]
**Describe the bug**
Not a bug but a question.
In an ActiveX project I get 
`[LINKER] compilation error detected in 'Zigzag.Generate'`

In VB6 the identical project compiles fine.

**To Reproduce**
Build the project - which you can't up to now, see additional context below.
Therefore this is a question not a bug report.

**Expected behavior**
tB points to the error.

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - twinBASIC 0.13.20

**Additional context**
The project is confidential, so I can't post it here.

**Comment by WaynePhillipsEA** [comment]
The majority of compilation errors are caught during the resolving stage, and these are the red squiggles that you will see in the editor.  In an ideal world, all errors would be caught at the resolving stage, but at the moment some errors slip through and only get caught at the final codegen stage.

Errors that occur at the codegen stage will either show as "COMPILATION ERROR" when you try to invoke the procedure via the debugger, or with the "[LINKER] compilation error detected' message during building.

I've been wanting to improve this situation for a while, and so tomorrow I'm going to see if I can at least add the line number to these codegen error messages, as that would help track down the problem more easily.

**Comment by WaynePhillipsEA** [comment]
v0.13.22 is now available, and the linker message (and the runtime COMPILATION ERROR message) will now include the line number associated with the first codegen failure.  e.g.
`[LINKER] compilation (codegen) error detected in 'Zigzag.Generate' at line #123`

Once you've identified the line causing the fault, please try to reduce the problem into a little snippet that you can post here so that I can look into it further for you.  Thanks!

**Comment by KarlSevenSeven** [comment]
To complex to strip down to a small example.
![image](https://user-images.githubusercontent.com/88059532/145019168-ac283850-c2c1-4c5c-8788-a78908c1a4fc.png)

```
[LINKER] compilation (codegen) error detected in 'Zigzag.Generate' at line #398
[LINKER] FAILED due to compilation errors 'q:\TB\MyTest\CPP\Build\CPP_win32.dll'
[BUILD] failed
```

```
        Set SubContZigzagTmp.Elements = ListRet
        Set SubContZigzagTmp.BoundingBox = BoundingBox
        SubContZigzagTmp.CT = CTZigzag
        ContZigzag.SubcontourCount = ContZigzag.SubcontourCount + 1
        Set ContZigzag.SubContour(ContZigzag.SubcontourCount - 1) = SubContZigzagTmp
```

I don't know how to proceed now.
As said, the source is confidential.
I could send the source in private but not in public.
You won't be willing to inspect everyones source and fix errors in the source.
On the other hand, there is no error in the source, it compiles and runs fine in VB6.

What do you propose?

**Comment by WaynePhillipsEA** [comment]
I'd be happy to take a look at it privately for you as that will be the quickest way forward.  I'm not mistaken, I think you've already got my email, so please just get in touch and I can send you a private link to share the file.  Thanks

**Comment by KarlSevenSeven** [comment]
No email received up to now...

**Comment by KarlSevenSeven** [comment]
Sent.
Is an answer to the preorder subject.

**Comment by WaynePhillipsEA** [comment]
Thanks, received.  I'll take a look.

**Comment by WaynePhillipsEA** [comment]
Yes there's a bug here, as the compiler is not allowing the RHS of the property-set to be an As-New variable (_SubContZigzagTmp As New Contour_).  I'll get that fixed, thanks for reporting.

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.13.23.   Thanks for reporting!

**Comment by KarlSevenSeven** [comment]
Thanks for the quick action.
I'll now try how the result behaves.
First observation: The result is very large in comp to the VB result.
Doesn't matter for now, I think this is addressed by optimized compilation later.

**Comment by WaynePhillipsEA** [comment]
Yes, the LLVM compiler will certainly help reduce the file size, but also remember that the tB compiled version is fully self-contained and does not require the MSVBVM60 runtime dll.
