### ISSUE TITLE
v0.13.23 appears to be causing issues when initialising factory objects enclosed within another object

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#537]
**Describe the bug**
I have a Lyst object.  The Lyst object exposes a Result object.  I can create a Result object no problem.  During the initialisation of the Lyst object, the assignment of the new result object causes an exception

This works fine
```
 Public Sub newResult()
        Dim myResult As Result = Result.Deb
    End Sub
```
But this causes an exception
```
 Public Sub newLyst()
        Dim myLyst As Lyst = Lyst.Deb
    End Sub
```
When we get to the line in Lyst which initialises the enclosed Result object
```
If p.Result Is Nothing Then 
            
            Set p.Result = Result.Deb.SetOkay
```
![CantInitEnclosedObject](https://user-images.githubusercontent.com/81257042/145052365-c6edfc7d-7040-4cb8-9a7b-89a631cd6eac.jpg)

p is an instance of my Properties UDT for the Lyst class
```
Private Type Properties
        
       Result                                   As Result
        
        
    End Type

    Private p                                   As properties
```
**To Reproduce**
Steps to reproduce the behaviour:
In the Attached zip, goto Module Pootle and run the two code snippets above.

[TwinLib64.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7669268/TwinLib64.zip)

And yes, TwinLib64.zip is the correct upload

**Desktop (please complete the following information):**
 - OS: WIndows 11
 - twinBASIC compiler version v0.13.23

**Comment by FullValueRider** [comment]
v0.13.24 is showing the same issue.  I'm also noticing a couple of other issues

VBA.Typename is not working

The error reported is '[equal] operator not allowed here, unable to convert type 'String' to type 'VBA' TypeName ( ByRef VarName As Variant ) As String'
![TYpeNameNotRecognised](https://user-images.githubusercontent.com/81257042/145180446-9bf9c4c7-9ccf-4619-87a1-d7c62d023f76.jpg)
If the VBA is emoved then a space is inserted betrween TYpename and (Me) which reappears if you delete it

In a similar fashion I'm getting an error trying to return a string via the function name
![CanotAssignString](https://user-images.githubusercontent.com/81257042/145180703-9bb6ec6b-3579-4164-b388-354d7e8148b2.jpg)

**Comment by WaynePhillipsEA** [comment]
> v0.13.24 is showing the same issue. I'm also noticing a couple of other issues
> 
> VBA.Typename is not working
> 
> The error reported is '[equal] operator not allowed here, unable to convert type 'String' to type 'VBA' TypeName ( ByRef VarName As Variant ) As String' ![TYpeNameNotRecognised](https://user-images.githubusercontent.com/81257042/145180446-9bf9c4c7-9ccf-4619-87a1-d7c62d023f76.jpg) If the VBA is emoved then a space is inserted betrween TYpename and (Me) which reappears if you delete it
> 
> In a similar fashion I'm getting an error trying to return a string via the function name The error reported here is 'unexpected end of expression unexpected end of line unrecognized symbol '{unexpected end of line}' ![CanotAssignString](https://user-images.githubusercontent.com/81257042/145180703-9bb6ec6b-3579-4164-b388-354d7e8148b2.jpg)
> 
> I've restarted vscode several times but the problems persist. Code is unchanged from the zip attached above

I haven't looked at the first issue posted here yet, but this second issue is a keyword clash with the Name syntax as mentioned in another issue (https://github.com/WaynePhillipsEA/twinbasic/issues/541#issuecomment-988628506).  See that link for a temporary fix for that.

**Comment by WaynePhillipsEA** [comment]
The above Name-As syntax clash is now avoided in v0.13.25.  I will hopefully get to look at the first issue detailed in this thread later today.

**Comment by WaynePhillipsEA** [comment]
OK, back to the opening problem.  This doesn't look to be a compiler bug.    Inside your Lyst class you've defined property get/set for `Result`, so your call to `Result.Deb.SetOkay` is binding the `Result` to the class property, and not the predeclared class `Result`.

I'll close this for now;  if you still feel something is not right, just let me know and I'll re-open
