### ISSUE TITLE
For/Next (general looping) with embedded Labels

### ISSUE THREAD

**Issue by mburns08109** [WaynePhillipsEA/twinbasic#539]
**Is your feature request related to a problem? Please describe.**
In VBA7, the following construct generates a (bogus) compile error:
FOR Each N in Whatever
DotItAgainForMe:
  'code to do some stuff with N here
  If SomeTestHere Then Goto DoItAgainForMe
Next    <-- next without For compiler error here

**Describe the solution you'd like**
This should not be a compiler error - While I can appreciate the woes of jumping to code OUTSIDE a loop, you should be able to jump to code WITHIN the loop as no execution contexts are really being violated.

**Describe alternatives you've considered**
Yes, I could refactor the code to make this go away. However, for temporary-/testing- type of coding scenarios, that's just plain overkill. There should be a way to accommodate this sort of thing - even at the peril of (ok, deserved) compiler warnings.

**Additional context**
Now, BEFORE you all jump down my throat about GOTOs...I want to point out that I occasionally need to do something like this in the context of some automated testing approaches (and NOT production-level code!) - so this is NOT a proposal to encourage GOTO programming...but for Temporary, Testing-level code, this should be acceptable practices and compile to runnable code! - even if we need to resort to some hack-ish code attributes or something to make it work:
For Each N In whatever
DoItAgainForMe:[Attribute: LoopLocalOnly]
  'code to do some stuff with N here
  If SomeTestHere Then Goto[Attribute: LoopLocalOnly] DoItAgainForMe
Next

**Comment by WaynePhillipsEA** [comment]
I'm not really following here, as what you've described is not a compile error:

```
Dim n As Variant, Whatever As Variant
For Each n In Whatever
DoItAgainForMe:
    'code to do some stuff with N here
    If SomeTestHere Then GoTo DoItAgainForMe
Next
```

**Comment by mburns08109** [comment]
> In VBA7, the following construct generates a (bogus) compile error:

I prefaced my comments with the above...in VBA it IS a compile error.  (that it's NOT in tB, cool with me!)
...but it begs a technical question.
I'd asked about this way back...Jeez, when I was doing GWBasic/BasicA code, because I once fell into a fatal GoSub loop...and ran the machine out of stack space until *boom*.
(it boiled down to a construct like this:
10 'do stuff here
20 Gosub 10
30 Return     '...oops!
)

I actually got a technical explanation for that failure - GoSub requires stack space for the current execution context of the code before it does its GoTo, and with only so much stack space available, the above eventually ran out of stack.
The VBA folks (again, way back), explained that "jumping out of loops with a GoTo" had a similar problem as loops also created an execution context that cleans itself up upon closing the loop normally. Goto-out-of-a-loop ran into many potential issues as a result, and they basically disallowed it (thus the VBA7 compile error mentioned above).

So, make this an "are you sure this couldn't be a problem" question, then...?

**Comment by WaynePhillipsEA** [comment]
The example you've given is still not an error, neither in VBA or tB...
 you're not jumping in/out of the for-loop, so there is no error.

**Comment by mburns08109** [comment]
Ok, you made me go back to the exact code I had just tried it and was getting the compile error in VBA7 just yesterday.
TODAY, I un=comment out the label inside the for loop and the Goto lines, and it compiles!?? WTH!

I swear to you that it was throwing Next without For compiler errors on this exact same code just YESTERDAY!!

So, change all this post to read, Hey, can tB be CONSISTENT about this at least!?? (as opposed to VBA, apparently) sheesh!

**Comment by WaynePhillipsEA** [comment]
No worries.  I'll close this as a non-issue.  Thanks.
