### ISSUE TITLE
Preprocessor conditional block expression evaluation error

### ISSUE THREAD

**Issue by wqweto** [WaynePhillipsEA/twinbasic#544]
**Describe the bug**
Preprocessor consts assigned expr with non-existent consts fail on evaluation.

**To Reproduce**
```
#Const ImplSomething = (NONEXISTENT_CONST_THAT_MUST_EVAL_TO_EMPTY <> 0)

#If ImplSomething Then                              <---- #if block expression error
    Private m_oLog As Object
#End If
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version [e.g. 0.13.26]

**Comment by WaynePhillipsEA** [comment]
This should now be fixed as of v0.13.27.  Thanks for reporting.
