### ISSUE TITLE
C-string types should be recognized in typelibs

### ISSUE THREAD

**Issue by wqweto** [WaynePhillipsEA/twinbasic#549]
**Describe the bug**
Currently `LPWSTR` (and probably `LPSTR`) data-type on method parameters of an interface in a typelib are flagged as `{unsupported}` data-type while VBx list these `As String`

**To Reproduce**
See `GetIDsOfNames` method of `IVbCollection` in the attached typelib: [UcsVbCall.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7693494/UcsVbCall.zip)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - twinBASIC: 0.13.27

**Additional context**
Attaching a typelib with redefinition of `VBA.Collection` where all `HRESULT`s retvals are converted to non-throwing `Long`s (so that key existence can be checked without error trapping).

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting.   There is already an issue for this, raised by @kr00l (#381), so I'll close this in favour of the earlier one.

**Comment by WaynePhillipsEA** [comment]
Just FYI, this is now supported, as of v0.13.32.
