### ISSUE TITLE
COM references: Import from file should auto-enable the new reference

### ISSUE THREAD

**Issue by WaynePhillipsEA** [WaynePhillipsEA/twinbasic#553]
### Discussed in https://github.com/WaynePhillipsEA/twinbasic/discussions/548

<div type='discussions-op-text'>

<sup>Originally posted by **wqweto** December 10, 2021</sup>
In PROJECT->Settings in `COM Type Library / ActiveX References` section the button `[Import from file...]` should probably add the newly imported typelib to `ENABLED COM REFERENCES` by default too, the way VBx does with the equivalent button.

Now it's mostly impossible to find the newly imported typelib in the long list of `ALL AVAILABLE COM REFERENCES` particularly if you don't actually know the name of the typelib the way they are listed there (you know only the `filename.tlb` you select in open file dialog).</div>

**Comment by WaynePhillipsEA** [comment]
Totally agree, I'll get that fixed.

**Comment by WaynePhillipsEA** [comment]
This is now effective as of v0.13.54, thanks @wqweto

**Comment by wqweto** [comment]
I somehow managed to get my project's `ImportTypeLibraries` folder our of sync with the list `ENABLED COM REFERENCES` flagged `[IMPORTED]`.

When I used `Import from file...` button to re-add the missing reference it said `Cannot copy tlb to ImportTypeLibraries as it's already present there` (or similar) but did not add `[IMPORTED]` reference which baffled me for a while if this is working at all.

At this point the only way to re-add the tlb as an `[IMPORTED]` reference was to first delete the file from `ImportTypeLibraries` folders which is not very intuitive IMO.

**Comment by WaynePhillipsEA** [comment]
The imported references will still appear near the top of the available references list, even if they are not enabled.

But I take your point, that this could be improved.

**Comment by wqweto** [comment]
Btw, the new search bar there is a nice touch :-))

**Comment by WaynePhillipsEA** [comment]
Lol it's not new... it has been there for about 6 months.  Which proves it must be in a bad position!

**Comment by wqweto** [comment]
Ouch!  If I've seen this would have never asked form quick-find by letter in the ListBoxes :-))

**Comment by WaynePhillipsEA** [comment]
No worries, that was needed from an accessibility POV anyway, so it's all good 😀

**Comment by bclothier** [comment]
I suspect the expectation is that the search functionality comes at the top of whatever it's going to search. Most web browsers and software pop up its searchbox in the upper (usually but not always upper right) quadrant of the area in response to ctrl + F. Only one (Firefox?) does it in the bottom left (not sure if they still do that).

**Comment by WaynePhillipsEA** [comment]
I'll re-open this so that I remember to tweak the search bar position

**Comment by WaynePhillipsEA** [comment]
Search bar is now more discoverable in v0.13.55

**Comment by Kr00l** [comment]
> Search bar is now more discoverable in v0.13.55

![image](https://user-images.githubusercontent.com/33756666/147215810-80c6fca2-5456-436b-8524-c46672ebf574.png)

It would be nice to have a magnifier with a red cross sign, so the filter can be simply removed by a click and not and manually erasing the filter phrase.
Also it would be a helpful indication that a filter is currently in place. (means the magnifier with red cross is grayed out when no filter is in place)

**Comment by WaynePhillipsEA** [comment]
Clear filter button now available in v0.13.56:
<img width="363" alt="tbReferenceImprovements4" src="https://user-images.githubusercontent.com/25738109/147334136-81cffc47-57f5-42d4-9477-6b5ed144b1be.png">
