### ISSUE TITLE
VB6 .vbp file?

### ISSUE THREAD

**Issue by DinyaZ** [WaynePhillipsEA/twinbasic#557]
Not a bug report, only a question. How can I import a simple VB6 written project to the Twinbasic? No GUI, nothing special in the code, just for test.
If it is not implemented yet, what is the roadmap about it?

**Comment by WaynePhillipsEA** [comment]
Not possible at the moment, but I'm looking at this in the coming week, so check back soon.

**Comment by mansellan** [comment]
Duplicate of #303

**Comment by WaynePhillipsEA** [comment]
This is now supported as of v0.13.36.  Please see [https://github.com/WaynePhillipsEA/twinbasic/issues/303#issuecomment-994564767](url) for more detail.
