### ISSUE TITLE
Add line label autocomplete to IntelliSense

### ISSUE THREAD

**Issue by mwolfe02** [WaynePhillipsEA/twinbasic#559]
**Is your feature request related to a problem? Please describe.**
After typing `GoTo ` at the start of a line, if I press [Ctrl] + [Spacebar] to bring up IntelliSense it only shows "{no match}".

**Describe the solution you'd like**
I'd like IntelliSense to show me the labels available as part of autocomplete.  That way, I can type `GoTo`, {space}, and then just arrow down once or twice to pick the label I want to reference.

**Describe alternatives you've considered**
Actually type every single character of the line label I'm trying to reference.  Like some kind of savage.

**Additional context**
Current behavior in twinBASIC:

![image](https://user-images.githubusercontent.com/305213/145726334-62d74d92-5342-4a8c-ad99-c5db8896e5f4.png)

Note that this is NOT implemented in the VBA IDE, either.  But, I think it would be a nice touch if it's not a lot of work to implement.  

This is definitely a low-priority request.

**Comment by WaynePhillipsEA** [comment]
This is now implemented in v0.13.54, thanks for the suggestion!
