### ISSUE TITLE
Failed build does not recover gracefully

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#561]
**Describe the bug**
It appears that if there was an error with the build due to it being in use, subsequent attempts to build after it is no longer in use will continue to fail without manual intervention of deleting the output.

**To Reproduce**
1. Create an ActiveX DLL project and create an object
2. In VBA host (Access), reference the project and load the object
3. With VBA host still open, try to build the tB project in VS Code. Get the following messages:
```
[UNREGISTER] previous type-library deregistration completed. DllUnregisterServer() returned OK
[LINKER] FAILED to create output file 'C:\Path\To\Sample_win64.dll'
```
4. Close VBA host.
5. Try to build again via VS Code. Get the following errors:
```
[LINKER] FAILED to create output file 'C:\Path\To\Sample_win64.dll'
[UNREGISTER] type-library deregistration FAILED.   DllUnregisterServer() returned TYPE_E_REGISTRYACCESS (launch VS Code with 'Run As Administrator' option)
```

The build will never succeed. One must then manually delete the DLL file before build works again. 

**Expected behavior**
In this case, the build on the step 3 was an user error so the error is expected. However, after the error has been corrected, it should have no problem re-building in step 5. It should not necessary to delete the DLL file to get the build to work again.

The suggestion to run VS Code as an administrator seems misguided in this context. Is it because there's no distinction between a missing key and a key without permission? If so, we may need a check to avoid suggesting running as an admin if it's a matter of missing key rather than lack of permission.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.13.30, 64-bit

**Comment by WaynePhillipsEA** [comment]
This is now improved in v0.13.50:
<img width="798" alt="tbRecoverBuild" src="https://user-images.githubusercontent.com/25738109/146890177-23f743a3-9906-4505-8961-8350820ee1d7.png">
Thanks for reporting!
