### ISSUE TITLE
Keywords in labels as quoted identifiers

### ISSUE THREAD

**Issue by wqweto** [WaynePhillipsEA/twinbasic#563]
**Describe the bug**
```
        Dim [Continue] As Long                      <--- this works
        [Continue] = 1
        Debug.Print [Continue]
        


'        GoTo [Continue]                            <--- this does not compile
'[Continue]:

        GoTo [Continue2]                            <--- this works
[Continue2]:
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version: 0.13.32

**Comment by WaynePhillipsEA** [comment]
I've fixed this in my internal build.  I'm just considering whether we could improve the backwards compatibility for the 'Continue' keyword here.  E.g.  if `Continue` is followed by a colon, then it is always treated as the line label, rather than the new Continue statement?   I'm not particularly fond of such exceptions, but I think in this particular case it might be worth it.

**Comment by wqweto** [comment]
I'm not conviced this is such particularly used label in VBx codebases that it need a special handling outside of generic "new keywords as labels/identifiers" solution.

It just happened that I stumbled upon it in my sources and keep on using in various discussions but the frequency of its usage is not certain at all.

**Comment by WaynePhillipsEA** [comment]
Yeah OK, we'll leave it as is for now.   Once implemented, the 'legacy' switch will turn off the Continue statement support, and so in a large old codebase it would be easy to fix that way.

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.13.33, thanks for reporting!

**Comment by wqweto** [comment]
I just noticed that plain `GoTo Continue` now works with no quoting while it's only the label `[Continue]:` which requires quotes which is a nice touch.

**Comment by WaynePhillipsEA** [comment]
> I just noticed that plain `GoTo Continue` now works with no quoting while it's only the label `[Continue]:` which requires quotes which is a nice touch.

Ah yes, I didn't change that.  The `Goto Continue` was only erroring previously because there was no matching label found.

**Comment by mansellan** [comment]
> I'm just considering whether we could improve the backwards compatibility for the 'Continue' keyword here. E.g. if Continue is followed by a colon, then it is always treated as the line label, rather than the new Continue statement? I'm not particularly fond of such exceptions, but I think in this particular case it might be worth it.

Rather than special-casing for `Continue`, couldn't you treat any line that had a single identifier (potentially with square brackets) and was _immediately_ followed by a colon as a label? IIUC, the other use for the colon (statement separation) is only valid as a separate symbol, i.e. it must be preceded and succeeded by whitespace?

**Comment by wqweto** [comment]
Reading [MS-VBAL.pdf](https://interoperability.blob.core.windows.net/files/MS-VBAL/[MS-VBAL].pdf) the section on Statement Labels
```
statement-label-definition = LINE-START ((identifier-statement-label “:”) / (line-numberlabel [“:”] ))
statement-label = identifier-statement-label / line-number-label
statement-label-list = statement-label [“,” statement-label]
identifier-statement-label = IDENTIFIER
line-number-label = INTEGER
```
. . . it looks like there is no whitespace after `LINE-START` and before `:` but I'm not sure for the former (`LINE-START` might be defined to skip whitespace at the end of it).

**Comment by mansellan** [comment]
Pinging @WaynePhillipsEA as he may not have seen this being as its already closed.

**Comment by WaynePhillipsEA** [comment]
> > I'm just considering whether we could improve the backwards compatibility for the 'Continue' keyword here. E.g. if Continue is followed by a colon, then it is always treated as the line label, rather than the new Continue statement? I'm not particularly fond of such exceptions, but I think in this particular case it might be worth it.
> 
> Rather than special-casing for `Continue`, couldn't you treat any line that had a single identifier (potentially with square brackets) and was _immediately_ followed by a colon as a label? IIUC, the other use for the colon (statement separation) is only valid as a separate symbol, i.e. it must be preceded and succeeded by whitespace?

That's a very good observation!  That's pretty much what happens already, _except_ for the keywords available in that context.  But from testing, it looks like your proposal is correct, and should not have any adverse affects.  I'll do some more tests, but I think that should be a very good fix for this, thanks.

**Comment by WaynePhillipsEA** [comment]
So in v0.13.38, line label bindings take precedence over keyword symbol matching in the root context, that will now allow 'Continue' to work as a regular line label.   Though it has the side-effect of allowing any keyword to be used as a line label...
<img width="203" alt="tbLineLabelsReservedWords" src="https://user-images.githubusercontent.com/25738109/146218479-7d0afa92-42b2-4261-9be2-8b4b9cf088d4.png">

But I'll leave it to the analysis extension API to warn about that (#51).   Thanks @mansellan!

**Comment by WaynePhillipsEA** [comment]
With v0.13.39, the fix has now been restricted to the `Continue` keyword.

**Comment by mburns08109** [comment]
@WaynePhillipsEA 
Actually, thinking about it - you should be able to parse those out appropriately still.
If the ":" is the last token on the line (other than possibly a comment only), then interpreting it as a line label would still be appropriate - even if that isn't 100% backward-compatible with VBx.

If there is anything OTHER THAN just a comment after the :, then the ":" would be a statement separator, but if only a comment, then it could still be a label declaration.

I don't see that as being a bad/breaking departure from the 100% backwards compatibility rule. ...or am i missing something?
