### ISSUE TITLE
Long variable not shown in MsgBox

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#566]
**Describe the bug**
a Long variable will not be shown in a MsgBox. (LongLong, Integer etc. works)

**To Reproduce**
```
Public Sub Main()
    
    Dim IntLng As Long
    IntLng = 100
    
    MsgBox IntLng
    
End Sub
```

**Expected behavior**
to display 100

**Screenshots**
![image](https://user-images.githubusercontent.com/33756666/146027591-b85f77a1-f313-4dbc-afdd-21b3fa27ba0f.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.13.34]

**Additional context**
`MsgBox CLng(IntLng)`
resolves the issue currently.

**Comment by WaynePhillipsEA** [comment]
Oops, a bit of a regression there!   Fixed in v0.13.35 being published now (available in about 5 minutes).  Thanks for reporting.
