### ISSUE TITLE
Doesn't support global variables

### ISSUE THREAD

**Issue by WaynePhillipsEA** [WaynePhillipsEA/twinbasic#57]
**Describe the bug**
twinBASIC does not yet support any form of global variables or constants.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.9.1666

**Additional context**
Global variables here specifically refers to:   
    Module-level private and public variables
    Module-level private and public constants
    Static variables
    Objects with predeclared identifiers

**Comment by WaynePhillipsEA** [comment]
This is a known limitation with the preview release.  Reported here so that we can track it.

**Comment by retailcoder** [comment]
Does this also affect public enum types or that would be a separate issue? Enums appear to export correctly and both the object browser and Rubberduck appear to be able to work with it, but consuming a twinBASIC enum in actual VBA code doesn't compile, says something about the type being unsupported in Visual Basic.

**Comment by WaynePhillipsEA** [comment]
No that sounds like a separate issue.

**Comment by WaynePhillipsEA** [comment]
v0.9.1881 adds initial support for global variables and constant.   Static variables and predeclared objects will be supported in a further update in a week or so.

<img width="462" alt="globalVarsDemo" src="https://user-images.githubusercontent.com/25738109/115662225-9519f580-a336-11eb-89b6-72707c32ab0b.png">

Inline initializers are supported, so you can simulate predeclared objects for now 😉

**Comment by Kr00l** [comment]
Out of curiosity. Is there a technical way difference between myAccess and myAccess2 ?

I know that in VB* a variable which is declared with "As New" has a small internal overhead each time referring to it. (It checks each time if is nothing and if yes it sets New)
Will myAccess be different?
Means is it the as if there is a second line "Set myAccess = New Access.Application
?

Thanks

**Comment by WaynePhillipsEA** [comment]
@Kr00l yes, the overhead is the same in twinBASIC.   myAccess is more efficient.

**Comment by t-dimitriou** [comment]
Just tried the new compiler (v0.9.1881). Global variable can be accessed from another Module but not from a Class. 

Here is my test code:

```
Module modMain
    Public myLong As Long = 250
    
    Sub Main()
        TestModule.Test
        
        Dim myTestClass As TestClass = New TestClass
        myTestClass.Test    
    End Sub
End Module

Module TestModule
    Sub Test()
        MsgBox modMain.myLong
    End Sub
End Module

Class TestClass
    Sub Test()
        MsgBox modMain.myLong
    End Sub    
End Class

```

**Comment by WaynePhillipsEA** [comment]
@t-dimitriou thanks!  confirmed.... on it 👍

**Comment by t-dimitriou** [comment]
@WaynePhillipsEA 👍

I am short of words to thank you for your incredible job. This will be a great product!

**Comment by WaynePhillipsEA** [comment]
Thanks!   Fixed in v0.9.1882 being published right now.  If you check back in 5 minutes, it should be ready in the marketplace.

**Comment by t-dimitriou** [comment]
@WaynePhillipsEA 

Confirmed. Works like a charm!

**Comment by EduardoVB** [comment]
> predeclared objects will be supported in a further update in a week or so.

Are predeclared objects already supported? I guess not because I'm trying to access a member of a GlobalMultiUse class from a DLL but get an error.

**Comment by WaynePhillipsEA** [comment]
@EduardoVB they're supported for tB classes, but not from external type libraries just yet.  Apologies as this went off the radar slightly.   I'll get to it this week 👍
