### ISSUE TITLE
Issues with the COM Addins sample

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#576]
**Describe the bug**
I identified 3 different issues relating to the COM Addin samples.

1) The 64-bit registry entries are not correct. It uses this path:
```
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\{Access or Excel}\Addins64\MyCOMAddin.MyCOMAddin
```

The issue is that there's no `Addins64` in the HKCU branch of Office addin registration. It should be simply `AddIns`. That also means we don't really need two separate .reg files for 32-bit and 64-bit. 

2) If I incorrectly mark the ribbon callback methods as `Private`, it could crash. Example:
```
	Private Sub OnHelloWorldClicked(Control As IRibbonControl)
		MsgBox "Hello world, from twinBASIC!" & vbCrLf & _
					"(via " & applicationObject.Name & ")"
	End Sub

	Private Function OnGetHelloWorldButtonImage(Control As IRibbonControl) As IPictureDisp
		Return LoadResPicture("twinBASIC_icon.bmp", vbResBitmap)
	End Function
```

The image handler is handled gracefully:
![image](https://user-images.githubusercontent.com/2367644/146647139-23694514-9803-48b1-b483-0ffbe15a50eb.png)

However, clicking the button results in a hard crash:
![image](https://user-images.githubusercontent.com/2367644/146647147-dc45a1e8-c12c-4759-a2ee-fa246e742a7e.png)

Lastly, I am not sure if that is an issue but the generated type library seem to have stubs that might should not be there:
```
    interface _MyCOMAddin : IDispatch {
        [id(0x60020000), restricted]
        void Missing7();
        [id(0x60020001), restricted]
        void Missing8();
        [id(0x60020002), restricted]
        void Missing9();
        [id(0x60020003), restricted]
        void Missing10();
        [id(0x60020004), restricted]
        void Missing11();
        [id(0x60020005), restricted]
        void Missing12();
```

**To Reproduce**
Registry File:
1. Create the add-in using the sample 5
2. Build, register with the appropriate reg file.
3. Open 64-bit Access or 64-bit Excel. Try to load the add-in. Note that it is not even available.
4. Close the application
5. Edit the reg, change from `Addins64` to `AddIns`
6. Open the application and try to load the add-in. It is now available.

Crash on ribbon callbacks:
1. Using the same project, change from `Public` to `Private` for the procedures `OnHelloWorldClicked` and `OnGetHelloWorldButtonImage`.
2. Open the host application. Go to `Options` and under general settings, enable that `Show Add-In Interface Errors` is checked.
3. Load the addin via the host application.
3. Navigate to the tab. Get the expected ribbon callback error.
4. Click the button without the image. Application will crash.

Missing entries:

-- Use OleView to inspect the type library embedded within the built DLL.

**Expected behavior**
No crashes on the ribbon callback and registration just works. A clean type library would be a bonus.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 64-bit Office
 - twinBASIC compiler version 0.13.43

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting.  

#1. Apologies, this is a mistake copied over from the VBE addin sample, which does use the Addins64 folder.  Typical Microsoft inconsistency.

#2 and #3 I'll check them, thanks

**Comment by WaynePhillipsEA** [comment]
In v0.13.44 I've updated Sample 4 and Sample 5 so that we no longer use the reg files.  Instead, the extra registration is now done through the DllRegisterServer callbacks, and of course I fixed the Addins64 issue for the Sample 5.   

I haven't looked at (2) yet.   

For (3) this is correct and matches VBx behaviour.  3 extra vtable entries are created per Implements statement, to match the vtable layout of VBx.

**Comment by WaynePhillipsEA** [comment]
As of v0.13.45, (1) and (2) are fixed.  As mentioned, the extra restricted vtable entries are as expected, so I'll close this issue now.

Thanks for reporting!

**Comment by NguoiHaiPhong** [comment]
I want to create functions that can be called directly from worksheet cells by COM Add-in.
please help me!

**Comment by bclothier** [comment]
@NguoiHaiPhong , 

Please note that this issue is closed; if you have a specific questions or comment, please open a new issue. Thanks!

There are samples you should play with. When you download beta release ( see #772 ) and launch it, you should see samples tab. Look at sample 5 and 9 (see screenshot below) for ideas. I also encourage you to look at other samples as well.

![image](https://user-images.githubusercontent.com/2367644/170829958-baa020a8-d289-46c6-818b-c8b614e4624a.png)

The two articles may also help:
https://nolongerset.com/creating-a-twinbasic-activex-dll/
https://nolongerset.com/create-activex-control-with-twinbasic/
