### ISSUE TITLE
Restricted attribute does not work late-bound

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#577]
**Describe the bug**
If a member is decorated with `Restricted` attribute, but is called late-bound, it seems to be circumvented. 

**To Reproduce**
1. Use the sample 6 to create a COM add-in project
2. Add `Restricted` attribute to the `OnAddInsUpdate` method. Uncomment the `Msgbox` code.
3. Register the add-in and launch the host application. Get the exepcted message box at the startup
4. Open VBIDE
5. Add the reference to the add-in project
6. Declare a strong-typed variable:
```
Public x As MyCOMAddIn.MyCOMAddin
```
7. Execute via immediate:
```
Set x = New MyCOMAddin.MyCOMAddin
x.OnAddInsUpdate Array(1,2,3)
```
8. Get the expected error message about method being restricted.
9. Change the variable from `MyCOMAddin.MyCOMAddIn` to `Object`.
10. Execute the code in immediate window again. The message box shows.

**Expected behavior**
The `[Restricted]` attribute ought to be effective. I suspect this is due to the `IDTExtensibility` interface being used rather than the `_MyCOMAddIn` interface. Not sure if it's possible to prevent late-bound calls from circumventing this.

**Additional Context**
I originally wanted report this because I had a hard crash but I was unable to reproduce this. 
 
**Desktop (please complete the following information):**
 - OS: Windows 10
 - 64-bit Office 365
 - twinBASIC compiler version 0.13.47

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.13.54, thanks!

**Comment by bclothier** [comment]
Just to check -- from changelog:

> fixed: members marked with the Restricted attribute can no longer be invoked via IDispatch::Invoke

That only applies for calls made from the automation context, and not from another part of the tB code or non-Automation context, right?

**Comment by WaynePhillipsEA** [comment]
No, that applies globally, as we don't currently determine the context of the IDispatch caller (which could be difficult to achieve reliably).  It is assumed that calling the code from tB will be early-bound (i.e. through the vtable), and so will bypass the restriction that way.
