### ISSUE TITLE
Regression with overloading in version 0.13.43 & 0.13.44

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#578]
**Describe the bug**
The custom controls sample no longer compiles, complains about ambiguous overloads between `New()` and `New(ColorRGBA As CustomControls.ColorRGBA, PositionPercent As Double)`. Reverting to 0.13.42, the project will then compile. 

**To Reproduce**
1. In 0.13.42, create a CustomControls sample project
2. Verify there are no errors & build. It should succeed.
3. Bump the version to 0.13.43 or 0.13.44. Reload the same project
4. The project reports 2 problems due to ambiguous overloads. The project no longer compiles.

**Expected behavior**
It should compile. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.13.43 and 0.13.44

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.13.45, thanks!
