### ISSUE TITLE
Unable to create a new form

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#579]
**Describe the bug**
A circular reference error is given when creating a new form. Custom Controls sample seem to work OK, and I am not able to see what might be different that causes the error.

**To Reproduce**
1. Create a 64-bit ActiveX DLL project
2. Add custom control library reference
3. Use add component and create a new form of whatever name
4. The `.twin` file reports a circular reference error.

**Expected behavior**
No errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/2367644/146676409-5500db6d-4584-465f-a676-59767744cd99.png)

Note: this does not exist in custom controls sample.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version [e.g. 0.13.42

**Comment by WaynePhillipsEA** [comment]
At the moment you are best starting with the CustomControls sample (sample 6).  

The error message is obviously incorrect here.  At a minimum, you need the zTemporarySupport.twin file and the WaynesForm.twin file copied into the project in order to get things working.

**Comment by lunasoft2001** [comment]
[twinForms.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7762070/twinForms.zip)
1. Settings - Reference: Enable [twinBASIC Extension‘ Custom Controls Library [v1.0]
2. paste the zip files into the corresponding folders
3. Refresh

**Comment by WaynePhillipsEA** [comment]
As of v0.13.84, the custom controls are now available in a TWINPACK package.   From now on, only add the `[twinBASIC Extension] Custom Controls Library [v1.0]` reference if you are **creating a new custom control.**

To use the provided (experimental) custom controls, you should now instead reference the ***package*** `CustomControlsPackage`, available via the package manager service.

**This means that you no longer need the zTemporarySupport.twin file, nor the WaynesGrid.twin files (etc), in your main project, and should delete all of them if you already have them to avoid conflicts going forward.**
