### ISSUE TITLE
Build does not work if there's multiple VS code sessions

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#580]
**Describe the bug**
If there are 2 instances of VS Code with different tB project in each, the 2nd project is unable to build.

**To Reproduce**
1. Create or open one tB project.
2. Verify that it builds by clicking build and seeing the output from debug console.
3. Open another instance of the VS Code (it should be two separate windows)
4. Open a second tB project
4. Try and build the second project. This simply does nothing and the compiler gets restarted but zilch.

**Expected behavior**
Should be able to view and build either projects concurrently.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.13.45

**Comment by WaynePhillipsEA** [comment]
Hmmm, I can't think what that would be off the top of my head.   I'll look into it.

**Comment by WaynePhillipsEA** [comment]
v0.13.46 should be available to you shortly.  Please let me know if that fixes the issue for you.

**Comment by bclothier** [comment]
Yep, it did! Thanks!
