### ISSUE TITLE
Compilation is failing

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#581]
**Describe the bug**
This is likely another egg on face scenario.  However, my TwinLib64 project  is showing no errors but I get a failed compilation message when I try to create the activeX.
![TwinBasicFailedCompilation](https://user-images.githubusercontent.com/81257042/146685549-4ee02e04-014c-415b-8c12-d99cf2365fe7.jpg)

Its not clear as to what the error is so I'm stuck trying to get resolution.

I can create Advent Of Code solutions and run them in the attached project.  Day 07 is included in the attached library as an example.

- I tried the clean build, no success.
- I deleted the dll found in the build directory, no success
- I round tripped to VBA and back.  In VBA (Word) I resolved all the compile and Rubber Duck inspection issues that were not evident in Twinbasic. No success.
- The class that is mentioned in the error message I've observed to change from KVP to KVPair depending on what I tried to tweak last.

**To Reproduce**
Try to compile the attached project

**Expected behaviour**
Compilation should succeed  hopefully with a slightly more informative message.  

**Desktop (please complete the following information):**
 - OS: WIndows 11
 - twinBASIC compiler version see screenshot

**Additional context**
[TwinLib64.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7741304/TwinLib64.zip)

**Comment by WaynePhillipsEA** [comment]
Parameters with explicitly `Empty` default values are causing type library generation to fail.  This will be fixed shortly.

**Comment by WaynePhillipsEA** [comment]
Now fixed in v0.13.47, thanks for reporting!
