### ISSUE TITLE
"Import from Visual Basic..." not available in F1 menu

### ISSUE THREAD

**Issue by mwolfe02** [WaynePhillipsEA/twinbasic#582]
**Describe the bug**
Importing from Visual Basic not an option in the F1 -> Create new project... menu.

**To Reproduce**
1. Press [F1]
2. Type "twinBASIC: Create new project"
3. Press [Enter]

**Expected behavior**
Make the option "import from Visual Basic ..." available in the F1 menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/305213/146700263-45e6998d-d6d2-42e0-937e-42ecb2a06a02.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version v0.13.46

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.13.47, thanks!
