### ISSUE TITLE
Trying to use a TwinBasic ActiveX dll gives "Class not registered"

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#583]
**Describe the bug**
Atempting to use classses defined in a TwinBasic activeX dll is giving a class not registered error

![ClassNotRegistered](https://user-images.githubusercontent.com/81257042/146733579-1d50c421-caf8-47d7-adb7-9fe6238d8707.jpg)

**To Reproduce**
1. Compile the attached library
[TwinLib64.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7743574/TwinLib64.zip)
2. In a new project add a reference to the library
3.  Attempt to run the following code.

```VBA
Module Pootle

Public Sub TestTwin64LibAccess()
    
    Dim myLyst As Lyst
    ' Deb calls the factory method that returns a new instance of the Lyst Class
    Set myLyst = Lyst.Deb
    myLyst.AddRange Array(1, 2, 3, 4)

End Sub

End Module
```
**Expected behaviour**
The call shoulld succeed

**Desktop (please complete the following information):**
 - OS: windows 11
 - twinBASIC compiler version see screenshot

**Comment by WaynePhillipsEA** [comment]
Is the project targeting the same bitness as the library?

**Comment by FullValueRider** [comment]
Yes. Both are 64 bit

**Comment by WaynePhillipsEA** [comment]
You've got the VB_Creatable attribute set to False:
`Attribute VB_Creatable = False`

This marks the coclass with the non-creatable COM flag, and so you won't be able to instantiate it via COM.

**Comment by FullValueRider** [comment]
Thanks for the pointer.  It seems that all my classes have that attribute set to false.  I'm assuming that this is because they were originally created in Word VBA.  In VBA classes are either Private or PublicNotCreatable. I created two classes, one 'PublicNotCreatable' and one 'Private'.  On export, both classes had the VB_Creatable flag set to False.

So the next challenge is to persuade VS Code to find/replace in all files in a TwinBasic Project.

**Comment by FullValueRider** [comment]
ANother issue has reared its head.  Setting the VB_Creatable attribute to True for the Kvp class and resolving the resulting compilation error in the AutoKeyByString class gives the following success but warning
![Bloating](https://user-images.githubusercontent.com/81257042/146754087-a9213a20-5ec9-41d4-95da-220c2d7ce667.jpg)

**Comment by WaynePhillipsEA** [comment]
> Thanks for the pointer. It seems that all my classes have that attribute set to false. I'm assuming that this is because they were originally created in Word VBA. In VBA classes are either Private or PublicNotCreatable. I created two classes, one 'PublicNotCreatable' and one 'Private'. On export, both classes had the VB_Creatable flag set to False.

Yes, that will be it, since VBA doesn't expose the classes that it creates to the COM world.

> So the next challenge is to persuade VS Code to find/replace in all files in a TwinBasic Project.

Global replace is a bit awkward at the moment.  You'll have to open every single file in the project (so that all tabs are open), and then you can use the VS Code builtin find & replace (via the magnifying glass in the left activity bar).   Note that VS Code will only find/replace in the documents that are currently open in the editor.   This is a long standing VS Code issue with virtual filesystems that has not yet been fixed.

>ANother issue has reared its head. Setting the VB_Creatable attribute to True for the Kvp class and resolving the resulting compilation error in the AutoKeyByString class gives the following success but warning

OK, don't worry about that.  That shouldn't affect things apart from the .DLL file being a little larger than it needs to be.  I will look into that with your file.

**Comment by FullValueRider** [comment]
No Worries, I guessed it was a VSCode issue.  The downside  is that it adds another step when round tripping to VBA to take advantage of the RubberDuck code inspections because the attribute is reset to False when files are Imported to VBA Land.

**Comment by WaynePhillipsEA** [comment]
Yes, we need to think about how best to handle that, because importing from VBA will likely be a common task.

**Comment by wqweto** [comment]
The issue with `VB_Creatable` attribute is the same in VB6 when you have a class module referenced by both a Std-EXE and an Ax-DLL projects.

There is no way to make the class public in the Ax-DLL without then suffering (numerous) warnings and auto-corrections when the Std-EXE is open.

Things become even murkier when one tries to use public UDTs in such shared class -- the Ax-EXE does *not* allow this although the UDTs are not exposed on any public typelib i.e. VB6 does not treat such UDTs as public is a .bas module (like they should be) for no apparent reason.

As a consequence this conditional compilation
```
#If ImplPublicClasses Then
Public Function OutputBrtFmt(uFmt As UcsBiff12BrtFmtType) As Long
#Else
Friend Function OutputBrtFmt(uFmt As UcsBiff12BrtFmtType) As Long
#End If
```
. . . I had to resort to this abomination on numerous occasions (like [here](https://github.com/wqweto/Biff12Writer/blob/master/src/cBiff12Part.cls)).

I've given up on this user-story but I hope in the future TB will come up with some reasonable solution for code/module sharing on github and between projects in general (probably module visibility attributes outside source code and in project file).
