### ISSUE TITLE
some questions for win64 build

### ISSUE THREAD

**Issue by nanchengjiumeng** [WaynePhillipsEA/twinbasic#586]
I want to upgrade my project to 64-bit because the older version of the project references a 32-bit DLL in VB6, but I got an error referencing a 32-bit DLL, is there any way?

when select win32:
![image](https://user-images.githubusercontent.com/25164432/146864258-6d214161-9bb8-446a-bde7-00c56824112a.png)

win64 got err: 
![image](https://user-images.githubusercontent.com/25164432/146864338-9b687cf8-19ea-4071-9cef-d7301484705a.png)

**Comment by WaynePhillipsEA** [comment]
No, a 64-bit application cannot load a 32-bit DLL.   

However, you might have some luck using the DllSurrogate feature of COM, that will spawn an out-of-process COM instance for you in the background which hosts the 32-bit component, and provides the IPC between the two processes automatically for you.  Have a search over on vbforums for DllSurrogate for more information.
