### ISSUE TITLE
using Workspaces blocks access

### ISSUE THREAD

**Issue by lunasoft2001** [WaynePhillipsEA/twinbasic#587]
**Describe the bug**
When executing a function to get the current database tables from the VBE using "DBEngine.Workspaces (0) .OpenDatabase" the access environment cannot be closed.

**To Reproduce**
1. Go to VBE
2. Click on Addins - Tables on App
3. Close VBE
4. Close Access

**Expected behavior**
Access is closed

**Screenshots**
![image](https://user-images.githubusercontent.com/12692231/146915489-398e2cac-360a-4843-8637-126f20d5f48f.png)
<img width="913" alt="Captura de pantalla 2021-12-21 a las 11 35 07" src="https://user-images.githubusercontent.com/12692231/146915770-7d3b9680-5db1-4783-8393-a71aa3786d4b.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version [0.13.50]

**Additional context**
  Access 365 Ver. 2111 Compilation 14701,20262

Code:
-----------
Class MyVBEAddin
 
	Implements IDTExtensibility2
	
	' PLEASE NOTE: make sure you create a DLL of the correct bitness to match your version of VBA
	' (e.g. if you're using the 64-bit version of VBA, make sure you change the 'Active Build' in the twinBASIC panel to 'win64')

	' For VB6 support, add a project reference to 'Microsoft Visual Basic 6.0 Extensibility'
	' Or for VBA support, add a project reference to 'Microsoft Visual Basic for Applications Extensibility'
	Private _VBE As VBIDE.VBE
   	Private _AddIn As VBIDE.AddIn

	

	Private WithEvents MyCommandBar As Office.CommandBarButton
	Private WithEvents MyCommandBar2 As Office.CommandBarButton
   
	Sub OnConnection(ByVal Application As Object, _
							ByVal ConnectMode As ext_ConnectMode, _
							ByVal AddInInst As Object, _
							ByRef custom As Variant()) _
							Implements IDTExtensibility2.OnConnection
		Set _VBE = Application
		Set _AddIn = AddInInst

	End Sub
	
	Sub OnDisconnection(ByVal RemoveMode As ext_DisconnectMode, _
						ByRef custom As Variant()) _
						Implements IDTExtensibility2.OnDisconnection
			Set _VBE = Nothing
			Set _AddIn = Nothing
	End Sub
	
	Sub OnAddInsUpdate(ByRef custom As Variant()) _
						Implements IDTExtensibility2.OnAddInsUpdate
	End Sub
	
	Sub OnStartupComplete(ByRef custom As Variant()) _
						Implements IDTExtensibility2.OnStartupComplete
		With _VBE.CommandBars("Add-Ins")
			Set MyCommandBar = .Controls.Add(Office.msoControlButton)
			MyCommandBar.Caption = "Juanjo"
			
			Set MyCommandBar2 = .Controls.Add(Office.msoControlButton)
			MyCommandBar2.Caption = "Tables on App"
		End With
	End Sub
	
	Sub OnBeginShutdown(ByRef custom As Variant()) _
						Implements IDTExtensibility2.OnBeginShutdown
	End Sub
	
	Sub OnClickButton(ByVal Ctrl As Office.CommandBarButton, CancelDefault As Boolean) _
						Handles MyCommandBar.Click
		MsgBox "You clicked me!"
	End Sub
	
	Sub OnClickButton2(ByVal Ctrl As Office.CommandBarButton, CancelDefault As Boolean) _
		Handles MyCommandBar2.Click
		MsgBox obtenerTablas
	
	End Sub
	
	Public Function obtenerTablas() As String
		

		Dim db As DAO.Database
		Dim strText As String
		Dim ruta As String
		Dim tdfBucle As TableDef

				
		ruta = _VBE.ActiveVBProject.FileName

		Set db = DBEngine.Workspaces(0).OpenDatabase(ruta)

		For Each tdfBucle In db.TableDefs
			If Not Left(tdfBucle.Name, 4) = "MSys" Then
				strText = strText & tdfBucle.Name & vbNewLine
			End If
		Next tdfBucle
		
		strText = "Las Tablas de " & ruta & " son: " & vbCrLf & strText
		
		db.Close
		If Not (db Is Nothing) Then Set db = Nothing
			
		Return strText
		
	End Function
	
	
End Class

-------------------

**Comment by WaynePhillipsEA** [comment]
Hmm I couldn't reproduce this problem.   After clicking "Tables on App", I get the list of tables, then when I close Access it closes fine and the MSACCESS.EXE process terminates

**Comment by lunasoft2001** [comment]
Incredible.
Yesterday I was fighting with him for several hours.
Today after restarting the PC it does not give any problem.

Sorry for wasting your time.

Thread can be closed

**Comment by WaynePhillipsEA** [comment]
No worries, these things happen sometimes.
