### ISSUE TITLE
twinBASIC classes cannot yet expose events

### ISSUE THREAD

**Issue by WaynePhillipsEA** [WaynePhillipsEA/twinbasic#59]
**Describe the bug**
twinBASIC classes cannot yet expose events (neither internally, or externally)

**Expected behavior**
twinBASIC must allow definitions of Events in class modules, and RaiseEvent calls from within the class members.

**Comment by WaynePhillipsEA** [comment]
This is a known limitation with the preview release.  Reported here so that we can track it.

**Comment by wqweto** [comment]
+1

Hope we get this resolved before starting work on the GUIs :-))

I have my porting/testing projects stalled only because of events missing as of now (which is major IMO) after most other issues got resolved or come up with workarounds.

**Comment by WaynePhillipsEA** [comment]
@wqweto Yup, it's very high on the list now, and most definitely before GUI :)

**Comment by WaynePhillipsEA** [comment]
Now available in v0.10.1841.
