### ISSUE TITLE
Have a Happy New Year everyone!

### ISSUE THREAD

**Issue by mburns08109** [WaynePhillipsEA/twinbasic#599]
**Is your feature request related to a problem? Please describe.**
I wish you all a Merry Christmas (or Kwanzaa/Haunakkah/etc.) and/or Happy Holidays and/or a Happy New Year   (take your pick(s) as desired).

**Describe the solution you'd like**
much happiness

**Describe alternatives you've considered**
sadness?

**Additional context**
You and/or family/friends/etc.

**Comment by AstrocalcVB** [comment]
Nice issue, I could work with that. Happy X-mas!

**Comment by WaynePhillipsEA** [comment]
Indeed, Merry Xmas to everybody, and of course a massive thank you to everybody for joining in with the twinBASIC preview this year... your feedback and ideas are massively helping shape the future of tB!

### Have a very Merry Xmas, and a fantastic New Year.  There's a lot to look forward to, in 2022 :)

**Comment by DinyaZ** [comment]
Merry Christmas! :) :)

**Comment by mwolfe02** [comment]
Important issue @mburns08109 .  As a matter of fact, I just wrote about this very same thing over at [nolongerset.com](https://nolongerset.com/merry-christmas-2/).

Merry Christmas, all!

**Comment by Kr00l** [comment]
The title may be changed from `Merry Christmas` to `Happy New Year`.
:))

**Comment by WaynePhillipsEA** [comment]
Best wishes to everybody for the coming new year.  

What a year it has been!  Despite all that is going on in the world, I hope everyone has enjoyed twinBASIC so far. 
 Thanks for being a part of the twinBASIC story.

Stay safe - I'll see you on the other side.

**Comment by mansellan** [comment]
On behlaf of the UK, welcome to 2022!

**Comment by mburns08109** [comment]
> On behalf of the UK, welcome to 2022!
> 
> ![Capture](https://user-images.githubusercontent.com/25420409/147841404-d68cacec-5f0a-4952-8fbe-6452a2413062.PNG)

Didn't you have something better to do (like be smooching someone special) right then!?
