### ISSUE TITLE
Outline panel incomplete

### ISSUE THREAD

**Issue by KarlSevenSeven** [WaynePhillipsEA/twinbasic#616]
**Describe the bug**
The outline panel doesn't show the outline of a function.

**To Reproduce**
1. Load this:
[OutlineTest.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7792446/OutlineTest.zip)
2. Explore the Outline panel.
3. In Function R, change `ByRef All As String` to `ByVal`.
4. See the in the Outline, All is there now, the other parameters are missing.

**Expected behavior**
Complete Outline

**Screenshots**
![image](https://user-images.githubusercontent.com/88059532/147741949-00fd056f-2d8e-458c-a544-ddab7516169a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC 0.13.59

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.13.60, thanks for reporting!

**Comment by KarlSevenSeven** [comment]
No...
![image](https://user-images.githubusercontent.com/88059532/147821148-24fc92e5-2c09-4cec-9b66-780fa7bd3369.png)

**Comment by WaynePhillipsEA** [comment]
@KarlSevenSeven apologies, that regression is fixed in v0.13.61
