### ISSUE TITLE
Get / Write Profile String

### ISSUE THREAD

**Issue by JohnLamontagne1996** [WaynePhillipsEA/twinbasic#622]
**Describe the bug**
These two functions

`Private Declare Function WritePrivateProfileString Lib "kernel32" Alias "WritePrivateProfileStringA" (ByVal lpApplicationname As String, ByVal lpKeyname As Any, ByVal lpString As String, ByVal lpfilename As String) As Long`

`Private Declare Function GetPrivateProfileString Lib "kernel32" Alias "GetPrivateProfileStringA" (ByVal lpApplicationname As String, ByVal lpKeyname As Any, ByVal lpdefault As String, ByVal lpreturnedstring As String, ByVal nsize As Long, ByVal lpfilename As String) As Long`

Throw a mismatched data type hint

Screenshots

![1](https://user-images.githubusercontent.com/87338545/147878413-58f73e07-1e07-459a-8b10-5f0dc8660781.png)
![2](https://user-images.githubusercontent.com/87338545/147878415-0d91ccc9-180b-495e-945c-b8ff5dedb310.png)

**Comment by WaynePhillipsEA** [comment]
This is correct.  The return datatype of both functions is Long, therefore the correct datatype suffix would be `&` not `$`.

VBx let's you get away with it, but tB warns you about it.  Note that this is a warning, not an error, so it doesn't affect compilation.
