### ISSUE TITLE
The editor could not be opened due to an unexpected error.

### ISSUE THREAD

**Issue by KarlSevenSeven** [WaynePhillipsEA/twinbasic#623]
**Describe the bug**
This message comes up every time I start VS:
`The editor could not be opened due to an unexpected error.`

**To Reproduce**
1. Start VS.

**Expected behavior**
No error.

**Screenshots**
![image](https://user-images.githubusercontent.com/88059532/147917215-3d3d2d41-514a-4e71-a013-717dde1543e5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC  0.13.61

**Additional context**
This issue is minor but a bit annoying.
'Try again' solves it.

**Comment by FullValueRider** [comment]
I see this too, and have been for some time.  

https://github.com/WaynePhillipsEA/twinbasic/issues/483

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting.  Yes, I am aware of this one, but haven't had chance to look at it yet.  Hopefully this week.

**Comment by WaynePhillipsEA** [comment]
This is now fixed in v0.13.68.   The message may appear briefly when you open the project, but it should fix itself now.
