### ISSUE TITLE
Unexpected crash when exiting function on second iteration of a testing loop

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#624]
**Describe the bug**
I have a library I am developing to assist with Advent of Code problems.  The library contains a dictionary called Kvp which, amongst many other things, will allow input of keys and items from other iterables.  In turn, the Kvp Class is based on a couple of objects of the Lyst Class (a Keys Lyst and an Items Lyst).  The Lyst class is a wrapper for the mscorlib ArrayList object.

I have a unit test which is stressing the Add method of the Kvp by adding combinationa of Variant array, collection, arraylist and list.

```VBA
Public Sub Test01_AddTwoIterables()
        On Error GoTo TestFail
        
        Dim myBaseItems As Variant
        myBaseItems = Array(10, 20, 30, 40, 50)
        
        Dim myBaseKeys As Variant
        myBaseKeys = Array(0&, 1&, 2&, 3&, 4&)
       
        Dim myExpectedKeys As Variant
        myExpectedKeys = _
            Array _
            ( _
                myBaseKeys, _
                Types.Iterable.ToCollection(myBaseKeys), _
                Types.Iterable.ToArrayList(myBaseKeys), _
                Types.Iterable.ToLyst(myBaseKeys) _
            )
        
        Dim myExpectedItems As Variant
        myExpectedItems = _
            Array _
            ( _
                myBaseItems, _
                Types.Iterable.ToCollection(myBaseItems), _
                Types.Iterable.ToArrayList(myBaseItems), _
                Types.Iterable.ToLyst(myBaseItems) _
            )
                
        Dim myResultKeys As Variant
        Dim myResultItems As Variant
        
        'Act:
        Dim myKeys As Variant
        Debug.Print
        For Each myKeys In myExpectedKeys
        
            Dim myItems As Variant
            For Each myItems In myExpectedItems
                
                Debug.Print TypeName(myKeys), TypeName(myItems)
                Dim myKvp As Kvp
                Set myKvp = Kvp.Deb  'Deb is the factory method for getting a new Kvp from the predeclaredId
                
                myKvp.Add myKeys, myItems
                'myResultKeys = Empty
                myResultKeys = myKvp.Keys
                'myResultKeys = myKvp.KeysRef.Host.toarray
                
                'myResultItems = Empty
                myResultItems = myKvp.Items
                'myResultItems = myKvp.ItemsRef.Host.toarray  
                
                
                'Assert.Strict.
                Assert.Strict.SequenceEquals myBaseKeys, myResultKeys, CurrentProcedureName & ":Keys using " & TypeName(myKeys)
                Assert.Strict.SequenceEquals myBaseItems, myResultItems, CurrentProcedureName & ":Items using " & TypeName(myItems)
                
                'myKvp.Clear
                
            Next
            
        Next
        
TestExit:
        Exit Sub
        
TestFail:
        Debug.Print CurrentProcedureName, " raised an error: #" & Err.Number & " - " & Err.Description
     
    End Sub
```

The problem I am seeing is that in the second iteration of the myItems loop I get a crash when returning from the myKvp.Keys method.  The problems persists despite whatever return strategy I try and is not related to the Items on the second iteration being derived from a Collection.
The string of calls to retrieve information from the ArrayList in Lyst in Kvp is

Kvp
```
'@Description("Returns a variant containing an array of the keys. For alignment with Scripting.Dictionaries. See Method KeysRef for a reference to the Keys lyst")
Public Function Keys() As Variant
Attribute Keys.VB_Description = "Returns a variant containing an array of the keys. For alignment with Scripting.Dictionaries. See Method KeysRef for a reference to the Keys lyst"

    Keys = p.Keys.ToArray               'this works fine
    'Return p.Keys.ToArray              'this works fine
   ' Return (p.Keys.ToArray)            'this works fine
    
End Function 'fails at this step on second iteration
```

Lyst
```
Public Function ToArray() As Variant
    ToArray = s.Host.toarray 'this works fine
    'Return s.Host.toarray
   ' Return (s.Host.ToArray)
End Function

```

**To Reproduce**
1. use the attached project
2. Goto the Testing module and run the Tester method, a breakpoint has been inserted at the second 'for' in the test above.
3. Use F10 to step through the code until you get to the second iteration of 'myResultKeys = myKvp.Keys'
4. Use F11 to follow the steps until the 'end function' where the crash occurs (as indicated by a comment)

**Expected behavior**
No crash

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WIndows 11
 - twinBASIC compiler version [0.13.61]

**Additional context**
The code for the Kvp Class is currently being refactored and this is the first issue I've hit that I can't resolve as can be seen by the code in comments. In debug view all objects get the correct information.   I have also round tripped to VBA and resolved all inspections highlighted by rubber duck so the odd missing 'set' have been caught and corrected.  I don't think I'm just befuddles by mismatched references or some other unfortunate oversight.

[TwinLib64.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7801761/TwinLib64.zip)

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.13.65, thanks for reporting!
