### ISSUE TITLE
TB0003 false positive on API declare

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#625]
**Describe the bug**
The TB0003 compiler warning raises a false positive on below code.

**To Reproduce**
```
Private Const PTR_SIZE As Long = 4
Declare Sub Assign Lib "kernel32" Alias "RtlMoveMemory" (Dst As Any, Src As Any, Optional ByVal BLen& = PTR_SIZE)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/33756666/147946097-4707382a-8fcb-4a5f-a250-a1c60b41dd9d.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.13.61]

**Additional context**
n/a

**Comment by WaynePhillipsEA** [comment]
Now fixed in v0.13.62, thanks for reporting!
