### ISSUE TITLE
API declare with no access level should be Public

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#626]
**Describe the bug**
An API declare, like below, which has no access level defined should be treated as `Public`.

**To Reproduce**
```
Module MainModule
    
    Declare Sub Sleep Lib "kernel32.dll" (ByVal dwMilliseconds As Long)
    
    Public Sub Main()
        
        Call RunSleep
        
    End Sub
	
End Module

Module AnotherModule
    
    Sub RunSleep()
        Sleep 1000
    End Sub
    
End Module
```

**Expected behavior**
To be able to run the Sleep API in AnotherModule.

**Screenshots**
![image](https://user-images.githubusercontent.com/33756666/147946753-e6e6f9e8-def5-428b-b1ba-bbaeaf29154e.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.13.61]

**Additional context**
n/a

**Comment by WaynePhillipsEA** [comment]
Now fixed in v0.13.62, thanks for reporting!
