### ISSUE TITLE
Parameter hints in wrong line

### ISSUE THREAD

**Issue by KarlSevenSeven** [WaynePhillipsEA/twinbasic#627]
**Describe the bug**
In combination with line continuation the parameter hints are in the wrong editor line.
See pic.
Also when using WordWrap, the editor wraps without respecting the parameter hints.
See 2nd pic.

**To Reproduce**
Load this and play with ParamHints and WordWrap:
[ParameterHints.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7802965/ParameterHints.zip)

**Expected behavior**
Parameter hints always before the parameter in the same line.
And taking WordWrap into account.

**Screenshots**
1st:
![image](https://user-images.githubusercontent.com/88059532/147954968-26297e32-eab9-44d0-a780-4a602f2eec9a.png)
2nd:
![image](https://user-images.githubusercontent.com/88059532/147955012-2281ee75-e3b8-4f29-a4d9-04312ddb15a4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC 0.13.61

**Additional context**
The errors don't matter regarding the parameter hints.
It's the same in the real source code, there are no errors but the same problem.

**Comment by WaynePhillipsEA** [comment]
Now fixed in v0.13.62, thanks for reporting!

**Comment by KarlSevenSeven** [comment]
Main issue is fixed, but not the 2nd part.
I should have reported it in a separate issue.
Will do so in future.
