### ISSUE TITLE
Sub Method/Declare and data type suffix

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#635]
**Describe the bug**
tB should disallow data type suffix for Sub methods/declares.

**To Reproduce**
```
Module MainModule
    
    Private Declare Sub Sleep$ Lib "kernel32.dll" (ByVal dwMilliseconds As Long)
    
    Public Sub Main()

        Sleep 1000
        
        Hello
        
    End Sub
    
    Sub Hello#()
        
        MsgBox "hello"
        
    End Sub
	
End Module
```

**Expected behavior**
Declare `Sleep$` should not be allowed and Method `Hello#` also not.
VBx throws a compile time error for it.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.13.62]

**Additional context**
n/a

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.13.64, thanks!
