### ISSUE TITLE
Issues with conditional compilation and prettifier/compiler

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#636]
**Describe the bug**
It appear that compiler and prettifier do not work very well when there are conditional compilation blocks using comparison operators.

**To Reproduce**
1. In a module, add the following code:
```
	#Const v = 100
	#If v >= 100 Then
	Public Declare PtrSafe Sub x1 Lib "y" ()
	#End If
	Public Declare PtrSafe Sub x2 Lib "y" ()
	#If v >= 50 Then
	Public Declare PtrSafe Sub x3 Lib "y" ()
	#End If
```
2. Following the last line, add a new line, `Public Declare PtrSafe Sub x4 Lib "y" ()`. Type the line instead of pasting. Note: typing mistakes exacerbates this bug, possibly especially around the `Declare` keyword.
3. The prettifier stops works. In some instances, the compiler won't restart and restart won't work. VSCode must be restarted.

**Expected behavior**
It ought to just work™.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.13.62

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.13.64, thanks!
