### ISSUE TITLE
Parameter type not syntax checked in Event declaration

### ISSUE THREAD

**Issue by KDGundermann** [WaynePhillipsEA/twinbasic#645]
**Describe the bug**
TB does not check the parameter type in an Event declaration

**To Reproduce**
![image](https://user-images.githubusercontent.com/208315/148648834-30688379-d7cc-4807-98cf-e7c4454a7f68.png)

**Expected behavior**
Mrk the syntax Error with the red wiggled line

**Desktop :**
 - OS: [e.g. Windows 10 21H2]
 - twinBASIC compiler version [e.g. 0.13.66]

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.13.67, thanks!
