### ISSUE TITLE
Public API in classes should not be allowed

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#646]
**Describe the bug**
tB currently allows to have `Public` API in classes. This also affects the Declares that have no access level defined.

**To Reproduce**
See #634 

**Expected behavior**
To dissallow it and thus encourage to have Public API in normal modules.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.13.66]

**Additional context**
n/a

**Comment by WaynePhillipsEA** [comment]
From what I can see, the public declares are a compile-error (not runtime-error as mentioned in #634), so I'll add that to tB.

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.13.69.  Thanks!
