### ISSUE TITLE
Debugger:Fixed Hidden Window

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#648]
**Describe the bug**
I have an ActiveX library compiled by twinBasic.  I have code that uses this library.  On the first run of the code that uses the library I see the following report

![HiddenWIndow](https://user-images.githubusercontent.com/81257042/148803232-b6f8866f-6fbe-45c1-b069-89f5ccde9752.jpg)

The Fixed Hidden Window report does not reappear until I restart VSCode.

There doesn't appear to be any downside to this report so this is more of an FYI than a report of a problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - twinBASIC compiler version  see Screenshot

**Comment by WaynePhillipsEA** [comment]
This is just a temporary warning, see #588.

Before the fix in #588, the window (MsgBox or whatever) would have been hidden behind the main VS code window.  The debugger now detects this, and brings it to the front for you (with the console warning for now).
