### ISSUE TITLE
Type Alias problems with paramarray (implements Via

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#656]
**Describe the bug**
I'm seeing a problem with twinbasic not recognising a paramarray when creating Type Aliases using the Implements Via inheritance structure.  If I take the following code_

![Inheritance1](https://user-images.githubusercontent.com/81257042/149499937-f3c53856-88ed-43d2-8dcb-4a636304f4c8.jpg)

and add an alias for the Lyst object

```
Public Class VentLine
    Attribute VB_Creatable = True
    Attribute VB_PredeclaredId = True
    Attribute VB_Exposed = True
    Implements Lyst Via LystFields
End Class
```
then update the code to use the alias, I get an error indicated 'Missing argument 'ipArgArray'

![Inheritance2](https://user-images.githubusercontent.com/81257042/149500633-1b6bfe4b-df9e-4ff1-8f49-d451db689322.jpg)

The signature for the affected Add Method being
```
Public Function Add(ParamArray ipArgArray() As Variant) As Lyst
```

Other issues, such as the Factory method ' Deb' not being recognised were resolved by adding the Attributes to the Alias definition.

This is a FYI issue as the first version of the code works fine. I was just trying out aliases using Implements Via

 - OS: [e.g. Windows 11]
 - twinBASIC compiler version [see screenshots]

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.13.73, thanks!
