### ISSUE TITLE
Importing working code crashes the compiler

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#660]
**Describe the bug**
my incantation for Advent Of Code day 05 was refactored and checked to be running whilst part of my TwinLib64 library.  Once working and producing the correct results I moved the Day05 code to my Twinbasic Advent of Code project.  The result has been a crashing compiler which is claiming problems with The Day05 file.  I've tried deleting the project and workspace files and recreating the project but the the same problem arises.  I'm occasionally seeing the message from the compiler saying it is crashing and to report the problem.
![NoDay05_1](https://user-images.githubusercontent.com/81257042/149541430-628e656d-dde4-45bd-81a3-b831748f9298.jpg)

![NoDay05_2](https://user-images.githubusercontent.com/81257042/149541445-1fd4d5c8-d073-4147-b115-f45d36ecdd23.jpg)

![NoDay05_3](https://user-images.githubusercontent.com/81257042/149541470-b7edd914-ec5e-4fb6-b4c0-1014a04cf942.jpg)
[AoC2021TwinBasic.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7871443/AoC2021TwinBasic.zip)

OS: windows 11 
TwinBasic Version  0.13.72

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.13.73, thanks!
