### ISSUE TITLE
UnitTests : add actual value when assertion failed

### ISSUE THREAD

**Issue by KDGundermann** [WaynePhillipsEA/twinbasic#661]
**Is your feature request related to a problem? Please describe.**
Would it be possible to show the actual value in an unit test when the test failed?
e.g. CStr(Actual) if it is a primitive datatype or Actual.ToString() when it is an object ?

**Comment by WaynePhillipsEA** [comment]
Do you mean to display the values in the Test Explorer? Or in the assertion error messages?

**Comment by retailcoder** [comment]
Something like "Assert failed: expected x, but actual was y"?

**Comment by KDGundermann** [comment]
![image](https://user-images.githubusercontent.com/208315/149636495-dddc6589-82a1-4700-81d4-e3fc37cbe09c.png)

**Comment by WaynePhillipsEA** [comment]
In v0.13.75, the Expected and Actual values are displayed in the assertion error message:

<img width="506" alt="tbAssertImprovement1" src="https://user-images.githubusercontent.com/25738109/149653016-8ff69aa7-298c-4e11-92a3-9bce5fce500a.png">

Thanks for the suggestion!
