### ISSUE TITLE
Implements via giving 'circular reference' and '[<object>] is not a  supported interface for Via'

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#665]
**Describe the bug**
Loading the current version of VSCode today is giving me errors from the Implements Via construct.
![circularreferences](https://user-images.githubusercontent.com/81257042/149677759-31b06943-e53d-4bf6-9cf2-5c622f8ab838.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - twinBASIC compiler version [see Screenshot]

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting.   I can't repro this.  Could you attach your project file?  Thanks.

**Comment by FullValueRider** [comment]
The project file is attached.  The error is in Day05 class. Kvp should only be defined in the Library that I uploaded as a package earlier today.
[AoC2021twinBasic.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7882705/AoC2021twinBasic.zip)
.

**Comment by WaynePhillipsEA** [comment]
The project you've attached does have a regular COM reference to your TwinLib64 library.  Hence, the Kvp/Lyst datatypes can't be used with Implements-Via at the moment in that way.

**Comment by FullValueRider** [comment]
Ah OK.  I think I'm a bit out of my depth here. When you say Com reference is this because the library is a targeted as an ActiveX dll.

**Comment by WaynePhillipsEA** [comment]
No, this is a regular COM reference to your library file:

<img width="357" alt="tbComRefFullValueRider" src="https://user-images.githubusercontent.com/25738109/149799536-bc8be5f1-2d0b-4ec8-aa3d-6c9e268a7aae.png">

If it was a package, it would appear a bit differently, with the licence type and your publisher name listed next to it.

**Comment by WaynePhillipsEA** [comment]
Changing to your library package should resolve the `[Kvp] is not a supported interface for Via` errors, but it doesn't resolve the `circular reference` error, which I will take a look at later or tomorrow.

**Comment by WaynePhillipsEA** [comment]
Implements-Via is now working correctly with packaged components in v0.13.77, fixing the 'circular reference' error.  Thanks for reporting.
