### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by KDGundermann** [WaynePhillipsEA/twinbasic#668]
**Describe the bug**
Intellisense not available for Objects using the `With ` command

**Screenshots**
![image](https://user-images.githubusercontent.com/208315/149825241-ce71c467-a4e8-49b9-98f7-83bd09bf0a22.png)
![image](https://user-images.githubusercontent.com/208315/149825549-2083ab0d-5f5a-438f-a2f2-f832b949ca0e.png)

**Desktop (please complete the following information):**
 - OS: Win10 21H2
 - twinBASIC compiler version v0.13.76

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.13.77, thanks!

**Comment by KDGundermann** [comment]
Sorry but now Intellisense is showing to much:
![image](https://user-images.githubusercontent.com/208315/149925991-6b456cd1-548f-4644-a485-933b4e8c763d.png)

**Comment by WaynePhillipsEA** [comment]
Yes, I've just spotted this.   I will get that fixed, thanks.

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.13.78, thanks!
