### ISSUE TITLE
Links to issues from ChangeLog do not work correctly

### ISSUE THREAD

**Issue by team-moeller** [WaynePhillipsEA/twinbasic#67]
When you click on a link in the ChangeLog the related issue is not shown.

**To Reproduce**
* Open the ChangeLog
* Click on one of the links

This is the link in the browser:
https:// github.com/ WaynePhillipsEA/ twinbasic/ issues/ 21%5D
(Blanks inserted to make the effect visible)

**Expected behavior**
This should be the link in the browser:
https:// github.com/ WaynePhillipsEA/ twinbasic/ issues/ 21
(Blanks inserted to make the effect visible)

It seems that the closing bracket is incidentally in the link.

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting, Thomas.  I'll fix that in the next release tomorrow morning.

**Comment by WaynePhillipsEA** [comment]
Fixed in 0.9.1676. Thanks for reporting.
