### ISSUE TITLE
Specifying ByVal for ParamArray As Any()

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#671]
**Describe the bug**
Using the [sqlite_db_config](https://sqlite.org/c3ref/db_config.html) as an example, if we look at the option for enabling foreign key on [this page](https://sqlite.org/c3ref/c_dbconfig_defensive.html#sqlitedbconfiglookaside), we are instructed:
> SQLITE_DBCONFIG_ENABLE_FKEY
> This option is used to enable or disable the enforcement of foreign key constraints. There should be two additional arguments. The first argument is an integer which is 0 to disable FK enforcement, positive to enable FK enforcement or negative to leave FK enforcement unchanged. The second parameter is a pointer to an integer into which is written 0 or 1 to indicate whether FK enforcement is off or on following this call. The second parameter may be a NULL pointer, in which case the FK enforcement setting is not reported back.

Based on this information, I would expect the definition of the `Declare` to be:
```
Private DeclareWide PtrSafe Function sqlite3_db_config _
CDecl Lib "sqlite3.dll" ( _
  ByVal sqlite3 As LongPtr, _
  ByVal op As ConfigOptions, _
  ByVal ParamArray Options As Any() _
) As Long
```

And I should then populate the `Options` array with this calling code:
```
sqlite3_db_config(Sqlite, SQLITE_DBCONFIG_ENABLE_FKEY, ByVal p1, p2)
```

However, this syntax is not currently legal and arguably may not be the optimal use. I tried the alternative syntax:
```
Dim p1 As Long = 1
Dim p2 As Long = 0
sqlite3_db_config(Sqlite, SQLITE_DBCONFIG_ENABLE_FKEY, p1, VarPtr(p2))
```

The call will succeed with no error but the data is not right. The `p2` should be changed from `0` to `1`. That is demonstrated by using the non-vardaric declare:
```
Private DeclareWide PtrSafe Function sqlite3_db_config2 _
CDecl Lib "sqlite3.dll" Alias "sqlite3_db_config" ( _
  ByVal sqlite3 As LongPtr, _
  ByVal op As Long, _
  ByVal p1 As Long, _
  ByRef p2 As Long _
) As Long
```

And using that in the calling code. The `p2` then gets updated correctly.

**Expected behavior**
Either we should be able to use `ByVal` or `VarPtr` should have worked. Though I'm not 100% sure about the `ByVal` syntax because we're already defining `ByVal` for the `ParamArray As Any()` so specifying it twice could look weird. Using `VarPtr` should have worked but it's not clear why it didn't, unless I'm missing a difference there. 

**Desktop (please complete the following information):**
 - OS: Windows 7
 - twinBASIC compiler version 0.13.80

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.13.81, thanks.

The `ByVal` inline attribute is now allowed for this use case.  Note that specifying `VarPtr` does nothing because referenceable variables are already passed as pointers unless the inline `ByVal` attribute is used to override that behaviour.  Also note that if you change it into an expression rather than passing the variable directly (e.g. `(p1)` rather than just `p1`), the value becomes non-referenceable and so has the same semantics as using `ByVal p1`.
