### ISSUE TITLE
Allow `SetDllDirectory` attribute on a module/class

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#672]
**Is your feature request related to a problem? Please describe.**
A while ago, we gained a handy attribute `SetDllDirectory` to handle the loading of transitive DLLs (#455 ). This is currently enabled on a per-statement basis for `Declare`. However, I'd think it's far more common to want to group several related functions from same DLL into a module and if we cannot be certain which one will be called, it would be necessary to add the attribute to every declaration.

**Describe the solution you'd like**
Allow the module to be decorated with the same attribute which would then apply to all the `Declare`s as if they had that attribute decorated.

**Describe alternatives you've considered**
Typing more. 😄 Or copying'n'pasting more.

**Comment by WaynePhillipsEA** [comment]
Thanks for the suggestion.  This is now supported in v0.13.81
