### ISSUE TITLE
Split results in wrong array dimension

### ISSUE THREAD

**Issue by KarlSevenSeven** [WaynePhillipsEA/twinbasic#677]
**Describe the bug**
Split results in wrong array dimension.

**To Reproduce**
1. Create new tB EXE project.
2. Paste this code in Sub Main:
```
Dim M As String
Dim V As Variant
Dim C As Long

M = vbNullString
V = Split(M, vbCrLf)

C = UBound(V)

Debug.Print "C = " ; C
```

3. Run
4. See `C = 0` in the Debug panel.

**Expected behavior**
Same result as in VB6.
The correct result is **-1**.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC 0.13.84

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.13.85, thanks!
