### ISSUE TITLE
Issues with downloading packages

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#680]
**Describe the bug**
I am seeing 2 different issues.

I published a private package. When I then try to download it I get:
```
[PACKAGES] downloading package '{B768C096-6072-450A-84A8-01D07F690907}/0/0/0/2' from the online database...
[PACKAGES] failed.  Server returned HTTPS code 501
```

I then try to download TwinLib package:
```
[PACKAGES] downloading package '{B768C096-6072-450A-84A8-01D07F690907}/0/1/3/0' from the online database...
````

In both cases, neither get downloaded and the checkbox is never checked.

I have no issues with downloading & installing the WayneExamplePackage and CustomControlLibrary.

Interestingly, at one point, I managed to get TwinLib64 checked but only after I downloaded the WayneExamplePackage and CustomControlLibrary. I could not then reproduce it again. I never was able to download my private package.

**To Reproduce**
1. Create a twinpack project, publish it privately.
2. Create a new twinBASIC project. 
3. Go to setting and verify that WayneExampleProject and CustomControlLibrary are downloaded without issues.
4. Try to download the package. Observe the error.
5. Try to download TwinLib64; it will start to download but then does nothing. 

**Expected behavior**
It should work.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - twinBASIC compiler version 0.13.86

**Comment by WaynePhillipsEA** [comment]
I think I can see the problem.  Both your package, and TwinLib64 have the same Project ID of '{B768C096-6072-450A-84A8-01D07F690907}' (which I believe came from one of the samples).   I'll delete the package your private package you uploaded here, and could you change the ID at your end, and re-upload?

The server will ordinarily disallow this from happening, but because yours was a private package, it wrongly allowed it through, so I'll get that fixed.

**Comment by WaynePhillipsEA** [comment]
TWINSERV will now disallow this, returning error code 553.   The next release of tB will provide a friendly message for error code 553 to explain that you need to change your project ID.

**Comment by WaynePhillipsEA** [comment]
So I believe this is now fixed with v0.13.87, but I will await your feedback.

**Comment by bclothier** [comment]
Thanks, will try when I have time. 

A quick aside - I think it'd be nice if package had a description field or did I miss it?

**Comment by WaynePhillipsEA** [comment]
<img width="238" alt="tbPackageDesc" src="https://user-images.githubusercontent.com/25738109/150582830-99825b28-c2f4-4106-9a92-407ab7729deb.png">
(it's the project description in the Settings file)

**Comment by bclothier** [comment]
I'm sorry, I can't see the red arrow you put in your screenshot. 😄 

I think I should have rephrased because I _did_ fill it out but I only put in a short description and I was thinking of a longer description, to explain a bit more about the package --- not a full `readme.md` but a paragraph or so explaining the scope and use of the library. That will be helpful in searching for right package as well.

**Comment by WaynePhillipsEA** [comment]
Lmao ... Yup, we should add that

**Comment by bclothier** [comment]
Ok, I can confirm that I got the expected message telling me to change the project ID and once refreshed, I was able to publish & select it in the 2nd project, so I think we are good on this issue.
