### ISSUE TITLE
Package public modules are not available?

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#682]
**Describe the bug**
It appears that if I create a package that contains a `Public Module` with `Public` members, that module is not available for use in the referencing project.

**To Reproduce**
1. Create a new package project.
2. Create a new module. Mark it `Public`. Add at least one `Public` procedure.
3. Build & publish the package.
4. In 2nd project, add the published package as reference.
5. In the source code of the 2nd project, try to access the package's module. We can access the pacakge's namespace but then it shows nothing beyond it. It cannot be used whether implicitly or explicitly.

**Expected behavior**
It should be available. 

**Desktop (please complete the following information):**
 - OS: Windows 7
 - twinBASIC compiler version 0.13.88

**Additional context**
I also noticed that the generated type library for that package was empty. That is kind of expected since normally VBx project don't export modules and its member into the generated type library. We kind of alluded to it in the #22 but I was expecting that a package reference would be more than just the type library. Is that a fair expectation?

**Comment by WaynePhillipsEA** [comment]
Can't repro this.   Followed your steps, but the referencing project was able to access and call the public member in the packaged project.

**Comment by bclothier** [comment]
Unfortunately I left out one critical detail. It ought to be a `Declare` procedure.

**Comment by FullValueRider** [comment]
I've just tried using my TwinLin64 library compiled as an ActiveX.  There is one .bas file which contains some public constants.  These constants are not visible in the Object browser from VBA (Word).

**Comment by bclothier** [comment]
Just as a FYI - I think this might be actually an user error, not a bug. It seems that because I used the same name for the project and the module, it could not resolve the ambiguity even though I fully qualified the path. When I changed the project name, I was able to see and access the `Declare`s.

**Comment by bclothier** [comment]
@FullValueRider 

> These constants are not visible in the Object browser from VBA (Word).

I think that's unfortunately expected as it is the same behavior you'd get if you had compiled a VB6 library and then referenced it from VBA. See the side discussion within the #22 thread.

**Comment by WaynePhillipsEA** [comment]
> Just as a FYI - I think this might be actually an user error, not a bug. It seems that because I used the same name for the project and the module, it could not resolve the ambiguity even though I fully qualified the path. When I changed the project name, I was able to see and access the `Declare`s.

That does need some compiler detection there, because I'm sure that conflict will happen often and be the source of some frustration.

**Comment by bclothier** [comment]
Just to clarify, should the fully qualified reference (e.g. `project.module.method` have worked, too? Or was it doomed anyway?

**Comment by WaynePhillipsEA** [comment]
> Just to clarify, should the fully qualified reference (e.g. `project.module.method`) have worked, too? Or was it doomed anyway?

Doomed if the project names were the same.

**Comment by bclothier** [comment]
I'm going to close this as I'm now fairly sure this is mainly a naming issue (e.g. an user error), rather than an issue with the package. I got too lazy and re-used same name in multiple names beyond just a project and a module which complicated the resolution and once I cleaned it up, it was all good.
