### ISSUE TITLE
Unable to publish, possibly due to 0.0.0.0 verison

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#685]
**Describe the bug**
When creating the package, I had forgot to change the version from 0.0.0.0 to 0.0.0.1. I got the big dialog with publish information. Realizing my mistake, I cancelled the dialog and incremented the version. I may have forgotten to save the changes but when I ran publish, it showed 0.0.0.1. It got published OK. 

In my other project, I went to twinpack references and I saw both 0.0.0.1 and 0.0.0.0. Odd. I picked the 0.0.0.1, no issues. I then start working on the project, realized some more changes was needed in the twinpack, so I return to the previous twinpack project, make some more changes. When I change version to 0.0.0.2, it failed to publish. I tried again with 0.0.0.3 just in case I accidentally missed a extra publish. This is what I see:
![image](https://user-images.githubusercontent.com/2367644/150664656-d8abb75d-ca2b-4a80-878e-11979f13a05f.png)

I wonder if the 0.0.0.0 is interfering with the process?

**Desktop (please complete the following information):**
 - OS: Windows 7
 - twinBASIC compiler version 0.13.90

**Comment by WaynePhillipsEA** [comment]
This should now be fixed in the server.  Thanks!
