### ISSUE TITLE
Short circuiting boolean conditions?

### ISSUE THREAD

**Issue by DaveInCaz** [WaynePhillipsEA/twinbasic#689]
**Is your feature request related to a problem? Please describe.**
Stealing from [this SO post](https://stackoverflow.com/a/4014925/3195477):

> VB6's `And` and `Or` don't short-circuit (which is the reason why the short-circuit versions are called `AndAlso` and `OrElse` in VB.net — backward compatibility).

**Describe the solution you'd like**
I'm interested to hear what approach tB is taking to this (if any so far). I always felt the lack of a short circuit in VB6 was questionable given its usefulness! 

Its also an easily understood feature once you learn about it (though I concede it could have the tendency to 'surprise' a new programmer in certain cases).

**Describe alternatives you've considered**
I don't know that I think the VB.Net approach is ideal. It was done for backwards compatibility (so maybe a necessary evil) but I don't personally think the new keywords like "AndAlso" are any more clear at hinting what will happen to the second clause than just "And" would have been.

There is no case, IMO, where you would not want short circuiting to happen - except that existing code may rely on side-effects from secondary clauses. Such side-effects are probably unintentional 99% of the time.

Is there any possibility that the compiler could decide when short-circuiting is "safe" (meaning: no side effects from the secondary clauses) and apply it only in those cases?

**Comment by bclothier** [comment]
This is already implemented:
![image](https://user-images.githubusercontent.com/2367644/150792576-05577724-bd2d-4160-b140-e98f7469635b.png)

It's not obvious but it is listed on [https://twinbasic.com/](https://twinbasic.com/) if you look for "new operators".

**Comment by DaveInCaz** [comment]
Thanks, I had looked on this issues list but didn't see it on the other site.

Not that its bad to pick the VB.Net approach to these features, but it is too bad (IMO) VB.Net had to add all the extra keywords to make the feature work. (In fact, VB.Net could have made the breaking change to modify how the usual operators worked! I wonder why they didn't...)

I'm not sure that a new BASIC programmed seeing "And" vs "AndAlso" would grok the difference just from the terminology.

**Comment by bclothier** [comment]
In our case, changing the behavior of `And` and `Or` would have broken the backward compatibility. We can't do that here. I agree it's a bit more awkward but given the backward compatibility requirement, I think that's the best we can do.

**Comment by EduardoVB** [comment]
What I'm going to say is a thought, a reflection, I'm not proposing to change anything.

Keeping OR and AND working as they are is of course technically correct and needed for full backward compatibility.
But I wonder how many of the codes really rely to work properly on the long-circuit feature.

In the several hundreds of thousands of code lines that I have in my programs, I have of course a lot of ORs and ANDs. But I guess if all conditions were short circuited, my programs would run properly anyway, only a bit faster.

I bet in real life programs, very few cases really would change behavior if ORs and ANDs were suddenly short circuited.

Why the original BASIC designers made them long-circuited IDK, it seems to me a huge design mistake.

If someone needs a function to be always executed: it is simple: put the result of that function into a variable first, then set the condition with the variable and not directly with the function.

**Comment by bclothier** [comment]
Keep in mind that `AndAlso` and `OrElse` are strictly logical whereas `And` and `Or` are both logical & bitwise. 

```
?3 And 4
 0 
?3 AndAlso 4
True
```

**Comment by EduardoVB** [comment]
And the parser cannot detect when it is logical and when it is bitwise?

**Comment by EduardoVB** [comment]
The parser needs to decide which ones are bitwise and which ones are logical as a first step. Then apply the logic for execution, but short-circuiting.

**Comment by EduardoVB** [comment]
May be there could be an `Option ShortCircuit` that could be also set as default as `Option Explicit` can be in VB6.

My guess is that 99,99% of cases would benefit from it.
It can be useful for existing code and the new AndAlso OrElse could be avoided. I don't mean not to include them, but not needed with such setting.

A tool like the code refactoring that you are planning to do, could analyze existing code to see if the code calls any function on boolean conditions and ask the developer to check whether these function need to be always executed or not.

Just an idea. But I think it is to consider, because as I said, my guess is that 99,99% of cases can be short circuited with no problem.

**Comment by bclothier** [comment]
With such refactoring tool, there would be no need for the `Option ShortCircuit`. You'd just ask the tool to make the changes whether on an one-by-one basis or by making changes into the component or into the project. 

The point is that we cannot make `And`/`Or` behave with short-circuiting without changing the behavior of the program. The refactoring places the burden on the developer to check whether it is the correct thing to do instead of trying to be smart like Excel or Outlook. 

Also:
```
If (1 + 2) And (2 + 2) Then
	Debug.Print "True"
Else
	Debug.Print "False"
End If
If (1 + 2) AndAlso (2 + 2) Then
	Debug.Print "True"
Else
	Debug.Print "False"
End If
```

Returns:
```
False
True
```

**Comment by EduardoVB** [comment]
@bclothier: your example is not valid because the first one is bitwise, not logical.

I think you didn't get the point that short-circuiting needs to (and can only) be applied to logical conditions, not to bitwise operations.

The parser need to know in advance which ones are bitwise and which ones are logical. It needs to do so already as it is working now (otherwise it wouldn't work).

**Comment by bclothier** [comment]
The point is that because the operator can have expression(s) on the either side, it won't be always immediately obvious that it's intended to be a logical operation or bitwise operation. As a consequence, guessing wrong can alter the program's behavior and therefore break the backward compatibility. Also, I do not think short-circuiting bitwise operator is a thing. 

FWIW:
```
int main()
{
    int result = 3 & 4;
    int result2 = 3 && 4;
    
    int result3 = (1+2) & (2+2);
    int result4 = (1+2) && (2+2);
    
    printf("result 1: %i\n", result);
    printf("result 2: %i\n", result2);
    printf("result 3: %i\n", result3);
    printf("result 4: %i\n", result4);

    return 0;
}
```
[Gives the same result](https://onlinegdb.com/zkAZb9dAS)

**Comment by EduardoVB** [comment]
How can a parser and compiler "guess" wrongly?

If you mean **that the programmer** guesses wrong what he is coding, then he doesn't know what he is coding. That would be a problem with short-circuiting, long-circuiting and whatever.

PS: I don't know C#

**Comment by DaveInCaz** [comment]
Maybe this is too simplistic a compiler rule, but it seems to be if the arguments are boolean, its logical; and if they are numeric then its bitwise. You might first have some bitwise operation than gets coerced to boolean, but would that affect the circuiting?

**Comment by bclothier** [comment]
No, the point is that if operator can have an expression on either or both sides, then those expressions can be anything which is not easy to infer, and in some case not even until runtime.

```
SomeCustomFunction And (SomeVariable Or AnotherFunction)
```

Quick, is it supposed to be a logical or a bitwise expression? 

Well, to know that, we'd need to account for each data types returned by functions and the variables. And if it's `Variant`, then we're toast. But even if all were `Long`, it doesn't guarantee that it's meant to be bitwise as it might be actually evaluating whether it's nonzero. 

The hypothetical refactoring tool can help with more simpler cases but in the cases where the values are determined at runtime, it is impossible to change without changing the program's behavior and for that reason, it's not always safe for the parser to make similar assumptions. Best that the developer has the opportunity to review the expression and make changes.

Hopefully the LLVM compiler will be able to help with optimizing out what it can safely infer, but the developer will need to get into the habit of using the new operators appropriately for the sake of clarity & readability and that's where the refactoring will help the most.

**Comment by EduardoVB** [comment]
I see that using Variants can be cases that can only be determined at runtime, true.

Then the `Option ShortCircuit` could short circuit only the cases that can be determined at compile time. Run time cases involving Variants would be kept long-circuited.

I guess that it still could benefit to vast majority of cases with performance improvements.

**Comment by wqweto** [comment]
In VBx the logical operators are always evaluated bitwise. This means operands are cast to integral types first (incl. boolean). Clever hack which saved the language defining bitwise operators per se.

Btw, here is a [list](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/operator-precedence) with precedence. This nails it once and for all how is `a Xor b Or c` evaluated -- must be `a Xor (b Or c)`.

**Comment by DaveInCaz** [comment]
Thanks @wqweto , that's what I had I figured VBx did and you've confirmed it.

**Comment by bclothier** [comment]
> This means operands are cast to integral types first (incl. boolean). Clever hack...

One consequence of the clever hack is that it makes some expression unsafe like those:
```
If x = True Then...
If x <> True Then...
```

For that reason, twinBASIC has a project setting to sanitize Booleans to avoid those expressions from failing. In VBA, it's usually best to rewrite into either:

```
If x Then...
If x <> False Then... 'Alternative to the previous line, gives same result
If x = False Then...
```

> Not sure about `a Xor b OrElse c` though.

Informal experiment:
```
?1 Xor 2 OrElse 3
-2 
(time taken: 0.0004253s)
?(1 Xor 2) OrElse 3
True
(time taken: 0.01005s)
?1 Xor (2 OrElse 3)
-2 
```

**Comment by bclothier** [comment]
Since this is supported already and the discussion's run dry, we will close this.

**Comment by EduardoVB** [comment]
> Since this is supported already and the discussion's run dry, we will close this.

Excuse me, what is supported?

**Comment by bclothier** [comment]
[See the 2nd post of the thread](https://github.com/WaynePhillipsEA/twinbasic/issues/689#issuecomment-1020110096).

**Comment by EduardoVB** [comment]
Then OrElse and AndAlso are supported? (I thought they were already supported, I was mistaken then).

**Comment by bclothier** [comment]
Yes, it's shown in the screenshot.

**Comment by EduardoVB** [comment]
OK, it thought it was something new that was added.
