### ISSUE TITLE
Polymorphism via abstract interfaces doesn't appear to be working

### ISSUE THREAD

**Issue by retailcoder** [WaynePhillipsEA/twinbasic#69]
At first I thought I might have finally hit a problem with my `This` pattern [ab]using `Private Type` declarations...

In this stack frame, the `SourcePath` object looks exactly as it should, just before it's being passed to the `IBindingStrategy.DefaultPropertyBindingFor` method:

![locals showing SourcePath.Object and SourcePath.Context having non-null references](https://user-images.githubusercontent.com/5751684/115150646-51be3f00-a037-11eb-88bb-dd9c2cf4fdd3.png)

In the next stack frame the `SourcePath` was passed `ByVal` to the `TextBoxBindingStrategy.DefaultPropertyBindingFor` method, and its internal state is ...wiped clean:

![locals showing Source.Object and Source.Context both 'Nothing'](https://user-images.githubusercontent.com/5751684/115150681-77e3df00-a037-11eb-90b1-9164a4c69ff3.png)

So I tweaked the `BindingPath` class to drop its `Private Type` and use `mVariableName` module-level variables instead, but the result was the same - the path object loses its state as it's being passed around.

Now, the `IBindingPath` interface is an artifact of the original VBA source code, that is redundant in twinBASIC... so I removed it and -- oh, there's my instance state!

![twinBASIC reads the state off a concrete type just fine](https://user-images.githubusercontent.com/5751684/115151066-4ec44e00-a039-11eb-912a-9b2b4efee595.png)

This appears to be a bug in how twinBASIC is implementing interfaces - *something* works differently than in VBA/VB6, causing objects being passed around as abstract interfaces to lose their state.. which could be problematic when a type implements an interface that *isn't* redundant.

...and indeed, just a few lines later I'm looking at members of the created `IPropertyBinding` object, and the object references are apparently not set:

![Binding source and target are 'Nothing' now](https://user-images.githubusercontent.com/5751684/115151345-7bc53080-a03a-11eb-99b9-bf978849197e.png)

Also noteworthy, the debugger isn't seeing any members for the `Notifier As INotifyPropertyChanged` object, which looks like everything is "working" through accidentally late-bound calls (didn't get any errors invoking members on an interface that "doesn't have any members").

**Comment by WaynePhillipsEA** [comment]
Thanks for the bug report!  I'll get this sorted tomorrow.  Any chance of a minimal cut down example?

**Comment by WaynePhillipsEA** [comment]
NVM... managed to reproduce

**Comment by retailcoder** [comment]
lol I was too busy adding comments into mine

**Comment by WaynePhillipsEA** [comment]
Could you confirm... this is a debugger error, not a compilation error?   i.e. the values are actually correct when read via code, it's just the debugger reporting them incorrectly?

**Comment by retailcoder** [comment]
@WaynePhillipsEA confirmed!

```vb
Module ModHelloWorld

    ' This project type is set to 'Standard EXE' in the Settings file, so you need a Main() subroutine to run when the EXE is started.
    Public Sub Main()

        dim concreteThing as Something = new Something("test")

        Debug.Print "concreteThing: " & concreteThing.PropertyValue
        'output: "test" | debugger: "test"
        
        TestConcreteByVal concreteThing
        TestConcreteByRef concreteThing
        TestAbstractByVal concreteThing
        TestAbstractByRef concreteThing
        
        
        dim abstractThing as ISomething = new Something("test")
        Debug.Print "abstractThing: " & abstractThing.PropertyValue                        
        'output: "test" | debugger: vbNullString

        TestConcreteByVal abstractThing
        TestConcreteByRef abstractThing
        TestAbstractByVal abstractThing
        TestAbstractByRef abstractThing
    
    End Sub
	
    Private Sub TestConcreteByVal(ByVal thing As Something)
        Debug.Print CurrentProcedureName & ": " & thing.PropertyValue
    End Sub
    
    Private Sub TestAbstractByVal(ByVal thing As ISomething)
        Debug.Print CurrentProcedureName & ": " & thing.PropertyValue
    End Sub
    
    Private Sub TestConcreteByRef(ByRef thing As Something)
        Debug.Print CurrentProcedureName & ": " & thing.PropertyValue
    End Sub
    
    Private Sub TestAbstractByRef(ByRef thing As ISomething)
        Debug.Print CurrentProcedureName & ": " & thing.PropertyValue
    End Sub

End Module

'@Description "An abstract interface representing a thing that has a property."
class ISomething
    public property get PropertyValue() As string
    end property
end class

'@Description "A concrete implementation of an abstract interface."
class Something
attribute vb_exposed = false 'COM exposure isn't considered in this scenario.
    implements ISomething
    
    '@Description "The encapsulated internal state."
    private mValue As string
    
    '@Description "Creates a new thing with the specified value."
    public sub New(byval value as string)
        mValue = value
    end sub
    
    '@Description "Gets the property value."
    public property get PropertyValue() as string implements ISomething.PropertyValue
        return mValue                           '^ unrelated, but this space shouldn't be underlined/part of the 'string' hint.
    end property
    
end class
```

```none
Executing 'HelloWorldProject.ModHelloWorld.Main'...
concreteThing: test
TestConcreteByVal: test
TestConcreteByRef: test
TestAbstractByVal: test
TestAbstractByRef: test
abstractThing: test
TestConcreteByVal: test
TestConcreteByRef: test
TestAbstractByVal: test
TestAbstractByRef: test
```

**Comment by WaynePhillipsEA** [comment]
*should be* Fixed in 0.9.1676.  Thanks for reporting. I'll await your confirmation before closing.

**Comment by retailcoder** [comment]
Fix confirmed with the above repro code 👍

**Comment by WaynePhillipsEA** [comment]
Non-related, but I like how you've got all data types semantically underlined 👍
