### ISSUE TITLE
Editing experience troubled by memory fragmentattion

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#699]
**Describe the bug**
This is a FYI to give the memory fragmentation issue I'm experiencing visibility.

When editing my project I am interrupted every one to two minutes by a message from the compiler saying that the memory is fragmented and that I need to reload the compiler.  I can tell that this is coming because intellisense stops working and/or colourising of keywords fails.  About once every half hour of editing reloading the compiler fails and I have to do a forced restart of VSCode by ending the VSCode task in task manager then restarting it.

Thus far, VSCode has been sufficiently robust that I haven't lost a chunk of editing through having to do a forced restart.  I'm also not too bothered as I understand that at the current stage of development this is likely part of the experience of having fun with twinBasic.

It might be helpful if anyone else experiencing a similar problem tags onto this report to give a better indication of how prevalent this issue might be (It could, of course, just be me and my dodgy code/computer)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - twinBASIC compiler version [e.g. 0.13.91]

**Comment by WaynePhillipsEA** [comment]
Just for a little information on this, it is only something you will see with the 64-bit compiler, and the larger the project is, the more often you will encounter the problem.

It's very much a solvable problem... it just hasn't had my attention so far, as I figured most people hadn't encountered it (yet)

**Comment by FullValueRider** [comment]
Thanks for the tip.  I'll switch to 32 bit mode for editing purposes for now.
