### ISSUE TITLE
Prefix/Postfix operators

### ISSUE THREAD

**Issue by mansellan** [WaynePhillipsEA/twinbasic#70]
**Is your feature request related to a problem?**
Incrementing and decrementing by 1 are very common operations. twinBASIC could benefit from operators to express this concisely.

**Describe the solution you'd like**
Prefix (```--i```) and postfix (```i++```) operators, similarly to C#.

**Describe alternatives you've considered**
twinBASIC already provides an improvement over legacy syntax using the ```+=``` and ```-=``` operators, but these are still not as terse as they could be. They also cannot be inlined into expressions.

**Additional context**
This would need to be an opt-in syntax, as multiple operators are legal syntax in VB6. For example, ```i = --j``` is valid VB6, but there's really no reason to ever do that. It's exactly the same as ```i = j```. 

Actually... ```i = ----------j``` is legal too....

**Comment by Greedquest** [comment]
With operator overloading `--` double operator won't necessarily be a reliable no-op. FWIW Python doesn't have increment/ decrement operators, but they do have := for inlining
```
a = ++i
a = (i := i + 1) #a bit contrived. Also what about i :+= 1 
```

**Comment by mansellan** [comment]
Given the recent discussion around operators (#396), I've changed my mind and no longer think these operators are appropriate for twinBASIC, so I'll close this issue.
