### ISSUE TITLE
Bizarre Project:Name bug

### ISSUE THREAD

**Issue by mwolfe02** [WaynePhillipsEA/twinbasic#701]
**Describe the bug**
Including the word "Update" in the project name causes the 32-bit build to require UAC elevation.

**To Reproduce**
1. Download Sample 1. Hello, World
2. In Settings, change Project: Name to include the word "Update"
3. Build a 32-bit executable
4. The generated executable requires admin rights

**Expected behavior**
Create an executable that does not require admin rights.

**Screenshots**
![image](https://user-images.githubusercontent.com/305213/151736540-abe47fed-f73e-4197-a22e-bebcc14f38be.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.13.91

**Additional context**
I was able to reproduce this bug on two separate devices.

I thought maybe the issue was actually the word "date" and not "update", but you can see from the screenshot that "Man**date**_win32.exe" does not require admin rights.  It really seems to be tied to the word "Update".

**Comment by jpbro** [comment]
Perhaps related to what's described in the _Installer Detection Technology_ section here: [Understanding and Configuring User Account Control in Windows Vista](https://web.archive.org/web/20080103025356/http://technet2.microsoft.com/WindowsVista/en/library/00d04415-2b2f-422c-b70e-b18ff918c2811033.mspx?mfr=true)

**Comment by mwolfe02** [comment]
OK, @jpbro, I'm impressed.  That's almost got to be the issue:

> Before a 32 bit process is created, the following attributes are checked to determine whether it is an installer:
>  - Filename includes keywords like "install," "setup," "update," etc.

**Comment by jpbro** [comment]
It was a common "issue" with legacy apps ~15 years ago. File this under "heuristics gone wrong/unintended consequences/best laid plans/ugly hacks/etc..." ;)

**Comment by WaynePhillipsEA** [comment]
FWIW I encountered this very issue myself a few months ago, though I think I had used the word 'patch' or something like that.  I remember wasting several hours before realising it was a Windows **feature**...

Anyway, I think this can now be closed :)
