### ISSUE TITLE
GUI, Properties

### ISSUE THREAD

**Issue by DinyaZ** [WaynePhillipsEA/twinbasic#708]
**Is your feature request related to a problem? Please describe.**
Now the checkbox items on the properties page works only if you click on the "rectangle". For example VISIBLE : True/False. In the original VB6 there is no checkbox "rectangle", and the whole properties itemtext can get the click.

**Describe the solution you'd like**
If would be more comfortable, if the TWBasic can also do this, and the checkbox texts can also be active.

**Comment by WaynePhillipsEA** [comment]
This should now match VBx, in v0.14.6.  If you double click on any part of the field it will now toggle the boolean value.

Thanks!

**Comment by DinyaZ** [comment]
Thanks Wayne! :)
