### ISSUE TITLE
GUI, character issue

### ISSUE THREAD

**Issue by DinyaZ** [WaynePhillipsEA/twinbasic#709]
**Describe the bug**
See attached screenshots. On the properties page, every hint text under the properties list starts with a rectangle, if you click the properties items

**Expected behavior**
Texts without "rectangle" prefix

**Screenshots**
See attached!

**Desktop (please complete the following information):**
 - OS: Window7
 - twinBASIC compiler version 0.14.5

**Additional context**
![Image51](https://user-images.githubusercontent.com/94013032/152653139-51f78c0d-d586-46a6-8d5e-f721f0ca015d.jpg)
![Image511](https://user-images.githubusercontent.com/94013032/152653170-b81e46c2-d721-4f9e-aa91-577e9f1c9830.jpg)

**Comment by WaynePhillipsEA** [comment]
This should've been shown as the unicode information symbol ⓘ, but the symbol mustn't have been available in your chosen VS code theme font.

I've now changed this to an image icon in v0.14.6, which will fix this issue.  Thanks!
