### ISSUE TITLE
CallByName throws an unspecified error

### ISSUE THREAD

**Issue by retailcoder** [WaynePhillipsEA/twinbasic#71]
**Describe the bug**
*A clear and concise description of what the bug is.*

`VBA.Interaction.CallByName` is throwing an *unspecified error*.

**To Reproduce**
1. Define a `Something` class with a `PropertyValue` property
2. Declare and assign a `New` instance of that class
3. Assign a test value to the property
4. Attempt to retrieve the property value with `CallByName`

![Exception has occurred](https://user-images.githubusercontent.com/5751684/115159233-27cd4280-a060-11eb-9049-f828eb23555a.png)

**Expected behavior**
*A clear and concise description of what you expected to happen.*

Invoking `CallByName` should invoke the specified member when it exists.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.9.1676

**Additional context**
*Add any other context about the problem here.*

The below minimal example code illustrates and reproduces the problem:

```vb
Module ModHelloWorld

    Public Sub Main()

        dim thing as Something = new Something("test")
        
        dim result as string
        result = VBA.Interaction.CallByName(thing, "PropertyValue", vbGet)
        debug.print result
                
    End Sub
	
End Module

class Something
attribute vb_exposed = false 'COM exposure isn't considered in this scenario.
    
    '@Description "The encapsulated internal state."
    private mValue As string
    
    '@Description "Creates a new thing with the specified value."
    public sub New(byval value as string)
        mValue = value
    end sub
    
    '@Description "Gets the property value."
    public property get PropertyValue() as string
        return mValue
    end property
    
end class
```

**Comment by retailcoder** [comment]
`CallByName` being the cornerstone that makes property bindings work, this puts `VBMVVM` on hold for now.

**Comment by Greedquest** [comment]
I think this comes under one of the caveats
 

> Late-bound calls to twinBASIC class objects are disabled (but late-bound calls to other normal COM objects are working fine)

i.e. callbyname requires dual interfaces/ IDispatch

**Comment by WaynePhillipsEA** [comment]
This one is a known limitation of the preview, due to IDispatch not being implemented on internal tB classes.   Should be ready by end of the coming week.

**Comment by retailcoder** [comment]
@WaynePhillipsEA awesome! I hope that gives me enough time to refactor things a bit as the new possibilities are still sinking in!

**Comment by WaynePhillipsEA** [comment]
CallByName is confirmed working now that twinBASIC offers late-bound (IDispatch) support on twinBASIC classes (v0.9.2021)
