### ISSUE TITLE
Compiler crashing on differences between 64/32 bits

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#712]
**Describe the bug**
This is kind of obscure and I had hard time getting a reproduction but from I find, it seems to have issues running the tests on 64-bit when there are broken 32-bit code. Furthermore, I also experienced cases where a change would _seem_ to work but in fact didn't because the following sequence happens:

1. I run tests, everything's fine
2. I make a change
3. Re-run the test, compiler crashes, I assumed I had a shutdown leak and make a mental note to look at it
4. Re-run test again and it works.
5. Save the changes
6. Run the test - now compiler is crashing consistently

Unfortunately, I no longer can reproduce this but I'm including this in the report in case it's helpful because what I _think_ happens is that when I make a bad change that causes the compiler to crash the first time, it basically reverts to the last saved state which is why it seems to work all fine until I save the changes

Once I realized that I had a broken 32-bit build and fixed the code in 32-bit, I then found that I no longer experience any crashing regardless of the changes I make in 64-bit build.

**To Reproduce**
1. Open the attached project, verify you are using 64-bit build
[BugRepro.zip](https://github.com/WaynePhillipsEA/twinbasic/files/8014679/BugRepro.zip)
2. Open `Tests.twin` and run the only procedure there
3. The compiler will crash consistently
4. Open `Callbacks.twin` and in the first callback procedure change from `ByVal lpRefData As TaskDialog` to `ByVal lpRefData As Object`
5. Run the tests in `Tests.twin`, and it no longer crashes
6. Switch to 32-bit and see errors, fix them (mainly just renaming some things that got renamed in 64-bit)
7. Build, test, and no crash.
8. Switch back to 64-bit, revert the change in step 4
9. No more crashing.

NOTE: before doing step 6, I used to experience the "crash once, works until saved" by fiddling with the changes in step 5. however in this reproduction, this doesn't happen anymore.

**Expected behavior**
No crashing.

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - twinBASIC compiler version [0.14.6]

**Comment by WaynePhillipsEA** [comment]
With #190 now fixed in v0.14.10, this issue is also now fixed.  Thanks for reporting!
