### ISSUE TITLE
VB.Clipboard/VB.App should be not creatable

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#717]
**Describe the bug**
Currently tB allows to create a `New` VB.Clipboard/VB.App

**To Reproduce**
```
Dim This As VB.Clipboard
Set This = New VB.Clipboard
```

**Expected behavior**
to throw a invalid use of New keyword error

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.14.8]

**Additional context**
n/a

**Comment by WaynePhillipsEA** [comment]
Yes, I'll get that fixed.   I'll also add the `Global` predeclared class implemented now too (which these two should be members of), as we'll be needing other bits from it soon.

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.14.10, and the `Global` class is now starting to take shape.
