### ISSUE TITLE
Window title should contain the project name

### ISSUE THREAD

**Issue by retailcoder** [WaynePhillipsEA/twinbasic#72]
**Describe the bug**

The Visual Studio Code title bar appears to intend to include the project name, but doesn't.

**To Reproduce**
1. Start a new twinBASIC project; make sure to name it.
2. Save the workspace
3. Visual Studio Code title bar says "NewProject - TWINBASIC" regardless of the project's name.

**Expected behavior**

The project's name should appear in place of "NewProject" in the VSC title bar. That way we would be able to tell two VSC/twinBASIC instances apart by their title:

![Windows taskbar preview showing identical titles for two distinct VSC instances](https://user-images.githubusercontent.com/5751684/115159713-84c9f800-a062-11eb-9ea4-f47271728d16.png)

 - twinBASIC compiler 0.9.1976

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.9.1750, thanks for reporting.
