### ISSUE TITLE
Problem with two monitors, running compiled build

### ISSUE THREAD

**Issue by rboeckka** [WaynePhillipsEA/twinbasic#724]
I build 'HelloWord' sample. When i move the running form to the second monitor with different dpi mode i get:
"Call to PostQueuedCompletionStatus failed." The program stops running. 
At designtime it works normaly; in the debug console i can see:
RuntimeLayoutForm DPI (712,815)
RuntimeLayoutForm DPI (407,466)

 [Windows 10], 64 bit, twinBasic v0.14.12
Screenresolution1: 2560 x 1440,  Screenresolution2: 3840 x 2160 (4k)

**Comment by WaynePhillipsEA** [comment]
Now fixed in v0.14.13.  Thanks for reporting!
