### ISSUE TITLE
Editing whilst debugging causes strange debug output

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#725]
**Describe the bug**
Stopping a debug session by editing text produces a large amount of text to appear in the debug window.

![BufferOverflow](https://user-images.githubusercontent.com/81257042/153424204-a8598194-bb9d-42f9-8769-e45a812f4ed0.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - twinBASIC compiler version [e.g. 0.14.13]

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.14.14, thanks!
