### ISSUE TITLE
Compiler cursor errors  (1.)

### ISSUE THREAD

**Issue by DinyaZ** [WaynePhillipsEA/twinbasic#727]
**Describe the bug**
Compiler cant cope with the cursor position, and gives error message. See attached screenshot. 
 
**To Reproduce**
1. Open the IPaddress demo project
2. Put the cursor on line25
3. Try to run the program, and you get the error message
4. But if you put the cursor on line30, it runs nicely, without problem!

**Screenshots**
See attached

**Desktop (please complete the following information):**
 - OS: Windows7
 - twinBASIC compiler version 0.14.15
![Image4212](https://user-images.githubusercontent.com/94013032/153558304-51f21c64-fa8f-4330-a63e-5662585a40c7.jpg)

**Comment by WaynePhillipsEA** [comment]
This is currently as-designed.  The F5 key (or pressing the running man icon in the debug floating toolbar) executes the code that is under the cursor (caret).  Since line 25 is not inside a procedure, the error is correct.

**Comment by WaynePhillipsEA** [comment]
There is a method for creating your own keyboard shortcut for executing a specific procedure, detailed [here](https://github.com/WaynePhillipsEA/twinbasic/issues/493#issuecomment-968058390).

Once we've got a setting for a 'startup object' like in VB6, we can probably rebind the F5 key to that (assuming others agree).

**Comment by DinyaZ** [comment]
It stopped working, error messages from everywhere, and finally:

![Image988](https://user-images.githubusercontent.com/94013032/153561464-f1ea142e-1afe-4a09-bcd3-dcdfa2747972.jpg)
