### ISSUE TITLE
IDE, compiler problems

### ISSUE THREAD

**Issue by DinyaZ** [WaynePhillipsEA/twinbasic#730]
**Describe the bug**
A tried to document a problem, which I ment before. See attached screenshots

**To Reproduce**
1. I opened the IPAddress demo project, and try to add a form to it. It starts on 32bit.
2. On the first screenshot there are "rectangles" again
3. I add th Windows Form Contol, but it is not enough to start a form, error message comes (screenshot 2.). Is it possible to add theese necessary packages to the project, without messages? 
4. Then I add the CustomControlsPackage also. (screenshot 3.) Below on the left side comes an yellow labeled short error message about a misterious connection which not works. I have got an automatic question about 64bit, to create something, ok lets go to 64, and it switched automatically to "win64"
5. The explorer page starts to do something, the little circle goes and goes around, it takes ca a minute. (screenshot 4)
6. And finally (screenshot 5) the IPAdress project disappeared, no form, no module. When I tried to push the File / Open file(?) Open folder(?) menuitem, then below and now on the right side come new and misterious error messages again, now "about file system".
(I cant reproduce it again, because I have lost this demo project.)

**Desktop (please complete the following information):**
 - OS: Windows7
 - twinBASIC compiler version 0.14.1
![Image301](https://user-images.githubusercontent.com/94013032/153583961-18a8661f-2799-473e-96a6-983608dada65.jpg)
![Image302](https://user-images.githubusercontent.com/94013032/153583967-8f93178a-6e52-4c41-9708-95c9c8d9ce83.jpg)
![Image303](https://user-images.githubusercontent.com/94013032/153583971-4d50a3f6-c118-4171-88d7-504cfefde5cb.jpg)
![Image304](https://user-images.githubusercontent.com/94013032/153583974-d71b57f4-fe68-4fdb-85bc-549e2add891a.jpg)
![Image305](https://user-images.githubusercontent.com/94013032/153583976-6480788b-becd-4380-8160-57eae3051be8.jpg)
5

**Comment by WaynePhillipsEA** [comment]
In v0.14.18, the unicode arrows have now been replaced, fixing point 2.

**Comment by DinyaZ** [comment]
Thank you, Wayne!

**Comment by WaynePhillipsEA** [comment]
I think all the issues discussed here have since been fixed, so I'm going to close this now.  Thanks for reporting.
