### ISSUE TITLE
Can't define module variable in Form Class

### ISSUE THREAD

**Issue by dmrvb** [WaynePhillipsEA/twinbasic#735]
In the class (.twin) associated with a windows Form (.tbform) a private or public variable declaration prevents execution.
No compiler warnings but after build either:
Form appears briefly then closes
or
An unhandled Error msgbox is shown

process exits with code -1073741819

**To Reproduce**

insert this above sub new():
private xxx as long
and click build.

**Expected behavior**
I would expect a rather nice windows form with my controls to display.
Without the private declaration it works and is starting to look quite impressive.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - twinBASIC compiler version 0.14.18
 -

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting.  I think I've just fixed this issue in the release that is being published right now.  Please check after about 10 minutes.

**Comment by WaynePhillipsEA** [comment]
Once you've updated to v0.14.19 (just released), this should be resolved.  If not, please report back and I will re-open this.

>Without the private declaration it works and is starting to look quite impressive.

Thanks!  Glad you like it!

**Comment by dmrvb** [comment]
Its fixed, a very impressive rapid response.
