### ISSUE TITLE
IFont.hFont reports blank or compilation error

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#74]
**Describe the bug**
Setting an IFont and retrieving hFont shows null or raises compilation error

**To Reproduce**
for compilation error (in Sub Main)

```
Dim MyFont As StdFont

set MyFont = new StdFont
MyFont.Size = 15
msgbox MyFont.Name
Dim This As IFont
Set This = MyFont
Dim LngValue as long
LngValue = this.hFont
msgbox LngValue
```

for blank value (also in Sub Main)

```
Dim MyFont As StdFont

Set MyFont = New StdFont
MyFont.Size = 15
MsgBox MyFont.Name
Dim This As IFont
Set This = MyFont
MsgBox This.hFont
```

**Expected behavior**
above code works flawless in VB6. Should be also in tB.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.9.1676]

**Additional context**
msgbox vartype(this.hFont) returns 0. (vbEmpty)
But this member should return a vbLong.

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.9.1750
