### ISSUE TITLE
UDT Members Not Recognized in With Blocks with Line Numbers

### ISSUE THREAD

**Issue by jpbro** [WaynePhillipsEA/twinbasic#744]
**Describe the bug**
tB does not recognize UDT members when they are used within a With block that has line numbers.

**To Reproduce**
Try the following code in a new tB project:

```
Module MainModule
    Private Type MyUDT
        Member As long
    End Type

    Public Sub Main()
        Dim UDT As MyUDT
        
10       With UDT
20           .Member = 5
30      End With
    End Sub
End Module
```

Results in "unrecognized symbol 'Member'. internal error, expected symbol"

Removing line numbers or unwrapping the With block to `UDT.Member = 5` fixes the problem.

**Expected behavior**
I would expect tB to recognize UDT members within With blocks that have line numbers.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.14.9

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.14.27, thanks for reporting!
