### ISSUE TITLE
Ambiguous references due to access to WindowsControls.PrivateWindowsAPI namespace

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#747]
**Describe the bug**
It appears that if there are Win32 API declares used with a project containing WinNativeForms, it causes an ambiguous reference which cannot be fixed.

**To Reproduce**
1. Create sample 1a. (Hellow World (WinNativeForms)
2. In a new module, add a declare:
```
Public DeclareWide PtrSafe Function SendMessageW Lib "user32" (ByVal hWnd As LongPtr, ByVal wMsg As Long, ByVal wParam As LongPtr, lParam As Any) As LongPtr
```
3. In `MyForm` module, replace the code as following:
```
    Sub New()
        SendMessageW 0, 0, 0, 0
    End Sub
```
4. See compiler error as shown in screenshot. Note also the 2nd error about duplicate declaration:
![image](https://user-images.githubusercontent.com/2367644/154810444-47df696a-1208-43b3-b2bf-f815e2d14e0f.png)

5. Delete the `MyForm` module & form
6. Go into setting and remove the WinNativeForms reference
7. Save the settings
8. Go to MainModule and change code as shown:
```
Module MainModule
    Public Sub Main()
        SendMessageW 0, 0, 0, 0
    End Sub
End Module
```

The same error persists, even after restarting the compiler. 

**Expected behavior**
No ambiguity. I think that generally any declares from the project should take precedence. I also assume the members of the `PrivateWindowsAPI` isn't meant to be accessible.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.14.27

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.14.34, thanks!
