### ISSUE TITLE
Problem with Method Named Error

### ISSUE THREAD

**Issue by jpbro** [WaynePhillipsEA/twinbasic#751]
**Describe the bug**
tB Reports an unexpected  "syntax error. no handler for this symbol" error in code that has a method named "Error".

**To Reproduce**
Consider the following code:

```
Module MainModule
    Public Function Error(ByVal Number As Long, ByVal Source As String, ByVal Description As String, ByVal Method As String, ByVal Line As Long) As CError
        Set Error = New CError
        
        Error.LogError Number, Source, Description, Method, Line
     End Property
End Module

Public Class CError
    Public Sub LogError(ByVal Number As Long, ByVal Source As String, ByVal Description As String, ByVal Method As String, ByVal Line As Long)
    End Sub
End Class
```

I would expect no errors to be detected, but tB reports "syntax error. no handler for this symbol" on the Error.LogError p_Number line, at the first comma separating the parameters.

If I change name of the Error function to something other than "Error", then no errors are detected any more.

**Expected behavior**
I would expect to be able to have a method name "Error" without producing any errors.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.14.31

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.14.32, thanks for reporting!
