### ISSUE TITLE
Prettifier Mishandling Ampersand Variable Suffix

### ISSUE THREAD

**Issue by jpbro** [WaynePhillipsEA/twinbasic#754]
**Describe the bug**
The prettifier (I think) is mishandling ampersand variable suffixes in If statements (and possibly elsewhere) by putting a space between the variable and the &, which prevents execution.

**To Reproduce**
Copy & paste the following code into a tB project:

```
    Public Sub Main()
        Dim X As Long
        Dim Y As Long

        If X = Y& Then
            MsgBox "A"
        End If
    End Sub
```

A space will be automatically inserted beween "Y" "and "&" resulting in "unrecognized symbol '{unexpected end of line}'" and "expected operand following the operator" errors.

**Expected behavior**
TBH, I will just remove the & from the code there - it's not needed and is unnecessarily complicating things. That said, it is legal VB6-ese, so I guess it should be prettified/parsed correctly.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.14.31

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.14.32, thanks for reporting!
