### ISSUE TITLE
Possible UDT Circular Reference Error with TLB

### ISSUE THREAD

**Issue by jpbro** [WaynePhillipsEA/twinbasic#755]
**Describe the bug**
I discovered another issue with the problematic  [Windows Unicode API TLB.](https://github.com/WaynePhillipsEA/twinbasic/files/8118446/winU.zip) discussed in Issue #753. When using the LOGPEN structures, tB complains of a possible circular UDT reference error.

**To Reproduce**
1. Reference WinU.tlb in a tB project.
2. Add the following code:
```
    Public Sub Main()
        Dim y As LOGPEN
    End Sub
```
3. See the following error: `unable to finalize variables of procedure [Main], possible circular UDT reference`.

**Expected behavior**
I would expect to be able to use the WinU.tlb LOGPEN structure in tB like I can in VB6.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.14.31

**Additional context**
Does the order of definitions in a TLB matter? I don't see how there could be a circular reference, but I do see that LOGPEN includes a POINTL structure member, and POINTL is defined after LOGPEN in the TLB. Not sure if that matters or not:

![image](https://user-images.githubusercontent.com/5287585/155193403-178e926b-f8fd-4834-be84-fe18e4ef1766.png)

Lastly, sorry for the barrage of issues, that's my last for the day! I'll probably end up getting rid of the WinU.tlb, but I thought I should report the issue in case it's something you need to address more generally for tB. Thank you :)

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.14.32, thanks for reporting!   Indeed this was due to the recent changes around UDT finalization.
