### ISSUE TITLE
Label Control Doesn't Remember Alignment at Runtime

### ISSUE THREAD

**Issue by jpbro** [WaynePhillipsEA/twinbasic#760]
**Describe the bug**
Setting a tB Label's Alignment property to vbRIghtJustify or vbCenter appears to work at design time, but reverts to vbLeftJustify at runtime.

**To Reproduce**
1. Add a .tbform called MyForm to a new project and add a Label to it.
2. Set the Alignment property of the Label to vbRightJustify (or vbCenter). Everything looks good so far:
![image](https://user-images.githubusercontent.com/5287585/155345375-550c007f-b012-4379-a661-a0b2035c1f19.png)

3. Add this code and run it to show the form:

```
Module MyModule
    Sub Main()
        Dim X As New MyForm
        
        X.Show
    End Sub
End Module
```

At runtime, the Alignment property value is not honoured:

![image](https://user-images.githubusercontent.com/5287585/155345683-c133bc78-5163-4469-9373-69bee3c43fff.png)

**Expected behavior**
I would expect the design-time Aligment property value to be honoured at runtime.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.14.31

**Comment by WaynePhillipsEA** [comment]
I was unable to reproduce the problem.  I think you might be running into #741 where you need to make sure that you save the project before building (at the moment!).    Let me know if that's not the issue, and I'll try again.  Thanks.

**Comment by jpbro** [comment]
Yest, that was the problem @WaynePhillipsEA, sorry for the noise!
