### ISSUE TITLE
Progress Marquee Doesn't Scroll Until Another Control Placed on Form

### ISSUE THREAD

**Issue by jpbro** [WaynePhillipsEA/twinbasic#761]
**Describe the bug**
If you add a ProgressBar to ta tB form and set the MarqueeAnimation property to True and the Scrolling property to PrbScrollingMarquee then run the app, the marquee doesn't scroll. If you subsequently add any other control to the form and run it, the Marquee will scroll. 

Note that adding controls *before* adding the ProgressBar doesn't work - if the ProgressBar is the last added control, then it will not scroll. You must add at least one control after the ProgressBar for marquee scrolling animation to work.

**To Reproduce**
1. Start a new project.
2. Add a new form.
3. Add a ProgressBar to the form and set MarqueeAnimation = True, Scrolling = PrbScrollingMarquee
4. Build and run the app. The progress bar is frozen:

![image](https://user-images.githubusercontent.com/5287585/155359860-6ac1ebd1-b1c6-4e7c-93e1-d79cd7350600.png)

5. Add any other control (a label or button for example), and build and run again. The ProgressBar marquee animation now works:

![image](https://user-images.githubusercontent.com/5287585/155360041-439ea667-2d98-4493-9ff5-89c075951a9f.png)

**Expected behavior**
I expect the ProgressBar's marquee animation to work without requiring any other controls to be added to the form.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.14.31

**Comment by WaynePhillipsEA** [comment]
I was unable to reproduce the problem.  I think you might be running into #741 where you need to make sure that you save the project before building (at the moment!).    Let me know if that's not the issue, and I'll try again.  Thanks.

**Comment by jpbro** [comment]
Yest, that was the problem @WaynePhillipsEA, sorry for the noise!
