### ISSUE TITLE
File System does Not support Input Function

### ISSUE THREAD

**Issue by dmrvb** [WaynePhillipsEA/twinbasic#766]
**Describe the bug**

twinBasic File System does not support the Input function. 

mystring  = Input(1, #stream) 

gives a compilation error, it should read a character.

compilation error is: unrecognized symbol 'input'
If I include the hash it also gives a "bad date literal" error

I think this has been discussed previously???
I have some old code that uses "input" so it is needed for 100% VB6 compatibility.

**Desktop (please complete the following information):**
 - OS: Win 10
 - twinBASIC compiler version  0.14.36

**Comment by Kr00l** [comment]
Duplicate with #621

**Comment by dmrvb** [comment]
Oops sorry, I thought I had seen this before but did not look hard enough. 
I'm trying to move parts of quite a big project over to tB (just to see how it goes) and am hitting a number of issues. Most of these are probably because the GUI is still at a very early stage so maybe not worth reporting yet. No Zorder in Form, no forms collection, forms not extensible, no hwnd on the progress bar etc etc and DPI trouble.
