### ISSUE TITLE
StrComp fails on zero length strings

### ISSUE THREAD

**Issue by dmrvb** [WaynePhillipsEA/twinbasic#767]
**Describe the bug**
StrComp fails with Error 5 if either string is zero length

**To Reproduce**
Dim s1 As String
Dim s2 As String
Dim response As Long
response = StrComp(s1, s2, vbTextCompare)

**Expected behavior**
VB6 returns -1, 0 or 1 as appropriate

Not my best bit of programming, but if tB wants 100% compatibility then this needs fixing.

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting.  The VBA.Strings module has insufficient test coverage at the moment, so there will be some edge cases, see  #187.

**Comment by dmrvb** [comment]
The observations from bclothier are interesting.
I have been half aware of differences between "" and vbnullstring etc for a while but have never investigated them.
It looks like its wise to initialise all strings to "".
Is this another example of why we might need an option in tB to select either "100% VB compatibility" or "logical behaviour" in which all strings would be initialised to "" and a few other string issues are resolved..

**Comment by WaynePhillipsEA** [comment]
> FWIW, I think that's a edge case.
> 
> ```
> ?strcomp("","")
>  0 
> ?strcomp(vbnullstring, "") 'Error 5
> ?strcomp(s1$, s2$) 'Error 5
> s1$="":s2$="":?strcomp(s1,s2)
>  0 
> ```

There are differences here that are very specific to Access VBA.  Your two examples that throw Error 5, do not throw errors in VB6 (nor any other VBA host).  This is due to Option Compare Database that is implicit within the Immediate Window.  If you specify vbCompareText or vbCompareBinary, StrComp no longer throws Error 5 in those cases.

**Comment by WaynePhillipsEA** [comment]
This has now been fixed in v0.15.4 of the compiler.   At the moment, only the new BETA IDE ships with this version of the compiler.   The VS Code version still uses compiler v0.14.36, and won't be updated for approximately 1-2 weeks.

Thanks for reporting.
