### ISSUE TITLE
The VarType() function used on a object instance which class implements a default (property get) member, returns the type of the default member function value, not vbObject.

### ISSUE THREAD

**Issue by francescofoti** [WaynePhillipsEA/twinbasic#769]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.9.1111]

**Additional context**

**Comment by WaynePhillipsEA** [comment]
dup of #770
