### ISSUE TITLE
VarType() function returns the type of the default member function value, not vbObject.

### ISSUE THREAD

**Issue by francescofoti** [WaynePhillipsEA/twinbasic#770]
**Describe the bug**
The VarType() function used on a object instance which class implements a default (property get) member, returns the type of the default member function value, not vbObject.

**To Reproduce**
1. Create a simple class with a default member, like:
```
Class CSimpleObject
	' add your member fields and procedures here
	Private msStringBuffer As String
	
	[ DefaultMember ]
	Public Property Get StringBuffer() As String
		StringBuffer = msStringBuffer
	End Property
	
	Public Property Let StringBuffer(ByVal psText As String)
		msStringBuffer = psText
	End Property
End Class
```
2. Create a module to test the return value of the VarType() function, like:
```
Module MainModule

    ' This project type is set to 'Standard EXE' in the Settings file, so you need a Main() subroutine to run when the EXE is started.
    Public Sub Main()
      Dim oSimpleObject As New CSimpleObject
      
      oSimpleObject = "This is a sample"
      Debug.Print VarType(oSimpleObject) & " (vbString = " & vbString & ")", GetVarType(oSimpleObject) & " (vbObject = " & vbObject & ")"
    End Sub

    'Function needed as tB invokes default member on VarType(A), where A is an object
    Public Function GetVarType(ByRef pvValue As Variant) As VbVarType
      Dim iType As VbVarType
      On Error Resume Next
      If IsObject(pvValue) Then
        iType = vbObject
      Else
        iType = VarType(pvValue)
      End If
      GetVarType = iType
    End Function
    
End Module
```
3. Run Sub Main.

**Expected behavior**
VarType(oSimpleObject) should return the same result as GetVarType(oSimpleObject)

**Screenshots**
![image](https://user-images.githubusercontent.com/6288870/159112168-9d3e4ba0-b0ba-404b-bca3-d6e60f841cea.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.14.36

**Comment by FullValueRider** [comment]
This is normal vb behaviour.

**Comment by francescofoti** [comment]
Ah yes, sorry, I got confused. I tried that with VB5 which gets the same results:
![image](https://user-images.githubusercontent.com/6288870/159112454-154a5155-b115-4b4b-adaa-305d549ba654.png)
(and it TB):
![image](https://user-images.githubusercontent.com/6288870/159112617-e2b6b9bb-5675-4fba-9987-42ddee659396.png)
Thanks !

**Comment by francescofoti** [comment]
Gosh, and it's even a duplicate of one of mine... sometimes ;-)
