### ISSUE TITLE
Erroneous "cannot coerce type 'Collection' to [ByRef] 'Object'"

### ISSUE THREAD

**Issue by wqweto** [WaynePhillipsEA/twinbasic#773]
**Describe the bug**
Has problems with data-type mismatch on `ByRef` parameters of Events.

**To Reproduce**
```
Class Class1
    Public Event Click(Obj As Object)
    
    Public Sub FireClick()
        Dim oCol As Collection
        RaiseEvent Click(oCol)             '<--- cannot coerce type 'Collection' to [ByRef] 'Object'
    End Sub
End Class
```

**Expected behavior**
Works in VB6.

Not sure if for `ByRef` parameters of events VBx is creating temporaries but suspect employs the same rules as for type coercion at callsites in general.

**Desktop**
 - OS: Windows 11
 - twinBASIC compiler version:  0.14.36

**Additional context**

**Comment by WaynePhillipsEA** [comment]
This issue has been fixed in IDE BETA 7 (compiler v0.15.7).

Thanks for reporting!
