### ISSUE TITLE
Linker Fails with Compilation (codegen) error detected message

### ISSUE THREAD

**Issue by jpbro** [WaynePhillipsEA/twinbasic#777]
**Describe the bug**
I'm trying to build one of my larger VB6 DLLs for which I've been able to whittle down the errors & warnings to 0, but on build I'm getting the following rather cryptic errors:

```
[LINKER] compilation (codegen) error detected in '.' at line #???
[LINKER] FAILED due to compilation errors 'c:\Users\jbrow\Documents\Dev\TwinBasic\SL5StockNG\Build\SL5StockNG_win32.dll'
[BUILD] failed
```

No DLL is produced in the build path.

**To Reproduce**
Hard to say how to reproduce it. I can provide the .twinproj over a secure backchannel for testing if it helps.

**Expected behavior**
I would expect the DLL to compile, especially since there are no errors/warnings.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.14.36

**Additional context**
Is there anywhere that more logging data exists that I can review to see if there are any clues as to what is going wrong with the linker?

**Comment by jpbro** [comment]
I just found this issue #535 that mentions checking the error line, but unfortunately the message shows ??? for the error line, so I'm not sure where it's going wrong. Sounds like it is having an issue before it gets to any line processing?

**Comment by WaynePhillipsEA** [comment]
That sounds like an interesting one.  There's no further log available in public builds of tB, so this will likely need me to take a closer look.  I'll get in touch by email.

**Comment by WaynePhillipsEA** [comment]
This particular issue has now been fixed in v0.15.5 of the compiler (available in BETA 5 of the new IDE).  There are some instability issues with the compiler when editing your project, but I will address these issues separately.  For now, please ensure you reset the compiler before building the DLL to ensure you get a clean build.

**Comment by WaynePhillipsEA** [comment]
Oh, and thanks for reporting, and providing the twinproj file which helped resolve the issue promptly. :)

**Comment by jpbro** [comment]
Awesome :) The DLL is now compiling, thank you!
