### ISSUE TITLE
Optionals?

### ISSUE THREAD

**Issue by cristianbuse** [WaynePhillipsEA/twinbasic#78]
**Is your feature request related to a problem? Please describe.**
Quite often there is a need for a primitive data type to have no value (e.g. nil/null) while at the same time different from the default value.

**Describe the solution you'd like**
[Optionals](https://developer.apple.com/documentation/swift/optional) in a similar way with the SWIFT language. An Optional is a type that represents either a wrapped value or nil, the absence of a value.

**Describe alternatives you've considered**
n/a

**Additional context**
Currently in VBA if I need, for example, a Double data type to have no value (while the default 0 is a valid value that I also need) then I usually use a Variant so I can hold any Double value and also a Null value. This approach ruins the type safety but I prefer it over wrapping each data type in a custom class or UDT. It would be good to be able to declare an Optional Double that would  only allow an actual Double value or nil.

I am aware that this might not be feasable at all but worth mentioning.

**Comment by WaynePhillipsEA** [comment]
Hi there, and thanks for this feature request.   I agree, supporting nullable types would be a great feature.   However, I feel that #66 already covers this request.

**Comment by Kr00l** [comment]
In fact you can solve it another way.
The IEEE Double can have a "NaN" value.
For this a built-in function NaN() and IsNaN() would be convenient.

```
Dim d As Double
d = NaN()
If IsNaN(d) Then MsgBox "NaN is set"
```

**Comment by cristianbuse** [comment]
Completely missed [#66](https://github.com/WaynePhillipsEA/twinbasic/issues/66). Sorry about that, I've read most of the issues but clearly not that one.

**Comment by WaynePhillipsEA** [comment]
@cristianbuse no problem at all, I'll close this one
