### ISSUE TITLE
Undeclared Variable set as local var instead of Global

### ISSUE THREAD

**Issue by wopag** [WaynePhillipsEA/twinbasic#782]
**Describe the bug**
Using an undeclared variable should be treated as a global.

**To Reproduce**
Project : option Explicit On ; set to NO

    Private Sub Form_Click()
        a = a + 1
        Me.Caption = a
    End Sub

**Expected behavior**
Clicking the form should bump A by one and display as the caption of the form.
It Stays at 1, indicating that the variable is declared as a local var in the sub

**Desktop (please complete the following information):**
twinbasic IDE BETA 6

**Comment by WaynePhillipsEA** [comment]
This looks to be the same behaviour as VBx

**Comment by EduardoVB** [comment]
Yes, I tested in VB6 and it always says 1 in the form's caption.

**Comment by wopag** [comment]
Please remove- after more testing - working as expected.

In my first test I must have been using a global var by mistake.

**Comment by WaynePhillipsEA** [comment]
No worries.  Thanks
