### ISSUE TITLE
Module ModHelloWorld -> End Module ?

### ISSUE THREAD

**Issue by DinyaZ** [WaynePhillipsEA/twinbasic#784]
**Describe the bug**
I think it is more a feature request than a bug...

**To Reproduce**
See the attached screenshot! 

**Expected behavior**
1. To have a module without "Module name   -> End Module", so the same way as in VB6
3. An idea: if I start a new Sub or function, can the twinBasic can attach automatically an End Sub or End Function line automatically, the same way as in VB6?

**Screenshots**

![Image2333](https://user-images.githubusercontent.com/94013032/161839502-7f7f6be1-a8e3-42d4-92bb-320a9d64e75c.jpg)

**Comment by WaynePhillipsEA** [comment]
Thanks for your suggestions.

For 1. you can use traditional BAS files, which don't require the Module blocks.  Go to menu:  Project > Add > Add Module (.BAS)

For 2. twinBASIC already does this.   Just hit ENTER at the end of a statement such as 'Public Sub Abc{ENTER}' and twinBASIC will add the End Sub for you, if it doesn't exist.

As I feel these features are already available, I'll close this issue.

**Comment by dmrvb** [comment]
The thing about not automaticallt adding the end-sub.....
Sometimes this does not work, I think its when the sub is the last sub in a module/class, and many users will be adding code at tghe end of the module. I will investigate this a bit more and give more details.
