### ISSUE TITLE
IDE BETA 7 - Can start a new project

### ISSUE THREAD

**Issue by wopag** [WaynePhillipsEA/twinbasic#786]
Once in a project you cant start a new one.

**To Reproduce**
FILE - new project
"You've made changes to this project. Save Now?  OK CANCEL"     
I don't want to save - cancel closes back to current project

**Expected behavior**
Maybe    YES + NO + Cancel  question ?

**Comment by WaynePhillipsEA** [comment]
Fixed in IDE BETA 9.  Thanks!
