### ISSUE TITLE
Compiler requests a bug report

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#793]
**Describe the bug**
The compiler went into the bug report mode whilst editing the last constant in Class TypesGrouped.  In VSCode the project cannot now  be opened, and with the new VBA IDE you get stuck at the initialisation.

[Lib.zip](https://github.com/WaynePhillipsEA/twinbasic/files/8463706/Lib.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - twinBASIC compiler version [0.14.36]

**Comment by FullValueRider** [comment]
This compiler errors are probably my including function calls in a Const declaration.  I have my stupid hat on today <sigh....>

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.15.19 (available in IDE BETA 19).  Thanks for reporting.
