### ISSUE TITLE
Immediately indexing into a collection returned from a function fails in compiled mode but not F5 mode

### ISSUE THREAD

**Issue by Greedquest** [WaynePhillipsEA/twinbasic#794]
**Describe the bug**
If a collection is returned from a function and consumed immediately, I think the ref count might be messed up in console app because the program crashes before outputting. Saving the function return result to a variable before indexing `(1)` fixes the issue.

**To Reproduce**
```vba
Public Sub Main()
    stdout.WriteLine dictGet(New Dictionary, "dsfs", flagValues("fdfs"))(1)
End Sub

Private Function flagValues(ParamArray values() As Variant) As Collection 'makes new collection from values
    Dim result As New Collection
    Dim value As Variant
    For Each value In values
        result.Add value
    Next value
    Return result
End Function

Private Function dictGet(ByVal dict As Dictionary, ByRef key As Variant, ByVal default As Variant) As Variant
    Return If(dict.Exists(key), dict(key), default)
End Function
```
compiled to a Console App.
where stdout is:

```vba
Public Static Property Get stdout() As ITextStream
    Dim fso As New Scripting.FileSystemObject
    Dim result As ITextStream
    If result Is Nothing Then Set result = fso.GetStandardStream(Scripting.StdOut)
    Return result
End Property
```

**Expected behavior**
Should print "fdfs" - and does in F5 mode. But crashes silently at the command line.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - twinBASIC beta editor (latest)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 20, thanks!
