### ISSUE TITLE
Now is not Now

### ISSUE THREAD

**Issue by KarlSevenSeven** [WaynePhillipsEA/twinbasic#795]
**Describe the bug**
After a loop with debug output, Now is the same as before the loop.

**To Reproduce**
Make a new project in Beta 12.
Add a Command Button.
Paste this:
```
Dim n As Long
Debug.Print "Start", Now
For n = 0 To 4000
Debug.Print CStr(n) ;
Next
Debug.Print
Debug.Print "End", Now

```
Run.

Result:
```
Start         12.04.2022 11:44:43 
012345
(shortened)
39903991399239933994399539963997399839994000
End           12.04.2022 11:44:43 

```

Next observation:
There is a ; after Debug.Print, but the output is not like that:
![image](https://user-images.githubusercontent.com/88059532/162933590-01afde65-8c9b-4ab2-8619-a8b594c2a604.png)

**Expected behavior**
Now is correct.

**Desktop (please complete the following information):**
Beta 12
Windows 10

**Comment by WaynePhillipsEA** [comment]
The code runs very quickly, therefore the time is unlikely to change, and the result of the Now function is correct.

It is the slowness of the IDE in processing the debug console messages, which it does asynchronously, that makes the result look incorrect.   I will address the debug console performance elsewhere.  Thanks for reporting.
