### ISSUE TITLE
Field not beeing assigned its value before Form Load Event

### ISSUE THREAD

**Issue by tdimitriou** [WaynePhillipsEA/twinbasic#799]
**To Reproduce**
Code to reproduce the error:

```
Class Form1

    Public MyField As String = "Field1"

    Sub New()
        Debug.Print "Form.New: MyField = " ; MyField
    End Sub

    Private Sub Form_Load() Handles Form.Load
        Debug.Print "Form.Load: MyField = " ; MyField
    End Sub

'<UPDATE>
    Private Sub Form_Initialize()
        Debug.Print "Form.Initialize: MyField = " ; MyField
    End Sub
'<UPDATE>

End Class
```

The debugger output will be:

```
Executing '[Form1].Show'...
Form.Load: MyField = 
Form.New: MyField = Field1

```

**Expected behavior**
The variable should be assigned its value as soon as it is declared.

**UPDATE**
After a closer look, I noticed that the cause of the issue is the Class lifecycle (events order as shown in the debugger output above). The Form.Load is fired before the Sub New (Class_Initialize) which does not match the VB6 (or any other Windows Forms App) behaviour, AFAIK.

I also noticed that the Form.Initialize Event is not fired at all (but has no real effect as we have the Sub New() or Class_Initialize instead).

**Desktop (please complete the following information):**
 - OS: Windows 11
 - twinBASIC IDE BETA 14

**Comment by WaynePhillipsEA** [comment]
Yup, load event is firing too early.   

ps. The Initialize event only fires for controls at the moment, not for forms.  It is useful for control inheritance, when you want to override properties (see https://github.com/WaynePhillipsEA/twinbasic/discussions/707)
