### ISSUE TITLE
Support RubberDuck annotation @ModuleDescription

### ISSUE THREAD

**Issue by WaynePhillipsEA** [WaynePhillipsEA/twinbasic#8]
**Describe the solution you'd like**
twinBASIC should understand the RubberDuck annotation of '@ModuleDescription 

**Additional context**
twinBASIC already allows the RubberDuck annotation of '@Description before a Module declaration, but the @ModuleDescription annotation is specific to Modules, and applies inside module block-scope rather than before the module definition

**Comment by retailcoder** [comment]
As a historical side note, in the VBE with single-module-per-file components Rubberduck needed a way to disambiguate a `@Description` annotation intended for a module's first member, vs. an identical annotation intended for the module itself:

```vb
Option Explicit
'@Description "this annotation could bind to the module or the procedure"
Public Sub DoSomething()
End Sub
```

`@VariableDescription` exists for the same disambiguation reasons, and translates to a slightly different (`VB_VarDescription`) attribute.

**Comment by WaynePhillipsEA** [comment]
Now supported, as of v0.9.2220
