### ISSUE TITLE
Add UserDocument

### ISSUE THREAD

**Issue by team-moeller** [WaynePhillipsEA/twinbasic#805]
**Is your feature request related to a problem? Please describe.**
I would like to build a addin to the vba editor where the form can be a tool window. Therefor I use the method "CreateToolWindow".
https://techshelps.github.io/VBOB6/html/vbmthcreatetoolwindowmethod.htm
This method only accepts a UserDocument but not a form. So I can't get it to work

**Describe the solution you'd like**
At the moment only forms are available. Please make also UserDocuments available.

**Additional context**
This is the code I would like to run:
```
        Const strGUID As String = "{BBA02DDB-3144-474D-88B9-8DA290707B08}"

        Set gwinAddIn = ThisVBE.Windows.CreateToolWindow(ThisAddIn, "BetterAccessVBAInspector.docAddIn", _
                        "Better Access VBA-Inspector", strGUID, aiAddIn)
```

**Comment by mansellan** [comment]
Linking #62, where it was commented that `.dob` (ActiveX Documents) seemed pretty useless, but it seems there is a use-case after all.

**Comment by WaynePhillipsEA** [comment]
Stay tuned :)

**Comment by mansellan** [comment]
Actually, wondering if the same use-case exists for `dsr` (designers) - is it possible to install those in the VBA IDE? Or only in VS6?

**Comment by WaynePhillipsEA** [comment]
Coming in the next update... preliminary ActiveX control creation support!

![tbToolWindow](https://user-images.githubusercontent.com/25738109/164206363-8a5cdd5c-f3b2-4c87-b8ff-02413d5319df.gif)

**Comment by WaynePhillipsEA** [comment]
Now also working as a regular ActiveX control on an Access form...
<img width="355" alt="tbActiveX1" src="https://user-images.githubusercontent.com/25738109/164286227-927fbcab-9f40-4e4c-81c7-cf856864ed18.png">

Mostly done on this for the preliminary release, so expect this to be available at some point tomorrow.

**Comment by WaynePhillipsEA** [comment]
Sorry folks, there's a few extra updates I want to get in to the next release so I'm going to delay it until tomorrow.  It'll be ready for you to have a play with over the weekend.

**Comment by WaynePhillipsEA** [comment]
BETA 21 is now available that includes this functionality.   Please look at Sample 4 that demonstrates how to create a simple ToolWindow in the VBE.

**Comment by team-moeller** [comment]
Thank you for the speedy implementation. I tried it and it worked as expected.
From my side this issue can be closed. What do you think?

**Comment by WaynePhillipsEA** [comment]
Great.  Let's close this then.  Thanks!
