### ISSUE TITLE
Recursive default member evaluation sends the compiler into an endless loop

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#807]
**Describe the bug**
Apologies.  I've confused the compiler again.  Unfortunately on this occasion I can't remember which module I was editing when the problem occurred.  I am keeping my code VBA compatible so I reloaded everything (apart from the tests) into VBA and Rubberducked it to remove all non-admin issues as possible.  Unfortunately, the 'cleaned' code is still confusing the compiler.  This occurs in VSCode and with Beta22
 
[Lib.zip](https://github.com/WaynePhillipsEA/twinbasic/files/8546937/Lib.zip)

**Comment by FullValueRider** [comment]
OK, so I have my stupid hat on again today.  I've now created a new project and copied files one by one.  I didn't get any compiler issues (yet) but I did find that the 'Enumerator' symbol had been corrupted.
![CorruptEnumerator](https://user-images.githubusercontent.com/81257042/164901168-63644ea5-a93d-463f-8740-c3f3242d7ed3.jpg)

**Comment by WaynePhillipsEA** [comment]
Not sure about the corrupted symbol.

Looks like the main issue is with the Deb member in the Box class.   It is marked as the default member, and it returns a type of itself (Box), so when the compiler encounters code that tries to evaluate the default member, you're sending it into a recursive loop in trying to resolve it.

There's not a simple/quick fix for this one.  Needs some thought how best to handle it.

**Comment by FullValueRider** [comment]
Ah.  I wasn't sure that was a good idea but it did seem to be working initially.  Now removed.  Thanks for the update.

**Comment by WaynePhillipsEA** [comment]
This is now fixed in IDE BETA 23 (compiler v0.15.23), thanks for reporting!
