### ISSUE TITLE
Shell isn't the same

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#812]
**Describe the bug**
Executing this via Excel VBA immediate window:
`Shell "cmd.exe"`

opens a command prompt as expected.

Executing the same via tB IDE Beta 25's debug console, the cmd process is spawned but the window is not visible. It has to be destroyed via the task manager. The window should have been visible.

**To Reproduce**
1. Create a standard EXE project, make it a console project.
2. Either create a test procedure or execute via debug console: `Shell "cmd.exe"`
3. No command prompt is opened.
4. Open task manager, find a running `cmd.exe` process. 

Note: this seems to work fine if I open another executable (e.g.`msaccess.exe`) -- it will open normally. `powershell.exe` fails, however. I tested the output of project in case the console setting had a effect - it did not.

**Expected behavior**
A normal command prompt window should show.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC IDE Beta 25

**Comment by bclothier** [comment]
Additional information:

It seems that the call to `ShellExecute` and `CreateProcess` fails similarly. I discovered that if I passed in `CREATE_NEW_CONSOLE` flag into the `CreateProcess`, I get the console window as expected. This might be due to twinBASIC already having its own console and the default behavior being to inherit its console. That might be an artifact of the development environment.

**Comment by WaynePhillipsEA** [comment]
Yes, that is the issue.   We can also see the problem if we set the project to be a console application, and run the EXE.  If you then run that EXE from the command line, you'll see that the new cmd.exe has inherited the console where we launched our EXE from.

So the fix is going to be to use CREATE_NEW_CONSOLE if we're debugging, OR if we're a console application.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 26 (compiler v0.15.26).  Thanks for reporting!
