### ISSUE TITLE
Jump to other line

### ISSUE THREAD

**Issue by lunasoft2001** [WaynePhillipsEA/twinbasic#814]
**Question**
How can I jump from Line 80 to 82 without execute line 81 in debug mode? (f5, f8, f6 ???)
I don't know where is the best place to make a question.

**Screenshot**
![image](https://user-images.githubusercontent.com/12692231/165743363-dfc6c8c3-3dff-4b37-9e10-0fa7c474ba12.png)

**Comment by WaynePhillipsEA** [comment]
Actually, that doesn't need to wait for E&C as it's more of a debugger thing and wouldn't take too much work to implement.  Ideally we'd be able to drag the yellow indicator just like in VBx, and also allow Ctrl+F9 to set it manually.

**Comment by bclothier** [comment]
FYI I assumed it was a E & C feature because I also have observed that if one toggles the breakpoint while in the break mode, it crashes the debugger with a message about E & C not being available.

**Comment by VB6-Programming** [comment]
> Actually, that doesn't need to wait for E&C as it's more of a debugger thing and wouldn't take too much work to implement. Ideally we'd be able to drag the yellow indicator just like in VBx, and also allow Ctrl+F9 to set it manually.

Yes please, as soon as possible :)

**Comment by WaynePhillipsEA** [comment]
> FYI I assumed it was a E & C feature because I also have observed that if one toggles the breakpoint while in the break mode, it crashes the debugger with a message about E & C not being available.

The E&C message should only be appearing if the source is changed.   I'll check & fix that.

**Comment by WaynePhillipsEA** [comment]
This is now available for testing in BETA 27.  Consider it experimental as I want to enable/disable the context menu etc based on the debugging context.

**Comment by lunasoft2001** [comment]
Incredible. An Update in less than 2 hours.
Good Job Wayne.

Be careful that you are spoiling us and then we complain because it takes you half a day to solve a problem.

**Comment by Greedquest** [comment]
Yeah the yellow drag doesn't let you jump to an expression if there are two on the same line with : or an in-line if statement
```vba
If bool Then Debug.Print bar : Exit Sub
```

Would be nice to jump to `If`, `Debug` or `Exit` in that, maybe with right click context menu or yellow drag anywhere in the screen, not just the left hand column. Not to mention inline breakpoints.

**Comment by WaynePhillipsEA** [comment]
> Yeah the yellow drag doesn't let you jump to an expression if there are two on the same line with : or an in-line if statement
> 
> ```vbnet
> If bool Then Debug.Print bar : Exit Sub
> ```
> 
> Would be nice to jump to `If`, `Debug` or `Exit` in that, maybe with right click context menu or yellow drag anywhere in the screen, not just the left hand column. Not to mention inline breakpoints.

Yeah, inline breakpoints and inline jumping will have to come later.  Probably worth opening an issue for them if there isn't already one.

**Comment by WaynePhillipsEA** [comment]
![tbDragExecutionPoint](https://user-images.githubusercontent.com/25738109/165891215-967502b5-49d6-4cf7-bdd2-d546edebf1a0.gif)

Dragging the execution point is now supported in BETA 28, so this issue will now be closed.  Thanks!
