### ISSUE TITLE
How can I get the path from a tbProject

### ISSUE THREAD

**Issue by lunasoft2001** [WaynePhillipsEA/twinbasic#815]
**Is your feature request related to a problem? Please describe.**
In Access I use currentProject. Path to obtain the path from the project.
How can I obtain the path from a Project in twinBasic? 
I assume that I need much more to learn and I don't want disturb you too much.
Where can I learn these tips that I need as medium VBA developer?

![image](https://user-images.githubusercontent.com/12692231/165774709-90efcd3c-9790-4022-bf9e-c7c089f68b52.png)

P.D.:
Sorry for my poor English but i'm trying to write without Google Translate

**Comment by WaynePhillipsEA** [comment]
If it's a standalone EXE, you can use `App.Path`.   If it's a DLL, and you're wanting to get the DLL path (and not the hosting EXE path), that's a little more involved.

**Comment by EduardoVB** [comment]
> If it's a DLL, and you're wanting to get the DLL path (and not the hosting EXE path), that's a little more involved.

I think that App.Path returns the DLL file path, not the exe path in a DLL project (not tested now).

**Comment by WaynePhillipsEA** [comment]
> > If it's a DLL, and you're wanting to get the DLL path (and not the hosting EXE path), that's a little more involved.
> 
> I think that App.Path returns the DLL file path, not the exe path in a DLL project (not tested now).

Hmmm... actually it looks like I already added `App.ModulePath` to give you the DLL path, so I assume `App.Path` really is the host EXE path, unless I mucked that up.

**Comment by EduardoVB** [comment]
[App.Path DLL.zip](https://github.com/WaynePhillipsEA/twinbasic/files/8584472/App.Path.DLL.zip)

**Comment by EduardoVB** [comment]
In a DLL or OCX, the "App" is the DLL or OCX, not the EXE.

**Comment by WaynePhillipsEA** [comment]
@EduardoVB  the tB implementation of App.Path was implemented correctly, it was my memory at fault, so no changes necessary.

@lunasoft2001 I'll close this as I think you got an answer.  If you want it reopened just let me know.
