### ISSUE TITLE
Incorrect Array dimensions do not generate an error until runtime

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#821]
**Describe the bug**
I found I had incorrectly typed some Array Dimensions as part of a Test
```
Dim myArray(5 To 9, -6, -2) As Long
```
Instead of
```
Dim myArray(5 To 9, -6 to -2) As Long
```
The incorrect version was not flagged as an error.  
![IncorrectArrayDImsBefore](https://user-images.githubusercontent.com/81257042/166145028-1036619f-3bb3-4dec-aaa3-cc5b58f89fb8.jpg)
At runtime an error is raised but only on the Declare line of the Method

![IncorrectArrayDimsAfterRun](https://user-images.githubusercontent.com/81257042/166145047-349b5194-db35-4043-bd7e-4b7dbaca4526.jpg)

It took some time to deduce the cause of the runtime error given where the error was flagged.

 - OS: Windows 11
 - twinBASIC IDE 28

Please note that the screenshots are from VSCode but the same effect occurs for Beta 28 of the IDE.

**Comment by wqweto** [comment]
The compile-time error in VB6 on  `Dim myArray(5 To 9, -6, -2) As Long` is "Range has no values" which I've never seen before.

**Comment by FullValueRider** [comment]
Apologies.  I should have added that VBA generates the "Range has no values" at compile time.

**Comment by EduardoVB** [comment]
> The compile-time error in VB6 on `Dim myArray(5 To 9, -6, -2) As Long` is "Range has no values"

I think VB6 assumes 0 as the first element when it is not specified, so -6 means 0 to -6.
But `Dim myArray(5 To 9, -6 To -6, -2 To -2) As Long` works.

**Comment by bclothier** [comment]
Given that the `SAFEARRAYBOUND` structure only stores the `lLbound`, it would have been an impossible situation to try and iterate a negative range. However, IMNSHO, I always thought it a misfeature which helps worsen the one-off error already prevalent in the programming. This would be a good candidate for a compiler warning when a weird bound is used instead of traditional 0 to size minus 1.

**Comment by EduardoVB** [comment]
I think that someone that writes (-5 to -2) must be doing it on purpose and should be well aware of what he is doing and why.
On the other hand, for someone that by mistake writes (-5) will receive the corresponding error.

**Comment by WaynePhillipsEA** [comment]
> I appreciate that folks enjoy rerunning religious wars over array indexing, but that wasn't the point of my post. The key point I was trying to get across was that the line of code that was highlighted was not the line which was causing the error. It was only when I moved the code into VBA and did a debug.Compile project that the true source of the error became apparent.

No worries, this will be fixed in the next release tomorrow.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 29, thanks for reporting.
