### ISSUE TITLE
`DateAdd` seems to crash at runtime

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#827]
**Describe the bug**
Given a standard EXE, code that uses `DateAdd` seems to crash.

**To Reproduce**
1. Create a standard EXE. Use sub main as the startup object.
2. In a module provide the following code:
```
Public Sub Main()
    Dim l As Long
    Dim s As Date
    Dim e As Date

    s = Now()
    MsgBox "hi"
    e = DateAdd("s", 30, s)
    MsgBox "the time will be " & Format$(s, "yyyy-mm-dd hh:nn:ss") & " soon"
End Sub
```
3. Run the procedure in IDE and verify it works OK.
4. Build the project. It will open the first messagebox with no issue but will then crash while executing the `DateAdd` - we never see the 2nd messagebox. 

**Expected behavior**
Don't crash, k? 😄 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC IDE 29

**Additional context**
It can be worked around by doing arithmetic (*gasp!*) on the dates. But I really would rather not do that.

**Comment by WaynePhillipsEA** [comment]
This bug also affects `DatePart` and `DateDiff`, again only in compiled files.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 30.  Thanks for reporting.
