### ISSUE TITLE
Is there any way of inspecting compiler attributes at runtime?

### ISSUE THREAD

**Issue by sancarn** [WaynePhillipsEA/twinbasic#828]
**Is your feature request related to a problem? Please describe.**

Currently trying to create a `VBIDEToolWindowCollection` class which handles window size storage, and object lifecycle. I'd like a `Add(caption as string, ctrl as tbControl)` function, but for that to be the case, at runtime, I need to obtain the CLSID of that window, which is defined in the class:

```
[ FormDesignerId ("9241AB4C-E36C-468E-9FD1-192339B9537A") ]
[ ClassId ("410B9622-5FF2-4541-9B34-9124006EC8EC") ]
Class t2

End Class
```

I'd expect this is already possible in one way or another. Typically I'd expect the attributes to be farmable by name or something. E.G.
`GetCompilerAttributes(ProjectName & "." & TypeName(obj), "CLSID")`(?)

**Comment by WaynePhillipsEA** [comment]
If I've understood correctly you want to obtain the CLSID of a given tB object instance at runtime.   At the moment the only way to do this is to expose it in your implementation, using the `VBA.Compilation.CurrentComponentCLSID` (string) property.  e.g. 

```
Public Property Get CLSID() As String
    Return VBA.Compilation.CurrentComponentCLSID
End Property
```

_(or you might prefer to expose it via a custom interface if you don't want to expose it on the implicit interface of the class)_

**Comment by sancarn** [comment]
> or you might prefer to expose it via a custom interface if you don't want to expose it on the implicit interface of the class

that is my current solution yes. Glad it will be supported eventually :) I will close this issue.
