### ISSUE TITLE
Names/filenames in Project Explorer

### ISSUE THREAD

**Issue by DinyaZ** [WaynePhillipsEA/twinbasic#830]
**Describe the bug**
Special characters (in this case ü) in the imported filename unsupported? It makes no problem in VB6 and works also fine in the Windows. 
See the attached screenshots

By the way a compatibility issue: is it possible to show the name of the form or module, and not only the filename? As it works in VB6. Theese names and the filenames arent automatically the same.

**Desktop (please complete the following information):**
 - twinBASIC compiler version BETA31

**Additional context**
![44433](https://user-images.githubusercontent.com/94013032/167249154-3f4d74d9-4c1a-45b1-a2b3-0513017fd7d7.jpg)

![Image434](https://user-images.githubusercontent.com/94013032/167249325-3ceb651d-f0f5-424e-9a1d-0f5aa460b64f.jpg)

**Comment by WaynePhillipsEA** [comment]
The internal filesystem fully supports unicode, so this is just a problem during import.  I'll get it fixed, thanks.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 32.  Thanks for reporting!
