### ISSUE TITLE
Misc issues, when I try to import a little VB6 project

### ISSUE THREAD

**Issue by DinyaZ** [WaynePhillipsEA/twinbasic#831]
It imports the VB6 project:

![Image84224](https://user-images.githubusercontent.com/94013032/167249900-e61c207d-5c08-4b78-8e05-45910f3a7097.jpg)

but without the form. And I cant add it later manually, because the PROJECT/ADD/ADD FORM menuitem is diasabled. So I cant test this old little project in TWB, but the code works fine in VB6.

The modules came in "successfully", but in reality with much issues. Only a few example:

- DirListBox and FileListBox are missing
- App.PreviInstance is also missing

![Image12654](https://user-images.githubusercontent.com/94013032/167250174-54bb59d8-c948-4ef1-b6a7-3dbb047416b2.jpg)

- screen.mousepointer:
![Image624](https://user-images.githubusercontent.com/94013032/167249817-0d6198da-928f-4b88-8208-e98a7edf6d29.jpg)

- variable declaration warnings
![Image1423](https://user-images.githubusercontent.com/94013032/167250648-765b700d-6e94-4223-a39f-e816ebb8141f.jpg)

- the code in the TWB is a bit too "colorful" for me. I see that you try to visualise the different syntax elements, names, variable types, etc with different colors, and it is good, but the result is bit too colorful perhaps. Can you add customization possibility, for example a list with the highlighted syntax elements in the setup, and the user can select, which is needed. Even the color itself should be customizable?

**Comment by WaynePhillipsEA** [comment]
You can add forms, but you must first add the WinNativeForms twinpack reference, via the project Settings.  In future, this reference will be added automatically for you to make this easier.

DirListBox/FileListBox -- known issue.  Sorry, but we haven't implemented then yet, as we concentrated on the most popular controls first.  This is on the roadmap for completion this quarter.

App.PrevInstance. -- known issue.  Only a few of the App members have been implemented yet.

Screen -- known issue.  Not yet implemented at all.

Variable declaration warnings -- these warnings are configurable.  See the warnings section of the project settings.

"Too colourful" -- this will be customizable in a future version of the IDE.  You can manually edit the "styles-twinbasic-dark.css" CSS file in the "ide" folder if it is bothering you.  At the bottom of that file is the colour setting for each syntax keyword type that we support.  When updating to a new version you'll have to amend it each time until we support this properly in the IDE.

**Comment by WaynePhillipsEA** [comment]
As all of the issues raised are already covered by other issues, I'll close this one.  Thanks.
