### ISSUE TITLE
Validation error when namespace contains underscore _

### ISSUE THREAD

**Issue by greatquux** [WaynePhillipsEA/twinbasic#832]
My project name contains an underscore character, which works perfectly fine in VB6.  It's also the namespace of my COM object so can't be easily changed.  Please add support for this.

![image](https://user-images.githubusercontent.com/1655942/167429365-e842e09c-fbf4-4707-aecc-3bd0527aa270.png)

**Comment by greatquux** [comment]
Thank you, verified this fixed the issue and I can save and check off references now!

**Comment by WaynePhillipsEA** [comment]
Thanks @greatquux, you beat me to it :)
