### ISSUE TITLE
IDE should not lose keyboard focus when Alt + Tabbing

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#840]
**Describe the bug**
If the caret is on a code pane in the IDE, and one uses `Alt` + `Tab` to switch windows, upon returning back to IDE, the caret is no longer there and one must then use a mouse to put the caret back and keep typing.

**To Reproduce**
1. Open any module and start typing something
2. Alt + Tab to switch to some other program
3. Alt + Tab again to return to the IDE
4. The caret is no longer there and any keystrokes go nowhere(?).

**Expected behavior**
The caret should stay where it is even after an Alt+Tab.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler BETA 38

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 39, thanks!
