### ISSUE TITLE
Friend members appear to leak in the implemented class.

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#843]
**Describe the bug**
tB allows the use of `Implements ... Via ...` to help forward all public members into the field, saving us the trouble of re-implementing the members already implemented by the class. However, it seems that friend members that are correctly hidden in the base class are exposed via the derived class. 

**To Reproduce**
1. Create an ActiveX DLL project
2. Create a base class. Create a public method and a friend method.
3. Create a derived class. In that derived class, use `Implements... Via` to implement the base class' members.
4. Build the project
5. Load the library via VBA host, and you can see the friend member in the object browser. On the base class, that same friend member is not exposed but it is on the derived class.

**Expected behavior**
The friend members on the base classes should not be exposed in the derived class. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler BETA 38

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 39, thanks!
