### ISSUE TITLE
twinBasic executes code between Select Case and first case statement

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#844]
**Describe the bug**
I'm not sure if this is a bug or deliberate policy.  However in a Select Case structure, twinBasic will execute code between the select Case xxxx and the first Case YYYY.  

VBA gives a compile error saying that Labels and Statements are invalid in such a location.

Personally, I quite like the twinBasic version.

In the code below, the statements in the inner case statement are executed.
```
Public Function Deb(ParamArray ipItems() As Variant) As WCollection
    ' This call is on the PredeclaredId of WCollection
    
   ' This is the only time New is required for WCollection
   With New WCollection
   
     Select Case True
     
         Case ParamArrayIsNotAllocated(CVar(ipItems))
     
             Set Deb = .ConstructInstance
         
    
         Case ParamArrayHasOneItem(CVar(ipItems))
         
            Select Case True
         
                ' Yes the next two lines **are** be executed in twinBasic
                Dim myVarType As VbVarType
                myVarType = VarType(ipItems(0))
                
                Case myVarType = vbString
                
                    Set Deb = .ConstructInstanceFromString(ipItems(0))
                    
                    
                Case myVarType = vbObject
                
                    Set Deb = .ConstructInstanceFromEnumerable(ipItems(0))
                    
                    
                Case Else
                
                    Err.Raise WCOLLECTION_ERROR, MY_NAME, "Unexpected constructor input"
            
            
            End Select
             
         Case Else
         
             Set Deb = .ConstructInstanceFromEnumerable(CVar(ipItems))
             
             
         End Select
             
    End With
 
End Function
```

![SelectCaseNovelty](https://user-images.githubusercontent.com/81257042/168469841-b842cfbe-d71a-4d90-b1e6-32af68f0051b.jpg)

**Desktop (please complete the following information):**
 - OS: WIndows 11
 - twinBASIC compiler version Beta Ide 39

**Comment by WaynePhillipsEA** [comment]
Interesting find!  That was definitely not intentional.

**Comment by wqweto** [comment]
If this stays what is the sematic of these "in-between" lines? When are these executed?

**Comment by bclothier** [comment]
I am going out on a limb and assume it’s a leaky abstraction of C++’s fall-through...  In VBx, it’s not allowed. I don’t see how this would be different from executing the same statement before entering the `Select Case`. Allowing a case to fall through would have some justification but that’s not what is happening here.

**Comment by WaynePhillipsEA** [comment]
The execution happens after the `Select Case` expression is evaluated, but before the comparison against the first expression in the first `Case` block.   If the `Select Case` expression has side effects, then the semantics would be slightly different to putting the code above the `Select Case` block.  Honestly, I can't think of a good reason to keep this one.

**Comment by bclothier** [comment]
The thing is that we can do the equivalent by assigning the result of the `Select Case` to a local variable, do things with it then enter the `Select Case` using the local variable instead of the original expression. That would be more clear and straightforward than putting statements between the `Select Case` and the first `Case`. For that reason, I would also vote against allowing statements between those 2 statements.

**Comment by WaynePhillipsEA** [comment]
I'm going to tag this as a bug.  If anyone wants to argue the case for keeping this behaviour, then you have maybe 12 hours to make your case ;)

**Comment by retailcoder** [comment]
![humor007.jpg](https://user-images.githubusercontent.com/5751684/168489882-fc71ded3-b116-45d1-8712-2a34fcbff417.jpg)
