### ISSUE TITLE
Compiler is crashing when I try to edit the Hello World example

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#85]
**Describe the bug**

The compiler crashes.  A dialog box pops up advising to report the bug.

VSCode also reports 'Failed to save 'HelloWorld.twin': Unable to write file 'twinbasic:/HelloWorldProject/Sources/HelloWorld.twin' (Unavailable (FileSystemError))

**To Reproduce**

1 Unpack helloworld.zip into a new directory
2  Open VScode
3 Open the Hello world workspace.
4 add the Line 'Public Const myHello as string = "Hello World"

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.9.1944.   Thanks for reporting.
