### ISSUE TITLE
Spurious error messages in debug console

### ISSUE THREAD

**Issue by dmrvb** [WaynePhillipsEA/twinbasic#852]
**Describe the bug**
Whilst typing code for (Public variable definition) I get a red  message in the debug console, and this is repeated many times.

[GLOBALS] internal error compiling global variables terminators.

This is not a functional issue but does not look good or inspire confidence in tB for new users 

**To Reproduce**
Create a new project, add a new module

in the module start typing:

Public xyz as 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - twinBASIC compiler version [all recent releases   Beta 35]

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 43, thanks!
