### ISSUE TITLE
LBound/UBound issue

### ISSUE THREAD

**Issue by KarlSevenSeven** [WaynePhillipsEA/twinbasic#857]
The array lock problem should now be resolved in BETA 42.   The LBound/UBound issue might be a different issue, so you might need to remove those new lines for now.

_Originally posted by @WaynePhillipsEA in https://github.com/WaynePhillipsEA/twinbasic/issues/855#issuecomment-1131217095_

**Comment by KarlSevenSeven** [comment]
While it's not important for the original array lock problem, LBound/UBound is used later in the project.
And, from the debug output, it leads to problems.
If you need further info, tell me.

**Comment by bclothier** [comment]
Closing this on the basis of #887 being closed. If the issue persist, feel free to reopen with more details.
