### ISSUE TITLE
Non Dim variable to default to variant ?

### ISSUE THREAD

**Issue by wopag** [WaynePhillipsEA/twinbasic#86]
Not sure its a bug so im listing it as a request.  (probably more of bad practice - but nice to know if its not supported)

Are there plans to allow variables to be created as local variants if they are not DIMed ?

**Comment by WaynePhillipsEA** [comment]
This is supported.   Please click on the project settings file:
<img width="248" alt="tb_settings1" src="https://user-images.githubusercontent.com/25738109/115818239-45016880-a3f4-11eb-8086-8caf723be3d0.png">

And then find the Option Explicit option
<img width="456" alt="tb_settings_optionExplicit" src="https://user-images.githubusercontent.com/25738109/115818258-521e5780-a3f4-11eb-9bf4-35138221f254.png">

Make sure it is ticked and set 'No' in the drop down.  Then close the Settings file and the compiler should restart.

**Comment by wopag** [comment]
Brilliant thanks
