### ISSUE TITLE
Tests fail when passing a whole paramarray but succeed when passing a paramarray item

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#860]
**Describe the bug**
I have a Class in an Excel file (WCollection) which has 146 tests.  IN VBA, using Rubberduck unit testing, all 146 tests pass.
If I split the tests and class into two Excel files and reference the WCollection from the testing file all 146 tests pass
If I move the Class related stuff into twinbasic and compile to an Active Dll, then when I reference the dll from the Excel file containing the tests I get 86 of the tests failing.

The common theme for the failing tests is that the Factory method (Deb) for the WCollection seems to fail if I forward a whole param array.  If I forward a single item from the paramarray all is fine.

The code for deb accepts a paramarray.  If the paramarray consists of a single item  then that single item is forwarded as ParamArray(0), otherwise the paramarray is forwarded as CVar(ParamArray)

Test which passes in VBA but fails in twinBAsic
```
'@TestMethod("Deb")
Private Sub Test04_DebWithParamArrayIsCountFive()
    On Error GoTo TestFail
    
    'Arrange:
    Dim myExpected As Long
    myExpected = 5
    Dim myList As WCollection
    
    Dim myResult As Long
    'Act:
    Set myList = WCollection.Deb(1, 2, 3, 4, 5)
    myResult = myList.Count
    
    'Assert:
    Assert.AreEqual myExpected, myResult

TestExit:
    Exit Sub
TestFail:
    Assert.Fail "Test 04 raised an error: #" & Err.Number & " - " & Err.Description
    Resume TestExit
End Sub
```

Passing test in VBA and twinBasic
```
'@TestMethod("Deb")
Private Sub Test05_DebWithOneArrayCountIsFive()
    On Error GoTo TestFail
    
    'Arrange:
    Dim myExpected As Long
    myExpected = 5
    Dim myList As WCollection
    
    Dim myResult As Long
    'Act:
    Set myList = WCollection.Deb(Array(1, 2, 3, 4, 5))
    myResult = myList.Count
    
    'Assert:
    Assert.AreEqual myExpected, myResult

TestExit:
    Exit Sub
TestFail:
    Assert.Fail "Test 05 raised an error: #" & Err.Number & " - " & Err.Description
    Resume TestExit
End Sub
```

**To Reproduce**
Open the WCollectionTesting.xlsm, add the reference the the file in the build directory, run the texts using the rubber duck test explorer (be sure to group by category first to get the fastest test experience)

**Expected behavior**
If a test passes in VBA it should also pass in twinBasic.

**Desktop (please complete the following information):**
 - OS: WIndows 11
 - twinBASIC  Ide 42

NB: I just upgraded to Ide 43 and the same problem exists.

I have my point sit in the corner because you're stupid hat on standby just in case.

**Additional context**
The xlsm files , compiled activex.dll and project are in the attached zip.
[WColllection.zip](https://github.com/WaynePhillipsEA/twinbasic/files/8732272/WColllection.zip)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 44, thanks!

**Comment by FullValueRider** [comment]
Thanks for this.  The fixed version still leaves 6 tests not passing. 1 is my problem. I've had a look at the remaining 5 but I can't see anything obvious that I'm doing wrong.

The tests in question are 
Mapit 79d, and four out of the five in Tests for the FilterIt Method (apologies, numbering is a bit screwed in these tests).

Please let me know if you'd prefer a new issue.

**Comment by WaynePhillipsEA** [comment]
Sorry, I only looked at the single issue listed in the OP.  If I get chance later today, I'll have a look at the others.

**Comment by FullValueRider** [comment]
No worries.  I think it is a different issue, I'm just being lazy as everything needed was already uploaded.
