### ISSUE TITLE
Tooltips misplaced

### ISSUE THREAD

**Issue by KarlSevenSeven** [WaynePhillipsEA/twinbasic#863]
**Describe the bug**
On hovering over an editor tab, the tooltip is in the wrong place.

**To Reproduce**
1. Place the mouse over an editor tab

**Expected behavior**
Tooltip near the tab

**Screenshots**
![image](https://user-images.githubusercontent.com/88059532/169595537-9446badc-6d53-4ec8-966a-f68d3a545180.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 GERMAN
 - twinBASIC beta 45

**Additional context**
I think the OPEN EDITORS panel is superfluous.

**Comment by WaynePhillipsEA** [comment]
I can't seem to reproduce this.  On my test machines, the tooltip appears correctly right next to the mouse position.

**Comment by KarlSevenSeven** [comment]
The screenshot was made in the center of a 4K screen.
I should have mentioned that.

If I move the window to the upper left, the tooltips are in the correct place.
Seems the tooltip reference is the screen not the window.

**Comment by WaynePhillipsEA** [comment]
Ah yes, I see now, thanks.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 47, thanks!
