### ISSUE TITLE
SaveAs doesn't save Open Editors

### ISSUE THREAD

**Issue by KarlSevenSeven** [WaynePhillipsEA/twinbasic#865]
**Describe the bug**
When SaveAs a project, the Open Editors are lost.

**To Reproduce**
1. Open a project, open some files in it so you have some tabs.
2. Save the project.
3. SaveAs the project.
4. Make a new project
5. Open the project saved by SaveAs.

**Expected behavior**
A copy of the first loaded project including the editors state.

**Screenshots**
https://user-images.githubusercontent.com/88059532/169684638-192b57a7-6fdf-470b-96df-2b08e53d2c6c.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10 GERMAN
 - twinBASIC beta 46

**Comment by WaynePhillipsEA** [comment]
Yes, I agree this should be the expected behaviour, so I'll mark this as a bug.  Thanks.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 47, thanks!
