### ISSUE TITLE
Statics in class outlive the instances

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#866]
**Describe the bug**
If there is a static variable within a class, it ends up outliving the instance, which may then lead to crashes in IDE and strange behaviors in VBx.

**To Reproduce**
1. Create a project and add the following code:
```
Private Class WhatIs
    Public Function IsTheNumber() As Long
        Static i As Long
        i += 1
        Return i
    End Function
End Class
Private Module Who
	Public Sub Colombo()
    	With New WhatIs
        	Debug.Print .IsTheNumber
    	End With
	End Sub
    Public Sub Holmes()
    	With New WhatIs
        	Debug.Print .IsTheNumber
    	End With
    End Sub
    Public Sub Dunnit()
        Colombo
        Holmes
    End Sub
End Module
```
3. Run the `Who.Dunnit`
4. Observe the debug console output. Repeat few times and you will see it continue to increase when it should have had reset.

**Expected behavior**
The static variable should be reset and be independent between instances.

**Screenshots**
![image](https://user-images.githubusercontent.com/2367644/169726836-c5077f7a-d602-4ed0-b48c-61186ba619e8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC IDE Beta 46

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 47, thanks!
