### ISSUE TITLE
Clean creates Build folder

### ISSUE THREAD

**Issue by KarlSevenSeven** [WaynePhillipsEA/twinbasic#868]
**Describe the bug**
The Clean command creates an empty Build folder.

**To Reproduce**
1. (Delete the Build folder if it should exist)
2. Click File - Clean...

**Expected behavior**
Clearing the Build folder and not creating a new one.

**Desktop**
 - OS: Windows 10 GERMAN
 - twinBASIC beta 46

**Additional context**
A tiny glitch only.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 47, thanks!
