### ISSUE TITLE
debug.print behaviour - cant use a comma to seperate variables

### ISSUE THREAD

**Issue by wopag** [WaynePhillipsEA/twinbasic#87]
**Describe the bug**
**debug.print** does not recognize a comma to separate variables

**To Reproduce**
debug.Print "hello","there"

**Expected behavior**
Should produce  
hello   <tab>   there

but instead compiler reports "sorry file operations are not yet implemented"

**Comment by tdimitriou** [comment]
@wopag The feature is not yet supported in the preview version

The following text has been copied from the [twinBasic Website](https://www.twinbasic.com/preview.html)
> ...
> Additionally, some language syntax is not yet supported, specifically:
> 
> - all file operations; Open, Write, etc, and the FileSystem.* namespace
> - 'Like' operator
> - Print and Debug.Print syntax... only a simple string is currently supported
> - Mid statement (though the normal Mid procedure is implemented)
> - RSet statement
> - Legacy ‘On GoSub’ syntax
> - Legacy ‘DefType’ syntax
> - There are known memory leaks in our LSP implementation, causing excessive memory usage during code editing
>

**Comment by wopag** [comment]
Cheers
