### ISSUE TITLE
TypeName on IUnknown gives "Object"

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#872]
**Describe the bug**
If the variable `oa` is an interface extending an `IUnknown` (and therefore not dispatchable):
![image](https://user-images.githubusercontent.com/2367644/169941954-62ef1168-d45b-427e-97ae-013c4f65977f.png)

The `TypeOf` gives correct answer but `TypeName` returns `Object` (aka `IDispatch`), which would be wrong. If the function `TypeName` cannot be used to report the interface's name, at very at least it should return `IUnknown` to make obvious that it's not compatible for late-bound coding.

**To Reproduce**
1. Create a variable that is typed after an non-dispatchable interface
2. Populate it somehow
3. Run `TypeName` and `TypeOf ... Is Object` and compare the results.

**Expected behavior**
At minimum, it should say `IUnknown`. Ideally, it should report the interface name if possible. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC IDE BETA 47

**Comment by wqweto** [comment]
Should `TypeName` results deviated from VBx behavior?

Currently VBx returns "Unknown" for `IUnknown` based interfaces. (Not sure which interface it checks is missing, might be not exactly `IDispatch`).

**Comment by WaynePhillipsEA** [comment]
Bear in mind that TypeName really only provides coclass type name support.   In cases where the coclass can't be determined, then it returns only "Object" or "Unknown" based on the interface passed in.   

I've fixed the bug here that was causing "Object" to be reported in TypeName() for tB declared interfaces that extend from IUnknown rather than IDispatch, which will be in tomorrows release.

**Comment by bclothier** [comment]
Given that multiple coclasses could potentially implement same interface, how would `TypeName` know it's coclass B and not coclass A?

**Comment by WaynePhillipsEA** [comment]
Runtime type information.   For IUnknown, you use IProvideClassInfo::GetClassInfo, for IDispatch you use ITypeInfo::GetTypeInfo.
