### ISSUE TITLE
DoEvents return value

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#876]
**Describe the bug**
The DoEvents function returns an Integer. tB seems to return always 0.
According to MSDN:
`The DoEvents function returns an Integer representing the number of open forms in stand-alone versions of Visual Basic, such as Visual Basic, Professional Edition. DoEvents returns zero in all other applications.`

**To Reproduce**
```
Class Form1
    
    Private Sub Command1_Click() Handles Command1.Click
        MsgBox DoEvents
    End Sub

End Class
```

**Expected behavior**
Return correct value.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [BETA 48]

**Additional context**
n/a

**Comment by WaynePhillipsEA** [comment]
Yes, when DoEvents was implemented, we had no forms support :)
