### ISSUE TITLE
Command Line Arguments missing

### ISSUE THREAD

**Issue by KarlSevenSeven** [WaynePhillipsEA/twinbasic#877]
**Describe the bug**
Not a bug but a missing feature.
Command Line Arguments is missing in project settings.

**Screenshots**
![image](https://user-images.githubusercontent.com/88059532/170212519-09d00e8b-6f44-4372-b6de-f29ab933c40c.png)

**Desktop**
 - OS: Windows 10 GERMAN
 - twinBASIC beta 48

**Comment by WaynePhillipsEA** [comment]
Yes, this used to be in the build-configuration settings in the VS code version, but we don't have the equivalent of that in the new IDE.  Let's just move it to the project Settings.

**Comment by WaynePhillipsEA** [comment]
There is now a project setting for this in BETA 49.  Thanks!
