### ISSUE TITLE
Long error message runs off the screen

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#885]
**Describe the bug**
If an error message is too long, it will run off the IDE's banner. It cannot be scrolled, even using the code pane's scrollbars. See screenshot:
![image](https://user-images.githubusercontent.com/2367644/170832854-313aeea8-c62a-4db2-ab86-014681053e2f.png)

**To Reproduce**
1. In a project, create a sub with long error message:
```
Public Sub Derp()
  Err.Raise 5, , RepeatString("01234567890", 10)
End Sub

Public Function RepeatString(Expression As String, Number As Long) As String
Dim i As Long
Dim s As String
  For i = 0 To Number
    s &= Expression
  Next
  Return s
End Function
```
3. Run the `Derp` procedure
4. Observe the error
5. Try to scroll to right using codepane scrollbar; the error does not scroll
6. Try to highlight the error. It also does not move to right.

**Expected behavior**
I would prefer that the error message automatically wrap. If this is not an option, at least provide a horizontal scrollbar if it's too long.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC IDE BETA 50

**Additional context**
This also seem to cause VS JIT debugger to trip up as well after aborting the execution. Something else may have had crashed when aborting it.

**Addendum**
It does appear that the text do wrap but too late. From some additional experiments, it looks like it does not auto-wrap before it hits the code preview scrollbar on the right and goes under it. This can be observed by watching how the message wraps when you resize the codepane with the code preview scrollbar active.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 53, thanks!
