### ISSUE TITLE
Reference errors for projects with WinNativeControls & Access object library

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#894]
**Describe the bug**
When a project references the WinNativeControls library and the Access object library, the control `ActiveXControlExtender` is flagged with the problems shown:
![image](https://user-images.githubusercontent.com/2367644/173828771-d49d7202-9024-4013-b019-ec269a6bfefc.png)

The order of references has no effect. Oddly, the project seem to build. 

**To Reproduce**
1. Create a new ActiveX control project
2. Via Settings, add the reference to Microsoft Access object library (usually 16.0 but I doubt version matters)
3. Restart the compiler
4. See package and the control light up red.

**Expected behavior**
There should be no problems having both referenced.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC BETA 54

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 55, thanks!
