### ISSUE TITLE
COM reference details

### ISSUE THREAD

**Issue by DinyaZ** [WaynePhillipsEA/twinbasic#896]
When I add COM reference, and check the details, it gives false version number. See  the attached screenshot!

![Image177](https://user-images.githubusercontent.com/94013032/173904380-75da89ab-7d00-4ba7-bc2a-a1bb995e6866.jpg)

PS: Can you make the checkboxes here a little bigger or more visible, when they are checked?

**Desktop (please complete the following information):**
 - OS: Windows7 64bit
 - twinBASIC compiler version Beta55

**Comment by Kr00l** [comment]
It's not a bug. The 1.0 you see and refer to is the typelib version.
