### ISSUE TITLE
Compiler not Connected

### ISSUE THREAD

**Issue by MinMatMR** [WaynePhillipsEA/twinbasic#90]
After opening the helloworld.code-workspace VS code is not able to connect to the compiler. Additionally I can't see the contents of the project. 

Is there a step of "Getting Started - Sample 1 - HelloWorld!" that I missed. Maybe it could be a permission problem with the software settings of my company. 

Where can I find the log-File to get further information.

![image](https://user-images.githubusercontent.com/83071582/115866816-8583d500-a43a-11eb-9bae-c7a050606b73.png)

**Comment by WaynePhillipsEA** [comment]
@MinMatMR Thanks for reporting.   Indeed, this will most probably be an anti-virus or firewall issue.  Our VS Code extension connects to the compiler on your machine via network sockets, and even though these are local sockets, they can sometimes get blocked by firewalls or anti-virus software.

There is no log file at present.   Error should be being reported via the UI, though clearly it isn't happening in this case, so we will look deeper at this to see if we are missing some error handling in this area.

First thing to check is whether the twinBASIC_win32.exe file exists on your machine and hasn't been quarantined by your anti-virus software.  The file should be in the following folder:

     C:\Users\{USERNAME}\.vscode\extensions\twinbasic.twinbasic-0.9.1944\out\bin

You won't be able to examine the project files until the compiler is connected.

**Comment by MinMatMR** [comment]
Yes you are right. 
I have the "twinBASIC_win32.exe" in the needed folder. But unfortunately I am not allowed to run any *.exe-file.

So I will get in touch with our admins and ask for permission.

Tanks for your help

**Comment by WaynePhillipsEA** [comment]
Thanks for confirming.  I will leave this issue open for now as a reminder that we need to improve the error handling in the VS Code extension so that we can catch and report this better.

**Comment by WaynePhillipsEA** [comment]
Improved error handling and notification in v0.9.2125.  Thanks for reporting.
