### ISSUE TITLE
Problem with adding certain ActiveX controls (including licensed controls)

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#903]
_Originally posted by @wopag in https://github.com/WaynePhillipsEA/twinbasic/issues/772#issuecomment-1152507161_

> add  CODEJOCK activeX suite
>  "failed to deserialize JSCON (bad length) "    when adding any component.
>
>
> 10Tec iGrid control (4.70) .... place it on screen .... 
> properties all seem valid
> try and place code under click - doesnt compile :-
>
>  Private Sub iGrid1_Click(ByVal lRow As Long, ByVal lCol As Long) Handles iGrid1.Click
> baseform.twin
> "COMPILATION (CODEGEN) ERROR AT LINE #9.  PLEASE REPORT THIS ERROR TO > > https://git.io/JMh6S"
>
>
> it does produce a message box with numbers  9402  , 9403  too (I presume debug lines)

**Comment by bclothier** [comment]
_Originally posted by @WaynePhillipsEA in https://github.com/WaynePhillipsEA/twinbasic/issues/772#issuecomment-1152639674_

> Thanks @wopag, I will look into those issues.   You should have better luck with Krools Common Controls library, or other VB6-based ActiveX controls at the moment.

**Comment by bclothier** [comment]
_Originally posted by @WaynePhillipsEA in https://github.com/WaynePhillipsEA/twinbasic/issues/772#issuecomment-1152643180_

> > Private Sub iGrid1_Click(ByVal lRow As Long, ByVal lCol As Long) Handles iGrid1.Click
baseform.twin
> > "COMPILATION (CODEGEN) ERROR AT LINE https://github.com/WaynePhillipsEA/twinbasic/issues/9. PLEASE REPORT THIS ERROR TO https://git.io/JMh6S"
> 
> What code did you put in the Click event? I just tried a simple MsgBox and the click event fired OK.
>
> _Edit: it looks like there's an issue with the Implements-Via feature at the moment, so you might have to use the `.Object` property to access the underlying object e.g. `iGrid1.Object.AddCol` instead of just `iGrid1.AddCol`_
>
> > it does produce a message box with numbers 9402 , 9403 too (I presume debug lines)
>
> I did just reproduce this one.  When it occurs, restart the compiler and it should be fixed (... temporarily).  I'll get that fixed properly in the next release.

**Comment by bclothier** [comment]
_Originally posted by @WaynePhillipsEA in https://github.com/WaynePhillipsEA/twinbasic/issues/772#issuecomment-1152935653_

> @wopag 10Tec iGrid should hopefully be working better in BETA 52 now.

**Comment by bclothier** [comment]
_Originally posted by @wopag in https://github.com/WaynePhillipsEA/twinbasic/issues/772#issuecomment-1154470385_

> CODEJOCK still cant add items to a form  ( failed to deserialize JSON (bad length))
> 
> If I try to add gif89 to the form,  IDE gets stuck in a loop  of drawing then "Please wait"

**Comment by bclothier** [comment]
_Originally posted by @WaynePhillipsEA in https://github.com/WaynePhillipsEA/twinbasic/issues/772#issuecomment-1154603917_

> @wopag. The demo versions of CODEJOCK are working.  We're not currently supporting licensed controls, so that's probably why they are not working for you.
> 
> I'll check gif89 though, as that sounds like a bug.

**Comment by bclothier** [comment]
_Originally posted by @WaynePhillipsEA in https://github.com/WaynePhillipsEA/twinbasic/issues/772#issuecomment-1156230578_

> @wopag BETA 54 supports the gif89 control, provided you turn off the DEP setting in the IDE (Tools > IDE options menu).  That control uses asm thunks that do not comply with DEP.

**Comment by bclothier** [comment]
_Originally posted by @WaynePhillipsEA in https://github.com/WaynePhillipsEA/twinbasic/issues/772#issuecomment-1156476767_

> @wopag I am unable to repro the problem with CODEJOCK controls.  I've now installed a licenced version of the ActiveX Suite (latest v20.3.0), and I'm able to use the controls in both 32-bit and 64-bit twinBASIC projects.

**Comment by bclothier** [comment]
_Originally posted by @wopag in https://github.com/WaynePhillipsEA/twinbasic/issues/772#issuecomment-1156505565_

> GIF89 - confirmed working :)
> 
> Using registered versions 12.0.1 and   15.1.2  still dont work.

**Comment by bclothier** [comment]
_Originally posted by @WaynePhillipsEA in https://github.com/WaynePhillipsEA/twinbasic/issues/772#issuecomment-1156540967_

> let's check those old versions again once tB supports licenced controls as I suspect it might just be that.

**Comment by WaynePhillipsEA** [comment]
Licensed controls are now supported in BETA 55, so we should check the state of this again.

**Comment by wopag** [comment]
I'll update this thread as its CODEJOCK related.

I'm testing through all of the CODEJOCK activeX controls as they vary between loads of styles of control.

It appears that none of the controls draw correctly in the IDE but do work at runtime.  (assign a visual style to see). Seems the IDE can display the basic background/foreground but when the activeX control needs to draw to itself that is not updated?



xtremeCalendarControl "Calendar Caption Bar" Add to a form, cycles redrawing the form and "sync" until its removed.

Xtremesuitecontrol TABCONTROL - cant add tab using IDE  (maybe similar to report thats reported about similar tab control)

**Comment by WaynePhillipsEA** [comment]
Drawing the controls is quite difficult because we have to draw them in a hidden window, take a snapshot of it and then display the snapshot in the IDE webpage.   Some controls don't quite conform to the ActiveX standards, and so are more problematic to work with.   In the current version of CodeJock controls, most controls seem to display reasonably well.   Some of them don't... but a lot of them do.

I was able to repro the problems with CalendarCaptionBar, and Xtreme TabControl.  Thanks

**Comment by WaynePhillipsEA** [comment]
I'm now experimenting with some tweaks to the snapshotting which appears to fix quite a lot of IDE rendering issues.  Hopefully will be available in tomorrows update.

**Comment by WaynePhillipsEA** [comment]
The IDE snapshots have been completely reworked in beta 57.  Let me know if that works better for you now.

**Comment by WaynePhillipsEA** [comment]
Let's close this now.  Any further problems can be opened as new issues.
