### ISSUE TITLE
ComctlLib .Tabs.Add does not work

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#904]
_Originally posted by @Kr00l in https://github.com/WaynePhillipsEA/twinbasic/issues/772#issuecomment-1153917154_

> ComctlLib the .Tabs.Add does not work. See below message.
> 
> ![image](https://user-images.githubusercontent.com/33756666/173364451-03c2e5b9-b64f-481c-9176-2515cce17060.png)

**Comment by WaynePhillipsEA** [comment]
This was fixed in BETA 54/55.  Thanks!
