### ISSUE TITLE
Unable to retrieve tab index and bring to is inversed. 

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#905]
_Originally posted by @camomille22003 in https://github.com/WaynePhillipsEA/twinbasic/issues/772#issuecomment-1152911326_

> Just to point it out:
> It lacks the property page to make SSTAB work, so it is impossible to retrieve the TAB number, nor previousTAB after a click to manage the passage from one tab to another.
> 
> ![Image1](https://user-images.githubusercontent.com/33807881/173186911-38164560-2d65-4e6b-92fe-27dd7c14ea5e.jpg)
> 
> Another report:
> Inversion of "Send to back" and "Bring to front"
> 
> ![Image2](https://user-images.githubusercontent.com/33807881/173186941-56867518-4671-4793-b381-3b2cef249f70.jpg)

**Comment by WaynePhillipsEA** [comment]
Whilst the property pages are now accessible in the latest BETAs, the SSTAB ones currently throw some spurious 'Invalid Property Value' errors when trying to use them.

**Comment by camomille22003** [comment]
Inversion of "Send to back" and "Bring to front" is now correct.

Apart from the 'Invalid Property Value' of the property sheet.
just for info,, what doesn't work in "SSTab":

In design, clicking on the top of a tab normally increments/decrements "Tab Properties" and changes the offset of the tab image (useful for anchors per page).
SSTab1_Click(ByVal PreviousTab As Integer) is inactive.

**Comment by WaynePhillipsEA** [comment]
These issues should now be fixed in BETA 56, thanks!
