### ISSUE TITLE
Multithreading in debug mode behaves differently

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#91]
**Describe the bug**
I had a working twinBasic project that demonstrates the multithreading with message pump. This was working up to the version 0.9.1750 but on and after the version 0.9.1881, it no longer works. The effect is that if I do `~BackgroundWork(x, y)` via the debug console, instead of immediately spawning a new thread, it is deferred until _after_ the main thread has ended. Of course, it can't then run because the context is already gone. 

**To Reproduce**
1. Create a project that has a routine `BackgroundWork()` and is set up to take messages from the background work. 
2. Provide a breakpoint or `Stop` in the main routine to pause the execution.
3. Run code by pressing F5
4. When the breakpoint/`Stop` is hit, execute via debug console `~BackgroundWork(...)`
5. Observe no new thread is created immediately
6. Allow the main routine to complete and exit.
7. Debug will then show a new thread created.

**Expected behavior**
The thread should be created immediately at executing the `~BackgroundWork(...)` 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.9.1881 and above are affected.

**Comment by WaynePhillipsEA** [comment]
Thanks for the bug report.  It will be the synchronization that I added to ensure global variables get instantiated from the main thread in 0.9.1881.   I will look into it and get this fixed tomorrow.

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.9.2021.  Thanks for reporting.
