### ISSUE TITLE
Launch problem

### ISSUE THREAD

**Issue by camomille22003** [WaynePhillipsEA/twinbasic#920]
Since version 56, to launch with Sart/continue or F5, it displays "Executing '[Form1].Show'..." but nothing happens, I have to "Stop" for the program to launch (do not did not occur in version 55)

 - OS: [e.g. Windows 10]
 - twinBASIC compiler version 56

**Comment by WaynePhillipsEA** [comment]
Can't reproduce this problem in any test projects here.

**Comment by WaynePhillipsEA** [comment]
When this happens, check the debugger callstack... something must be preventing it from firing.

**Comment by camomille22003** [comment]
I don't know how to do "check the debugger call stack", but since it's not a nuisance, I'll wait for a version that fixes the problem.

**Comment by bclothier** [comment]
@camomille22003  Normally, it's on the upper right corner of the IDE:
![image](https://user-images.githubusercontent.com/2367644/174444712-762f1a53-fb83-411d-bdf3-36110071c62a.png)

However, it can be collapsed or moved around, so double check you didn't collapse it. When you run code and have breakpoint, it will show up there automatically.

**Comment by camomille22003** [comment]
Thank you for the help, unfortunately you have to know how to interpret what is wrong.

![Image1](https://user-images.githubusercontent.com/33807881/174448250-e5f7495f-2151-49c3-aa8c-727ecffd5e67.jpg)

**Comment by WaynePhillipsEA** [comment]
Thanks, that is probably enough info for me to work out what's going on.

**Comment by WaynePhillipsEA** [comment]
I was unable to reproduce the problem, but from reviewing the callstack snapshot I can at least see where the problem occurred.  I have implemented a fix for it in BETA 58.  Please confirm if that resolves the issue for you.

**Comment by camomille22003** [comment]
Version 58 fixed the problem.
Thank you

**Comment by WaynePhillipsEA** [comment]
Thanks
