### ISSUE TITLE
A number of issues related to debugging

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#928]
**Describe the bug**
Whist debugging I had occasion to try to view the contents of a dynamic array containing 16384 elements.  I observed the following.

1.  It took more than a minute to show the elements
2.  The numbering of the array elements was string sequential and not numeric sequential

![ArrayElementOrder](https://user-images.githubusercontent.com/81257042/174759034-bd6820dd-8674-49be-aacb-dd625d2e257f.jpg)

3. If the view of the array elements was not closed then each subsequent F11/F10 in the method where the view was requested took a about a minute to complete.
4.  It was no possible to end the program using the run/end instruction (or I didn't wait tong enough) (I kept getting the 'main thread is busy' message
5. The project could be saved and closed BUT when reopened, if the array view had  not been previously closed , then the delays were present again when the code entered the method in which the array view had previously been requested.

Steps to reproduce the behaviour:
1. Open the 'AoC2021NoLib' project
2. start execution of main in MainModule using F6
3. At each break point press F5 to continue
4. The delay issues should manifest after the second F5
5. The array being viewed was mKeys in Method Keys in Module cHashD

**Expected behaviour**

Array elements should be listed in numerical order of the index of the array elements not the string order

The delay to show the array contents of an array with 16k elements is unexpected, based on debugging in VBA and other languages I'd expect a delay of a couple of seconds at most.

The run/end code may need to be revised to avoid the problem of not being able to end a program.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - twinBASIC compiler version Beta Ide 58

**Additional context**
These issues are not urgent, just a little frustrating.

[twinBasic.zip](https://github.com/WaynePhillipsEA/twinbasic/files/8947438/twinBasic.zip)

**Comment by WaynePhillipsEA** [comment]
There should be a slight improvement here in BETA 60 ;)

The remaining short delay now comes from the webpage rendering of the DOM list nodes, similar to the debug console performance from earlier issues.  Ideally we need to group the array elements e.g. `(0 - 100)`, `(101 - 200)` etc so that we can reduce the number of live DOM nodes and make accessing individual elements easier.  I'll open another issue for that.
