### ISSUE TITLE
Need a little better fault handling in IDE

### ISSUE THREAD

**Issue by mburns08109** [WaynePhillipsEA/twinbasic#929]
**Describe the bug**
IDE fails to launch compiler DLL due to Norton/anti-malware quarantine actions.
So, the compiler .DLL fails to load, leaving the IDE in a blank white screen with no recourse but to shift-F4 and wait to close the IDE.

**To Reproduce**
rename or relocate the compiler DLLs from your install and launch the IDE.

**Expected behavior**
Would be nice to get a msgbox or something else with an option to exit peaceably.

**Screenshots**
![image](https://user-images.githubusercontent.com/11444628/174812818-25167459-d319-428a-aff5-2367b0b35819.png)

**Desktop (please complete the following information):**
Windows 10
anu Beta IDE version prior to 57

**Additional context**
How can we arrange to play nice with the antivirus folk?

**Comment by WaynePhillipsEA** [comment]
> How can we arrange to play nice with the antivirus folk? 

It will be difficult at the moment due to the churn of EXEs/DLLs we produce in the daily betas.  Once things get more stable, it will be worthwhile sending the EXEs and DLLs to the major antivirus vendors for whitelisting.

Additionally, I need to start signing the executables, as that helps build up reputation (a little).

**Comment by mburns08109** [comment]
OK, I have a new symptom for you, Wayne.

I DL'd and install VB6EE (well, at least up until the installer got hung up no something that WIn10 didn't seem to like).

I fired up VB6, and got in, so Yay!...(even though the installer was still hung).

Then I open tBIDE...and double-clicked on the ssTab project, and got:
![image](https://user-images.githubusercontent.com/11444628/174940055-3ad4dac2-ec58-4c7e-99d2-0ecc9eb80dd4.png)
The Please wait window kept appearing and disappearing ad nauseum.

The IDE fell into a (infinite?) loop of some sort I had to Task Manager it to get out.

So, yeah, idiot me tried it on 25+year-old Vb6 code/controls for pre-SP6 VB6.
I'm not complaining about this situation per se, but this illustrates another failure mode for the IDE that will need some attention (infinite loops trying to initialze stuff n time as n->inifity just isn't fun to get stuck in).

**Comment by mburns08109** [comment]
Oh, BTW this is what the application event log was recording during the stuck in a loop time:
Faulting application name: twinBASIC_win64.exe, version: 0.0.0.0, time stamp: 0x6204b6c9
Faulting module name: twinBASIC_win64.dll, version: 0.0.0.0, time stamp: 0x62b1cd01
Exception code: 0xc0000005
Fault offset: 0x00000000001351e5
Faulting process id: 0x12b4
Faulting application start time: 0x01d885eb9dcf8ab5
Faulting application path: C:\Users\Mark\DEV\TwinBASIC_IDE\bin\twinBASIC_win64.exe
Faulting module path: C:\Users\Mark\DEV\TwinBASIC_IDE\bin\twinBASIC_win64.dll
Report Id: e650eac7-1341-4dcb-a6d5-d7590b110167
Faulting package full name: 
Faulting package-relative application ID:

**Comment by WaynePhillipsEA** [comment]
Thanks, I'll make some improvements in this area.

I see that you're running in 64-bit mode.  You'll need to run in 32-bit mode for trying out the SSTAB ActiveX Control.

**Comment by mburns08109** [comment]
Doh!  I'm sure that would've hit me over the head at some point.
Hmmm...VS6 SP6 doesn't seem to want to install now.  :-(

**Comment by WaynePhillipsEA** [comment]
<img width="293" alt="tbMissingDll" src="https://user-images.githubusercontent.com/25738109/174954148-b3a8dc6b-d886-42e6-9a9b-7e73b297c8f3.png">

Improved the error dialog and process shutdown in BETA 60.

Also limited the form-designer reconnection attempts to 5 in BETA 60.  We'll adjust this number lower once things get more stable.

Thanks!

**Comment by mburns08109** [comment]
Wayne,

I'm still seeing some odd behaviors.
but now that I restored the .DLLs, I'll have to await the next Beta to re-create the error I saw.
The short of it - clicking OK on the new "missing Compiler DLL" dialog did not close the TB window. Rather, it tried to load a URL sorta like this: Https://localhost(somethingorother%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20(somethingorother)
...and just hung open, requiring the task manager to close again.

Now, as got the SSTab control, When I load the project with Wn64 as the startup default, I see:
![image](https://user-images.githubusercontent.com/11444628/175853598-9b594dd3-b9a9-4d9e-8b30-2c9115dd9be9.png)
When I switch it to Win32, I see:
![image](https://user-images.githubusercontent.com/11444628/175853681-0b921326-479f-4758-ae57-4c217b01b288.png)

BUT, If I switch back to Win64 again...it goes back to the "ActiveX Licensing Error" message.
but that's not really appropriate, is it? Shouldn't there be something more like an "Incorrect Processor Bit-ness for this ActiveX Control" error message?
I mean, an ActiveX Licensing Error is its own legit thing, so this really should throw a different error (and I don't think that this is a backwards-compatibility-restricted thing, either, since there was no 64-bit VB6, there is no history to be compatible with in this regard.

**Comment by mburns08109** [comment]
![image](https://user-images.githubusercontent.com/11444628/176232535-16939857-9be5-43c3-9f3b-b66d133da496.png)

**Comment by mburns08109** [comment]
I did the test in that sequence because I was acting as a "suspicious user of this new code" suspecting adware, etc. and not wanting to needlessly expose my PC to "unneeded stuff".

So yeah, this test is a teensy bit like David Bowman pulling HAL's memory modules one by one, but *shrug* that's why they call them torture tests, right?
