### ISSUE TITLE
Tab key confined inside VBCCR17.LinkLabel

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#935]
**Describe the bug**
The tab key is confined inside the VBCCR17.LinkLabel control.
However, it is designed to move to the next control when tabbing on the last link item. (same with back tabbing on the first link item)

**To Reproduce**
reference VBCCR17 and add two textboxes with a LinkLabel control in the middle.
Add the below code in Form_Load:
`LinkLabel1.Caption = "hello <A>test</A> world <A>test2</A>"`

**Expected behavior**
to tab out accordingly.

**Screenshots**
![Llb_TabIssue](https://user-images.githubusercontent.com/33756666/175023862-8b679eb5-9167-4d43-b582-cf503f6cb600.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [BETA 60]

**Additional context**
In the case it should tab out the LinkLabel resorts to the original IOleInPlaceActiveObject::TranslateAccelerator implementation which takes care of moving to the next or previous control. So there might be an issue on that.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 67, thanks!
