### ISSUE TITLE
ActiveX based OptionButton problem by code

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#940]
**Describe the bug**
As of BETA 61 the ActiveX based OptionButton is supported.
This works by user input but not via code.

**To Reproduce**
Place two or more option buttons on a form and set all to True by code. The last one set should remain True at the end.

**Screenshots**
![Opt_ByCode](https://user-images.githubusercontent.com/33756666/175781051-737facba-b385-4ccc-b7b1-2a1158448ae5.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [BETA 61]

**Additional context**
n/a

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 63.  Thanks!
