### ISSUE TITLE
Empty is treated as object nothing

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#943]
**Describe the bug**
I'm unsure if this is a bug or deliberate twinBasic policy.

The following code Prints 'Its Nothing" in twin basic but in VBA raises an error at the if statement, the error being an object is required.
```
Public Sub TestNothing()

    Dim myObj As Variant
    
    myObj = Empty

    If myObj Is Nothing Then
    
        Debug.Print "Its nothing"

    Else
        
        Debug.Print "Its something"

    End If

End Sub

```
**To Reproduce**
Run the presented code

**Expected behavior**
Its not a problem but it would be helpful to known which of the two behaviours to expect as standard in twinBasic.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - twinBASIC compiler version Beta Ide 62

**Comment by WaynePhillipsEA** [comment]
Most definitely a bug, thanks for reporting.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 63.  Thanks!
