### ISSUE TITLE
Property changes on third party ActiveX controls delayed update

### ISSUE THREAD

**Issue by EduardoVB** [WaynePhillipsEA/twinbasic#945]
**Describe the bug**

For controls that are not intrinsic, I mean for ActiveX controls, when a property of a control is changed, it is updated on the designer, but when F5 is pressed to run the program, the last change is not reflected. It takes another property change to update the previous (and so on).

**To Reproduce**

I tested with Krool's controls, with a CheckBoxW, with a SStab and with a SSTabEx.
Changing any property that has a visible effect.

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - twinBASIC compiler version 62

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 63.  Thanks!
