### ISSUE TITLE
Save with a file dialog does nor save

### ISSUE THREAD

**Issue by EduardoVB** [WaynePhillipsEA/twinbasic#947]
**Describe the bug**
The Save and Save As menu options do not save the project.

**To Reproduce**
1. Open tB IDE and start a new project
2. White something, like Msgbox "Hello" in `Private Sub Form_Load`
3. Got to Menu File, Save Project As
4. Specify a file name (that doesn't exist)
5. Click the "Save" button on the dialog.
6. Close the IDE from the X button
7. There appears the message "You've made changes to this project. Save now?". This message should not appear because there was no new changes.
8. Click the "Discard changes" button.
9. Go to check in the folder that you specified, the file was not saved.

**Expected behavior**
To save immediately in the Save and Save As menus after specifying the file, if the dialog operation was not canceled.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - twinBASIC compiler version 62

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 63.  Thanks!
