### ISSUE TITLE
Resizing form in IDE drawing error

### ISSUE THREAD

**Issue by wopag** [WaynePhillipsEA/twinbasic#954]
BETA 64 windows 10

Not noticed it before, but when you resize the form say just the width, the "white" part of the form doesnt get drawn until you loose go of the resizer?  It seems to draw with transparent area?

It happens all the time if you just size either the height or the width.  Maybe looks like the form redraw is using the new height and width the wrong way around?

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 65.  Thanks!
