### ISSUE TITLE
Naming of components with Duplicate or Copy/Paste

### ISSUE THREAD

**Issue by VB6-Programming** [WaynePhillipsEA/twinbasic#957]
When duplicating an intrinsic control (with Duplicate or Copy/Paste) , the control naming is wrong.

Example: duplicating a Textbox named 'Text1' gives a new control named 'TextBox1'

Applies to:  TextBox, CommandButton, OptionButton, CheckBox, ComboBox, ListBox, HScrollBar, VScrollBar

 - OS:  Windows 10
 - twinBASIC compiler version Beta 66

Not a critical issue.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 67, thanks!
