### ISSUE TITLE
Duplicating a Frame

### ISSUE THREAD

**Issue by VB6-Programming** [WaynePhillipsEA/twinbasic#958]
When duplicating a Frame control, the new Frame is placed inside the original frame.

It would be better to behave like a Copy/Paste and create the new frame in the top left corner of the form.

 - OS:  Windows 10
 - twinBASIC compiler version Beta 66

Not a critical issue

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 68, thanks!
