### ISSUE TITLE
Assigning value to a Boolean property generates compiler error - external reference

### ISSUE THREAD

**Issue by machthree** [WaynePhillipsEA/twinbasic#96]
**Bug description**

Using Excel as an external reference, trying to assign the value True to the .Visible property of the application generates a compiler error message: too few arguments, expected 2 in call to 'Visible'. Additionally the TwinBasic shows a definition for the .Visible property which indicates it understands that it is a Boolean. Assignment of a string value to the .Caption property works correctly so I assume the reference has been attached correctly.

1. Take the HelloWorld project
2. Add Microsoft Excel as an external ActiveX type reference to the project properties
3. Add the following code to the HelloWorld Main routine:
 
        dim xl as excel.Application = new excel.Application
        xl.Caption = "Test"
        xl.Visible = True

4. Attempt to run or debug the code and observe the error message

**Expected behavior**
Similar code in VBA compiles and runs correctly

**Screenshots**
Screenshot showing external references
![Screenshot 2021-04-29 183819](https://user-images.githubusercontent.com/17429508/116594477-28948d00-a91a-11eb-90a3-e228c535c09e.png)
Screenshot showing intellisense error and compiler error
![Screenshot 2021-04-29 183753](https://user-images.githubusercontent.com/17429508/116594603-5083f080-a91a-11eb-991f-22d09426494e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.9.2100

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting this!   The Excel Visible property has an implicit and hidden LCID argument that the compiler has to provide.  This was broken in this case, but is now fixed in v0.9.2136, which should be available for you to update shortly.
