### ISSUE TITLE
I can't assign a recordset field value to an array item

### ISSUE THREAD

**Issue by OldestCoderInTown** [WaynePhillipsEA/twinbasic#961]
**Describe the bug**

I have some code that can trawl an MS Access Database, and put the contents of a field, into a list box.

When I try to put the contents of that same listbox, into an array, it fails.

mydata = "z:\invoices.mdb"
    Set cdb = OpenDatabase(mydata)
    Set mcslrs = cdb.OpenRecordset("select * from clients order by fullname")

'    Do Until mcslrs.EOF = True
        DoEvents
'Next line fails when assiging any value to an array.
     mClients(mcslrs(0)) = "493"
    
  mClients(mcslrs(0)) = mcslrs(1)

The error seems related to assigning to an array, not the databse aspect.

**Expected behavior**
I wanted the array to be populated with the field contents

**Screenshots**

**Desktop (please complete the following information):**
 - OS:Windows 10 Pro
 - twinBASIC compiler version IDE Beta 65

**Additional context**

**Comment by KDGundermann** [comment]
- where is the definition of your array mClients?
- what is the value of mcslrs(0) and mclrs(1)?

**Comment by OldestCoderInTown** [comment]
sorry 
Dim mClients(999) As String
    mydata = "z:\invoices.mdb"
    Set cdb = OpenDatabase(mydata)
    Set mcslrs = cdb.OpenRecordset("select * from clients order by fullname")

    xgt = 0
'    Do Until mcslrs.EOF = True
Dim bp As Single
    For bp = 1 To 380
    xgt = xgt + 1
       ' Me.Caption = mcslrs(1)
        DoEvents
'Next line fails when assiging any value to an array.
     ' mClients(mcslrs(0)) = "493"
     ' mClients(mcslrs(0)) = mcslrs(1)
      mClients(mcslrs(0)) = mcslrs(1)

but mClients(xgt) = mcslrs(1)      works

field 0 is number 
field2 is text

**Comment by OldestCoderInTown** [comment]
Here is a clearer failing example.

[ Description ("") ]
[ FormDesignerId ("3D00F729-4D9E-47F6-B0F7-56F7CC0F284A") ]
[ PredeclaredId ]
Class Form1
Public xgt As single
Public gt As String
Public mydata As String
Public cdb As Database
Public mcslrs As Recordset

Sub stick()
'code fired by the test button
Dim mya (999) As String
Dim g As Single
For g = 1 To 17
mya(g) = Str(g)
List3.AddItem mya(g)
Next
MsgBox mya(13)
'All good to here
    mydata = "z:\invoices.mdb"
    Set cdb = OpenDatabase(mydata)
    Set mcslrs = cdb.OpenRecordset("select * from clients order by fullname")
    Do Until mcslrs.EOF = True
    List3.AddItem mcslrs(0)
    List1.AddItem mcslrs(1)
'That all works ok up to here
mya(mcslrs(0)) = "test" 'Codegen error at line 30 (This line)
the value of field 0 is a number in the MS Access database

        mcslrs.MoveNext
    Loop
End Sub

**Comment by wqweto** [comment]
Try if any of these works
 - `mya(mcslrs(0)) = "test"`    <-- Codegen error
 - `mya(mcslrs(0).Value) = "test"`
 - `mya(mcslrs.Fields(0)) = "test"`
 - `mya(mcslrs.Fields(0).Value) = "test"`
 - `mya(mcslrs.Fields.Item(0)) = "test"`
 - `mya(mcslrs.Fields.Item(0).Value) = "test"`

**Comment by OldestCoderInTown** [comment]
I am now havin =g a mental block.

I can't type Public mya(999) to create an array that all parts of the application can access. What am I doing wrong?

**Comment by OldestCoderInTown** [comment]
mydata = "z:\invoices.mdb"
    Set cdb = OpenDatabase(mydata)
    Set mcslrs = cdb.OpenRecordset("select * from clients order by fullname")
    Do Until mcslrs.EOF = True
         qg = mcslrs.Fields(0)
         mya(qg) = mcslrs.Fields(1)
         mcslrs.MoveNext
    Loop
MsgBox "Done"
