### ISSUE TITLE
JTI/suspect.196612!7617db2c4502  C:\tmp\twinBASIC_IDE_BETA_67\twinBASIC.exe

### ISSUE THREAD

**Issue by retsyo** [WaynePhillipsEA/twinbasic#962]
[twinBASIC_IDE_BETA_67.zip](https://github.com/WaynePhillipsEA/twinbasic/releases/download/beta-67/twinBASIC_IDE_BETA_67.zip) is reported by McAfee as
```
JTI/suspect.196612!7617db2c4502 
C:\tmp\twinBASIC_IDE_BETA_67\twinBASIC.exe
```

maybe it is a false report, but this report does do harm for twinbasic in the feature

**Comment by WaynePhillipsEA** [comment]
Closing, as this is similar as already reported under #959.    It is a false positive.
