### ISSUE TITLE
Is GUI editor availble or planned ?

### ISSUE THREAD

**Issue by graysuit** [WaynePhillipsEA/twinbasic#98]
**Is your feature request related to a problem? Please describe.**
As you know, its 2021, and everyone is lazy including me.
So we need an basic GUI builder like winform has.
With also having `list of events` and `properties`
By this way, we would be able to focus on business strategy more than messing with code.

**Describe the solution you'd like**
You can use winform, and at build `get all controls properties` and save it as visual basic syntax.
But again, I don't know how twinbasic works.
Nor I'm that expert.

**Additional context**
N/A

**Comment by WaynePhillipsEA** [comment]
Hi, firstly thanks for looking at twinBASIC!  Yes, full GUI support is planned, please see the roadmap discussion #75.

I will close this issue for now as this is a long term goal covered by other issues, but I appreciate you participating 👍
