### ISSUE TITLE
Number of array dimensions

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#99]
**Is your feature request related to a problem? Please describe.**
Since tB has now an in-built IsArrayInitialized() function it would be nice to have also an in-built function to get the number of dimensions a array has.

**Describe the solution you'd like**
Use-case would be for example a Property/Method where an Array should be passed. We can check if the value/argument is what we expect (IsArray()), if it is valid (IsArrayInitialized()). Now the last validation step would be to get the dimension count. For example the property/method could behave differently for an 1-dim array vs an 2-dim array and raise error in 3-dim or more arrays.

Naming proposals:

NumberOfArrayDimensions()
GetDims()
ArrayDimensions()

**Comment by Greedquest** [comment]
In python numpy there is `shape` which returns a list of the dimensions eg. [2,3,3] for a 2x3x3 array

**Comment by wqweto** [comment]
> In python numpy there is `shape` which returns a list of the dimensions eg. [2,3,3] for a 2x3x3 array

In COM array dimensions can have lower bounds too unlike most languages which hardcode this to 0.

**Comment by Kr00l** [comment]
In VB.net it's called 'Rank'. So Array.Rank returns the number of dimensions.
So, another naming proposal would be then..
ArrayRank()

**Comment by bclothier** [comment]
Just to point out that if the #100 is adopted, it probably would be `.Rank`, `.GetLowerBound`, `.GetUpperBound`, and `.Length` on the array variable. No need to add new global functions.

**Comment by Kr00l** [comment]
> Just to point out that if the #100 is adopted, it probably would be `.Rank`, `.GetLowerBound`, `.GetUpperBound`, and `.Length` on the array variable. No need to add new global functions.

Sure. I just love global functions as these are so legacy VB-Ish. Well, I hope both ways will get into consideration. IsArrayInitialized() is now thankfully built-in and is a global function.
Thanks anyhow. :)

**Comment by bclothier** [comment]
FWIW, I'm adamantly opposed to having both; only one or other should be chosen and regardless which one is picked, it should be consistently followed for [the reasons outlined here](https://github.com/WaynePhillipsEA/twinbasic/issues/36#issuecomment-820810043). I personally do not agree with doing things the "legacy VB-ish" way. I'm in favor of doing it the "BASIC" way, e.g. following the ideal that a program code should read more or less like an English instruction manual and thus is clear and readable. Not all aspects of "legacy VB" fulfilled that ideal and for tB's new features, it should avoid those pitfalls. 

There is a reason nobody's making solutions in Perl today.... And even though JavaScript is "popular", there is lot of gnashing and weeping over using it, not to mention the ridiculous amount of toolchains to work around all warts...
